### ISSUE TITLE
Pulling image microsoft/bcsandbox:fr causing errors

### ISSUE THREAD

**Issue by nicolassaleron** [HodorNV/ALOps#10]
Hello,

I am testing the build pipeline and while the ALOpsDockerStart task is executing, it returns the following error:

*** Importing required PS-Functions
*** Validate configuration
Add tag 'ltsc2019' to image for OS Match
*** Pull Docker Image: microsoft/bcsandbox: fr:ltsc2019
##[error]invalid reference format
##[section]Finishing: ALOpsDockerStart

I think there is a mistake when "ltsc2019" is added to the image name.
If ":" is already there, the suffix should be -ltsc2019 instead of :ltsc2019

**Comment by nicolassaleron** [comment]
By the way, a workaround is to add -ltsc2019 explicitly to the image name :)

**Comment by waldo1001** [comment]
Thanks!  That is indeed a valid workaround (never hurts to explicitly set the tags ;-)).  It's a bit complicated to get this automatically working, but we will get there ;-).  Fix coming up!

**Comment by AdminHodor** [comment]
@nicolassaleron This is indeed a bug, the tag "ltsc2019" should never be added with the ":" prefix, but always with "-". We certainly will have this patched in the upcomming release.

**Comment by AdminHodor** [comment]
Fixed in the version v1.141 released today. the workaround with adding the tag is not needed anymore.
