### ISSUE TITLE
Using Docker Image mcr.microsoft.com/businesscentral/onprem:ch Result in error

### ISSUE THREAD

**Issue by InnoNavSupport** [HodorNV/ALOps#110]
**Using Docker Image mcr.microsoft.com/businesscentral/onprem:ch Result in error**
##[error]The remote name could not be resolved: 'bcdocker.blob.core.windows.net'
during ALOpsDockerWait Task.

*** Initiate Docker Session
*** Working folder: C:\agentALOps2\_work\6\s
*** Copy Working folder to Docker Container: 0d0d56e72647ece80c1fd6e44d6d5f7b0d94b78a469294ec929e26f12d071a7b
*** Docker Working Folder: c:\Run\DevOps\
*** Copy from [C:\agentALOps2\_work\6\s] to [c:\Run\DevOps\]
*** Compression Enabled Transfer
*** Compress Source Files
*** Transfer compressed Archive to session
*** Expand source files in target session
*** Source File setup completed
*** Patch '16.0.11240.12076' Test-Apps for Country [CH]
*** Downloading new test apps for this version from [https://bcdocker.blob.core.windows.net/public/12076-patch/CH.zip]
*** Extract new test apps to [c:\Run\DevOps\16.0.11240.12076-CH-Tests-Patch]
*** Overwrite new test apps in [c:\Applications\BaseApp\Test]
*** Patch '16.0.11240.12076' applied successfully.
##[error]The remote name could not be resolved: 'bcdocker.blob.core.windows.net'
Finishing: ALOpsDockerWait

![JobLogScreen1](https://user-images.githubusercontent.com/62563638/79247762-372d1500-7e7b-11ea-8665-535648552a90.png)

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport ,

Does the container have an internet connection? There is a bug in the v16.0 concerning the Test-Apps, therefor we implemented a fix that will download the correct Test-Apps for a v16.0 container and install them.

If you are not planning to use the Tests from v16.0, we can add a parameter to this Task that will allow to skip the patch installation. 

Kind regards,

**Comment by InnoNavSupport** [comment]
Dear @AdminHodor,

We are planning to use the Tests from V16.0 so
I established a Internet connection for the container and the problem is solved.

Thanks!

Kind Regards!
Daniel
