### ISSUE TITLE
Enable System Diagnostic results in Error during ALOpsDockerStart

### ISSUE THREAD

**Issue by InnoNavSupport** [HodorNV/ALOps#111]
If I enable "Enable System Diagnostics" before I start the Build-Pipeline, the ALOpsDockerStart Task get the following Error:

##[debug]INPUT_SQL_DATABASE (empty)
##[debug]INPUT_SQL_DATABASE_USER (empty)
##[debug]INPUT_SQL_DATABASE_USER_PASSWORD (empty)
##[debug]INPUT_SQL_BACKUP_FILE (empty)
*** Importing required PS-Functions
##[debug]Leaving C:\inn-des-001\_work\_tasks\ALOpsDockerStart_0c42062e-04ee-4507-af30-009a5d8f1983\1.428.1196\70022c29-e8d5-4f59-8d15-2ef9492d150c.ps1.
##[debug]Caught exception from task script.
**##[debug]Error record:
##[debug]Invoke-Expression : Die Benennung "otX" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.**
##[debug]In C:\inn-des-001\_work\_tasks\ALOpsDockerStart_0c42062e-04ee-4507-af30-009a5d8f1983\1.428.1196\ps_modules\alops\82c5a45c-4cf6-413f-aa90-d0e16fa7697f.ps1:1 Zeichen:1
##[debug]+ Invoke-Expression -Command ([System.Text.Encoding]::UTF8.GetString([S ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : ObjectNotFound: (otX:String) [Invoke-Expression], CommandNotFoundException
##[debug]    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
##[debug] 
##[debug]Script stack trace:
##[debug]bei <ScriptBlock>, <Keine Datei>: Zeile 1
##[debug]bei <ScriptBlock>, C:\inn-des-001\_work\_tasks\ALOpsDockerStart_0c42062e-04ee-4507-af30-009a5d8f1983\1.428.1196\ps_modules\alops\82c5a45c-4cf6-413f-aa90-d0e16fa7697f.ps1: Zeile 1
##[debug]bei <ScriptBlock>, <Keine Datei>: Zeile 68
##[debug]bei <ScriptBlock>, <Keine Datei>: Zeile 1
##[debug]bei <ScriptBlock>, C:\inn-des-001\_work\_tasks\ALOpsDockerStart_0c42062e-04ee-4507-af30-009a5d8f1983\1.428.1196\70022c29-e8d5-4f59-8d15-2ef9492d150c.ps1: Zeile 2
##[debug]bei <ScriptBlock>, <Keine Datei>: Zeile 1
##[debug]bei <ScriptBlock>, <Keine Datei>: Zeile 22
##[debug]bei <ScriptBlock>, <Keine Datei>: Zeile 18
##[debug]bei <ScriptBlock>, <Keine Datei>: Zeile 1
##[debug]Exception:
##[debug]System.Management.Automation.CommandNotFoundException: Die Benennung "otX" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
##[debug]   bei System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
##[debug]   bei System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
##[debug]   bei System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   bei System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[debug]   bei System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
##[debug]   bei System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
##[debug]   bei System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
##[debug]   bei System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
##[debug]   bei System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
##[debug]   bei System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
##[debug]   bei System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
##[debug]   bei Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
##[debug]   bei System.Management.Automation.CommandProcessor.ProcessRecord()
##[error]Die Benennung "otX" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
##[debug]Processed: ##vso[task.logissue type=error]Die Benennung "otX" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
##[debug]Processed: ##vso[task.complete result=Failed]
Finishing: ALOpsDockerStart

![Setup2](https://user-images.githubusercontent.com/62563638/79248179-c6d2c380-7e7b-11ea-92cf-49ef5003d98d.png)
![JobLogScreen2](https://user-images.githubusercontent.com/62563638/79248186-c9cdb400-7e7b-11ea-9f0d-09dad39c3198.png)

**Comment by waldo1001** [comment]
We know.  It's more of a PowerShell limitation than an ALOps limitation.
But we are looking into this on how we can improve this behavior.  In the meantime - don't use this..

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport,

We took this in consideration for ALOps v2 which is currently in the making, we made from the start that running Debug/Diagnostics is possible with the v2 version. 
Next to that we also added Azure Application Insights which together with the diagnostics will you full followup capabilities.
If all goes to plan, the v2 should be available in preview by the end of next month.

Kind regards,
