### ISSUE TITLE
ALOpsAppCompiler : Problem with "Get-ServicePath" 

### ISSUE THREAD

**Issue by OUAIRY** [HodorNV/ALOps#125]
Hi guys !

We are trying to create / build your first pipeline without using Docker but in the step of compilation we got this error  "### [error] The term "Get-ServicePath" is not recognized as a cmdlet name, function, script file, or executable program. Check the spelling of the name, or if a path exists, verify that the path is correct and try again."

![image](https://user-images.githubusercontent.com/41148282/80944956-fc1f6100-8dea-11ea-919c-2a3abf2e95ef.png)

Can you help us, if you see something wrong or if something is missing on your YAML :

![image](https://user-images.githubusercontent.com/41148282/80944979-0ccfd700-8deb-11ea-8e21-fe3a0fb97fd3.png)

![image](https://user-images.githubusercontent.com/41148282/80945017-2113d400-8deb-11ea-977e-96af18443522.png)

We tried many things and option for each step but we got always the same error.

Best Regards,

Jean-Charles

**Comment by AdminHodor** [comment]
Dear @OUAIRY ,

Apologies for this, this bug was hotfixed yesterday and should already be available.

Kind regards,

**Comment by OUAIRY** [comment]
Great ! Thank @AdminHodor it works !
