### ISSUE TITLE
ALOpsAppCompiler: Exception calling "GetResponse" with "0" argument(s)

### ISSUE THREAD

**Issue by nixpt82** [HodorNV/ALOps#127]
Hi, 

Im getting this error while run the task on docker, 

![image](https://user-images.githubusercontent.com/35833855/80999114-6fa18c80-8e44-11ea-9207-ede94ce7671e.png)

**Comment by waldo1001** [comment]
Can you share the complete yaml?

**Comment by nixpt82** [comment]
pool:
  name: DevAgent
  demands: DevOps

steps:
- task: Hodor.hodor-alops.alopsdockerstart.ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image: mcr.microsoft.com/businesscentral/onprem
    accept_image_outdated: true
    enable_api_services: true
    memory_gb: 8
    container_restart: always
    docker_parameters: '--isolation=hyperv'

- task: Hodor.hodor-alops.alopsdockerwait.ALOpsDockerWait@1
  displayName: 'ALOps Docker Wait'

- task: Hodor.hodor-alops.alopslicenseimport.ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    usedocker: true
    license_path: '$(Parameters.license_path)'
    print_license_info: true
    license_scope: NavDatabase

- task: Hodor.hodor-alops.alopsdeploytask.ALOpsAppCompiler@1
  displayName: 'ALOps App Compiler'
  inputs:
    usedocker: true
    nav_app_version: '16.0.0.*'
    setup_working_folder: true

- task: Hodor.hodor-alops.alopspublishtask.ALOpsAppPublish@1
  displayName: 'ALOps App Publish'
  inputs:
    usedocker: true

- task: Hodor.hodor-alops.alopsdockerremove.ALOpsDockerRemove@1
  displayName: 'ALOps Docker Remove'
  continueOnError: true
  condition: always()

**Comment by AdminHodor** [comment]
Dear @nixpt82 ,

Could you please share the output of the corresponding "DockerWait" step. 
It seems strange that the download symbols tries to use a "localhost" reference instead of the container name.

Kind regards,

**Comment by nixpt82** [comment]
Dear @AdminHodor 

That is the output. 

> 
> Starting: ALOps Docker Wait
> ==============================================================================
> Task         : ALOps Docker Wait
> Description  : ALOps Docker Wait
> Version      : 1.429.1393
> Author       : Hodor
> Help         : Wait until the Business Central container is started.
> ==============================================================================
> *** Validate configuration
> *** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
> Cleanup old Tasks
> *** Importing required PS-Functions
> *** Waiting for Docker Container Log Entry: Ready for connections!
> 
> Starting Container
> Hostname is e24abe2c3717
> PublicDnsName is e24abe2c3717
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint 52BFAB43B383BA291496F62DB70CA26EECF8110F
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Registering event sources
> Creating DotNetCore Web Server Instance
> Creating http download site
> Setting SA Password and enabling SA
> Creating admin as SQL User and add to sysadmin
> Creating SUPER user
> Container IP Address: 172.29.40.117
> Container Hostname  : e24abe2c3717
> Container Dns Name  : e24abe2c3717
> Web Client          : https://e24abe2c3717/BC/
> Admin Username      : admin
> Admin Password      : Leka9119
> Dev. Server         : https://e24abe2c3717
> Dev. ServerInstance : BC
> 
> Files:
> http://e24abe2c3717:8080/ALLanguage.vsix
> http://e24abe2c3717:8080/certificate.cer
>

**Comment by nixpt82** [comment]
Hi @AdminHodor  

I think you are corrected, i take a look on the last successful run and was using the container name. 
Is anyway to change it?!

Thanks

**Comment by nixpt82** [comment]
> Cleanup old Tasks
> *** Importing required PS-Functions
> *** Initiate Docker Session
> *** Set Docker Container ErrorActionPreference = Stop
> *** Override [DnsName] with NAVComputername value [localhost] `**I think is this the issue**`
> *** Import NAV/BC Management DLL's
> *** Loading assemblies for ServiceTier [BC].
> *** Loadin assemblies from: [C:\program files\microsoft dynamics nav\160\service]
> *** Setting up AL Compiler [ALLanguage]
> *** Downloading AL Compiler [ALLanguage]
> *** Get Extension from Local-Disk...[C:\Run\ALLanguage.vsix]
> *** Resolving Path [C:\Run\ALLanguage.vsix]
> *** VSIX Path Resolved: [C:\Run\ALLanguage.vsix]
> *** Unpacking Extension to folder...
> *** Loading Json Object: [c:\Run\Microsoft.al\al-ALLanguage\extension\package.json]
> *** Using AL Compiler [vALLanguage] located [C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe]

**Comment by nixpt82** [comment]
I force the NavComputerName variable empty and seems to resolved the issue.
