### ISSUE TITLE
ALOps App Compiler: Error when importing license ... antivirus software.

### ISSUE THREAD

**Issue by ThierryPermentier** [HodorNV/ALOps#128]
Hi all, 

Any idea on which rules we have to implement on the antivirus software?

```
Starting: ALOps App Compiler
==============================================================================
Task         : ALOps App Compiler
Description  : Compiles NAV Apps
Version      : 1.429.1396
Author       : Hodor
Help         : Compile a Business Central extension from AL code.
==============================================================================
*** Validate configuration
*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
Cleanup old Tasks
*** Importing required PS-Functions
##[error]At line:1 char:1
+  ieX (( [RunTImE.intEROpsErvicEs.mARsHAl]::PTRTOSTRiNgansI( [rUnTIMe. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
Finishing: ALOps App Compiler
```

**Comment by AdminHodor** [comment]
Dear @ThierryPermentier ,

The default recommendations for running DevOps/Docker are not running the anti-virus. 
You could try to exclude the "_work" folder of the DevOps agent in the Anti-Virus.

Another option is to try setting the pipeline variable "alops_disable_amsi" = true. This should indicate to the AntiVirus to not check this session.

```yml
variables:
- name: 'alops_disable_amsi'
  value: true
```

Kind regards,

**Comment by ThierryPermentier** [comment]
We removed the anti-virus from the sersers running the agent. This solved the problem, but is not ideal.

**Comment by lvanvugt** [comment]
@ThierryPermentier I am running into the same, but wondering if you did try any/all of the options suggested by @AdminHodor?

**Comment by waldo1001** [comment]
Anti-virus and PowerShell/Obfuscation/docker doesn't really go along really well.. therefore the option to disable for the pipeline.. .

**Comment by lvanvugt** [comment]
This indeed works
```
variables:
- name: 'alops_disable_amsi'
  value: true
```
