### ISSUE TITLE
Suggestion: Hyper-V Isolation as Default?

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#130]
Since there are recently so [many issues](https://github.com/HodorNV/ALOps/issues?q=Hyper-V+Isolation) related to Hyper-V Isolation, shouldn't be Hyper-V Isolation the default e.g. in the GitHub-Examples and the Azure DevOps Templates?

**Comment by waldo1001** [comment]
Good question - and we have been thinking about it.  But if we set it default now, we are changing the pipelines of many people .. and possibly causing problems (while we realize NOT putting it default also causes problems.. .

Still - not sure though.  We run close to a thousand builds a day .. we don't want to mess with them too much ;-).

**Comment by DanielGoehler** [comment]
In the example yml-example files? I hope that doesn’t change anything on existing installation :-D

You are right about the Azure DevOps Pipeline Task...

**Comment by waldo1001** [comment]
Lol, that's  true .. yeah, we should do that.. .

**Comment by AdminHodor** [comment]
Seems you can set Hyper-V Isolation as default via the daemon.json config of docker.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2019%2Cwindows-10-2004#mitigation---use-hyper-v-isolation-with-docker-swarm

- Edit C:\ProgramData\docker\config\daemon.json
- Add a line with "exec-opts":["isolation=hyperv"]
- Stop-Service docker
- Start-Service docker
