### ISSUE TITLE
ALOps Publish with Batch_publish > add batch_install parameter

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#135]
If we think of our product as a group of apps, our release pipelines would use the latest version of all the apps / artifacts to deploy the latest version of the 'product' to the different stages / environments.

The batch_publish option of ALOPS does a great job publishing all apps according their depencies. However, all the apps are automatically 'installed' as well. This is not always wanted behavior. We prefer to setup an environment where all the apps are published but not installed by default (since the consultant / customer should have the option to choose whether an app / functionality is needed or not). When installing only some of the apps, deploying an update of the full 'product' to this environment should still publish the newest version of the apps, but not automatically 'install' all of them.

E.g. we might think of including all optional modules (or 3rd party extension like 'Document Capture') as part of our full 'Product' release pipeline to an internal test / training / ... db, but it is not always wanted to have the app installed on all of these environments (or the customers environments).

Would it be an option adding a new 'batch_install' settings to ALOps Publish task with the option 'All' (will publish and install each app) or 'Previously Installed' (will publish all apps but only install those that had been previously installed on the target environment)

**Comment by waldo1001** [comment]
Makes sense - no promises, but I'll put it on the list!

**Comment by fvet** [comment]
@jcoe-nvt

**Comment by waldo1001** [comment]
As we talked about - we won't fix this.
