### ISSUE TITLE
ALOps Package Import documentation / best practices

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#136]
Is there any documentation / best practices available on how to use the 'ALOps Package Import'?

- Any best practice on where to store the configuration packages? We currently prefer to store them on an Azure Blob Storage account. (http://www.peterzentner.com/2019/09/03/adding-demo-data-to-your-apps/). Loading these upon install of the test app seems not to work, so we decided to embed an extra pipeline step.
- Where to make these packages available for ALOps to be aware? In the pipeline artifacts or docker container?
- How will ALOps detect which configuration packages (rapidstarts) to import / deploy (and which order)?
- Is the size / number of tables of the package important?
- Any ALOps template scripts available on how to copy Azure Blob content to the pipeline?

**Comment by fvet** [comment]
@daansaveyn

**Comment by waldo1001** [comment]
We have it in our build-pipeline, but apparently, we forgot to add it in the examples - i'll see what I can do!

**Comment by fvet** [comment]
Small question: For these steps to run ...

```
*** Start RapidStart Package Validation
*** RapidStart Package Handler: no configuration found, defaulting to all *.rapidstart packages
*** RapidStart Start Package Validation
*** RapidStart Configuration Loaded
    - UID        : 4039d54b-f776-4ced-ba37-b3b5ff211db7
    - Name       : --AutoGenerated--
    - Packages   : 0                               // >>>> Nothing to import
    - Tables     : 0
    - Records    : 0
    - Exceptions : 0
    - Valid      : True

```

... is it actually required by the script to update the service tier first?

```
*** Set Docker Container ErrorActionPreference = Stop
*** Create User for Invoke-NAVCodeunit
*** Switch ServiceTier to Windows Autentication)

```

Just wondering in case no *.rapidstart files had been found, that we might gain some time by not updating the NST authentication.

**Comment by waldo1001** [comment]
We're planning to make an example-yaml for this - would that work better?

The documentation for all parameters is already there.

**Comment by fvet** [comment]
The task itself only has 3 parameters and all of these are clear ;) If the example-yaml would contain steps / support to download configuration packages from Azure Blob, that would be nice!

I was especially curious on the _*** RapidStart Package Handler: no **configuration** found ..._ message, not knowing how / where to define a 'confguration'.
