### ISSUE TITLE
ALOpsDockerStart - Cannot find an overload for "GetObjectsForNativeVariants"

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#138]
Encountered the same issue as #40 today when applying the Windows updates on our build server.

```
Starting: Start Docker Container
==============================================================================
Task         : ALOps Docker Start
Description  : ALOps Docker Start
Version      : 1.429.1405
Author       : Hodor
Help         : Start Business Central docker container.
==============================================================================
*** Importing required PS-Functions
##[error]Cannot find an overload for "GetObjectsForNativeVariants" and the argument count: "1".
Finishing: Start Docker Container

```

![image](https://user-images.githubusercontent.com/25268332/84564230-37ee0480-ad61-11ea-9ae9-5de257bcebe4.png)

Restarting the server did not solve the issue. 

Had to re-install the build agent to unblock the pipeline failures. Although I definitly want to avoid that in the future.

**Comment by fvet** [comment]
@jcoe-nvt

**Comment by waldo1001** [comment]
You should disable auto updates on the build server, and isolate the buildserver accordingly.  Sorry about this - but this is out of our control.  Docker/Windows/MIcrosoft images are very tightly bound at this moment.

As I explained in another thread - there are steps being taken.  Most of it by Microsoft, by building their images competely different (always the right dependency on the host, while now, when you do a windows update, the generic layer might be incompatible).  

At this point, all I can point to is:
- don't do auto windows update, but schedule them, and make sure you can roll back.
- try hyper-v isolation.

When we release our .Net-version of ALOps, this is not going to be solving this issue - as it's out of ALOps's hands .. but it will also do something on the PowerShell-dependency that some scripts suffer from at this moment.. .

**Comment by fvet** [comment]
I did uninstall the Windows updates, although I can't be sure if we plan to install build agents on a customers server that updates will not have been installed already. 

Would be good if these recommendations were available on https://github.com/HodorNV/ALOps/blob/master/Documentation/installation.md so we could forward to our IT responsible on how to deploy/provision new build servers.

**Comment by waldo1001** [comment]
Could it be you enabled the debug-option of a pipeline?

We can't support that debug-option, I'm afraid.  The way we call powershell, it's not possible.

In an upcoming version (ALOps 2.0), we'll have this running.  But for now, please don't use the debug-option.

**Comment by fvet** [comment]
No, we didn't enable the debug-option. 
For your info, issue no longer occurs (on our buildserver) since we uninstalled the Windows updates.
