### ISSUE TITLE
No ALOps App Compiler output - AL Compiler Exit Code: -1073741502

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#139]
Output of the ALOps App Compiler normally contains info like below.

```
*** Starting AL Compiler...
*** App.Name         = Core
*** App.Publisher    = Navitrans
*** App.Compiler Path= C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe
*** Checking for Assemblies in App
*** Add Windows Assembly Path [C:\Windows\assembly]
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps\app" /out:"c:\Run\DevOps\Navitrans_Core_17.0.0.2110_APP.app" /fullpaths /ruleset:"c:\Run\DevOps\app\.vscode\nvt.ruleset.json" /assemblyprobingpaths:C:\Windows\assembly
*** AL Compiler Exit Code: 0
*** AL Compiler raw logs: Start
Microsoft (R) AL Compiler version 5.0.3.64355 Copyright (C) Microsoft Corporation. All rights reserved  Compilation started for project 'Core' containing '124' files at '13:19:9.27'.  c:\Run\DevOps\app\extensionsPermissionSet.xml(1,1): info AL1027: The file at location 'c:\Run\DevOps\app\extensionsPermissionSet.xml' matches the definition for 'PermissionSet'.  Compilation ended at '13:19:17.735'. 
*** AL Compiler raw logs: End
*** Start processing compile results.
c:\Run\DevOps\app\extensionsPermissionSet.xml(1,1): info AL1027: The file at location 'c:\Run\DevOps\app\extensionsPermissionSet.xml' matches the definition for 'PermissionSet'.

AlertCode Line RelativePath                    File                        AlertSource AlertMessage                    
--------- ---- ------------                    ----                        ----------- ------------                    
AL1027    1    app\extensionsPermissionSet.xml extensionsPermissionSet.xml AL Compiler The file at location 'c:\Run\...


*** Store compile log to [c:\Run\DevOps\compilelog.txt]
*** Start processing compile results done.
*** Transfer App Artifact from Docker container.
*** Transfer Compile Log from Docker container.
*** Attach Compile Log to Vsts Build info.
*** Process Compile results.
*** Process Compile results: retrieve status.
*** Transfer App file to Artifacts.
*** AL Compiler Finished.
***
*** Compile OK.
```

However, after reinstalling our Build Agent and rerunning the failed pipelines, the ALOps App Compiler seems not the compile the app any longer? No output. 

```
*** Starting AL Compiler...
*** App.Name         = Core
*** App.Publisher    = Navitrans
*** App.Compiler Path= C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe
*** Checking for Assemblies in App
*** Add Windows Assembly Path [C:\Windows\assembly]
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps\app" /out:"c:\Run\DevOps\Navitrans_Core_17.0.0.2178_APP.app" /fullpaths /ruleset:"c:\Run\DevOps\app\.vscode\nvt.ruleset.json" /assemblyprobingpaths:C:\Windows\assembly
*** AL Compiler Exit Code: -1073741502              // >>>>> ???
*** AL Compiler raw logs: Start

*** AL Compiler raw logs: End
*** Start processing compile results.
*** Compile OK.
*** Start processing compile results done.
*** Transfer App Artifact from Docker container.
##[error]Cannot find path 'c:\Run\DevOps\Navitrans_Core_17.0.0.2178_APP.app' because it does not exist.

```

**Comment by fvet** [comment]
@jcoe-nvt

**Comment by waldo1001** [comment]
We call the compiler.  Any output comes from the alc.exe .. .  That exit code comes from the alc.exe.  Not much we can do more.. .

First question that I need to ask - does the code compile?  I'm going to assume it does.

Also: alc.exe is also heavily influenced with the docker isolation.  Since you reinstalled your build agent - could you make sure it's in hyperv-isolation, as Microsoft indicates: "if it doesn't work, it will probably work with hyper-v isolation"?

In terms on Docker, a lot is about to change:
- Microsoft is working on a different way to provide Docker images
- we are working on abandoning PowerShell, an moving our logic to .Net.  This makes it less error-prone to things we don't have under our control in ALOps.. .

**Comment by fvet** [comment]
Actions taken / lessons learned:
- Tried settings the hyper-v isolation (it is installed on the VM), but the pipelines failed with 'CreateComputeSystem virtual machine could not be started because a required feature is not installed'. Don't have the backgroud / access to perform actions suggested on https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/#comment-2411, so I did not further look into this. 
- Uninstalled the windows updates (reverted back to January). Pipelines are running again ... Sigh :)

Would have been nice if all this was documented somewhere in the installation documentation on how to provision a build server.

TODO > https://github.com/HodorNV/ALOps/blob/master/Documentation/installation.md

**Comment by sriniGalway** [comment]
Hi Waldo, 

we are facing the same issue. We are currently using windows 2019 with containers.  There were three updates which we weren't able to uninstall as they were essential.
Iff we use windows 2016 OS then the agent doesn't appear in default agent pool.
Kindly advice.

Srini

**Comment by waldo1001** [comment]
Hi @sriniGalway,

I can't advice anything else than I already did above.
Did you try to use hyperv isolation?

**Comment by sriniGalway** [comment]
@waldo1001 Yes the Hyper-V is installed 
Get-WindowsFeature -Name Hyper-V
Display Name Name Install State
------------ ---- -------------
[X] Hyper-V Hyper-V Installed

Still fails with below error:
*** AL Compiler Exit Code: -1073741502
*** AL Compiler raw logs: Start

Kindly advice , if anything comes in mind

**Comment by waldo1001** [comment]
What I mean is: did you use hyper-v isolation mode for Docker:

here is an example:
```yaml
- task: Hodor.hodor-alops.alopsdockerstart.ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox:be-ltsc2019'
    accept_image_outdated: true
    enable_symbol_loading: true
    memory_gb: 6
    container_restart: always
    docker_parameters: '--isolation=hyperv'
```

**Comment by sriniGalway** [comment]
@waldo1001 Thanks for this piece. We are checking this and will get back.

**Comment by sriniGalway** [comment]
@waldo1001 This is amazing. Thanks. It worked after providing hyper-v isolation. Much appreciated with the help.

**Comment by waldo1001** [comment]
@fvet ,

We recently had this with another partner, and we re-installed the build agent, which solved it.  

Is this still an issue?

**Comment by waldo1001** [comment]
Hi @fvet, 

Can I point you to this blog for installing the build agent:
https://www.waldo.be/2020/07/13/installing-a-devops-agent-with-docker-with-the-most-chance-of-success/

Is it still an issue?

**Comment by fvet** [comment]
We'll look into it asap and create a new issue in case we would still face problems. Thx.
