### ISSUE TITLE
Artifact published while publish_artifact = false

### ISSUE THREAD

**Issue by jcoe-nvt** [HodorNV/ALOps#140]
I've disabled the publish_artifact option in the compile step to handle the publishing of artifacts myself. This works when app compiles without warnings. But in case of warnings, the compilelog.txt is still uploaded as artifact

![image](https://user-images.githubusercontent.com/49404625/84871807-46019500-b081-11ea-91e9-ce3e63fd1027.png)

**Comment by AdminHodor** [comment]
Dear @jcoe-nvt ,

We changed the behaviour for this as requested. If the parameter "PublishArtifacts" is set to False, the compile-log will not be uploaded anymore as the only artifact.

Please let us know if this fix works for you.

Kind regards,

**Comment by jcoe-nvt** [comment]
Thanks, fix is working.
