### ISSUE TITLE
ALOps Install/Compile/Publish Custom Base Application

### ISSUE THREAD

**Issue by InnoNavSupport** [HodorNV/ALOps#141]
Hi,
ist there a recommended way, how to install / compile / publish a custom base application with ALOps?

Best Regards
Daniel

**Comment by waldo1001** [comment]
Well, your custom base application would be yet another app.  So it should be treated as such.

What is the problem you're running against?

**Comment by InnoNavSupport** [comment]
The Upload of the Application into the Docker engine takes very long and never finish. 
(e.g. Screenshot 35min) 

I also limited the RAM Consumption with 12GB. 
![image](https://user-images.githubusercontent.com/62563638/84900969-1bc4cd00-b0ab-11ea-9ef1-8c000a1e9045.png)

![image](https://user-images.githubusercontent.com/62563638/84900552-8fb2a580-b0aa-11ea-8ee2-6172528e17a1.png)

**Comment by InnoNavSupport** [comment]
We Updated our Pipeline Server to an Windows Server 2019 and it works until Compile Extension. 
There we run into a lot of AddIn-Errors. **Is there a way to fix them,** 

I already tried to copy the C:\ProgramData\NavContainerHelper\Extensions\BC160xxx\.netPackages manuel into the docker environment, but still the same errors. 

Is there also a way to **get the current docker container name** during the Pipeline-Process to use it inside a custom powershell?

**Comment by InnoNavSupport** [comment]
I found, why I get this .net Missing DLL´s Errors.
During the Compile Process with the ALC.exe, there is no reference in the assemblyprobingpath to
- C:\Program Files (x86)\Microsoft Dynamics NAV\160\RoleTailored Client
- C:\Program Files\Microsoft Dynamics NAV\160\Service
after copying all the dll´s inside my c:\run\devops Folder in the Docker environment, the compile process was succesfull.

Is there a way to change the assemblyprobingpath manually?
Is there also a way to get the current docker container name during the Pipeline-Process to use it inside a custom powershell?

-

**Comment by waldo1001** [comment]
In next release, we have done some changes regarding this.  It seems that NST doesn't take right probing paths, while compiler does.  To solve this, we fixed the copy-step for "in-use" dlls, which should solve this as well.

We expect this release to be online this weekend.  Please report back next week.

**Comment by waldo1001** [comment]
In the next release (this week), we have a new compiler.  Not sure if this will help anything, but you'll be able to compile without Docker at least.  May be this will help a bit in your case.. .

**Comment by waldo1001** [comment]
Hi @InnoNavSupport ,

could you give this new compiler a go?
Examples can be found here:
https://github.com/HodorNV/ALOps/tree/master/Examples/Compiler%20V2

**Comment by waldo1001** [comment]
Microsoft has been having caching issues with the compiler, which should have been fixed in the next version of their compiler. 
We are adding an option to refer to another VSIX (like "next"), which might help you using an insider version of the compiler.

Do you have any feedback whether this is still a problem?

**Comment by waldo1001** [comment]
@InnoNavSupport ,

Since the latest compilers, this should be performing better.

Can you report back whether this is still a problem or not?
