### ISSUE TITLE
ALOps Install Testtoolkit not Working in BC Insider

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [HodorNV/ALOps#142]
It seems like Microsoft has added a new Dependency for the Testtoolkit

![image](https://user-images.githubusercontent.com/35697862/85666525-d6148f80-b6bc-11ea-8cc4-c11cbef22329.png)

**Comment by waldo1001** [comment]
Thanks!

That's solved and part of the next release!

**Comment by AdminHodor** [comment]
Dear @PatrickGrabensteiner ,

The fix for this is released today, apologies for the delay.
Please let us know if this fix works for you.

Kind regards,
