### ISSUE TITLE
Issue with a german special character

### ISSUE THREAD

**Issue by mrabus** [HodorNV/ALOps#145]
Hi all, 

I'm testing ALOps since a few days and came across a strange issue. 

I try to compile one PTE that has a dependency to the following PTE: 
![grafik](https://user-images.githubusercontent.com/2485163/86049610-bb427200-ba52-11ea-8de1-a9895ef5e972.png)

It works if I use "ue" as a replacement for the German "ü" in the publisher name. 
![grafik](https://user-images.githubusercontent.com/2485163/86032810-364a5f00-ba38-11ea-99c4-aba0f6d1dc5e.png)

The following output of the pipeline comes up when compiling the dependant app:
Invoke-RestMethod -Method Get -Uri https://257e176fcb75:7049/BC/dev/packages?publisher=B.i.TEAM+Gesellschaft+f%c3%83%c2%bcr+Softwareberatung+mbH&appName=easyPDF&versionText=1.0.0.0&tenant=default
##[error]Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."

If I reproduce the process in my local docker container downloading the symbols and compiling the app is possible. Then the request to download the symbols looks like this:
http://customername:7049/BC/dev/packages?publisher=B.i.TEAM Gesellschaft für Softwareberatung mbH&appName=easyPDF&versionText=1.0.0.0

Seems to me that escaping the "ü" causes the issue.

**Comment by mrabus** [comment]
Any idea? @waldo1001?

**Comment by waldo1001** [comment]
Well - actually how VSCode does it, is an "illegal" URL :-/, so we'll have to do this as well.

What we will probably do is to create a global variable that you can set to disable UrlEncode.  Would that work for you?

**Comment by mrabus** [comment]
That would be the perfect solution. 

No pressure - buuuut can you give me a timeline for it?  :-)

**Comment by waldo1001** [comment]
It's a small fix - depending on Marketplace validation (which is haunting us for the moment), we'll try to release it this weekend.

**Comment by mrabus** [comment]
Do you know if it was included in today's release?

**Comment by waldo1001** [comment]
Well, it's going to be included in the next release - but Microsoft has changes the validation process.  We can't get the release validated at the moment, and Microsoft isn't really telling us why :-/.  We're looking into it..

**Comment by mrabus** [comment]
The update was rolled out. Do you know the name of the new global to prevent the encoding?

**Comment by waldo1001** [comment]
It's not, I'm afraid. 
The date that it's reporting gets updated even when the validation process is running .. makes no sense.
As long as the version says 1.429, it's not correct - we're trying to push 1.430.
VSMarketplace-support is completely unresponsive :(.

**Comment by AdminHodor** [comment]
Dear @mrabus ,

We managed to get our release to the Marketplace back up-and-running, big thanks to the Microsoft support team.

For the issue with the character convert we introduced a new global boolean parameter/variable  "alops_disable_urlencoding".
The default is set to "false", setting this variable to "true" will disable the Url-Encoding.

Please let us know if this works for you.

Kind regards,

**Comment by mrabus** [comment]
Currently, I'm struggeling with issue #154. Will provide feedback after that is sorted out.

**Comment by mrabus** [comment]
I'm having a related issue with special characters with my pipeline: 

The app has no dependencies (besides System & Base App) and compiles just fine but transfering to artifacts leads to the following error: 
*** Start processing compile results done.
*** Transfer App Artifact from Docker container.
##[error]Cannot find path 'c:\Run\DevOps\B.i.TEAM Gesellschaft fÃ¼r Softwareberatung mbH_easyPDF_1.0.202029.341.app' because it does not exist.

The problem is reading my app.json: 
![grafik](https://user-images.githubusercontent.com/2485163/87776767-90b13100-c828-11ea-83b4-0bfc1b054391.png)

It is read in the task "Compile Extension" as follows:
*** Starting AL Compiler...
*** App.Name         = easyPDF
*** App.Publisher    = B.i.TEAM Gesellschaft fÃ¼r Softwareberatung mbH
*** App.Compiler Path= C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe

Can you please look into it or do you want me to open a new issue?

**Comment by mrabus** [comment]
Any ideas? 

The flag "alops_disable_urlencoding" did not solve it unfortunately.

**Comment by mrabus** [comment]
@AdminHodor or @waldo1001? Any ideas how we will proceed with the issue?

**Comment by AdminHodor** [comment]
Dear @mrabus ,

We tracked down the issue to an Encoding step that was ignoring UTF8, Fix for this is available for the next release.
Currently we are creating some test-pipelines with unicode characters for validation. We should be able to get the release
on the marketplace by Thursday at latest.

Kind regards,

**Comment by AdminHodor** [comment]
Dear @mrabus ,

The new version v1.431.1520 is released as we speak and is available on the marketplace.
We applied some changes to the encoding for Json files, which should mitigate this issue.

Could you please validate again? 

Kind regards,

**Comment by mrabus** [comment]
Looks fine to me, thanks a lot
