### ISSUE TITLE
ALOpsAppPublish Change Sync-Mode not possible

### ISSUE THREAD

**Issue by InnoNavSupport** [HodorNV/ALOps#146]
Hi,
is there a possibility to change the ALOpsAppPublish Modus from Syncronize to ForceSync?
Changeing the MS Base Application to a Custom MS Base Application requires to Force the schema.

![image](https://user-images.githubusercontent.com/62563638/86230627-9d2f5b80-bb91-11ea-9b49-b48dcce15eae.png)

**Comment by waldo1001** [comment]
No there isn't .. and it's actually quite intentional, because facilitating a "force" in a build pipeline is very bad practice .. OnPrem and SaaS.  We strongly recommend to "force" manually ... and avoid as much as possible.. .

Can you give me your business case?

**Comment by waldo1001** [comment]
We'll put it on the agenda!

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport ,

We extended the "ALOpsAppPublish" task with a new boolean parameter "forcesync". Could you please validate if this solution works for you? The enchancement is available from ALOps v1.431

Kind regards

**Comment by JohnnyUndercover** [comment]
I tried to publish using forcesync but i get the following error:
![image](https://user-images.githubusercontent.com/30835996/88817545-ed640280-d1bd-11ea-89c4-e83bd082506a.png)

**Comment by waldo1001** [comment]
@JohnnyUndercover , the fix is part of the next release!  Thanks for notifying us!

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport,

We implemented a fix for this, could you please validate the workings?

Kind regards,
