### ISSUE TITLE
New Version of the Compile task to save Artifacts to PipelineArtifacts

### ISSUE THREAD

**Issue by pri-kise** [HodorNV/ALOps#148]
Could you add a new version or a setting for the compile task to save the Artifacts as Pipeline Artifacts instead of BuildArtifacts
(see: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
([Difference of Build and Pipeline Artifacts](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2341))

**Comment by waldo1001** [comment]
We'll look into it - can you give me a business case why you want this?

**Comment by pri-kise** [comment]
We have mutiple Repositories in one project and we need to Download the Artifacts of one pipeline of this project to another pipeline of the same project (The pipelines of the different repositories). 

Now we have the problem that the Task DownloadBuildArtifacts has problems to Download the Artifacts for this specific case.

We are able to Download Artifacts from other Projects Pipelines and from the same Pipeline (e.g. previouse version), but the Download does not work from other Pipelines of the same Project.
Since Microsoft annoucned that the Download and Upload Pipeline Task should replace the BuildArtifact tasks, I guess that they won't try to solve this issue.
At the moment it is  still possible to Download BuildArtifacts with the DownloadPipelineArtifacts Command, but it results in a warning that mention to use the PublishPipelineArtifacts Command.

**Comment by waldo1001** [comment]
It looks like you have a problem with your DevOps setup, and build artifacts would be a workaround.

Suggestion:
on the compile-step, you could disable the "publish_artifact", and you could introduce the default devops "publish artifacts" step to publish whatever file you want.

**Comment by AdminHodor** [comment]
We just release v1.433.1659, can you check if this works for you?

Kind regards,
