### ISSUE TITLE
'ALOps Docker Wait' step is slow

### ISSUE THREAD

**Issue by jcoe-nvt** [HodorNV/ALOps#151]
Our base application is our biggest app and logically it's corresponding pipeline is 1 of the longest running ones.

I've analysed the process in order to see where we could gain some time.
We lose quite some time on the 'ALOps Docker Wait' step.
More specific in copy of the working folder to the container:

![image](https://user-images.githubusercontent.com/49404625/87305937-8e449380-c517-11ea-9707-7847a7d94ee3.png)

Most of the time is spent on compressing and expanding the workfolder. Copying the compressed file to the container takes less then 10 seconds. But when I set usecompression: false, then this step requires 6 minutes.

I don't know what method is used to compress the working folder, but I think the key to a faster 'ALOps Docker Wait'-step might be found there. I'm able to compress the 4911 files (214 MB) to 1 file (18MB) in less then 10 seconds using the default windows (un)-zip-functionality. (Test performed on same build server)

**Comment by AdminHodor** [comment]
Dear @jcoe-nvt ,

For the compression we use the default "Compress-Archive" and "Expand-Archive" from Powershell.
We are aware there are reports about slow performance on these cmdlets in specific Powershell versions.

To mitigate this we could switch to the Dotnet variant for Compression, which should be significantly faster.
We'll investigate asap and let you know if we can provide this enhancement in the near future.

Kind regards,

**Comment by waldo1001** [comment]
Latest release (1.432.1540) should be faster.  Can you confirm?

**Comment by AdminHodor** [comment]
Dear @jcoe-nvt ,

We replaced the powershell ZIP entirely with the dotnet version, both on the agent and container side.
Depending on the amount of files in your solution, we can see a 2x to 8x decrease in time required.

Kind regards,

**Comment by jcoe-nvt** [comment]
@AdminHodor: Time has indeed decreased since that update. The docker wait step went from ~3min40 to ~1min40. Thanks for this enhancement.
