### ISSUE TITLE
AlOps Compile App - Download Symbols Error

### ISSUE THREAD

**Issue by TroelsMuffThygesen** [HodorNV/ALOps#152]
Hello
If I am not mistaken AlOps was updated today and I think this might be the reason why one of our pipelines suddenly failes.
It seems that the error is that it is no longer possible to download symbols for one of our dependency apps possibly because we use an & in our publisher name:
![image](https://user-images.githubusercontent.com/64460327/87669036-8847f000-c76d-11ea-82ab-f70666b2c189.png)

Yesterday everything was working fine and then the log looked like this:
![image](https://user-images.githubusercontent.com/64460327/87669100-a6adeb80-c76d-11ea-89cc-8b9e5281b7db.png)

As you can see the '&' sign is no longer replaced by '%26' and the '/' is not replaced by '%2f'. 

Can you see if this is caused by something you have changed in the release today?

BR Troels Muff Thygesen

**Comment by mrabus** [comment]
Hi, 

I think that is related to my issue #145. ALOps wants to introduce a new global variable to determine if an encoding is necessary. 

Wait for the updated docu and check if that solves the issue

**Comment by AdminHodor** [comment]
Dear @TroelsMuffThygesen ,

Thanks for noticing and reporting, it's indeed a bug related to #145 .
We instantly created a hotfix for this, which is already released on the marketplace (v1.431.1511). 
Please not it can take a couple of pipeline run for DevOps to pickup and download the new version.
With this the fix, the default behaviour for encoding Urls is re-enabled. 

To disable the Url-Encoding, the boolean variable "alops_disable_urlencoding" can be set to "true" (Issue #145 )

Apologies for the inconvenience.

Kind regards,

**Comment by TroelsMuffThygesen** [comment]
We now get the same issue is reported in #154.

**Comment by TroelsMuffThygesen** [comment]
It is working again now.
