### ISSUE TITLE
after update of alops pipeline ALOps Compile Extension: App fails with Get-VstsTaskVariable' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#154]
*** Propagated Dependency: Microsoft - System Application - 1.0.0.0
*** Propagated Dependency: Microsoft - Base Application - 16.0.0.0
*** Download System-Symbols for [16.0.0.0]

term 'Get-VstsTaskVariable' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by sriniGalway** [comment]
we are facing the same issue. Need help in updating the required powershell script accordingly.

**Comment by pri-kise** [comment]
We are facing the same problem 

> The term 'Get-VstsTaskVariable' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by mrabus** [comment]
Having exactly the same issue

**Comment by dNsl9r** [comment]
Same issue here.

**Comment by gintuoklis** [comment]
having the sames issue too

**Comment by pri-kise** [comment]
For me, this happens only for Pipelines where we  publish the previous version before the compile task.

**Comment by PatrickGrabensteiner** [comment]
We have the same issue we need an urgent fix

**Comment by waldo1001** [comment]
We are aware of the problem ... and are truly sorry for this .. we are working on resolving it asap.

**Comment by titofffffff** [comment]
same issue on my side, it was working yesterday

**Comment by waldo1001** [comment]
Fix should be online.  Version 1.431.1514.  Please report back if the problem persists!  And thanks for reporting this - the problem did not pop up in our test-pipeline because of a stupid reason we didn't think of - which we are changing as we speak in our build/release system as we speak.  Things like this should not happen :(.

**Comment by titofffffff** [comment]
I confirm it's ok.

Thank waldo, you saved my vacation :)

**Comment by waldo1001** [comment]
We didn’t save it, we made it a bit stressful.  And for that I apologise.

We put a lot of effort in avoiding situations like this... but I guess it had to happen some time.  At least we learned a lot from it ... this will not happen again ;-).

**Comment by pri-kise** [comment]
Is there a way to tell the build agent to use the latest version of a task? The Build Agent is still using the Version 1.431.1511 of the Compile Task although the extension was updated on Azure DevOps

**Comment by gintuoklis** [comment]
I guess you are trying to rerun failed job. When you do rerun, it will always run on original context it was created. That includes artifacts, and script versions. Just trigger new job run, and it will pick up latest version

**Comment by pri-kise** [comment]
@gintuoklis thanks. This was exactly my probem.

**Comment by waldo1001** [comment]
Thanks, @gintuoklis , I didn't know that ;-)
