### ISSUE TITLE
UICop analyser not detected

### ISSUE THREAD

**Issue by sriniGalway** [HodorNV/ALOps#156]
Hi Waldo,

We are trying to utilise the PerTenantExtensionCop and UICop AL analyser.
The AL Ops compiler detects the PerTenantExtensionCop analyser but not the UICop.

Pipeline:
- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    targetproject: 'XXX/app.json'
    setup_working_folder: true
    failed_on_warnings: false 
    al_analyzer: PerTenantExtensionCop,UICop
    app_file_suffix: '_APP'

Warning:
** Starting AL Compiler...
*** App.Name         = XXX
*** App.Publisher    = XXX
*** App.Compiler Path= C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe
*** Checking for Assemblies in App
*** Add Windows Assembly Path [C:\Windows\assembly]
*** Searching CodeCop: PerTenantExtensionCop
*** Codecop found: C:\Run\Microsoft.al\al-ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.PerTenantExtensionCop.dll
*** Searching CodeCop:  UICop
##[warning]Codecop not found:  UICop

Kindly advice.

**Comment by sriniGalway** [comment]
There was space in between the analyser
as is: al_analyzer: PerTenantExtensionCop, UICop
expected: al_analyzer: PerTenantExtensionCop,UICop

This resolved the issue.

**Comment by waldo1001** [comment]
Thanks!  I didn't notice it :(.
