### ISSUE TITLE
[Feature Suggestion] ALOps Sync Translate

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#159]
It would be nice if ALOps could provide some tools / scripts to ease the AL translation experience:

- Schedule a build pipeline (per app) that compiles the app and generates the g.xlf file 
- Sync the g.xlf changes to any target language xlf files. (in combination with https://github.com/rvanbekkum/vsc-xliff-sync/issues/31 ?)
- In case of any xlf file updates, create a new branch with the updated xlf file to be translated.

**Comment by fvet** [comment]
@kasperdj, I've noticed the GenerateXliffFiles step in one of your pipelines. Is this something worth sharing ;) ?

```
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# EV: Generate Xliff files
- template: 'OnPrem-Builds/GenerateXliffFiles.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

**Comment by rvanbekkum** [comment]
@fvet Looks like it does an initial build to get the latest `.g.xlf` file from the compiler. Looking at the output in https://github.com/HodorNV/ALOps/issues/185 the script also writes something to a file for target language `da-DK`.
```
2020-08-26T09:43:39.2488244Z Generating Xliff files using AL Compiler: C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe
2020-08-26T09:43:39.8226961Z Start Build 'EV Customizations' With Compiler Version: 1.0.0
2020-08-26T09:43:40.9218646Z Build Complete 'EV Customizations'
2020-08-26T09:43:40.9611067Z Generate Xliff for EV Customizations.g.xlf
2020-08-26T09:43:41.0952120Z Write File: EV Customizations.da-DK.g.xlf
```
I'm also curious to know if this does something that might be useful.

**Comment by kasperdj** [comment]
@fvet & @rvanbekkum nice to see the outcome of your reverse enginnering of my pipeline output.

In short we have built our own VS Code Extension that is available on the Market Place:

![image](https://user-images.githubusercontent.com/54669593/91637196-0ce18b80-ea07-11ea-9bc0-27abbc6ba4af.png)

A nuget packet of this tool is installed in Docker Continer in of my steps. Furthermore, we use the developer comments in AL on captions, labels etc. to specify the Danish caption in our case (the tool support multiple languages but we typically deliver solution in English and Danish) and then after the standard ALOps Compile step, we run an extra step which generates the Danish translations based on the developer comments. The last additional step is a re-compilation of the app to get the Danish xliff embedded in our app :-)

You can look at our VS Code Extension and with some additional reverse engineering, you can find the powershell scripts that does the magic.

We do this to put the Language/ML Caption back in control with the developer - just like in C/Side.

**Comment by rvanbekkum** [comment]
@kasperdj Thanks for your reply. I found the source of the step here: https://bitbucket.org/Jens_R_Rasmussen/business-central-development-tool/src/master/Source/PowerShell%20Module/AL/Invoke-EVGenerateXliffFiles.ps1
Summarized: takes the `.g.xlf` generated by the compiler, iterates through the trans-unit nodes in that file, parses the translation from the Developer note (i.e., matching the `Comment` from the AL source code, e.g., `DAN=Min oversættelse|NLD=Mijn vertaling`) in each-transunit and add the translation as the text of the target-node of the trans-unit, then finally saves the result to a new `.xlf` file for that language.

There are others that take the same approach for translation as well (see https://github.com/rvanbekkum/vsc-xliff-sync/issues/37) 😉. A benefit of doing it this way is that you can leave the .xlf files out of your repository and have your pipeline handle the creation of the translation files that will be used in your AL .app.
