### ISSUE TITLE
Unpublish all extensions in container

### ISSUE THREAD

**Issue by JeppeBylov** [HodorNV/ALOps#161]
Hi,

I'm in the process of making a build pipeline for a modified baseapp (Waldo already hinted to me on twitter, that it might be stupid :D).
To do this i need to unpublish all extensions and publish a new modified baseapp.

I've tried multiple different approaches, let me briefly explain:

1. ALOpsDockerStart, ALOpsDockerWait, ALOpsLicenseImport, ALOpsAppClear
- This seems to do some sort of uninstall of apps, but if i don't remove the container at the end, but open it manually and do Get-BCContainerAppInfo i still get all sorts of apps.
2. AlOpsDockerStart, ALOpsDockerWait, ALOpsLicenseImport, Powershell -> Clean-BCContainerDatabase
- In this approach i do a powershell step that runs Clean-BCContainerDatabase against the latest created container. 
- This fails with an error from NAVContainerHelper that says container must be started with a developer license (even though i do LicenseImport. Works if Import-BCContainerLicense is run manually)
3. AlOpsDockerStart, ALOpsDockerWait, ALOpsLicenseImport, Powershell -> ImportLicense/Clean-BCContainerDatabase
- I would have thought that this would have worked, but it seems the container is created without NavContainerHelper, as the C:\programdata\navcontainerhelper\.. folders don't exist and as such the license import fails.

So i'm kind of at the point of trying to make the pipeline from scratch. 
That is unless you can help me resolve any of the above issues 👍 

i'll share pipelines and everything needed, when necessary.
Thanks in advance.

**Comment by waldo1001** [comment]
Hi @JeppeBylov ,

we are currently fully dedicated on making the Artifacts work in ALOps, and since we don't have any repro ourselves for this, it hasn't been easy to look into this.  

Is there an updated status on the issue?  Or is the question still open?

**Comment by waldo1001** [comment]
Hi @JeppeBylov ,

wa found a possible solution for this issue .. we'll add a parameter in the "ALOpsAppClear" to remove the Microsoft-apps as well (which it doesn't indeed).  It should be release this week.

**Comment by AdminHodor** [comment]
Dear @JeppeBylov ,

We just released v1.435.1864, now there is an extra boolean parameter [includemicrosoftapps] which when enabled will also remove the Microsoft apps.
Please note it could take a couple of pipeline runs for DevOps to pickup the new version.

Kind regards,
