### ISSUE TITLE
How to use Shared Access Signature token in ALOps

### ISSUE THREAD

**Issue by dNsl9r** [HodorNV/ALOps#162]
Related to working with artifacts the login for the Insider Builds changed from username & passwort to SAS token.
My first try, just using it without username in the service connection did not work.

How can I use the SAS token to get the latest insider builds with ALOps?

**Comment by waldo1001** [comment]
Hi Danis,

You can't just yet.  We're still working on supporting the new artifacts in ALOps.  We need to do this so we can support this in build pipelines, so it's a bit different than "just" using bccontainerhelper... .  Stay tuned!

**Comment by dNsl9r** [comment]
Hi Eric,
thanks - do you have any milestone planning when this will be available? 👍

**Comment by waldo1001** [comment]
It NEEDS to be live before Microsoft doesn't publish the old way of images anymore.  So August is the absolute deadline for us.

**Comment by waldo1001** [comment]
(end of August, that is ;-))

**Comment by waldo1001** [comment]
But .. do know you can already build your own image in PowerShell, and refer to that one within ALOps.  So there is a way around already (just an extra step to built the image).

**Comment by dNsl9r** [comment]
> But .. do know you can already build your own image in PowerShell, and refer to that one within ALOps. So there is a way around already (just an extra step to built the image).

I'll check this out. Any links / documentation for this?

**Comment by DanielGoehler** [comment]
> (end of August, that is ;-))

@waldo1001 So no out-of-the-box build pipelines tests of the August Updates, which might be relased next week, until End of August? Ref: https://freddysblog.com/2020/07/05/july-updates-are-out-they-are-the-last-on-premises-docker-images/

**Comment by waldo1001** [comment]
Just look for the "New-BcImage" CmdLet in the bccontainerhelper (execute it on the docker host (= build agent machine).

By the way - this is theory - but should work ;-)

**Comment by waldo1001** [comment]
> > (end of August, that is ;-))
> 
> @waldo1001 So no out-of-the-box build pipelines tests of the August Updates, which might be relased next week, until End of August? Ref: https://freddysblog.com/2020/07/05/july-updates-are-out-they-are-the-last-on-premises-docker-images/

I don't understand the question?

**Comment by DanielGoehler** [comment]
In his blog post Freddy said, with July Update the last Business Central container were created. Usally the next August Updates (like Business Central 16.4) might be released next week, but only as artifacts. If your deadline is End of August, this means I could test Business Central 16.4 maybe not until the end of august. Otherwise I would have to create docker images (New-BcImage) on the Build Agent Servers.

**Comment by waldo1001** [comment]
Well .. we never did build our own images during a build pipeline .. so we need time.  Sorry for this. We'll do our best to make it earlier!

**Comment by DanielGoehler** [comment]
Please, don't feel sorry, Freedys first announcement was posted one month ago on June 25, 2020. For my taste  very short notice announcement this kind of change.

We wouldn't create the image during build pipeline. I didn't test this yet. If you create your own docker image on all Build Agents,
```
$artifactUrl = Get-BCArtifactUrl -country "us" -version "16"
New-BcImage -artifactUrl $artifactUrl -imageName myownimage:latest
```
we should been able to use this in the pipeline:
```
- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'myownimage:latest'
    memory_gb: '6'
    docker_parameters: '--isolation=hyperv'
    accept_image_outdated: true
```

**Comment by waldo1001** [comment]
exactly

**Comment by dNsl9r** [comment]
Could create the image, but there seems to be a permission problem:
`##[error]Error response from daemon: pull access denied for mybcnextmajor, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

I'll try some more maybe I'll get it up and running 😃

**Comment by waldo1001** [comment]
Can you share the yaml?

Did you switch off "always pull"?

**Comment by dNsl9r** [comment]
Sure,
I can share the relevant part.
`  jobs:
  - job: CreateBuildImage
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Import-Module navcontainerhelper
          $sasToken = "call me a token"
          $artifactUrl = Get-BCArtifactUrl -country de -storageAccount bcinsider -sasToken $sasToken
          New-BcImage -artifactUrl $artifactUrl -imageName mybcnextmajor:de

  - job: StartDockerContainer
    dependsOn: CreateBuildImage
    condition: succeeded('CreateBuildImage')
    steps:
    - task: ALOpsDockerStart@1
      inputs:
      docker_image: mybcnextmajor:de
      accept_image_outdated: true
      enable_symbol_loading: true
      docker_pull: false
      docker_parameters: '--isolation=hyperv'
      memory_gb: '5'
`

**Comment by waldo1001** [comment]
We'll look at it!

Could you try to provide the "docker_registry: localhost" parameter?  I think it's the default value that's causing this.. .

**Comment by waldo1001** [comment]
Can you please provide the complete output?  Because I'm not sure where it fails..

**Comment by dNsl9r** [comment]
Sure, I will on Monday 👍🏻

**Comment by dNsl9r** [comment]
Added *docker_registry: localhost*, full log:

```
Starting: ALOpsDockerStart
==============================================================================
Task         : ALOps Docker Start
Description  : ALOps Docker Start
Version      : 1.431.1527
Author       : Hodor
Help         : Start Business Central docker container.
==============================================================================
*** Importing required PS-Functions
*** Validate configuration
*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
*** Pull Docker Image: mybcnextmajor:de
##[error]Error response from daemon: pull access denied for mybcnextmajor, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Finishing: ALOpsDockerStart

```

**Comment by waldo1001** [comment]
Hi @dNsl9r ,

I'm puzzled.  I just set this up for myself, and it works as expected:
https://dev.azure.com/msdyn365bc/DynamicsCon/_build?definitionId=37

I'm still working to get the repo compileable, but the part to create an image with bccontainerhelper, and use it with ALOps is just working as expected.. .

**Comment by dNsl9r** [comment]
Hi waldo, strange that it's working with your example.
I took a look on the YAML logs of your steps and I have to admit that I am confused about this in ALOpsDockerStart:

```
*** Importing required PS-Functions
*** Validate configuration
*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
*** Pull Docker Image: bccurrent:be
Error response from daemon: pull access denied for bccurrent, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
*** Pull Docker Image: bccurrent:be [OK]

"docker" run --detach --env accept_eula=Y --env accept_outdated=Y --restart no --label TFSBuild=DesignPatterns_585 bccurrent:be
*** Container Started: e4517b9e70866386dccba0a0110074918f0c6645e4ec17e9c38d8cb6cd256a4e
*** Container Labels:

```

There is also the error "pull access denied" - but the step is trying a second time and now successful? 🤔

**Comment by waldo1001** [comment]
Yes, I've seen that .. .  Pipeline is very simple though ..

```yaml
name: $(Build.BuildId)

pool: WaldoHetzner

variables:
  - group: Secrets
  - name: AppVersion
    value: '1.0.[yyyyWW].*'
  - name: DockerImageName
    value: bccurrent:be


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Import-Module bccontainerhelper
      $artifactUrl = Get-BCArtifactUrl -country be
      New-BcImage -artifactUrl $artifactUrl -imageName $(DockerImageName)

- task: ALOpsDockerStart@1
  inputs:
    docker_image: $(DockerImageName)
    docker_pull: false

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

```

**Comment by dNsl9r** [comment]
Any idea why there is the second attempt?  I changed my ALOpsDockerStart to the same steps that you are using - still failing after one attempt..
Another question: Why is the step trying to pull when "docker_pull" is set to false?

**Comment by waldo1001** [comment]
No idea - investigating.  Did you try to run it today?

**Comment by waldo1001** [comment]
Can you check the DockerStart-step that you're on "1.431.1527"?

**Comment by dNsl9r** [comment]
Just ran it 10 minutes after you posted your (working) example 😉 
DockerStart says I'm using: 1.431.1527

**Comment by waldo1001** [comment]
Found why it did that (you don't want to know... :-))- should be released tomorrow morning ... .

I also read that error-catching works is very dependent on the build agent - let's hope it solves your problem.. .

**Comment by dNsl9r** [comment]
Until now, there was no new Release of ALOps, right? 🤔

**Comment by waldo1001** [comment]
Not yet, sorry .. we're trying to put the DLL-fix in the same release.. .

I'll see what I can do..

**Comment by waldo1001** [comment]
We're pushing an intermediate release - try again in 30mins.

**Comment by dNsl9r** [comment]
Works like a charm 😄
