### ISSUE TITLE
Deployed Version Check

### ISSUE THREAD

**Issue by sriniGalway** [HodorNV/ALOps#166]
Hi Waldo,

Can I check two things based on the deployment failure we had last week,

1. Below is the snippet of the deployment.
we had 1.0.0.8 version of XXXX deployed in release 1 using ALOps Extension API task (basic Auth)
and then in release 2, we again deploy v 1.0.0.8 version of XXXX using ALOps Extension API task (basic Auth) which one of the component deployment as part of the release 2 and we end up with Operation Failed.

```
2020-07-31T15:47:00.7689622Z name publisher appVersion operationType schedule status startedOn
2020-07-31T15:47:00.7702650Z —- ——— ———- ————- ——– —— ———
2020-07-31T15:47:00.7710617Z AAAA BBBB 1.0.0.8 Upload Immediate Completed 2020-07-31T15:44:10.643Z
2020-07-31T15:47:00.7719780Z YYYY BBBB 1.0.2.3 Upload Immediate Failed 2020-07-31T15:31:54.49Z
2020-07-31T15:47:00.7727723Z ZZZZ BBBB 1.0.4.3 Upload Immediate Completed 2020-07-31T15:45:36.377Z
2020-07-31T15:47:00.7736382Z XXXX BBBB 1.0.0.8 Upload Immediate Failed 2020-07-31T15:47:00.47Z

```
is there a way to mitigate this scenario.

2. In ALOps Extension API task (basic Auth), is there an option to check whether version 1.0.0.8 version of XXXX is already deployed and hence no need to deploy it again in release 2.

Thanks in advance.

Regards
Srini

**Comment by waldo1001** [comment]
The log you post above, doesn't seem familiar - it isn't an ALOps log.. is this your PowerShell?

In BC you can see why those apps failed (deployment status - page 2508).
Also in the output in devops, it should say if a deployment failed.

Regarding publishing:
In a way, ALOps should automatically do what you said: if the version is already published, it will not publish it again.

**Comment by waldo1001** [comment]
The ALOps Publish step has a "Batch Deploy" option, which will do everything for you.. .

**Comment by sriniGalway** [comment]
Waldo,

Thanks for the reply.
It is ALOps log from ALOps Extension API task in release pipeline.

Below is details from BC on deployment failure:
Error details for Operation Failed. A different .app file with the same App ID (b0a7c46a-77a3-4385-a34f-4ea80173e378) and version (1.0.0.8) has already been uploaded to an environment in our service. Please verify that the App ID assigned to this extension is the correct one, increment the version number to one that has not been used, and redeploy the package. Read more here https://go.microsoft.com/fwlink/?linkid=2128807 .

We have dependency of app XXXX dependant on YYYY. Hence we are deploying the apps one by one rather than batch deploy.
Kindly advice based on error posted above and with the dependency we have with apps.

Thanks in advance.

**Comment by waldo1001** [comment]
Can you share screenshots or yaml from the setup?  It doesn't make sense this is an ALOps step

It says exactly what you need to do: increment the version :-).  Why don't you?

YOu can safely batch deploy with multiple apps.  We batch deploy with +25 apps every hour - no problem.. .

**Comment by sriniGalway** [comment]
Waldo,
Attached is the screenshot for reference.  I had to update app names in screenshot.
https://ibb.co/6vY3k2T

We have incremented version of all apps and freshly initiated a release, This has same issue.

We could try batch deploy after bumping the version and let you know. but will the batch deploy take care of the dependency apps? Kindly advice

Thanks.

**Comment by waldo1001** [comment]
Batch deploy takes care of dependent apps indeed.

Ah, this seems to be BC SaaS.

Please share your build as well - as that's where you should handle the version of your apps.

And share the settings of your release pipeline.

thx!

**Comment by sriniGalway** [comment]
Thanks for confirming that the batch deploy takes care of dependent apps.
yes it is BC SaaS.
As mentioned, we have dependency of app XXXX dependant on YYYY.

Build pipeline YYYY app:
`name: $(Build.BuildId)

trigger: none

pool: Default

variables:
  - name: version
  - group: license

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019'
    accept_image_outdated: true
    enable_symbol_loading: true
    memory_gb: 6
    docker_pull: true
    container_restart: always
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bcdeploylicense)

- task: PowerShell@2
  displayName: 'Get version from app.json'
  inputs:
    targetType: 'inline'
    script: |
      $app_content = Get-Content './YYYYY/app.json' -raw | ConvertFrom-Json
      $version=$app_content.version

- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '$(version)'
    targetproject: './YYYY/app.json'
    setup_working_folder: true
    failed_on_warnings: false 
    al_analyzer: PerTenantExtensionCop,UICop

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: 'YYYY_*.app'
    skip_verification: true 

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()`

Build pipeline XXXX app:
`name: $(Build.BuildId)

trigger: none

pool: Default

variables:
  - name: version
  - group: license

steps:
  - checkout: self
    clean: true

  - task: ALOpsDockerStart@1
    displayName: 'ALOps Docker Start'
    inputs:
      docker_image: 'mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019'
      accept_image_outdated: true
      enable_symbol_loading: true
      memory_gb: 6
      docker_pull: true
      container_restart: always
      docker_parameters: '--isolation=hyperv'

  - task: ALOpsDockerWait@1
    inputs:
      search_string: 'Ready for connections!'

  - task: ALOpsLicenseImport@1
    inputs:
      usedocker: true
      license_path: $(bcdeploylicense)
      print_license_info: true

  - task: DownloadBuildArtifacts@0
    displayName: 'Download YYYY from specific branch'
    inputs:
      buildType: 'specific'
      project: 'abcdefg-hijk-lmno-pqrs-tuvwxyz'
      pipeline: '71'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latestFromBranch'
      allowPartiallySucceededBuilds: true
      branchName: $(Build.SourceBranch)
      downloadType: 'specific'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: ALOpsAppPublish@1
    inputs:
      usedocker: true
      nav_artifact_app_filter: '*.app'

  - task: PowerShell@2
    displayName: 'Get version from app.json'
    inputs:
      targetType: 'inline'
      script: |
        $app_content = Get-Content './XXXX/app.json' -raw | ConvertFrom-Json
        $version=$app_content.version

  - task: ALOpsAppCompiler@1
    displayName: 'Compile Extension'
    inputs:
      usedocker: true
      nav_app_version: '$(version)'
      targetproject: './XXXX/app.json'
      setup_working_folder: true
      failed_on_warnings: false
      al_analyzer: PerTenantExtensionCop,UICop

  - task: ALOpsAppPublish@1
    displayName: 'Publish AL-App'
    inputs:
      usedocker: true
      nav_artifact_app_filter: 'XXXX_*.app'
      skip_verification: true

  - task: ALOpsDockerRemove@1
    displayName: 'Remove Docker Container'
    enabled: true
    condition: always()`

Release pipeline setting with batch deploy in Yaml (we use the UI based release pipeline):
`steps:
- task: Hodor.hodor-alops.ALOpsExtensionAPI.ALOpsExtensionAPI@1
  displayName: 'ALOps Extension batch publish'
  inputs:
    usedocker: true
    interaction: batch
    api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/abcdefg-hijk-lmno-pqrs-tuwxyz/integration/'
    authentication: basic
    azure_tenant_id: 'tuwxyz-pqrs-lmno-hijk-abcdefg'
    username: 'adminuser'
    password: '$(credential)'`

**Comment by sriniGalway** [comment]
want to update that-
The show deployment status check box is enabled.
due to this it shows failure from past deployment.
However the current version of deployment is success for all apps.

Kindly advice to mitigate this.

**Comment by AdminHodor** [comment]
Dear @sriniGalway ,

Could you please try again with our latest release v1.432.1569, we made a fix for this. Now only the current versions for deploymentstatus will be filtered out.

Kind regards,

**Comment by sriniGalway** [comment]
Waldo,

Thanks for the update.
Yes, will check and let know. much appreciated with help.

Regards
Srini
