### ISSUE TITLE
Best Practice localization Build/Release 

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#168]
What would the best practice setup for alops in regards to be able to test your app against all released localization by microsoft as this is a requirement before pushing to appsource.

1. Would you suggest to make build pipelines for each localization  (currently 31)  
2. Would you suggest to publish the app as a release pipeline stage (31 stages)
3. or any better solution.

Just hit me with you pro and cons please.

**Comment by waldo1001** [comment]
What steps needs to be included?  Compile & Run Tests?  Just Compile?

Simplest solution: create 31 build pipelines, and schedule them every day on your release branch (if you have any).  You can even reuse one build pipeline, and schedule it with different variables.. .  This doesn't have any approval flow .. just reporting the current state of that branch.

If this needs to be an approval kind of thing .. you could try to create a release stage with multiple agent jobs with similar tasks (different containers).  The more agents in a pool, the more you would be able to do simultaneously.  It's quite some work in a release pipeline designer window, but in a multistage pipeline, it's fast to set this up ... .  This would only run when you decide to create a release (pipeline).  And you can even schedule it - or trigger it from some kind of branch .. .
YOu could also have a stage per localization (as you propose).  May be this is easier to follow up.. .  this would be my preferred solution.

**Comment by MortenRa** [comment]
Thanks, I will try to configure Release Pipeline to handle this and see if this would my preferred solution.
