### ISSUE TITLE
[Question] Compiling Multiple apps in one repo - Batch Compile

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#169]
I'm new to ALOps and wondering if it supports multiple apps in one repo. The apps have multiple dependancies so the step to compile these should figure out which one should come first.

So something like this:
projectfolder/app1_foundation
projectfolder/app2_dependant_on_foundation
projectfolder/app3_dependant_on_foundation
projectfolder/app4_dependant_on_foundation_and_app3

How do we configure ALOpsAppCompiler to pick all the folders in projectfolder (with their own app.json) and Compile them?

**Comment by dNsl9r** [comment]
I think this demo of @waldo1001 will help you: https://dev.azure.com/ALOpsWebinars/02_Dependencies/_git/2_AllDependenciesInOneRepo

**Comment by waldo1001** [comment]
Yep - this is the youtube video about it: https://www.youtube.com/watch?v=CCJG9cnjmLs&t=3207s

**Comment by peterz84** [comment]
Thanks, but I watched the video, and the answer is: there is no batch compile (yet). So I have to configure the compile myself by adding different steps for different apps.

**Comment by waldo1001** [comment]
Indeed.  

I'm not really in favor of the batch compile (personally). I want things to fail when some dependency is added without intentional approval.. .  And DevOps is where we approve code, so ...

**Comment by peterz84** [comment]
I think there are 2 sides: 
- it makes you aware of the dependancies and the order in which it should compile
- but with 100's of customer it's a hell of a job to maintain 100's of yamls. Not every developer will change the yaml file when adding a dependancy or extra app. (yes they have to)

**Comment by waldo1001** [comment]
I'll put it on the "enhancements" list - no promise though .. need to talk this through with the team ;-).

**Comment by waldo1001** [comment]
Hi,

we have a new compile-step that will soon be released - this one will have a "batch compile" and will run even without any Docker container, super fast.  We expect this release this week.

**Comment by AdminHodor** [comment]
Please check out the new compiler beta version => ALOpsAppCompiler@2
It takes the same parameters as for ALOpsDockerCreate and compiles without using docker, also allows for Batch compilation
https://github.com/HodorNV/ALOps/issues/126#issuecomment-703070084

**Comment by waldo1001** [comment]
hi @peterz84 , did you try the CompilerV2?

**Comment by peterz84** [comment]
I haven't yet, we are in the progress of setting up new buildservers on a new location. Have to wait for that to finish.

**Comment by waldo1001** [comment]
I'll close this issue for now .. if you have an issue with the CompilerV2, please let me know!

Example on this compiler:
https://github.com/HodorNV/ALOps/tree/master/Examples/Compiler%20V2
