### ISSUE TITLE
Error: Cannot find drive D when agent is installed on D

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#170]
FYI: When I install the agent on a different drive then C (this case D), the Import License task fails:

> 020-08-07T09:58:05.0826766Z ##[section]Starting: ALOpsLicenseImport
> 2020-08-07T09:58:05.1003029Z ==============================================================================
> 2020-08-07T09:58:05.1003292Z Task         : ALOps License Import
> 2020-08-07T09:58:05.1003498Z Description  : ALOps License Import
> 2020-08-07T09:58:05.1003673Z Version      : 1.432.1540
> 2020-08-07T09:58:05.1003830Z Author       : Hodor
> 2020-08-07T09:58:05.1004023Z Help         : Import Business Central license (.flf).
> 2020-08-07T09:58:05.1004454Z ==============================================================================
> 2020-08-07T09:58:08.3862846Z *** Validate configuration
> 2020-08-07T09:58:08.9022375Z *** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
> 2020-08-07T09:58:09.1224325Z *** Importing required PS-Functions
> 2020-08-07T09:58:10.5242194Z *** Connect Docker Session
> 2020-08-07T09:58:10.6576415Z *** Initiate Docker Session
> 2020-08-07T09:58:10.9118169Z *** Set Docker Container ErrorActionPreference = Stop
> 2020-08-07T09:58:11.2501109Z *** Copy BC-License to Docker Container: 5f23453be42fb214fecd078fc337b646f92ab1905a952621810677a1c1c56ae3
> 2020-08-07T09:58:11.2526830Z *** Docker BC-License Folder: D:\Agent\_work\1\s\License
> 2020-08-07T09:58:11.4607512Z ##[error]Cannot find drive. A drive with the name 'D' does not exist.
> 2020-08-07T09:58:11.7527498Z ##[section]Finishing: ALOpsLicenseImport

after reconfiguring the agent on drive C, it succeeds.

**Comment by waldo1001** [comment]
Did you install the agent on D, or did you refer to a working-folder on D?

**Comment by peterz84** [comment]
I installed it on D. So I did put the folder on D:\Agent and ran the config. Not a high priority issue, but I thought you should know and maybe fix it.

**Comment by waldo1001** [comment]
Well - it is a bug if it doesn't work ;-).  Never tried it - and never got the report - so thank you very much for reporting it.
We'll set up a test case.. .  But indeed .. it won't get the highest prio ... we're focussing on the artifacts as we speak .. .

**Comment by AdminHodor** [comment]
Dear @peterz84 ,

Seemed to be a small issue which was easily fixable, could you please try our latest release v1.432.1571 and validate the solution?

Kind regards,

**Comment by JesperNavtilus** [comment]
I am running on ALOps version 1.434.1680 and I experience the same (or a similar) problem with the ALOpsLicenseImport:

```
*** Selected module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Management.dll]
##[error]Cannot find drive. A drive with the name 'D' does not exist.
Finishing: ALOps License Import
```

The odd thing is that it works for another project using an almost (essentials) identical yaml, license(path), agentpool and agent.

The agent's work folder is on a D drive and I have tried installing/running the agent from both the C and D drive, but with the same result.
