### ISSUE TITLE
ALOps Extension API

### ISSUE THREAD

**Issue by mrabus** [HodorNV/ALOps#174]
**Describe the bug**
Hi ALOps Team, I created a simple release pipeline to deploy some apps to my local BC16 environment. 

**the used yaml**
My pipeline is rather simple containing just one step: 
![grafik](https://user-images.githubusercontent.com/2485163/90339374-a022c600-dff0-11ea-887b-bda15c3f91bf.png)

**the output**
![grafik](https://user-images.githubusercontent.com/2485163/90339436-1a534a80-dff1-11ea-9e44-bfaf1c0d15c6.png)

The output confuses me a little bit because the pipeline was talking to my API just fine (it figured out the company and the installed apps). How can I pass the correct service tier to it? Or where is it getting the information from?

**Comment by mrabus** [comment]
@AdminHodor or @waldo1001: Any ideas? :-)

**Comment by waldo1001** [comment]
Seems to be the same as #176 ... we're trying to figure it out.

**Comment by waldo1001** [comment]
Hi,
we found a minor issue regarding this, and fixed it. We can't just do a minor release just yet, though, as we need to finish other things first (working with artifacts).

**Comment by AdminHodor** [comment]
We just release v1.433.1659, can you check if this works for you?

Kind regards,

**Comment by mrabus** [comment]
I re-ran it this morning, unfortunately I get exactly the same error as before: 

![image](https://user-images.githubusercontent.com/2485163/91439559-75950080-e86d-11ea-8c22-5f8efa8959e9.png)

I also checked the expression to find the DLLs on the server, it should be working: 
![image](https://user-images.githubusercontent.com/2485163/91439772-d7556a80-e86d-11ea-8b6e-3331091623b8.png)

**Comment by waldo1001** [comment]
Are you sure you're checking the right server?  We need the dlls on the build agent, not on the server where you deploy to.. .

**Comment by waldo1001** [comment]
Hi @mrabus  , did you check my comment above?

**Comment by mrabus** [comment]
Hi @waldo1001, 

I made the publishing work when I copied the DLLs to the server where the agent is.
