### ISSUE TITLE
Qeustion: Fixed_tag & "ALOps Docker Remove"

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#175]
Hey Guys, 

Another question regarding Fixed_tag usage. If i start & wait container with Fixed_tag  property, do i also have run "ALOps Docker Remove" at the end of the pipeline too?  At the moment we don't do that.

The reason I am asking. I have container (using Fixed_tag) that just runs automated tests cases. We noticed significant performance degradation after 5 or 6 times it runs. Now wondering if we need to release some resources or something after each run. 

Gintautas

**Comment by waldo1001** [comment]
Usually when you use "Fixed_Tag", you remove the "remove docker" step, because it is used to re-use a certain container.

We also have this scenario (kind of) to run tests .. but honestly we don't really have that degradation.. .  May be schedule a restart every day or so?

**Comment by gintuoklis** [comment]
Just tried to re-create container, and it seems fixed the problem. 

We also noticed that when fixed_tag is used, dockerWait starts printing out crazy amount of evenviewer log lines. Have you experienced similiar issue as well?

**Comment by gintuoklis** [comment]
We also noticed that time required to AlOPsDocerWait increases with every run when Fixed_tag is used. For e.g., it was taking 10s in the beginning, now after ~40 runs it takes 3min53seconds. Seems that it just takes time to print all eventviewer logs. Now it prints log file of 40MB, which is crazy imho

![image](https://user-images.githubusercontent.com/16342128/90614082-7ba23600-e20a-11ea-8cce-e3ce70522636.png)

I could add additional script to my pipeline, to delete eventlog after each run. But don't know if it's important for AlOPsDocerWait. Could you help on that?

**Comment by gintuoklis** [comment]
I tried to clear eventlog

But it seems it has not affect. You can see my log is clean

![image](https://user-images.githubusercontent.com/16342128/90641244-4b21c280-e231-11ea-9d35-56c0e9797826.png)

Nevertheless, AlOPsDockerWait stil continues printin all 40MBs of data to the to AzureDevops.

Could you please let me know, where does it reads that information from?

**Comment by gintuoklis** [comment]
any advice here @waldo1001?

**Comment by waldo1001** [comment]
There might ben an option to disable logging in such a container - I'm just trying to find out how ...

**Comment by AdminHodor** [comment]
We just release v1.433.1659, can you check if this works for you?

Kind regards,

**Comment by gintuoklis** [comment]
Thank You, 
just tried your solution. It worked. Plus, it went faster. Intead of 20seconds (quite fresh container), it took 5seconds to run. Will monitor if that number increases over the time.
