### ISSUE TITLE
Cannot bind argument to parameter 'Path' because it is an empty string.

### ISSUE THREAD

**Issue by sriniGalway** [HodorNV/ALOps#176]
When we try to publish using ALOps Extension batch publish, we get below error:
2020-08-20T10:32:23.2753142Z *** Batch Publish Extensions
2020-08-20T10:32:23.2783856Z   * Artifact Path  : 
2020-08-20T10:32:23.6497939Z ##[error]Cannot bind argument to parameter 'Path' because it is an empty string.
2020-08-20T10:32:24.0408874Z ##[section]Finishing: ALOps Extension batch publish

**Expected behavior**
Before it was working well and below was the log snippet:
2020-08-12T09:05:35.5158437Z *** Batch Publish Extensions
2020-08-12T09:05:35.5176732Z   * Artifact Path  : 
2020-08-12T09:05:35.5374719Z *** Resolved Path  : C:\Run\DevOps\

**Comment by waldo1001** [comment]
Can you please report your yaml?

**Comment by sriniGalway** [comment]
Waldo,

Thanks for the reply.
Its release pipeline and we are using the UI format - below is yaml for the ALOps Extension batch publish task

#Your build pipeline references a secret variable named ‘credential’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Hodor.hodor-alops.ALOpsExtensionAPI.ALOpsExtensionAPI@1
  displayName: 'ALOps Extension batch publish'
  inputs:
    usedocker: true
    interaction: batch
    api_endpoint: 'https://<bc api url>'
    authentication: basic
    azure_tenant_id: 'abcdef-ghij-klmn-opqr-stuvwxyz'
    username: 'admin'
    password: '$(credential)'
    showdeploymentstatus: false

kindly advice if you need any more details.

**Comment by waldo1001** [comment]
Hi,
we found a minor issue regarding this, and fixed it.  We can't just do a minor release just yet, though, as we need to finish other things first (working with artifacts).

**Comment by sriniGalway** [comment]
waldo, thanks for letting us know on the minor issue. will await for the release of fix. 
Regards
Srini

**Comment by AdminHodor** [comment]
We just release v1.433.1659, can you check if this works for you?

Kind regards,

**Comment by sriniGalway** [comment]
Hi,
Thanks for the reply,
We have the v1.433.1659 installed.
Its not yet working for us.
020-08-24T14:21:53.1262150Z   * Artifact Path  : 
2020-08-24T14:21:53.3884942Z ##[error]Cannot bind argument to parameter 'Path' because it is an empty string.

Regards
Srini

**Comment by AdminHodor** [comment]
Dear @sriniGalway ,

Could you please check the parameter [artifact_path] is not defined in your yaml ?
The default for this parameter is set in the Task itself, and therefor should not be empty unless overriden.

```
{
            "name": "artifact_path",
            "type": "string",
            "label": "Path to publish",
            "defaultValue": "$(System.ArtifactsDirectory)",
            "required": false,
            "helpMarkDown": "Path for App Artifact.",
            "visibleRule": "interaction=publish || interaction=batch"
}
```

Kind regards,

**Comment by sriniGalway** [comment]
the parameter artifact_path was empty and hence we updated the artifact_path to C:\Run\DevOps and its working well now.
Before, it was recognising the artifact_path if it was empty, its not any more.
`2020-08-05T16:16:29.1889647Z *** Batch Publish Extensions
2020-08-05T16:16:29.1906685Z   * Artifact Path  : 
2020-08-05T16:16:29.2029749Z *** Resolved Path  : C:\Run\DevOps\`

We will try updating the value to $(System.ArtifactsDirectory) and update you soon.

Regards,
Srini

**Comment by sriniGalway** [comment]
Hi Waldo,

so, we checked with $(System.ArtifactsDirectory)  as path to publish, but this concatenates the copied path with the artifact path.

Cannot find path 'C:\Run\DevOps\C:\Agent\_work\r3\a\_BUILD_App1\abc-beta' because it does not exist.

Can you kindly advice whether we can get a fix or advice on this.
Our deployments are failing due to this

Regards
Srini

**Comment by waldo1001** [comment]
Hi,

the publish-step needs the dlls from the service-folder to get app-specifics.  A workaround is to simply copy/paste the service-folder to the right location on the server where the build agent is running.  Do you think you can do this?

Meanwhile, we identified this as a bug, so we're working on a fix.

**Comment by waldo1001** [comment]
Hi @sriniGalway ,

in the meantime, we did quite some updates.  Could you please check again and confirm it works or doesn't?

if not,
could you please provide a clear repro-scenario?

thanks!

**Comment by waldo1001** [comment]
Hi @sriniGalway,

do you have feedback?

**Comment by waldo1001** [comment]
Hi @sriniGalway ,

this issues should have been resolved since the last release.
can you confir?

**Comment by sriniGalway** [comment]
Hi Waldo,

Hope you are well. I no longer work for that project and hence unable to
verify it. You can change it to resolved for now.

Regards
Srini
