### ISSUE TITLE
How do I refer to multiple repositories when using ALOps tasks

### ISSUE THREAD

**Issue by JesperNavtilus** [HodorNV/ALOps#197]
I have a project (let's just call it MyProject) with multiple repositories like this:

BaseApp - all the AL that only depends on the BC Base apps
CustomEDIApp - an app with customizations related to EDI. It has the BaseApp and a standard EDI app as dependencies.

I only have one pipeline yaml for the entire project - located in the BaseApp repository.
The pipeline is triggered by commits to the master branch in the BaseApp repository.
But it is also triggered by commits to the master branch in the CustomEDIApp by these lines in the yaml:

```
resources:
  repositories:
  - repository: 'CustomEDIApp'
    type: git
    name: 'CustomEDIApp'
    trigger:
    - master
```
The triggering of the pipeline is works fine.

My goal is to have a pipeline that always compile and publish both the BaseApp and the CustomEDIApp into the same container (and run some tests) - no matter how the pipeline was triggered.

But I do not know how to make ALOps work with code from the CustomEDIApp repository.

I checkout the code like this:

```
- checkout: self  # this is the BaseApp as the yaml is located here
- checkout: 'git:/MyProject/CustomEDIApp'
```

When compiling the BaseApp the targetproject is '.\app.json'.
But how do I refer to the app.json in/from the CustomEDIApp
repository?

I know how to do this if the project instead was created as one repository and using the "multi root" model.
But in this case the code is organized in repositories instead.

**Comment by waldo1001** [comment]
Thing is, you want to access the SCM of one repo, from a build from another repo.  I don't know if that's a good way to look at it - I'd simply create two pipelines (one for each repo).

You could try to clone (git clone) instead of checkout - that way, you're downloading the code somewhere that you might be able to compile... just a guess.

Is there any reason why not to use multiple pipelines?  or why not to have just one repo?

**Comment by JesperNavtilus** [comment]
Multiple pipelines will not be usefull in the given situation - as all the repositories are needed for the complete custom solution (this is not an AppSource app, but multiple apps for on custom solution) and a change in one repository (app) may break some code in one of the other repositories (f.ex. overlapping object/field numbers).  So no matter which repo a change is commited to, I want all the repositories (customer apps) to be compiled and published into the same container.
The Git and pipeline (yml) in Azure DevOps are made for SCM across multiple repositories.

On this page:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops

You can f.ex. see the branch policy is used when the yml is located in one repo but triggered by multiple repos:

![billede](https://user-images.githubusercontent.com/59687451/93775427-ad038c80-fc22-11ea-86a9-fdd03b3f2c47.png)

Since I first posted this issue, I have learned that when there are multiple checkout's in the pipeline - like this:

    - checkout: self
    - checkout: 'git://MyProject/AnotherRepository'
      clean: true 

Then instead of cloning the code directly under the 's' folder on the Azure Pipeline Agent's working folder, it will instead create a subfolder for each repo under 's' with the repository's name - like:

..\s\OneRepository
..\s\AnotherRepository

So I am pretty sure how to point out the app.json as the targetproject to ALOpsAppCompiler and I guess/hope that the rest of the ALOps tasks (like ALOpsAppSign, ALOpsAppPublish etc.) will then also know where to locate the *.app generated by the ALOpsAppCompiler.

But I have not come so far because I am stuck with issue #195 (ALOpsLicenseImport cannot find the 'D' drive) that terminates the pipeline even before it gets to the compiling task.

**Comment by waldo1001** [comment]
Next release, we'll release a new way to compile (the compile-step will have a second version).  

This compile is able to "batch compile" and is much faster.  You could use this to 
1- checkout all necessary repos in one folder
2- use the new compile to batch-compile all

let's wait for this release (this week) and re-evaluate this issue?

**Comment by JesperNavtilus** [comment]
Okay - I am looking forward try it out.

**Comment by waldo1001** [comment]
It's already release, but I need time to work on documentation.  If you want, you can try it out yourself.  It's a preview-feature that is a second version of the compile-step.

Here is an example:
![image](https://user-images.githubusercontent.com/12088142/94131381-22a76c80-fe5e-11ea-91bf-360a4ba58a07.png)

and the params are pretty self-explanatory:
![image](https://user-images.githubusercontent.com/12088142/94131479-44a0ef00-fe5e-11ea-9d4c-7f56fe97d753.png)

Sorry, that's all I can share now, need to find time to document it :(.

**Comment by JesperNavtilus** [comment]
Thank you, 

1) now I am looking forward to reading the documentation :-)

2) I have tried it out but ran into an error that it is can not get access to a folder 'c:\windows\TEMP\ALOps-xxx...' that it has just succesfully created and added files to.   

   [ALOpsAppCompiler_2 - pipeline.yml.txt](https://github.com/HodorNV/ALOps/files/5293522/ALOpsAppCompiler_2.-.pipeline.yml.txt)
   [ALOpsAppCompiler_2 - raw log.txt](https://github.com/HodorNV/ALOps/files/5293529/ALOpsAppCompiler_2.-.raw.log.txt)

   Notice: The Azure Pipeline Agent is installed/executed and has its _work folder on a D drive.

3) Is it correctly understood, that the docker creation/startup is fully integrated in the new compiler step? 

4) Does the parameter "Publish Artifact" mean that it will be published to Azure DevOps an artifact - or is this a replacement/alternative to using the ALOpsAppPublish step?

**Comment by waldo1001** [comment]
To answer your questions:
1. Documentation is online in the form of new examples!  
2. let's try it again with the new docs
3. No, we don't do any Docker with CompilerV2
4. Yes, DegOps indeed.  If you want to publish to an NST, you'll need the ALopsAppPublish as well. 

If you have any other issues, please create a new one (you can relate to this one)!
