### ISSUE TITLE
Azure DevOps pipeline caching

### ISSUE THREAD

**Issue by mbaic** [HodorNV/ALOps#20]
Hi,

I just finished with first tests of public template "Base AL app" and everything seems to be fine less or more. I had some minor issues with *.yml file (e.g. license path) since agent was "Hosted VS2017".  

I've been thinking, is it possible to speed up CI process in accordance with “pipeline caching” described in this link:
https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops

So, for example, we don’t have to wait each time BC image to be downloaded, etc. Instead, just a new container can be created and process will continue with other defined tasks. It is about Azure DevOps default agents (e.g. "Hosted VS2017"), not self hosted. 

Below is a screen dump for "ALOpsDockerStart", this task took around 35 mins:
<img width="807" alt="ALOpsDockerStart_Info" src="https://user-images.githubusercontent.com/35611941/62125285-02693580-b2cd-11e9-947d-1eeca5ecd1ff.png">

If ALOps can be improved with "pipeline caching" for such scenarios, that would be much appreciated.

**Comment by waldo1001** [comment]
We will look into this.  We were not aware of this "pipeline caching" (thanks for pointing that out ;-))
At this point, we don't prefer to use hosted agents, as it's too slow and limited..

**Comment by mbaic** [comment]
I understand and agree, but I would use hosted agents by Microsoft for demo and test purposes (e.g. new ALOps features, bug fixes, etc.). Afterwards, when I am sure about everything, I would continue with self hosted agents and real scenarios.  

Self hosted scenario works good, since once downloaded image we can keep and just recreate containers in new builds, so CI will be faster indeed.

In any case, thank you for considering this topic.

**Comment by AdminHodor** [comment]
Hello @mbaic ,

We investigated the PipelineCaching feature. It can be interesting for a lot of scenario's, but it doesn't cover the docker related features required. Using the cache we where not able to 'maintain'a docker image and therefor speed up the process. 

We are however looking into providing a "Host-BC-Agent" service, purpose build hardware with many BC-Images pre-loaded for lightning fast builds.  

Kind regards,

Bart Bourgeois
