### ISSUE TITLE
ALOpsDockerCreate - Package 'BcContainerHelper' failed to download.

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#207]
**Describe the bug**
Our pipeline failed since the **ALOpsDockerCreate** step did not fully complete successfully.
Is it mandatory for ALOpsDockerCreate to fail if the BcContainerHelper failed to download? I guess if a version of BcContainerHelper is already available, pipeline would still be able to continue?

**the output**
```
Starting: ALOpsDockerCreate
==============================================================================
Task         : ALOps Docker Create
Description  : Create Docker image from Business Central Artifacts
Version      : 1.434.1755
Author       : Hodor
Help         : Create Docker image based on NAV/BC Artifacts.
==============================================================================
*** Validate configuration
*** ALOps License:
  * Licensed To: Navitrans

*** For documentation, please visit   : https://www.alops.be/documentation

*** Memory Status: 26.32/31.84 (82.67% Free)
*** Importing required PS-Functions
*** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]
##[warning]Source Location 'https://www.powershellgallery.com/api/v2/package/BcContainerHelper/1.0.6' is not valid.
##[error]Package 'BcContainerHelper' failed to download.
Finishing: ALOpsDockerCreate


```

Looking in the pipeline that ran just before the failure occured, there was no issue at all and BCContainerhelper 1.0.6 was already present. So why need to download the same BCContainerhelper version again in the next run?

```
Starting: ALOpsDockerCreate
==============================================================================
Task         : ALOps Docker Create
Description  : Create Docker image from Business Central Artifacts
Version      : 1.434.1755
Author       : Hodor
Help         : Create Docker image based on NAV/BC Artifacts.
==============================================================================
*** Validate configuration
*** ALOps License:
  * Licensed To: Navitrans

*** For documentation, please visit   : https://www.alops.be/documentation

*** Memory Status: 26.41/31.84 (82.95% Free)
*** Importing required PS-Functions
*** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]

ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     1.0.6      BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-...
*** Get Artifact Url for Version [16.3.14085.14238] / Country [w1] / Type [OnPrem]

```

**Comment by waldo1001** [comment]
We never had this issue :-/.

Do you know why it failed?  Does it happen a lot?
We'll see if we can catch it..

**Comment by fvet** [comment]
Why? No.
A lot? Faced it 3 times on one day this week.
Prio? Low ;)

Would be great if it can be catched, so I don't have to investigate why pipeline are failing if there's nothing wrong.

**Comment by AdminHodor** [comment]
We force the install to make sure BcContainerHelper is always running on the latest version.

>>I guess if a version of BcContainerHelper is already available, pipeline would still be able to continue?
Good suggestion; we implemented this for the next release. Now we'll install/update container helper silently, hide possible errors in this step. The Import-Module is still uncatched, so as long as there is a version of BcContainerHelper this should be an issue anymore.

We'll keep you posted on the release of the fix.

**Comment by fvet** [comment]
FYI, just got a similar build failure

```
*** Memory Status: 25.67/31.84 (80.63% Free)
*** Importing required PS-Functions
*** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]
##[warning]Could not get response from query 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='BcContainerHelper'&$skip=40&$top=40'.
##[error]Unable to resolve module reference ''.
Finishing: Create Docker Image - w1 / Current Build

```

**Comment by AdminHodor** [comment]
We implemented a 'fix' for this for next release. We'll try-catch the BcContainerHelper installation, so if its not available for any reason at the time it won't fail you pipeline. 
The import-module on BcContainerHelper isn't catched, so if its available the pipeline will resume as normal

**Comment by AdminHodor** [comment]
Dear @fvet ,

We just released v1.435.1856 which should tackle this issue.
Please note it could take a couple of pipeline runs for DevOps to pickup the new version.

Kind regards,

**Comment by fvet** [comment]
@AdminHodor @waldo1001 Just got a pipeline waiting for **7 minutes** on the bccontainerhelper download ...
```

2020-10-30T07:30:39.5523266Z *** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]
2020-10-30T07:37:49.0459706Z ##[warning]Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
2020-10-30T07:37:49.0560201Z *** Install/Update container helper failed: No match was found for the specified search criteria and module name 'BcContainerHelper'. Try Get-PSRepository to see all available registered module repositories.
2020-10-30T07:37:50.3393700Z
```

**Comment by JeppeBylov** [comment]
I have the same issue.

**Comment by waldo1001** [comment]
PowerShell gallery is down :(.
![image](https://user-images.githubusercontent.com/12088142/97677253-4cbe0100-1a92-11eb-8109-a816801f32e7.png)

Does the pipeline fail?

**Comment by waldo1001** [comment]
Problem is that the call takes long - but pipeline shouldn't fail, does it?

**Comment by JeppeBylov** [comment]
> Problem is that the call takes long - but pipeline shouldn't fail, does it?

Pipelines don't fail, just takes an extra 5-8 minutes. Hopefully it's resolve itself, when PowerShell Gallery comes back up.

**Comment by AdminHodor** [comment]
We have another way of loading BcContainerHelper in ALOps@v2, it does not auto-update container helper, just checks the minimum version. We'll backport it right away and deploy a hotfix asap that should mitigate the Gallery being down.

Kind regards,

**Comment by AdminHodor** [comment]
Dear @JeppeBylov , @fvet ,

Hotfix is online, v1.435.1904. Please not it could take a couple of pipeline runs to pickup the new version.

Loading BcContainerHelper works differently in this version. We have a required-minimum-version defined in ALOps,
if at least that version is present it is loaded and no update check is done. (so no Gallery issues).

Kind regards

**Comment by fvet** [comment]
Thanks for your quick response!

**Comment by JeppeBylov** [comment]
Works!
