### ISSUE TITLE
Show extended parameter info for ALOps steps

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#216]
**Is your feature request related to a problem? Please describe.**
We heavily depend on templates / parameters / variables to call the ALOps steps. In the pipeline logs, it's not always clear which values / variables have been used (build pipeline var / template defaults / ...), which makes trouble shooting not always easy. It would be nice if at the start of each pipelines we could (toggle) print the content of the variables (when resolved) used for the step execution.

**Describe the solution you'd like**

```
Starting: Compile xxx
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extensions for Business Central
Version      : 1.434.1775
Author       : Hodor
Help         : Compile a Business Central extension from AL code.
==============================================================================
Parameters:
- usedocker : true
- failed_on_warnings : true
- al_analyzer: CodeCop
  ...
==============================================================================
...
```

**Comment by AdminHodor** [comment]
Dear @fvet ,

In the next major version (v2) of ALOps we got this implemented by default for every task, the next version you will also be able to use DEBUG and other standard devops tools.

We'll check if we can backport this functionality to v1 making it available asap.

Kind regards,

**Comment by AdminHodor** [comment]
Dear @fvet ,

We checked and we are able to backport the v2 functionality to v1, making the Parameter printout available for all tasks.
It will iterate all possible inputs and there values, here's an example:

![image](https://user-images.githubusercontent.com/51383893/95887989-d080a980-0d80-11eb-94b4-54517e9a248d.png)

Could you confirm this is what you are looking for?

Kind regards,

**Comment by fvet** [comment]
Haven't seen it in my pipelines yet. Do I need to set any parameter (other than alops_show_variable)?

I've tried yesterday by enabling the 'alops_show_variable: true' globally, but I get to much ALOPS / BUILD / AGENT / OS variables which are of less importance (to me). The above is more what I was looking for ;)

**Comment by AdminHodor** [comment]
Dear @fvet ,

The screenshot is from the pre-release, so it is not yet available yet for the public. 
It already passed the pipeline and passed all tests, so it's ready to release. Just wanted to make sure the output is what you where looking for.

Kind regards,
