### ISSUE TITLE
Artifact Syntax for RTM and Latest version within a Major version

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#217]
We are optimizing our pipelines and would like to ensure that we handle both RTM and latest version within a given major version correctly.

**Sample pipeline:**
`
variables:
- name: 'BC_Version'
  value: '16.3'
- name: 'BC_Localization'
  value: 'dk'
- name: 'BC_Type'
  value: 'OnPrem'

- task: ALOpsDockerCreate@1
  inputs:
    artifactversion: $(BC_Version)
    artifactcountry: $(BC_Localization)
    artifacttype: $(BC_Type)
`

**Question 1:**
What is the syntax for BC16 RTM - is that 16.0, 16 or 16.RTM?

**Question 2:**
How can I, based on my example, configure the pipeline to use latest version of BC16 - which is 16.5 at the moment without hardcoding this in the yaml file?

**Comment by AdminHodor** [comment]
Dear @kasperdj ,

Both questions are handled the same, it just depend on how specific you are.
- artifactversion: 16  => Latest version of Major v16 (currently 16.5.*.*)
- artifactversion: 16.0  => Latest version of Major v16 Minor 0 (RTM)
- artifactversion: 16.3  => Latest version of Major v16 Minor 3

The more you specify in the artifact version, the more it will filter down. You define it very generic like "artifactversion: 16" for getting the latest v16, or you can drill down to a specific build "artifactversion: 16.4.14693.15445" 

Kind regards,

**Comment by kasperdj** [comment]
Thx :-)
