### ISSUE TITLE
ALOps Job not working for Sandbox with different name

### ISSUE THREAD

**Issue by JaGrie** [HodorNV/ALOps#22]
Hello,

when I am using the the "ALOps SaaS Publish Extension"-job in my pipeline it works well, when the name of the environment where I want to publish my extension in is "Sandbox" or "Production". When the name of the environment is different, it doesn't work and throws me a 404. 

I have no idea what to make of this and would appreciate any help!

![Bildschirmfoto 2019-08-11 um 17 56 17](https://user-images.githubusercontent.com/53572892/62836226-5971f180-bc61-11e9-8da6-f10ec3862ede.png)

![Bildschirmfoto 2019-08-11 um 17 48 58](https://user-images.githubusercontent.com/53572892/62836134-67734280-bc60-11e9-940d-a8a566be81fd.png)

Thanks in advance and best regards,
Jakob

**Comment by JaGrie** [comment]
@waldo1001 

Hi there,

can I expect a solution in the near future or is there a workaround with which I can publish Apps to differently named sandboxes?

Best regards,
Jakob

**Comment by waldo1001** [comment]
Not a lot of feedback - sorry about that.  In reality, we have been looking for a solution, but it doesn't seem that Microsoft supports this in their API.. .  We're trying to find out...

**Comment by waldo1001** [comment]
If you're on the readytogo yammer insider program, you can find my post here:
https://www.yammer.com/dynamicsnavdev/threads/321010160214016

**Comment by AdminHodor** [comment]
The fix  for will be included in the upcoming release.

Regards
