### ISSUE TITLE
ALOpsAppCompiler@2 - Read codeanalyzers from settings.json if not specified in yaml alcodeanalyzer

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#225]
**Is your feature request related to a problem? Please describe.**
Previous to the ALOpsAppCompiler@2 version, we had setup to compile, once for the app and once for the test app. Both had been configured with **different** alcodeanalyzer. Switching to v2 seems like ALOpsAppCompiler is able to compile both app and test app at once, both using the **same** alcodeanalyzer.

Since we've currently not enabled the same alcodeanalyzers for the app and test app, and failonwarnings is true, our test app now fails :(

Would it be possible to apply different alcodeanalyzer, possibly by reading / inheriting the contents from the **settings.json** file instead (if not specified in the pipeline)

**Comment by waldo1001** [comment]
@fvet ,

it will take the rulesets from the according apps - would it be a solution to create rulesets for all according rules in the test-app?  In the meantime, we'll see what we can do...

**Comment by fvet** [comment]
I already have different rulesets per app / test-app. I only want to avoid certain codeAnalyzers to run on certain (test-) apps.
Our structure is something like this:

- Repo : Core
  - Folder : App
    - Settings.json : **AppSourceCop**, CodeCop, UICop
    - Ruleset.json
  - Folder : Test
    - Settings.json : CodeCop, UICop
    - Ruleset.json

- Repo : Base
  - Folder : App
    - Settings.json : **AppSourceCop**, CodeCop, UICop
    - Ruleset.json
  - Folder : Test
    - Settings.json : CodeCop, UICop
    - Ruleset.json

So the ALOpsAppCompiler should ideally take the alcodeanalyzers from the settings.json file where the app.json resides, together with the ruleset.json that the settings.json file refers to.

**Comment by waldo1001** [comment]
We're going to try to do it like this:
- when no value for "al_analyzer", we'll read the settings.json
- when there IS a value, we'll take that value, and overrules the settings.json.

**Comment by waldo1001** [comment]
We'll have to do this for V1 compiler as well - but we'll do so!

**Comment by fvet** [comment]
Maybe worth adding an extra value "**None**" to "al_analyzer" (and update the documentation / tooltip of the parameter, so it's visible when configuring this step), allowing to prevent the new default fallback to settings.json. This would support compatbility with pipelines where no code_analyzers are required, but the project still has them as part of the settings.json.

E.g. : I've a pipeline that simply calls the compile step to create the latest 'project.g.xlf' files, so we can sync them and send to a translation service. Running default codeAnalyzers seems overhead here.

**Comment by waldo1001** [comment]
We finished the previous, but we'll add the "None" in this or either the next release!
Thanks for the suggestion!

**Comment by AdminHodor** [comment]
Dear @fvet ,

We just release v1.437 which contains the update for this.
=> ALOpsAppCompile: Read CodeAnalyzers from VSCode settings

Kind regards,
