### ISSUE TITLE
app_file_suffix in ALOpsCompile@2

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#227]
**Is your feature request related to a problem? Please describe.**
Apparently, the **app_file_suffix** parameter is no longer supported in ALOpsCompile@2. 
How can we include an additional suffix (without changing the app name) in the artifact name to ease filtering (later in the release / deploy stage)? See #204 

Would be good if we had the option to name our app files Navitrans_Core_16.3.0.4921_OnPrem_16.3_w1_**MYSUFFIX**.app, so we could use it when applying the **nav_artifact_app_filter**.

If not, then we need extended filtering options on nav_artifact_app_filter to:
- exclude the *-test* apps, since 'normal' apps can no longer be recognized by their *_APP* name (we'd like to exclude test apps from certain deployments)
- support concat multiple filter values : *be.*|*dc.*

**Comment by waldo1001** [comment]
What we do today is to give an explicit "_TEST" name in the according test-app, which makes filtering possible (and app_file_suffix not necessary anymore).  When doing batch_compile, you can't rely on one setting to suffix.

we'll try to see what we can do to facilitate this.

**Comment by jcoe-nvt** [comment]
@waldo1001 How can you reverse the filter?
Previously filter was used to include certain apps, but now we will need to specify which apps to exclude. Would it look like this?
`<>*_TEST.app`

**Comment by waldo1001** [comment]
You are right, I was too fast, my apologies.  

This is only a way to get the tests out - and the idea is to have an extra step to remove the test app (you can do that easily with PowerShell).  I don't have this in scripts yet, though.. .

**Comment by fvet** [comment]
The original request to add a suffix is no longer needed, we found a workaround. Nevertheless, we still need to find a standard ALOps way to exclude the test apps from being published.

Wouldn't it be easier to provide support for **glob patterns** in the **nav_artifact_app_filter**? 
I would expect since it's widely used on DevOps, that ALOps should support the pattern too. So we can use something like `!**/*-test*.app` to exclude the test apps.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

**Comment by waldo1001** [comment]
We'll add this ability in the V2 compiler

**Comment by AdminHodor** [comment]
Dear @fvet ,

We just release v1.437 which contains the update for this.
=> ALOpsAppCompile@2: New string Parameter [appfilenametemplate] that allows for setting custom appnames, prefixes and suffixes.

Kind regards,
