### ISSUE TITLE
(Question) ALOpsAppCompiler@2 - /assemblyprobingpaths with Sandbox

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#228]
**Describe the bug**
If my app would be targetting cloud only (artifacttype = Sandbox), why does this alc.exe still needs to be called with the /assemblyprobingpaths included? Shouldn't we exclude all options of using add-ins of any kind (except for the Mock assemblies) when targetting SaaS? 
_The assemblyprobingpaths in the settings.json file is empty too._

& alc.exe /packagecachepath:"C:\DockerInstallation\Agent\_work\4\s\App\.ALOPSCache" /project:"C:\DockerInstallation\Agent\_work\4\s\App" /out:"C:\DockerInstallation\Agent\_work\4\a\Navitrans_Core_16.3.0.4937_Sandbox_16.3_w1.app" /fullpaths **/assemblyprobingpaths:C:\Windows\assembly,C:\bcartifacts.cache\sandbox\16.3.14085.17832\platform\Test Assemblies\Mock Assemblies,C:\bcartifacts.cache\sandbox\16.3.14085.17832\platform\LegacyDlls\program files\Microsoft Dynamics NAV\160\RoleTailored Client\Add-ins,C:\bcartifacts.cache\sandbox\16.3.14085.17832\platform\ServiceTier\program files\Microsoft Dynamics NAV\160\Service\Add-ins** /analyzer:"C:\bcartifacts.cache\sandbox\16.3.14085.17832\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll","C:\bcartifacts.cache\sandbox\16.3.14085.17832\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll","C:\bcartifacts.cache\sandbox\16.3.14085.17832\platform\ModernDev\program files\Microsoft Dynamics NAV\160\AL Development Environment\ALLanguage\extension\bin\Analyzers\Microsoft.Dynamics.Nav.AppSourceCop.dll" /ruleset:"C:\DockerInstallation\Agent\_work\4\s\App\.vscode\nvt.ruleset.json"

**Comment by waldo1001** [comment]
I don't get the problem on this one?  Do you expect wrong results?

**Comment by fvet** [comment]
You can ignore this one, I won't fail indeed.
