### ISSUE TITLE
ALOpsDockerWait succeeds even if there's an error 

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#237]
Hey Guys, 
ALOpsDockerWait succeeds even if there's an error (expired license for e.g.). 
Expected behavirou. AlopsDockerWait should fail with error, and no other steps should continue (unless i program in other way in my yaml)

My : ALOpsDockerWait scripts is very simple (i don't have any continueonError stuff)
```
- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'
```
And here is the result
![image](https://user-images.githubusercontent.com/16342128/97556542-ee354c00-19d9-11eb-870d-8b65b49bcc37.png)

**Comment by waldo1001** [comment]
Can you please share the complete output of the wait-step?

**Comment by gintuoklis** [comment]
![image](https://user-images.githubusercontent.com/16342128/97560400-e62bdb00-19de-11eb-9301-a0a0ed40a846.png)
