### ISSUE TITLE
Compiling using the latest marketplace vsix? (for non insider builds)

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#239]
**Is your feature request related to a problem? Please describe.**

Most of our developers are working on the **latest marketplace vsix** (6.1...). Based on the app.json runtime, the compiler will behave differently. Plain and simple.

In the past, I've raised various CodeCop suggestions on AL github that have been solved in this latest vsix. So I thought now is the time to cleanse my ruleset.json and enforce these new rules. This all works fine in VS Code, however, when the code is compiled with ALOps, it uses the 'old' vsix (5.0.4.26576) that comes with the artifact build (in my case version 16.3)

Build/version cannot be changed be 16.3, since I need the application symbols from this version to compile, however, I don't see any reason why we should not compile against the latest (marketplace) vsix.

Below is the error output on DevOps, using an older version of the vsix. 

```
** AL Compiler Exit Code: 0
*** AL Compiler raw logs: Start
Microsoft (R) AL Compiler version 5.0.4.26576 Copyright (C) Microsoft Corporation. All rights reserved  Compilation started for project 'Core' containing '151' files at '12:42:7.489'.  c:\Run\DevOps\app\src\Status\COD Get Status Code.al(30,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(49,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(76,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(95,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(114,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(133,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(152,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(171,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(190,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(209,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(228,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(247,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Status\COD Get Status Code.al(294,17): warning AA0205: Use of unassigned variable 'TempRecStatus'. c:\Run\DevOps\app\src\Azure Functions\TAB API Setup.al(187,74): warning AA0205: Use of unassigned variable 'Parameters'. c:\Run\DevOps\app\src\Alert\COD Alert Mgt.al(50,81): warning AA0205: Use of unassigned variable 'AdditionalRemarks'. c:\Run\DevOps\app\extensionsPermissionSet.xml(1,1): info AL1027: The file at location 'c:\Run\DevOps\app\extensionsPermissionSet.xml' matches the definition for 'PermissionSet'.  Compilation ended at '12:42:13.333'. 
*** AL Compiler raw logs: End
*** Start processing compile results.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(30,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(49,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(76,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(95,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(114,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(133,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(152,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(171,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(190,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(209,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(228,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(247,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Status\COD Get Status Code.al(294,17): warning AA0205: Use of unassigned variable 'TempRecStatus'.
##[warning]c:\Run\DevOps\app\src\Azure Functions\TAB API Setup.al(187,74): warning AA0205: Use of unassigned variable 'Parameters'.
##[warning]c:\Run\DevOps\app\src\Alert\COD Alert Mgt.al(50,81): warning AA0205: Use of unassigned variable 'AdditionalRemarks'.

```
Any input? Would it make sense to be able to compile against application version X using a different vsix Y?

**Comment by fvet** [comment]
Would it make sense to add an option 'Latest' to the al_compiler_version of the ALOpsAppCompiler step?
This would take the compiler version of the bc-artifacts tagged as 'Latest' (which should be the version that is available on Marketplace?)

**Comment by waldo1001** [comment]
We are considering our options on this .. .

**Comment by fvet** [comment]
Any update?
Facing a similar issue when preparing the upgrade to BC 17.

Our master is currently configured with BC 16.3 and thus the linked compiler (5.x). When preparing our PR's with BC17 changes to the master, compilation fails because the BC 16.3 compiler does not support runtime 6.0. 

In short, we should be able to assign a different compiler version than the one included in the BC application artefacts used to get the BC dependend symbols.

**Comment by waldo1001** [comment]
In CompilerV1, you have parameter `vsix_download_path`.  So that should work already.

In CompilerV2, we're struggling to make the download stable .. this marketplace download is pretty "special".  

We will do this in 2 steps:
1) we create a `vsix_download_path` as well in V2. then you' can manage this yourself, manually.
2) we will create parameter, that will get it from the marketplace.  We already have tried, but we're struggling a bit getting this stable enough .. so need more time.

**Comment by fvet** [comment]
Hi @waldo1001, can we expect any New Years presents soon for the CompilerV2 ?  ;)
This is still keeping us from moving towards AppSource ...

**Comment by fvet** [comment]
Hi @waldo1001,

Did some tests with the new alternativevsixurl, by pointing it to a path (instead of URL)
E.g. "\\BUILDSERVER\c$\ALCompiler\ALLanguage.vsix"

Due to the size of the vsix, the unpacking step takes approx. 20 seconds. And this for each new pipeline run. This makes the runtime of our pipelines increase ...

```
2021-01-20T14:26:00.2433047Z *** VSIX Path Resolved: [\\BUILDSERVER\c$\ALCompiler\ALLanguage.vsix]
2021-01-20T14:26:00.2439445Z *** Prepare Extension for Unpack
2021-01-20T14:26:00.2460453Z *** Unpacking Extension to folder...
2021-01-20T14:26:19.2660323Z *** VSIX Available: [C:\DockerInstallation\Agent\_work\_temp\VSIX\custom]

```
Using the normal approach - without alternativevsixurl - the alc.exe (and other dependencies / dlls) are taken from the VSIX folder within the bcartifacts.cache path (no need to unpack / copy / ...)

`2021-01-20T11:23:35.7785795Z *** ALC Path: C:\bcartifacts.cache\onprem\17.2.19367.19735\VSIX\extension\bin\alc.exe`

Any reason why this approach can't be used for the alternativevsixurl , where we provide a fix location with an unzipped \VSIX folder that can be re-used accross all pipelines (without the need to unpack / copy?

**Comment by AdminHodor** [comment]
Dear @fvet ,

Could you please check this in our latest release v1.438 ?

Kind regards

**Comment by fvet** [comment]
@AdminHodor See my yesterdays reply ...

**Comment by fvet** [comment]
I started implementing the AppSourceCop rules (specifying a version in the AppSourceCop.json) today running the BC 17.2 artifacts, and the breaking changes are detect pretty fast (approx. 1+ minute) without specifying a specific vsix. Guess MS has fixed something (or ALOps ? :)), but for us the vsix path is currently no longer needed in our pipelines ... So issue closed ;)
