### ISSUE TITLE
ALOpsAppCompiler@2 (alc.exe) is very slow when using AppSourceCop.json

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#248]
**Is your feature request related to a problem? Please describe.**
ALOpsAppCompiler@2 takes very long when using AppSourceCop together with AppSourceCop.json containing a version.

When packaging my project via **VSCode** (on our buildserver) with codeAnalyzers enabled , I get (lightning) fast results:  +-50 to 75 seconds

```
Microsoft (R) AL Compiler version 6.1.5.31404
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'Navitrans 365' containing '4500' files at '15:13:57.362'.
...
Compilation ended at '15:15:15.381'.

Success: The package is created.
```

When using ALOpsAppCompiler@2, it takes over **10+ minutes**, and fails (timeout?) on issues when resolving the symbols of the previous app ('MISSING' errors, that I don't get in VSCode). Since I'm using BC 16.3, the compiler was still of version 5.x. Replacing the binaries in C:\bcartifacts.cache\onprem\16.3.14085.14238\VSIX\extension to the 6.1.5.31404 didn't fix it either.

```
##[error]\app\src\_Obsolete\TAB VAT Business Posting Group.al(1,24): error AS0068: The target table of table extension 'NVT VAT Business Posting Group' has changed from 'MISSING' to 'VAT Business Posting Group'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\_Obsolete\TAB VAT Posting Setup.al(1,24): error AS0068: The target table of table extension 'NVT VAT Posting Setup' has changed from 'MISSING' to 'VAT Posting Setup'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Transport\Maintenance\Tyre Management\TAB Item Ledger Entry.al(1,24): error AS0068: The target table of table extension 'NVT Item Ledger Entry' has changed from 'MISSING' to 'Item Ledger Entry'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Business Central\Accounting\TAB Gen. Journal Line.al(1,24): error AS0068: The target table of table extension 'NVT Gen. Journal Line' has changed from 'MISSING' to 'Gen. Journal Line'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Business Central\Accounting\TAB Gen. Journal Template.al(1,24): error AS0068: The target table of table extension 'NVT Gen. Journal Template' has changed from 'MISSING' to 'Gen. Journal Template'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Business Central\Accounting\TAB General Ledger Setup.al(1,24): error AS0068: The target table of table extension 'NVT General Ledger Setup' has changed from 'MISSING' to 'General Ledger Setup'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Business Central\Accounting\TAB General Posting Setup.al(1,24): error AS0068: The target table of table extension 'NVT General Posting Setup' has changed from 'MISSING' to 'General Posting Setup'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Business Central\Accounting\TAB GL Account.al(1,24): error AS0068: The target table of table extension 'NVT G/L Account' has changed from 'MISSING' to 'G/L Account'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Warehousing\Business Central\TAB Inventory Setup.al(1,24): error AS0068: The target table of table extension 'NVT Inventory Setup' has changed from 'MISSING' to 'Inventory Setup'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Warehousing\Business Central\TAB Return Receipt Header.al(1,24): error AS0068: The target table of table extension 'NVT Return Receipt Header' has changed from 'MISSING' to 'Return Receipt Header'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Warehousing\Business Central\TAB Return Shipment Header.al(1,24): error AS0068: The target table of table extension 'NVT Return Shipment Header' has changed from 'MISSING' to 'Return Shipment Header'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\app\src\Warehousing\Business Central\TAB Sales Shipment Header.al(1,24): error AS0068: The target table of table extension 'NVT Sales Shipment Header' has changed from 'MISSING' to 'Sales Shipment Header'. Changing the target of a table extension that has been published is not allowed, because this might break the upgrade of existing installations.
##[error]\ap
```
In other cases, the alc very often fails on ...
`
2020-11-03T14:27:35.2769651Z ##[error]\app\AppSourceCop.json(1,1): error AS0003: The version '16.0.0.5400' of the extension with publisher 'Navitrans' and name 'Navitrans 365' could not be found in the package cache folder. If you do not want to validate breaking changes, remove the property 'version' from the AppSourceCop.json.`

... while the app was actually part of the workingdir/app/.ALOPSCache folder.

Other thing that I've notice is packaging from VSCode uses a lot more CPU / memory (although it include vscode / editorserviceshost / alc / ...) (and is fast!) than the alc.exe process launched by ALOps. Can we assign more resources to the alc process? (priority high?)

![image](https://user-images.githubusercontent.com/25268332/97994905-22e44180-1de6-11eb-8498-0f2ac533a157.png)

Can it be due to the number of apps (87 apps in my case, including all MS test / translation apps of which most are not needed) that is placed inside the /packagecachepath folder?

**Comment by waldo1001** [comment]
Not sure I understand what you mean - haven't seen this anywhere yet.

can you share the yaml?

**Comment by fvet** [comment]
Summary: Compilation with VSCode actually works, compilation with alc.exe shows different output / errors of not locating the AppSource previous app / slower performance.

As discussed, cause is probably related to wrong(?) alc.exe parameters, where the 'previous app' files are passed as part of the 'alpackagecache'. It will be verified if a hidden alc.exe parameter is available to pass a breaking change app path instead.

In addition, it would be interesting to know if exposing the /parallel and /maxdegreeofparallelism parameters would increase the compilation speed, by making a maximum use of the buildserver resources.

```
/parallel[+|-]                      Concurrent compilation. (Short form /p[+|-])
/maxdegreeofparallelism:<n>   Specifies the maximum number of concurrent tasks the compiler should use when compiling the project.
```

**Comment by waldo1001** [comment]
For internal reference:
https://devops.hodor.be/Waldo/ALOpsExamples/_build?definitionId=28&_a=summary

**Comment by waldo1001** [comment]
We decompiled how VSCode does the compile, and we don't see any different in performance unfortunately.  Still, we forced the exact way how VSCode is compiling, so hopefully, it's going to make a difference in this case.

**Comment by fvet** [comment]
FYI, it seems vsix version related. So having an alcompilepath on ALOpsAppCompile@2 would definitly help us moving forward.

![image](https://user-images.githubusercontent.com/25268332/100884699-11a85680-34b2-11eb-8e59-4f4c10bf406f.png)

**Comment by waldo1001** [comment]
The VSIX param is on its way ..

**Comment by AdminHodor** [comment]
Dear @fvet ,

Could you please check this in our latest release v1.438 ?

Kind regards
