### ISSUE TITLE
Publish, but not install? Install, but not publish?

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#253]
One of our pipelines handles our platform build, which produces an application database including all the "standard" apps, which mostly comes from Microsoft or 3rd. party. Some of these 3rd. party apps are not included in our development license, but only in our production license. But we are still publishing them, without installing when running our release to Dev and Test.

So I am looking for a way where it is possible during my build to publish an app, without installing it.

And in our deployment pipeline I'm looking for a way to install apps, without having to publish it again.

**Comment by waldo1001** [comment]
At first glance, this is not going to be possible, but I have a feeling I can improve the way you are using the builds/deployments.

Though, I'm not sure I understand what you're doing here.

Could you elaborate more?  Like .. do you try to use the same environment for building, in your deployment?

**Comment by epernst** [comment]
Yes I'm currently evaluating how we can use ALOps on the large onprem v14 C/Side + AL Hybrid project I'm working on. 
I'm trying to rid of some of the more than 22000 lines of PowerShell scripts we use to handle it today.

Fortunately the C/Side part is not changed very often. So we have a "platform repo" which builds whenever we have C/Side updates incl. new MS CU's. The two main artifacts build by the pipeline is a single tenant database used by our app developers in the local containers and as the application database for our deployments. This platform contains all required apps deployment to all stages and for the developers a test company. 
Test apps (and objects) are not included in the application database, but are published and installed in our dev and test environments, but not in staging and prod. 
Our app-pipeline build compiles the apps and the deploys them to our development environment, where it runs the automated tests. But here it seems to work just fine and was especially looking forward to the v2 compiler....

**Comment by waldo1001** [comment]
Hi @epernst ,

We'll add an option to the publish: "don't install".  
The other way around, the publish-step does already no re-publish when the app is already there - so an "install only" is already possible.

**Comment by AdminHodor** [comment]
Dear @epernst ,

We just release v1.437 which contains the update for this.
=> ALOpsAppPublish: Installation of published Apps can be skipped by setting [installpublishedapps] = false

Kind regards,
