### ISSUE TITLE
AlOps intellisense in vscode?

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#255]
Is there a way to get the intellisense for ALOps to work in VSCode?
It's quite annoying that it reports everything as problems.

![image](https://user-images.githubusercontent.com/5236163/98673385-8bd43800-2357-11eb-8d44-3714491ddb6e.png)

**Comment by waldo1001** [comment]
I'm afraid not .. well .. probably there is a way, but not actually what I advise is to edit ALOps pipelines in DevOps.  Just go to the pipeline, click edit, and you'll have a VSCode-like editor in the browser WITH intellisense ;-).

**Comment by waldo1001** [comment]
hi @epernst , did you test the above?
