### ISSUE TITLE
Timeout to DockerWait

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#256]
Sometimes the Docker Deamon on the Build Server(s) is not responding correctly (typically resolution is a restart). When this happens the DockerWait task will run for 1 hour before aborting the operation and in that timeslot cannot process other requests).

I would like an optional Timeout parameter added to the DockerWait task in ALOps, so that I can specify the maximum no. of minutes that this task may take. If I e.g. have specified 4 minutes and it takes longer, then the task should fail and the Pipeline should fails as well.

**Comment by waldo1001** [comment]
I will take this up with development - looks do-able and a good suggestion.

**Comment by waldo1001** [comment]
Hi @kasperdj ,

could you try `timeoutInMinutes`:
```
- task: string  # reference to a task and version, e.g. "VSBuild@1"
  condition: expression     # see below
  continueOnError: boolean  # 'true' if future steps should run even if this step fails; defaults to 'false'
  enabled: boolean          # whether or not to run this step; defaults to 'true'
  timeoutInMinutes: number  # how long to wait before timing out the task
  target: string            # 'host' or the name of a container resource to target
```

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml

thanks!

**Comment by kasperdj** [comment]
You suggestion solves the issue, thx.
