### ISSUE TITLE
The socket connection was aborted.

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#261]
**Describe the bug**
When running my pipeline creating a new container and publishing 40+ apps on the container, I recently started getting an Unhandled errormessage (The socket connection was aborted.) after approx. 4 minutes during the PublishApp step.

This pipeline used to run well before switching to BC 17, never got any issues, timeouts, ... Docker config has not been changed (24 Gb assigned on a 32 Gb machine). Restarted the machine already.

Any hints?

**the used yaml**
Difficult too share (template based)

**the output**
```
 * App File = [C:\Run\DevOps\Artifacts\Apps\Navitrans_Container Dispatch_17.0.0.6136_OnPrem_17.1_w1.app]

 * App.ID        = bd5e46bb-51a5-4af2-a0fe-8a3b40de361c
 * App.Name      = Container Dispatch
 * App.Publisher = Navitrans
 * App.Version   = 17.0.0.6136
 => Publishing App 'Container Dispatch v17.0.0.6136'
*** Get Tenants
*** Sync Tenant default
*** Sync App [Container Dispatch] on tenant [default]
*** Install App [Container Dispatch] on tenant [default]
WARNING: UnhandledErrorMessage
The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being 
exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '10675199.02:48:05.47758
07'.
At line:156 char:17
+ ...             $Result = Invoke-Command -Session $DockerSession -ScriptB ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-NAVApp], CommunicationException
    + FullyQualifiedErrorId : System.ServiceModel.CommunicationException,Microsoft.Dynamics.Nav.Apps.Management.Cmdlet 
   s.InstallNavApp
```

**Comment by fvet** [comment]
Update, still investigating ...
- Removed the app from the compile pipeline and the pipeline completed successfully. 
- Tried to isolate the app on which the failure occured, by setting up a separate pipeline only including this app (and the dependents). All works fine (so the app seems not the issue)

**Comment by waldo1001** [comment]
Can you please check your install/upgrade code.  It's very much possible there is a cause.  Try to disable all install/upgrade codetunits and try again.  If this fixes it, try to see what happens during these codeunits...

**Comment by waldo1001** [comment]
Hi @fvet ,

can you update us with a status?

**Comment by fvet** [comment]
@jcoe-nvt Can you please provide status update? ;)

**Comment by fvet** [comment]
@waldo1001 Following the bccontainerhelper issue #1592, is there any way I can provide the 'New-BcContainer script' used to create the container? To simulate without ALOps? 

In addition, I see a lot of errors during container creation, is this something we should care about?

```
Message : 
The Federation Service endpoint login failed because the following audience URI does not match an AppIdUri or wtrealm in server or application configuration.

```

**Comment by waldo1001** [comment]
The container creation is a custom script - however, we provide all details in variables, so you *should* be able to run any bccontainerhelper command against it.. .  Did you try?

**Comment by fvet** [comment]
No, haven't found the time yet.
Guess I'm close to a solution for this issue.

It's an(other) AL bug ...

**Comment by waldo1001** [comment]
Weird.
I had similar issues with the right error in the publish step. 

Just to be sure - did you use the ExtensionAPI (so the ALOps.ExternalDeployer) or the regular publish-step?

**Comment by fvet** [comment]
The regular publish step. It would have been nice seeing the exact error indeed ...

(If I remember well, ALOps.ExternalDeployer seems not to work if using batch publish > reported via separate issue)
