### ISSUE TITLE
Question: how to get .bak file as artefact?

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#268]
**Issue**
When running a whole bunch of tests (like MS tests) with a lot of errors, it would make my work more efficient if I do get the .bak file of the build delivered as artefact. I can download this artefact and get a local container up and running with this database to allow to inspect the errors.

**Question**
How to get .bak file as artefact?

I might have overlooked something that already helps me to get this.

**Comment by waldo1001** [comment]
Let's try to change the mindset a bit ;-).

Why not leave the container as is?  Just think about this:
- create an always running container
- create an extra release pipeline that publishes also to your "test container"
- schedule pipeline to run the tests

You can just access the container whenever you need?

(this is what we do ;-))

**Comment by lvanvugt** [comment]
Is indeed an option, but a .bak file allows anyone in my org to build a local container and do their thing. I do not need to provide access to that _always running container_ to all of them. I would love to have that option to.

**BTW**
For me personally also would love to have that option, as the build server to my public projects does not run continuously. My laptop does. ;-)

**Comment by waldo1001** [comment]
We'll make it possible to get the database from a script.  But we'll not add it as artifact (that's going to be too intensive for your pipelines).  It's probably going to be just a parameter in the DockerRemove-step: "BackupPath".  If set, we'll add the backup in that path.

Sit back, relax, we've got you covered ;-).

**Comment by lvanvugt** [comment]
Thanx, but it's not that intensive. We had it in our build pipelines with no major issues. But OK, if i have a pass I reckon I would be able to turn it into an artifact myself.

**Comment by AdminHodor** [comment]
Dear @lvanvugt ,

>>that's going to be too intensive for your pipelines
This was meant to be "for _our_ pipelines", which just comes down to for us to Diskspace.

>>But OK, if i have a pass I reckon I would be able to turn it into an artifact myself.
We got it covered and we'll be glad to make adjustments too it. 
To make it as easy as possible for the majority users, we implemented it as you suggested. 
A default Upload as Artifact, which for special cases can be overruled to go another route.
With the current default you would only have to set [createsqlbackup] = true for the requested scenario.

We added 4 new boolean parameters in the ALOpsDockerRemove step for extracting backups:

- [createsqlbackup]  (default=false)
  => Create SQL Backup from the Database in the container (Not yet multitenant)

- [sqlcompression]  (default=false)
  => Use the SQL-Compress feature, only available on SQL Development/Standard/Enterprise

- [zipsqlbackup]  (default=true)
  => Use dotnet ZIP to compress the BAK file
  => Could come in handy when Transfer speed 2 DevOps is the limiting factor

- [publishsqlbackup]  (default=true)
  => Publish the BAK or ZIP as a pipeline artifact

The final backup path (BAK or ZIP) relative to the DevOps Agent is stored in a Variable [$(ALOPS_CONTAINER_SQLBACKUP)],
this allows you to use other methods for saving the backup with other DevOps Tasks (Azure Upload, FTP, UNC Copy,...)

For your scenario following YAML should do just fine:
```yaml
- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  inputs:
    createsqlbackup: true
```

The resulting Log:
![image](https://user-images.githubusercontent.com/51383893/102021784-afd5cf80-3d82-11eb-8a8e-b3a777a80ed6.png)

The resulting Artifacts:
![image](https://user-images.githubusercontent.com/51383893/102021801-cd0a9e00-3d82-11eb-8ebd-04eb82a00806.png)


This feature will be included in the upcoming v1.147 release (14/12 ~ 16/12).

For the next release we already got 2 improvements lined up:
- Multitenant compatibility (now we only backup the main database)
- Only Create the backup on pipelines in "Failed" or "Partially Succeeded" status (configurable)
- ...suggestions are welcome!

We'll pong on this issue as soon as it's released.

Kind regards,

**Comment by AdminHodor** [comment]
Dear @lvanvugt ,

We just release v1.437 which contains the update for this.
=> ALOpsDockerRemove: Export Container Database via new parameters [createsqlbackup], [sqlcompression], [zipsqlbackup], [publishsqlbackup]

Kind regards,

**Comment by lvanvugt** [comment]
@AdminHodor, we have just implemented this feature in our pipeline. The backup is there, but why do we get two artifact folders with exactly the same content?

![image](https://user-images.githubusercontent.com/18466198/104703136-3f222a00-5717-11eb-99e4-b2775812a6b5.png)

**Comment by waldo1001** [comment]
Hi @lvanvugt ,

could you please open a new issue (with decent title ;-)) and also provide the yaml?  We did quite some plumbing around this area, and have a new release coming up  .. and if a fix is necessary, we need to include that!

**Comment by lvanvugt** [comment]
Of course. I guess you reckon me to be good at indecent tiles. ;-)

**Comment by waldo1001** [comment]
Actually no, but this particular issue isn't really related to the issue you have now ;-)
