### ISSUE TITLE
[Offtopic] Notification upon new ALOps release?

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#270]
**Is your feature request related to a problem? Please describe.**
A bit offtopic, but what is the best way to get notified on new ALOps releases?
E.g. I'd like to get notified when https://github.com/HodorNV/ALOps/blob/master/Documentation/changelog.md has been updated.

PS: And maybe have some insights on when the 'upcomming release' is approx. scheduled.

**Comment by waldo1001** [comment]
Hi @fvet,

We don't have a decent solution for this .. I'll see what I can do but for now, I'll try to create a tweet on "https://twitter.com/BC_ALOps" for each new release.

As we work as agile, it's difficult to predict what's upcoming. We tag the issues with "part of upcoming release" when it's being worked on .. that's kind of an indication.  Would that work?

The "when" is really difficult to schedule, as it's dependent on many things that is out of our hands: the marketplace validation for example.  Some uploads have taken days, others have taken minutes - both success and failures.  And it's difficult to predict :(.  And together with the agile approach, we just don't know when a new update reaches you.

**Comment by waldo1001** [comment]
We're thinking about having a pinned issue, and posting updates on that, and then you can subscribe to that issue for updates - what do you think?

**Comment by fvet** [comment]
👍 It's visible to everyone and I like the subscription part of it.

![image](https://user-images.githubusercontent.com/25268332/101988189-5f824300-3c98-11eb-866d-45fae0e1585a.png)

**Comment by waldo1001** [comment]
HI @fvet ,

here's the issue you can subscribe to!

https://github.com/HodorNV/ALOps/issues/284
