### ISSUE TITLE
Question: ALOps Publish: Your program license does not allow you to publish

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#271]
I'm trying to deploy an extension in an addon range 112....... to a customer database (with the customers license). When I try to do this, I get the error "Your program license does not allow you to publish". 

I can import the development license temporary, but then I need to restore the customers license afterwards. Is there a way to export the customers license to a temp folder, for later restore?

Or is there another way to do this? Am I missing something?

**Comment by peterz84** [comment]
Only option is to create a runtime package?

**Comment by waldo1001** [comment]
I think this should be possible with a runtime package, indeed .. not sure.

I never exported a license from a server .. but know you can execute ALOpsDockerExec - which basically executes powershell inside the docker container.  You could go "fance" with it ;-).

also, if it's not in a container - you can obviously just run powershell in between the ALOps - steps.

So - assuming exporting a license is possible - and assuming one can import a license that was previously export - you could do it like that?

**Comment by peterz84** [comment]
Runtime package works indeed.
