### ISSUE TITLE
Remove internalsVisibleTo before compile

### ISSUE THREAD

**Issue by kaspermoerch** [HodorNV/ALOps#272]
**Is your feature request related to a problem? Please describe.**
If the Access property is used to limit access to specific areas of your app, but you still want to be able to run automated tests, you have to add the test app to internalsVisibleTo in app.json of the app. However it might not be desirable to have internalsVisibleTo in the app.json of the app you actually publish.

**Describe the solution you'd like**
I want to be able to specificy one or more app ids in ALOps App Compiler. If these app ids are listed in internalsVisibleTo they should be removed before compiling.

**Describe alternatives you've considered**
I don't see any alternatives besides cleaning up the app.json and then recompiling the app.

**Additional context**
No additional context.

**Comment by waldo1001** [comment]
You can create 2 app.json files.  

In the compile-step, you provide a "targetproject" which refers to an app.json.  By providing the specific app.json, you can "switch versions".

Look at issue: #218 

Does that sound as a solution for you?

**Comment by kaspermoerch** [comment]
Yes, that could surely work.
I'll give it a try and report back.

**Comment by kaspermoerch** [comment]
> You can create 2 app.json files.
> 
> In the compile-step, you provide a "targetproject" which refers to an app.json. By providing the specific app.json, you can "switch versions".
> 
> Look at issue: #218
> 
> Does that sound as a solution for you?

I can confirm that I'm able to achieve the desired result using the suggested solution.
