### ISSUE TITLE
AlOpsAppCompile '-Ruleset' parameter

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#275]
**Is your feature request related to a problem? Please describe.**

Can we have a new 'ruleset' parameter on pipeline level (AlOpsAppCompile@2) allowing us to specify a different ruleset then the project ruleset? This would allow us to (pre-)check on (new) warnings using a 'company' ruleset, without having to update all individual ruleset first for each repo. Any thoughts on this?

Cfr. https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=898650889617408

![image](https://user-images.githubusercontent.com/25268332/101469142-a2fd4a00-3944-11eb-886c-3b8923a68872.png)

**Comment by waldo1001** [comment]
This is possible, and very interesting!  Will add!

**Comment by AdminHodor** [comment]
Dear @fvet ,

We just release v1.437 which contains the update for this.
=> ALOpsAppCompile@2: Define Ruleset via parameter [ruleset], overrules VSCode settings

Kind regards,
