### ISSUE TITLE
ALOps - 'Generate permission set'

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#277]
**Is your feature request related to a problem? Please describe.**
Is there a way to run the 'Generate Permission Set for current Extension objects' (VS Code commandlet) using ALOps? Before releasing our apps, we're thinkin to include one 'APPNAME ADMIN' permission set that contains all objects. Or what's the best way to update permission sets in an semi-automated way (if no different permission sets apply)

**Comment by waldo1001** [comment]
Hm, executing VSCode commands .. I don't know if that's even possible.. .  It all depends on how it was developed by Microsoft.

In my opinion, that function is not really good practice anyway, but I understand that in some cases it might help.. .

I'm going to put it on the (way too long) list to figure out .. .

**Comment by waldo1001** [comment]
Hm, may be it's not a bad idea afterall - looking at it from the "it's an admin permission set".  Any app needs an admin permission set.

We'll see what we can do.

**Comment by fvet** [comment]
Looking into https://github.com/microsoft/AL/issues/6002, it might be better if we would have a new AppSourceCop warning that detects missing permissions. Developers then need - as part of their PR being rejected - fix the permission set from within VS Code, so no need to have ALOps or the pipeline generate the permission sets. If think it could be sufficient if we're already warned about it.
