### ISSUE TITLE
ALOps App Publish is blocked by Kaspersky Security

### ISSUE THREAD

**Issue by CarloAxians** [HodorNV/ALOps#278]
We want to publish our app on a server of one of our customer's.
The executing of the powershell scripts is blocked by the virus scanner, Kaspersky Security.

In Azure DevOps I get the error message:
_Access to the path 'C:\Agent\_work\_tasks\ALOpsAppPublish_c004e2d2-e842-40f0-9ed4-89fb9bdd2e33\1.436.1953\ps_modules\alops\0beaf3f5-c58f-4cf2-a652-0ac8ca8155ea.ps1' is denied._

When I try to open the file on the server I get the error:
![image](https://user-images.githubusercontent.com/75834758/101889360-9a548000-3b9f-11eb-937c-61f3b81d6b42.png)

Other PowerShell scripts of ALOps are not blocked, so it has something to do with the code in this particular file.

**Comment by waldo1001** [comment]
This might be because of the type of obfuscation we use .. we'll have a look!
