### ISSUE TITLE
Custom "fixed_tag" for containers not created with ALOps

### ISSUE THREAD

**Issue by borisimple** [HodorNV/ALOps#281]
I need to use ALOps to release apps in Docker in a container which is not created with ALOps, but with a custom script shown bellow.

```
    New-BCContainer `
        -accept_eula `
        -updateHosts `
        -artifactUrl $localization `
        -containerName $containerName `
        -auth NavUserPassword `
        -credential $cred `
        -licenseFile $tempLicensePath `
        -additionalParameters @("
                                -l traefik.enable=true 
                                -l traefik.http.routers.$containerName.tls=true 
                                -l traefik.http.routers.$containerName.tls.certresolver=myresolver 
                                -l traefik.http.services.$containerName.loadbalancer.server.port=80 
                                -l fixed_tag=$containerName ")
```

If I do ```docker inspect *container ID*``` I can see that my tag is there:

![image](https://user-images.githubusercontent.com/16119596/102351774-48e53000-3fa7-11eb-9c2b-f7617a4dd494.png)

In the release pipeline, I am using that value for "Fixed Container Tag" parameter.

![image](https://user-images.githubusercontent.com/16119596/102352008-9c577e00-3fa7-11eb-8fbb-fb10b94d95bf.png)

Unfortunatelly, ALOpps App Publish fails to find the container.

![image](https://user-images.githubusercontent.com/16119596/102352124-c27d1e00-3fa7-11eb-8f87-c2e475f8915b.png)

**Comment by waldo1001** [comment]
This is a very good question and a nice usecase .. which we also apply ourselves.

But .. what we simply do, is we install the alops.externaldeployer in the container (you can add a script to automatically do that) .. and just publish with the "extension API"-step.  

That said - it should also be possible with the fixed-tag, but i'll have to look up how that is done ..

**Comment by waldo1001** [comment]
Try this:

```PowerShell
    New-BCContainer `
        -accept_eula `
        -updateHosts `
        -artifactUrl $localization `
        -containerName $containerName `
        -auth NavUserPassword `
        -credential $cred `
        -licenseFile $tempLicensePath `
        -additionalParameters @("
                                -l traefik.enable=true 
                                -l traefik.http.routers.$containerName.tls=true 
                                -l traefik.http.routers.$containerName.tls.certresolver=myresolver 
                                -l traefik.http.services.$containerName.loadbalancer.server.port=80 
                                -l TFSBuild=$containerName ")
```

The label needs to be "TFSBuild", that's what we're looking at in the "fixed_tag" .. .

**Comment by borisimple** [comment]
Yep, that did the work.
