### ISSUE TITLE
[Feature Request] ALOps Extension API with AAD Application

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#287]
**Describe the solution you'd like**
The release pipeline in combination with the ALOps Extension API (Publish) requires a (licensed) BC-User credentials. With the AAD Application from within Business Central we can register an App with the Client ID. It would be awesome if it would be possible to use the ALOPS Extensions API without using to have a  BC-User and skipping the Username and Password-fields setup for the release pipeline.

**Additional context**
<img width="952" alt="Schermafbeelding 2020-12-20 om 12 12 16" src="https://user-images.githubusercontent.com/44637996/102711824-bc937f80-42bc-11eb-8d8e-8eb34aff50b4.png">

**Comment by waldo1001** [comment]
We're looking into the ability to use service-to-service communication .. which should already work.. .  Will report back!

**Comment by DanielGoehler** [comment]
Freddy has this enabled in BcContainerHelper: https://freddysblog.com/2021/01/27/publishing-apps-to-a-business-central-online-environment/

**Comment by waldo1001** [comment]
Exactly.  
We're also adding this to ALOps.  👍

**Comment by Arthurvdv** [comment]
The ALOps Extension API works perfectly in combination with the AAD Application from within Business Central.
Best guide to setup is here: https://www.kauffmann.nl/2020/09/14/service-to-service-authentication-for-automation-apis-in-business-central/ (also mentioned in an other issue here somewhere).

**_CSPs can also pre-consent an app for partner AADs that they are managing by adding the AAD application to the Adminagents group in the partner tenant. For more information see https://docs.microsoft.com/en-us/graph/auth-cloudsolutionprovider._**
This is, for us as CSP-provider, an important note on the end of the guide from AJ. This works briljant, where the deployment for al our customer is easy to setup without having to register an App on every ADD.
