### ISSUE TITLE
Filter App Published by ALOpsAppCompiler v2

### ISSUE THREAD

**Issue by pri-kise** [HodorNV/ALOps#288]
**Is your feature request related to a problem? Please describe.**
We would need some easy way to filter which app files should get published by the new CompileTask v2

**Describe the solution you'd like**
Having a Pattern Similiar to the DowloadBuildArtifact Task

   ` publishAppPattern: '**/*.app'`

**Describe alternatives you've considered**
Having multiple Compile task with the parameter
`alsourcepath` set to different folders and enabling or disable `publishartifact`.

**Additional context**

**Comment by waldo1001** [comment]
Hi, to mitigate this, you can switch off the publish-parameter in the compile-step, and publish the artifacts that you want, in a separate step (default DevOps step).

Would that be a solution?
