### ISSUE TITLE
ALOps Extension API: allow to filter when using Batch Publish

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#289]
**Issue**
My repo contains multiple apps, including test apps and dependencies. When deploying them using the **ALOps Extension API** I need to use the _API interaction_ type **Batch Publish**.
As there is no _App filter_ parameter available it will publish all apps, including the test apps. I would like to be able to only install the APP apps, by setting a filter like I can using the  _API interaction_ type **Publish**. The latter can not help me as it will not take into account the dependencies between the APP apps.

**Solution**
Provide _App filter_ parameter (with functionality behind) for the _API interaction_ type **Batch Publish**.

**Comment by lvanvugt** [comment]
Any progress on this as we are in need of this now.

**Comment by waldo1001** [comment]
Luc,

It's not on the list, but we're working on other prios at the moment.
Tell me why this is a showstopper, and let me see if I can find a way around.. .  There are enough building blocks that should facilitate any workflow.. .

**Comment by lvanvugt** [comment]
It seemed to be a showstopper as it will not allow me to filter out the test apps when deploying. However, we just found out we can live with the workaround of not publishing the test app in the build pipeline. So, for now OK, but on longer term our build pipelines will need to publish the test app(s) too.

**Comment by lvanvugt** [comment]
@waldo1001 the work around for now is to no publish the test app as a build artifact. I nocer workaround (that I actually wanted to use) is to unselect the test app as _Artifact download_ in the **Agent job** step of my release stage. But it seems that the _Dynamicxs 365_ folder is not shown here. Instead a _AgriwareDevelopment_ folder is displayed. Not sure but it seems this relates to the name of the ADO project. It's not soemthing we did configure.

![image](https://user-images.githubusercontent.com/18466198/109518291-67d56780-7aaa-11eb-935b-9b0fa162d8bd.png)

It looks like this has to do with the difference between build and pipeline artifacts. The two other folders are the result of two PublishPipelineArtifact task we added to our build pipeline.

**Comment by waldo1001** [comment]
What we do is to delete the test-apps before publish (pure powershell) 
Advantage is that you have more in control what to keep, and what to throw away.. .

Would that be an option for you?

**Comment by lvanvugt** [comment]
> Would that be an option for you?

The option above. See screenshot. That's simplest for any user.

**Comment by waldo1001** [comment]
Not sure we can get this right.. .  I mean - what is a testapp?  It's just an app.  There are projects that have like 15 apps within one repo.  We just compile them, and make the into an artifact.

We coult turn every single app into a different artifact .. but that wouldn't let it end up here either, apparently 🤔.  

Also, in my case for instance I'm downloading 35 artifacts from different pipelines.  Removing all test-apps is one line of powershell .. much less work than having to uncollapse/select stuff in that list.. .

I'll see what I can do, but last time we changed anything on the artifacts, we broke some builds for people depending on the way it works now.  May be with yet another extra setting, we can get something done - where I'd chose for splitting all apps into a separate artifact folder.. IF possible.

**Comment by waldo1001** [comment]
Having said that - do remember that there is/was a DevOps bug that didn't let us split apps into separate folders, where you rightfully reported that all artifacts were put into both.. .  So .. not sure if we'll be able to do this..

**Comment by lvanvugt** [comment]
> What we do is to delete the test-apps before publish (pure powershell)
> Advantage is that you have more in control what to keep, and what to throw away.. .

Could that be an ALOps step?

**Comment by waldo1001** [comment]
Could be - but it's really just a oneliner (the writehost really isn't necessary) in PowerShell :-).

Here it is: 
![image](https://user-images.githubusercontent.com/12088142/109554591-b566ca00-7ad4-11eb-9e2e-9708ded7642d.png)

The PowerShell:
```powershell
Write-Host "Cleaning [$(System.ArtifactsDirectory)] => [*-TEST_*.*]"
Get-ChildItem -Path "$(System.ArtifactsDirectory)" -Filter "*-TEST_*.*" -Recurse | Remove-Item -Force:$true -Confirm:$false -ErrorAction SilentlyContinue
```

**Comment by lvanvugt** [comment]
Thanx. Will use it.

**Comment by acjdekorte** [comment]
The switching off of artifact downloads does not lead not to the correct behaviour, since no apps are downloaded anymore to the ADO agent. Which lead to problem when trying to publish.
