### ISSUE TITLE
Sign app and Publish artifact after running ALOpsAppCompiler@2 

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#292]
I can see it is possible to Publish artifact by adding  publishartifact: true in the ALOpsAppCompiler@2 

but is it also possible to sign and then publish artifact.

I can sign by using ALOpsAppSign@1, but if I set publishartifact: true  in the ALOpsAppCompiler@2 it is publish before it is signed.

Is this possible or do I have to use ALOpsAppCompiler@1 in order to solve this.

**Comment by waldo1001** [comment]
Hi Morten,

I don't get it.  Can't you use sign in combination with the compilerV2?  I wouldn't know why?

**Comment by MortenRa** [comment]
Maybe I can but then I´m not sure how it should be configured in the yaml and I can not set the app_file_suffix in the ALOpsAppCompiler@2

If I set publish_artifact : true  I would expect it to publish. 

I will try some more testing

**Comment by waldo1001** [comment]
Yes, but you'll have to set that to false, then sign, then publish the artifact yourself (it's a DevOps step).

**Comment by MortenRa** [comment]
Okey I´ll try and app_file_suffix is not supported in compilerv2 correct?

**Comment by waldo1001** [comment]
Correct.  But you CAN work with your naming template .. would that help?

**Comment by waldo1001** [comment]
Can you check this example if that is a solution for you?

https://github.com/HodorNV/ALOps/blob/master/Examples/Compiler%20V2/06_AppSigning.yml

**Comment by waldo1001** [comment]
@MortenRa , can this be closed?

**Comment by MortenRa** [comment]
Yep I´m all good
