### ISSUE TITLE
PFX Password not set. Use parameter pfx_password to set the PFX Password

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#30]
Keep getting this error, could you either update your examples in the documentation on how to set the parameter. or comment here with example, seems do to be straight foward. 

ALOps App Sign
4s
Starting: ALOps App Sign
==============================================================================
Task         : ALOps App Sign
Description  : ALOps App Sign
Version      : 1.422.538
Author       : Hodor
Help         : Codesign Business Central extension with .pfx.
==============================================================================
*** Validate configuration
##[warning]PFX Password not set. Use parameter pfx_password to set the PFX Password.
##[error]Cannot bind argument to parameter 'String' because it is null.

**Comment by AdminHodor** [comment]
Hello,

The pfx_password is done via Environment-Variables instead of parameters. 
Hereby the correct example YAML task to make this work:

````
- task: ALOpsAppSign@1
  displayName: 'ALOPS App Sign'
  env:
    pfx_password: $(alops_pfx_password)
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    pfx_path: $(PFXFile)

Thanks for the notice, we will update the documentation and make a change to allow this parameter as input instead of environment variable.

**Comment by BartBourgeois** [comment]
Hello, in the next release v1.426 we provided a more standard way of linking the password via parameters. We kept the environment variable and added the same variable on input level.

[Current]
- task: ALOpsAppSign@1
  displayName: 'ALOPS App Sign'
  env:
    pfx_password: $(alops_pfx_password)
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    pfx_path: $(PFXFile)

[New]
- task: ALOpsAppSign@1
  displayName: 'ALOPS App Sign'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    pfx_path: $(PFXFile)
    pfx_password: $(alops_pfx_password)
