### ISSUE TITLE
Use ALOps on a server without agent over PowerShell Remote

### ISSUE THREAD

**Issue by borisimple** [HodorNV/ALOps#303]
Consider this case (OnPrem only):

- You don't have access to a production server and you cannot install an agent on it
- You are not able to use ALOps to publish/release your apps

Have you considered enabling remoting services using PowerShell to accomplish this?

**Comment by waldo1001** [comment]
So, basically it can be compared to "how can you walk when you'd loose both legs" ;-).

Remote PowerShell is something we won't do from ALOps scripts.  Basically because it's too dependent on the customer's (or partner's) infrastructure.  

Why you ask?

**Comment by borisimple** [comment]
> Why you ask?

Because I am being asked 🤣
