### ISSUE TITLE
ALOps Compile does not include assemblyprobingpaths to alc.exe parameters and fails to compile app

### ISSUE THREAD

**Issue by ik3ras** [HodorNV/ALOps#304]
**Describe the bug**
Since this morning all piplelines crash due to failing to compile apps which have dot net assembles defined.
ALOps Compile does not include assemblyprobingpaths to alc.exe parameters and fails to compile app

```
*** Assemblies in App found. Adding Probing Paths (2).
  * C:\Run\DevOps\app\.netpackages
  * C:\Run\DevOps\app\gac
*** Add Windows Assembly Path [C:\Windows\assembly]
*** Detect ALC.EXE Features.
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /?
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps\app" /out:"c:\Run\DevOps\AppName.app" /fullpaths
*** AL Compiler Exit Code: 1
*** AL Compiler raw logs: Start
```

when it was working, log looked like this:
```
*** Checking for Assemblies in App
*** Assemblies in App found. Adding Probing Paths (2).
  * C:\Run\DevOps\app\.netpackages
  * C:\Run\DevOps\app\gac
*** Add Windows Assembly Path [C:\Windows\assembly]
*** Detect ALC.EXE Features.
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /?
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps\app" /out:"c:\Run\DevOps\AppName.app" /fullpaths /assemblyprobingpaths:"C:\Run\DevOps\app\.netpackages","C:\Run\DevOps\app\gac","C:\Windows\assembly"
*** AL Compiler Exit Code: 0
```

**Comment by waldo1001** [comment]
ALOps didn't change .. so something must have changed on the project-side.  Are you sure you still have the right settings?

Please provide more info like suggested when creating this issue.

**Comment by ik3ras** [comment]
Sorry, but projects did not change. I even tried to run  build on old commit which was built yesterday, but it also failed.
ALOps has changed yesterday. 
This version is being run today
```
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extensions for Business Central
Version      : 1.438.2067
Author       : Hodor
Help         : Compile a Business Central extension from AL code.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                                              value
----                                              -----
usedocker                                          True
fixed_tag                                              
targetproject         C:\DevOps\_work\11\s\app\app.json
nav_computername                                       
nav_serverinstance                                BC140
nav_tenant                                      default
nav_ports_dev                                      7049
bc_username                                            
bc_password                                            
al_compiler_version                          0.12.15355
ruleset                                                
al_analyzer                                            
nav_app_version                         17.2.[yyyy]01.*
vsix_download_path                                     
use_ssl                                           False
download_test_symbols                             False
usecompression                                     True
publish_artifact                                   True
failed_on_warnings                                False
app_file_suffix                                    _APP
updatebuildnumber                                  True
setup_working_folder                              False
```
This version was running yesterday
```
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extensions for Business Central
Version      : 1.438.2062
Author       : Hodor
Help         : Compile a Business Central extension from AL code.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                                              value
----                                              -----
usedocker                                          True
fixed_tag                                              
targetproject         C:\DevOps\_work\11\s\app\app.json
nav_computername                                       
nav_serverinstance                                BC140
nav_tenant                                      default
nav_ports_dev                                      7049
bc_username                                            
bc_password                                            
al_compiler_version                          0.12.15355
ruleset                                                
al_analyzer                                            
nav_app_version                         17.2.[yyyy]01.*
vsix_download_path                                     
use_ssl                                           False
download_test_symbols                             False
usecompression                                     True
publish_artifact                                   True
failed_on_warnings                                False
app_file_suffix                                    _APP
updatebuildnumber                                  True
setup_working_folder                              False

```

Yaml for task is
```
steps:
- task: Hodor.hodor-alops.alopsdeploytask.ALOpsAppCompiler@1
  displayName: 'Compiling the $(app_name)'
  inputs:
    usedocker: true
    targetproject: app/app.json
    nav_app_version: '17.2.[yyyy]01.*'
    app_file_suffix: '_APP'
```

**Comment by ik3ras** [comment]
![image](https://user-images.githubusercontent.com/45070842/105981806-30386180-609f-11eb-9cf1-5d36f1b3de89.png)

**Comment by waldo1001** [comment]
Sorry about this .. I'm going to dive into it!

**Comment by ik3ras** [comment]
Also, not sure if bug or just a question not realy related to issue itself.
You notice '17.2.[yyyy]01.*' in version - this is due to the fact that previously [yyyyww] was producing results like 202051 and after year changed it now produces 20211 instead of 202101. This also caused us crashing builds becouse of versions built after new year were lower than last year.
Not sure if this is by design because i cannot find where such variables like yyyy are described. Is there any documentation on this?

**Comment by kasperdj** [comment]
We have the exact same problem. AlOps identifies the folders with add-in's and add this to the AssemblyProbingPaths but still compilation fails. This is both for custom dll and for "general" SQL.NET

![image](https://user-images.githubusercontent.com/54669593/105992645-acce3e80-60a5-11eb-8562-d3b302d11497.png)

**Comment by InnoNavSupport** [comment]
Same problem here. ALC.exe runs without AssemblyProbingPaths.

**Comment by waldo1001** [comment]
We're on it!  My apologies - I wasn't aware we pushed a hotfix yesterday, which broke the above... I will keep you posted!

**Comment by waldo1001** [comment]
Hi - can you all try again? The fix is online.

**Comment by kasperdj** [comment]
It works again, thx. for a quick fix :-)

**Comment by ik3ras** [comment]
Thanks, looks like it is working. At least for first few builds.

Can you also shed some light on previous question:

> Also, not sure if bug or just a question not realy related to issue itself.
> You notice '17.2.[yyyy]01.*' in version - this is due to the fact that previously [yyyyww] was producing results like 202051 and after year changed it now produces 20211 instead of 202101. This also caused us crashing builds becouse of versions built after new year were lower than last year.
> Not sure if this is by design because i cannot find where such variables like yyyy are described. Is there any documentation on this?

**Comment by waldo1001** [comment]
Thanks all for confirming - and again my apologies for any inconvenience.. .

@ik3ras,
We actually just apply the default .Net datum formats .. so I'm not sure why this is behaving differently with you than with us.

The version is perfectly formatting in our case:
![image](https://user-images.githubusercontent.com/12088142/106008051-39cdc380-60b7-11eb-9330-81e5c5f65753.png)
setting:
![image](https://user-images.githubusercontent.com/12088142/106008217-5d910980-60b7-11eb-9243-8e17f4799523.png)

Could it be some kind of regional setting? 🤔

**Comment by waldo1001** [comment]
@ik3ras ,

I'm going to close this issue - but could you please be so kind to open a new one with the above issue, and with a pipeline that has that problem, including the output?

**Comment by ik3ras** [comment]
Sure, i will do some tests prior creating new issue. Thanks again!
