### ISSUE TITLE
ALOps Extension API: Unpublish previous version

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#320]
**Is your feature request related to a problem? Please describe.**
The list of Installed Extensions is getting cluttered after a while of releasing new versions of a extensions. Having the older versions here could create a possible issue when the user ignorant installs a previous version of the extension. The default sorting on only the name column doesn't help and shows the active version somewhere in between.

**Describe the solution you'd like**
A flag to set true/false to unpublish previous versions after a successful publish and install of a newer version of the extension. 

Maybe include a extra flag keepversions? Not sure if that's a valid use case, but then we can specify the amount of older versions to leave published and not installed behind.

An other option would be to have a interaction 'unpublish'. Then I need to figure out howto implement this in the Release pipeline, but could give more flexibility for a maintenance pipeline to separate the publishing and installing from the unpublishing action. I think I prefer a flag combined with the Publish interaction to keep the release pipeline less complex?

**Describe alternatives you've considered**
Leave it as it is :-) There's no technical justification to do this, but it would be better to not leave a complete history of uninstalled apps behind. Not sure if the 'Not installed' Apps are automatically removed on a Major update (SaaS).

**Additional context**
![image](https://user-images.githubusercontent.com/44637996/108583084-95e2db00-7337-11eb-9d6c-dfc34cb52259.png)

**Comment by waldo1001** [comment]
I'm not sure we're going to be able to do that, as it's rather a cloud-thing.  The only thing we can do from the automation api is to upload the extension.  

That said - I don't seem to remember to have had this behaviour in our test-environments .. so i'll check.

**Comment by waldo1001** [comment]
We checked.  This is a feature that we can't do because of the limitation of the automation api.  

Is this a screenshot of a sandbox?  I assume so, because in a product tenant, it should be cleaned...

**Comment by Arthurvdv** [comment]
This is indeed a Sandbox. I’ll check the behavior on de Production environment and report back here.

**Comment by Arthurvdv** [comment]
On a Production-environment unfortunately the same result as the Sandbox-environment.
How are other ALOps users handeling this with SaaS I'm wondering.

![image](https://user-images.githubusercontent.com/44637996/110084580-6b117180-7d90-11eb-853b-c7cf202ce114.png)

**Comment by waldo1001** [comment]
I checked in my own tenant.  I *assume* it just cleans after a while.. .

Let's give it some time.. .

**Comment by Arthurvdv** [comment]
You’re right, it indeed cleans after while. This while is two time a year after an major release when the environment is upgraded.

Keeping up to six months of different PTE extensions versions isn’t ideal, but I get that this is limitation of the automation API from Microsoft.

If in the future the API also supports unpublish methods let’s discuss again if ALOps can integrate with that.

**Comment by waldo1001** [comment]
Then we most probably will ;-)
