### ISSUE TITLE
TestResults.xml contains skipped tests which is fuzzing the success rate

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#324]
TestResults.xml, the main result of the **ALOpsAppTest** step, contains, next to passing and failing tests, also the skipped tests (based on the DisabledTests.json input to ALOpsAppTest. IMHO this is unwanted as this fuzzes the success rate of a test run.
Taking the following resume of the test tab of an ADO pipeline the success rate (or pass percentage) appears as 84.17%. However, this, IMHO real pass rate (being the tests that passed compared to the total number of tests run) is higher:

`649/(649+26) = 96,14%`

If skipped tests will stay, you will never be able to get a success/pass rate of 100%.

![image](https://user-images.githubusercontent.com/18466198/108895094-6f60c080-7613-11eb-9d6d-cf2f36fa9b09.png)

**Expected behavior**
Skipped tests should not be in the TestResults.xml

I am reporting this here as I  am not sure whether this is handled by ALOps or BCContainerHelper. If it is the latter I will raise this issue there (i.e. [https://github.com/microsoft/navcontainerhelper](https://github.com/microsoft/navcontainerhelper))

**Comment by waldo1001** [comment]
Hm, I don't know I agree with that viewpoint.

You have passed tests, failed ones, and skipped ones.  With the disabledtests, you skip them .. if you don't want them in your output, they shouldn't be skipped, but deleted.. .  It's just a way how DevOps reports them.. .

I have no idea how Freddy reports them - but I would say the same (not sure!).

Now .. we ARE working on testability, so I'll see what we can do ..

**Comment by lvanvugt** [comment]
> Hm, I don't know I agree with that viewpoint.

Thought so ;-)

The thing is, IMHO: if you have a set of tests of which some are failing for a reason that we cannot tackle for the moment, but we want to have a clear cut reporting that all other tests are OK, then disabling them means: they are not part "of the game", and you want to see green for the test run for those not disabled. Clear cut green (100%) or red (< 100%). 
If the disabled ones are in the reporting it will never be green (100%).

> I have no idea how Freddy reports them - but I would say the same (not sure!).

Question: you're implicitly saying that ALOps is creating the TestResults.xml without making use of BCContainerHelper?
 
> Now .. we ARE working on testability, so I'll see what we can do ..

I know, just helping you a bit.

**Comment by waldo1001** [comment]
We're not using BcContainerHelper for this step - but the solution is based on the same: a page in BC that we use to get the feedback.  That's why I'm not sure - Freddy might post-process the xml.. .

**Comment by lvanvugt** [comment]
OK, I'll start the discussion with Freddy too. ;-)

**Comment by waldo1001** [comment]
may be we should test Freddy's output first..

**Comment by lvanvugt** [comment]
Indeed.

**Comment by waldo1001** [comment]
We'll add it as a parameter... (something in the line of "removeSkippedFromResult")

**Comment by lvanvugt** [comment]
@waldo1001, I checked what Run-TestsInBCContainer returns in the TestResults.xml and it's only the successes and the failures. Skipped tests are not part of it. So, that's in line with my view on this.

**Comment by waldo1001** [comment]
Fair enough - skipped tests are not reported as skipped tests 😜.

**Comment by lvanvugt** [comment]
@waldo1001 any update on this?

**Comment by CarloAxians** [comment]
Hi @waldo1001 and @lvanvugt, 
I noticed this issue is closed, but I cannot find the parameter removeSkippedFromResult.
Is this still on the roadmap to be released, or is there an other solution for this?

**Comment by lvanvugt** [comment]
@CarloAxians, the way it seems to be solved is that skipped tests are not exported into the **TestResults.xml** anymore.

**Comment by waldo1001** [comment]
Indeed.
The skipped tests resulted in a lower pass-percentage, as Luc correctly mentioned.

**Comment by lvanvugt** [comment]
> Do I need to specify something to accomplish this, because in the TestResults.xml I get this:
> 
> <assembly name="139151 DocumentSendingPostTestsSMTP" test-framework="PS Test Runner" run-date="2021-10-16" run-time="16:06:17" total="83" passed="51" failed="0" **skipped="32"** time="29.974">
> 
> And I would have expected that the skipped ones are removed from the result.

I am currently having the same, but it seems (still investigating) that it might relate to setting up the test suite by means of a install codeunit or using the `extensionid` parameter of the `ALOpsAppTest` task.

**Comment by lvanvugt** [comment]
OK, just completed the test: indeed when using the the `extensionid` parameter skipped tests will not be included in the results. When using an install codeunit it will not give this result.

**Comment by CarloAxians** [comment]
Thanks @lvanvugt for looking into this. We are also creating the test suite in the install codeunit. I'll have a look if I can change this in our scripts.
