### ISSUE TITLE
ALOps App Sign Verify: can not bind argument path

### ISSUE THREAD

**Issue by mrabus** [HodorNV/ALOps#330]
**Describe the bug**
I added the code signing steps from your example 09 to my pipeline. When executing the pipeline, the signing works just fine but "ALOps App Sign Verify" fails and I don't know what I can do to fix it. Additionally, it would be appreciated if you could dive a bit into what the step is actually verifying. Do I even need the step if I signed my app one step before? 

**the used yaml**
![image](https://user-images.githubusercontent.com/2485163/109425249-b241e000-79e7-11eb-93b4-68e2c0d5724f.png)

**the output**
![image](https://user-images.githubusercontent.com/2485163/109425204-7b6bca00-79e7-11eb-8291-ca43b6c3484c.png)

**Expected behavior**
Successful execution of the step :-)

**Comment by waldo1001** [comment]
It *might* have something to do with the "ü" character.. . 🤔

You can remove the step in the meantime, the verify is basically only there as a check .. it failing on a path shouldn't fail the sign itself.. .

**Comment by mrabus** [comment]
It works without the verifying step. What is the step testing actually? 

Is it possible to work around / escape the special characters?

**Comment by waldo1001** [comment]
We were able to repro it, and release a bugfix for it - which should be online?

**Comment by mrabus** [comment]
Will check that

**Comment by mrabus** [comment]
Worked like a charm, case closed. 

Thanks for the quick resolution
