### ISSUE TITLE
Cannot bind argument to parameter 'ContainerID' because it is an empty string.

### ISSUE THREAD

**Issue by marcelvos1** [HodorNV/ALOps#334]
Since yesterday all build pipelines faild with the same error (Cannot bind argument to parameter 'ContainerID' because it is an empty string.). I have investigate this problem but cannot find any solution. When I run the 'ALOps Agent Maintenance' task and remove all artifacts the problem is gone. Today I run again in the same error. After removing the artifacts the first build was successful, but the 2nd build failed again.
Please advice. Thanks!

The error occurs in task 'ALOPS - Start Docker Container'.

![afbeelding](https://user-images.githubusercontent.com/41510009/110034627-fb24cc00-7d3a-11eb-94f7-5d15e7e3ee8e.png)

[log failed task.txt](https://github.com/HodorNV/ALOps/files/6086787/log.failed.task.txt)

**Comment by waldo1001** [comment]
I'm afraid it's maintenance on your build sever.

Look at the previous step (most probably "DockerCreate".  It will have a message in the end .. may be you ran out of space on your build agent?

**Comment by marcelvos1** [comment]
Hi Waldo,

See the log from the Create Docker step
[CreateDocker.txt](https://github.com/HodorNV/ALOps/files/6088875/CreateDocker.txt)

Step 4 failed. 
I have 10GB free on the drive where the agent is installed. Is that a problem.

**Comment by waldo1001** [comment]
10Gb is quite steep.  Not sure it is the problem, but I do suggest a major cleanup.

Few options:  Log on to the server, and do a "docker system prune" or "docker image prune".
Use the ALOPs step "ALOpsAgentMaintenance" to perform a cleanup (including artifacts).

**Comment by marcelvos1** [comment]
Hi Waldo,
I have already run the "ALOpsAgentMaintenance" step multiple times. After running this step the first build will work.
I will also try your other recommendations.

See the little part of the Create Docker Log. Why search step 4 for in the pl-PL? In step 2 you see that we use nl. I'am very confused now.

2021-03-04T22:51:31.7763408Z Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.1757
2021-03-04T22:51:31.7770813Z  ---> 1d6c29d61aaf
2021-03-04T22:51:31.7774173Z Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/16.3.14085.22653/nl filesOnly=False
2021-03-04T22:51:31.7835478Z  ---> Using cache
2021-03-04T22:51:31.7836950Z  ---> 47484295968d
2021-03-04T22:51:31.7838388Z Step 3/6 : COPY my /run/
2021-03-04T22:51:31.7859991Z  ---> Using cache
2021-03-04T22:51:31.7861094Z  ---> 674c817e4b3d
2021-03-04T22:51:31.7862627Z Step 4/6 : COPY NAVDVD /NAVDVD/
2021-03-04T22:51:46.8647277Z failed to copy files: failed to copy directory: open \\?\Volume{0d99e255-7a56-46ed-b2d1-1022f674e96a}\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV\160\RoleTailored Client\pl-PL\Microsoft.Dynamics.Framework.UI.WinForms.DataVisualization.resources.dll: The system cannot find the file specified.

**Comment by marcelvos1** [comment]
Hi Waldo,
The docker prune is running.
Here an other example. I used nl, but step 4 used es.

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.1757
 ---> 1d6c29d61aaf
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/17.4.21491.22792/nl filesOnly=False
 ---> Using cache
 ---> 65eded7339c8
Step 3/6 : COPY my /run/
 ---> Using cache
 ---> b4600dd10650
Step 4/6 : COPY NAVDVD /NAVDVD/
failed to copy files: failed to copy directory: chtimes \\?\Volume{0d99e255-7a56-46ed-b2d1-1022f674e96a}\NAVDVD\ServiceTier\program files\Microsoft Dynamics NAV\170\Service\es\Microsoft.ReportViewer.DataVisualization.resources.dll: The system cannot find the file specified.
Building image took 92 seconds
*** Created Image: myimage:sandbox-17.4.21491.22792-nl-10.0.17763.1757-ltsc2019

**Comment by waldo1001** [comment]
Very strange indeed .. .  Let's see if the docker system prune helps.

you can also try to run the "Flush-ContainerHelperCache"..

**Comment by marcelvos1** [comment]
Hi Waldo,

After monitoring the build server the drive has almost no space available during the build. So we will move the agent to an other drive. We continue testing after moving the agent. 
We will update you.

**Comment by waldo1001** [comment]
👍

Drive space is something that gets eaten by creating new images all the time.  Make sure the clean them very regularl

**Comment by marcelvos1** [comment]
Problem solved. The drive space was the problem, but the error was very confusing because the error was a missing language folder on step 4 in the create docker step.

What really happens I don't know. But Wednesday we run for the first time in this error. After running the maintenance task there where 10 artifacts deleted. The next day the error returned after 2 different builds with 2 different dockers. The question is now why gives the build after 2 different dockers the error and not after 10? Do I miss something?

I have one question:
Is it possible to changed the bcartifact.cache folder to an other drive? The c-drive is only for the operating system. see also the blog from Freddy: https://freddysblog.com/2020/10/10/bccontainerhelper-configuration/
I tested the recommendations from Freddy, but if I change the cache folder the build dropped the artifacts again on the c-drive. It will be nice if we can handle this with a parameter. 

Thanks for helping!

**Comment by waldo1001** [comment]
Makes sense - we'll look at it!

**Comment by marcelvos1** [comment]
Thanks Waldo.
