### ISSUE TITLE
Location of bc.artifactscache

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#336]
**Is your feature request related to a problem? Please describe.**
**Question 1**
Our buildserver has 2 disks. Build agents are installed on the C:\ drive and the bc.artifacts are downloaded to the default C:\bc.artifactscache folder. (cfr. https://www.waldo.be/2020/08/28/using-microsoft-dynamics-365-business-central-artifacts-to-get-to-the-source-code-of-the-default-apps/)

Is there any ALOps setting that allows to put the bc.artifactscache on another disk? We've another data disk (D:\) which has more space left (and might be re-used for question 2).

**(This is a nice to have)**

_**Question 2**  (Not linked to ALOps at all). Do you know when creating a Docker container locally, if you can use the bc.artifactscache from another location then your local C:\bc.artifactscache. Might be interesting if developers are spinning up a container locally, not having to download all artifacts once by developer, but using an internal share instead._

**Comment by AdminHodor** [comment]
Dear @fvet ,

**Question 1**
There is a config file in BcContainer helper where you can change the Cache folder, but from our experience not stable at all.
We recommend to use folder redirection instead, which is proven stable. (MKLINK)
https://github.com/HodorNV/ALOps/issues/201#issuecomment-696932932

If you want the ArtifactCache on the D-Drive, we suggest the following:
- Move the "c:\bc.artifactscache" folder to "d:\bc.artifactscache" (or any other path)
- Create Symbolic link 
```
mklink /d "c:\bc.artifactscache" "d:\bc.artifactscache"
```

**Question 2**
The same answer applies here, you can also use MKLINK for this.
```
mklink /d "c:\bc.artifactscache" "\\server.local.net\MyShare\ContainerArtifacts\"
```
But be aware this could have performance impact, the extract done by BcContainerHelper on the artifacts is far from performant
and will definitely not improve over a network connection. I would be very careful changing this.

>>Might be interesting if developers are spinning up a container locally, not having to download all artifacts once by developer, but using an internal share instead.
If you want the most performant solution, I would suggest not letting the developers build containers. Pre-Build them in a pipeline, upload the images to a local repository. Developers can then easily pull images from you repository without the need for rebuilding. 

Kind regards,
