### ISSUE TITLE
Question: DevOps Pipeline Library and MultiStage

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#338]
Question about : https://github.com/HodorNV/ALOps/edit/master/Examples/AppSource/AppSourceValidationTemplateMultiStage.yml

```YAML
stages:
- ${{ each country in parameters.countries }}:
```

What is the best practice to convert the string from the library to parameter of the type array?

![image](https://user-images.githubusercontent.com/44637996/110295968-0e14f600-7ff2-11eb-9023-8d880e5af407.png)

**Comment by fvet** [comment]
FYI, we currenly make the default part of the pipeline parameters:

`name: $(Build.BuildId)

resources:
  repositories:
    - repository: templates
      type: git
      name: Templates
      ref: 'refs/heads/master'

variables:
- group: PipelineVariables
- group: PipelineSecrets

parameters:
- name: validatecurrent
  displayName : 'current'
  type: boolean
  default: true
- name: validatenextminor
  displayName : 'nextMinor'
  type: boolean
  default: false
- name: validatenextmajor
  displayName : 'nexMajor'
  type: boolean
  default: false
- name: countries
  displayName : 'Countries'
  type: object
  default:
    - AT
    - BE
    - CZ
    - DK
    - FI
    - FR
    - DE
    - IS
    - NL
    - NO
    - SE
    - CH
    - UK
    - US
    - CA
    - AU
    # - IT
    # - ES

stages:
- template: appsourcevalidation.yml  
  parameters:
    countries: ${{ parameters.countries }}
    validatecurrent: ${{ parameters.validatecurrent }}
    validatenextminor: ${{ parameters.validatenextminor }}
    validatenextmajor: ${{ parameters.validatenextmajor }}`

Templates

`parameters:
  countries: ['be']
  validatecurrent: false
  validatenextminor: false
  validatenextmajor: false

stages:
- ${{ each country in parameters.countries }}:
  - stage: 'build_${{ country }}'
    displayName: '${{ country }} '
    # dependsOn: [] #run indepedently - ALOps bug to be fixed (containername is bcserver for all stages)
    jobs:
    - job: 'build_${{ country }}'
      displayName: 'Country ${{ country }}'
      pool: $(pool_build_parallel)
      workspace:
        clean: all
      steps:
      - checkout: none

      - template: download_artifacts\scripts.yml
      ...
      - template: download_artifacts\navitrans_365.yml          

      - task: PowerShell@2
        displayName: 'Remove Test Apps'
        inputs:
          filePath: $(System.DefaultWorkingDirectory)\Scripts\Development\Devops\DeleteTestApps.ps1
          arguments: -FolderToClean '$(System.DefaultWorkingDirectory)'

      - task: ALOpsAppValidation@1
        displayName: 'Run AppSource Validation'
        inputs:
          license_path: $(alops-bc-license)
          countries: ${{ country }}             
          affixes: 'NVT'                        
          artifact_path: $(System.DefaultWorkingDirectory) 
          artifact_filter: '*.app'                      
          memory: 12G                          
          validatecurrent: ${{ parameters.validatecurrent }}
          validatenextminor: ${{ parameters.validatenextminor }}
          validatenextmajor: ${{ parameters.validatenextmajor }}
          sastoken: $(bcinsider-sas-token)      
          skipverification: False               
          skipupgrade: False                    
          skipappsourcecop: False               
          skipconnectiontest: True             
          includewarnings: False                
          failonerror: True                     `

**Comment by waldo1001** [comment]
Honestly, I have no idea, and I think the approach from Frederic is the best one to do in devops/yaml.. .

Complex types in parameters in devops seems not possible.. .

I'll try to look at a powershell trick...

**Comment by MortenRa** [comment]
Maybe enable support to use the "supportedCountries": in the AppSourceCop.json if possible

**Comment by Arthurvdv** [comment]
Good idea @MortenRa.

I’m going to close this one and continue here: https://github.com/HodorNV/ALOps/issues/387
