### ISSUE TITLE
Change ApplicationInsightsKey as part of the Build Pipeline

### ISSUE THREAD

**Issue by Vibaek** [HodorNV/ALOps#344]
Hi,

From BC17 it´s a requerement that we apply an "applicationInsightsKey" in the app.json

We have created two Application Insights services on Azure with different keys, one for TEST and one for RELEASE
We want to use test key while developing and testing our ISV solution, but need to change the property to use the RELEASE key as part og the Build Pipeline.

Is this going to be a part of your "building blocks" or do we need to handle this our self with some PS ?

**Comment by kaspermoerch** [comment]
I think you could use the same method as described in [issue 272](https://github.com/HodorNV/ALOps/issues/272) and then controlling which app.json to use for compiling with a pipeline variable.

**Comment by Vibaek** [comment]
Thank you @kaspermoerch that could work.
I See the sugesstion has been marked as "part of an upsomming release" so let´s see whats comming up next time.

**Comment by waldo1001** [comment]
We will add the ability to overwrite the AppInsightsKey from the pipeline, as requested ;-).

But indeed, working with 2 app.jsons should also work. 👍

**Comment by AdminHodor** [comment]
Dear @kaspermoerch ,

Please check out our latest release v1.441 which included this feature.

Kind regards,
