### ISSUE TITLE
Question: how can I add extra artifacts to go in the same folder as the ALOps artifacts?

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#348]
Currently ALOps puts its artifacts _compilelog.txt_, _***_APP.app_ and _***_TEST.app_ in the artifacts folder **Dynamics 365**.

### Question
How can I add additional artifacts to the same folder?

**Comment by waldo1001** [comment]
Hi Luc,

that's just a default DevOps task.

Here you have an example:
![image](https://user-images.githubusercontent.com/12088142/112599298-0cc83380-8e10-11eb-8d03-464e5b409c9d.png)

**Comment by lvanvugt** [comment]
Or rather use [PublishPipelineArtifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact).

Nevertheless, this means I have to hard code the folder **Dynamics 365**. OK, hoped there was a bit more generic way, so, that I only needed to place my additional artifacts somewhere so they would be picked up in an ALOps step automatically.

**Comment by lvanvugt** [comment]
@waldo1001, unfortunately referencing **Dynamics 365** will not work anyway:

`##[error]Artifact Dynamics 365 already exists for build 3781.`

![image](https://user-images.githubusercontent.com/18466198/112606873-d642e680-8e18-11eb-94e7-cd8b201ba69d.png)

I actually knew this as we tried this before, being the (unconscious) background to my question.

**Comment by waldo1001** [comment]
Not sure - we'll look into this.

**Comment by jcoe-nvt** [comment]
@lvanvugt We work around this limitation by disabling the Publish Artifact by ALOps. After all steps are executed, we have an extra step to move apps/addins/... with powershell in a subfolder and publish it as desired artifact:

![image](https://user-images.githubusercontent.com/49404625/113315099-35b75f80-930d-11eb-8fbf-93432c9f12c6.png)

**Comment by waldo1001** [comment]
Makes sense! Thanks, @jcoe-nvt .

**Comment by lvanvugt** [comment]
Indeed. Great thinking, @jcoe-nvt!
