### ISSUE TITLE
Question: ALOpsRepositoryPublish

### ISSUE THREAD

**Issue by StijnBt** [HodorNV/ALOps#352]
Hello,

I'm a bit unclear on what the "ALOpsRepositoryPublish@1" step does.
For now I have found no missing steps in my pipeline and I can relate to most other steps mentioned.
But maybe I'm missing out on something concerning this one :)

Thanks.

**Comment by waldo1001** [comment]
Hi @StijnBt ,

That's more of an internal thing.  We created an app in BC with an API.  This step can publish to that endpoint with a given username/password.  Since we never released the app (which is kind of not in scope), this step is useless for customers.

**Comment by StijnBt** [comment]
Ok, thanx!
