### ISSUE TITLE
ALOps Compile failing on many issues

### ISSUE THREAD

**Issue by NAVRockClimber** [HodorNV/ALOps#355]
**Describe the bug**
AlOps Compile step fails if there is a large number of warnings from the AL compiler. 

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- task: ALOpsAppCompiler@1
    displayName: 'ALOps Compile App'
    inputs:
      usedocker: true
      targetproject:      ${{ parameters.AppJson }}
      nav_app_version:    $(AppVersion)
      vsix_download_path: '$(job.VSIX_PATH)'
      failed_on_warnings: $(job.Compile.FailOnWarning)
      al_analyzer: $(Job.CodeCops)
```

**the output**
I shortened the output to the in my opinion relevant part due to the log is about 30MB big. 
```
AA0008    650  app\src\PM\Pages\ManuStructureSubf.Page.al       ManuStructureSubf.Page.al     CodeCop     You must s...
AA0008    653  app\src\PM\Pages\ManuStructureSubf.Page.al       ManuStructureSubf.Page.al     CodeCop     You must s...
AA0008    667  app\src\PM\Pages\ManuStructureSubf.Page.al       ManuStructureSubf.Page.al     CodeCop     You must s...
AA0008    668  app\src\PM\Pages\ManuStructureSubf.Page.al       ManuStructureSubf.Page.al     CodeCop     You must s...
AA0005    675  app\src\PM\Pages\ManuStructureSubf.Page.al       ManuStructureSubf.Page.al     CodeCop     Only use B...
##[error]Exit code -1073741571 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\azp\agent\_work\_tasks\ALOpsAppCompiler_6ccb97e4-cd3b-4f5c-82d0-3b733949d45d\1.440.2371\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\azp\agent\_work\_tasks\ALOpsAppCompiler_6ccb97e4-cd3b-4f5c-82d0-3b733949d45d\1.440.2371\0a58f47c-8907-456b-8685-9aa45742dfd9.ps1'''))"'.
Async Command Start: Add Build Tag
Build '39455' has following tags now: AL.Compiler.ALLanguage, BC.Platform.18.0.22893.24077, BC.Version.18.0.23013.24264, bcartifacts/cosmo-bc-sandbox-18.0.23013.24264-de-mt
Async Command End: Add Build Tag
```

**Expected behavior**
Due to the compiling itself was successful to complete the step.

**Screenshots**
Compile step generates a extra amout of about 36k lines after the compiler output. 
ALOps Output:
![image](https://user-images.githubusercontent.com/37535503/114544496-fff26f00-9c5a-11eb-858c-bf6521c80395.png)
End of Compiler Output:
![image](https://user-images.githubusercontent.com/37535503/114544946-9b83df80-9c5b-11eb-89eb-35387b682608.png)

**Additional context**
We are currently in the process of switching to COSMO Self-Service. The Ruleset file was disabled for evaluating purposes. A vast of the warning come from rules like: AL0604 (implicit with), AA0470 (Placeholders should have a comment explaining their content), etc.

A switch for disabling the additional output would be nice.

**Comment by waldo1001** [comment]
Hi, can I ask - is this a solution with that many warnings anyway?  Would it be an option to disable the codecops for the compile (as nothing useful for that many warnings anyway)?  Do you happen to have debug-mode on?

**Comment by NAVRockClimber** [comment]
As I stated above this is the output without the ruleset file. Most of the warnings are about implicit with and missing tooltips, etc. 

IMHO it does not help to improve the quality if you simply turn off everything that throws a warning. Additionally we would be flighing blind in the AppSource.

But I get your point. Unfortunately for ISVs with big solutions the reducing of warnings quite a task and takes time.

What do you mean with debug mode? The pipeline's system diagnostics? These have not been enabled.

**Comment by waldo1001** [comment]
Indeed debug mode - but please don't enable it (it would only make things worse).

What you could do is to use a custom ruleset to remove (most of the) warnings.  I mean: if you have the with-warning, you'll probable tackle that at some point anyway .. no need to fill the devops output with all the separate warnings.

So, you could use a coderuleset-file to use in the pipeline with the "ruleset"-parameter.  That way, only the pipeline will take the ruleset, and hide all these warnings in the compile, while your VSCode won't just take that (if you don't put it in the settings.json).

makes sense?

**Comment by waldo1001** [comment]
Would you be able to attach (a zipped) full log?  So we can look ourselves?

**Comment by NAVRockClimber** [comment]
Ok, maybe I made myself not clear enough.  We have a ruleset but during pipeline development I had it switched off. With the ruleset I the compile step completes.

I will upload it to a file share and send you the link per mail.

**Comment by waldo1001** [comment]
Got it - we'll have a look!

**Comment by waldo1001** [comment]
We can't really se anything wrong - it's just A LOT.  Not sure if there's anything we can do about it - it smells like a DevOps limitation.

**Comment by NAVRockClimber** [comment]
This was what I suspected. 
Therefore my initial suggestion of a switch for disabling the output at the end of the Compile Task.

If we could disable this with a switch:
![image](https://user-images.githubusercontent.com/37535503/115731832-bf47d380-a387-11eb-9a89-3ce994258e52.png)

**Comment by waldo1001** [comment]
Thing is, agreeing to these kinds of parameters and switches will end up in an endless amount of parameters in the future .. .  I want to protect our customers from that.

So.  To mitigate the issue, please use the existing options:
- change codecops for this pipeline 
- use a custom ruleset for this pipeline
- solve the warnings  😉

**Comment by tfenster** [comment]
@waldo1001 I can see your point but if we get to the basics, then we have a scenario that fails, not because of the warnings but because of your additional output and we don't have a way to suppress that. We are working on solving the warnings and for that reason want to have a constant reminder of them, so your options 1 and 2 aren't ideal for us and 3 takes time, but we need to compile in the meantime. Can you see the argument there as well?

**Comment by waldo1001** [comment]
Honestly, I see it differently: the amount of output is because a "failing" app, which DevOps can't handle (but ALOps can).  But that's semantics - you just see it as ALOps output causing it .. I see it as the warnings causing it ;-).  The options to avoid the output are there...

How I handle such apps:
- I spend some time in compiling a ruleset, and tag all rules you want to solve as TODO (they end up in the todo tree or other todo tool in vscode) (this doesn't take long, I promise)
- Branch / solve 1 rule / commit
- repeat

It's a very neat and efficient way to get rid of the errors (because you focus on one particular warning at a time), VSCode speeds up tremendously (no warnings is A LOT faster), and there is still an overview of things to do, just in a different place.

Nevertheless - I'll put it on the table with my team, I can't promise the highest prio though.

**Comment by tfenster** [comment]
DevOps can handle it perfectly fine if we don't use ALOps... It's the additional output by ALOps in the end which breaks it. I agree, it's semantics, but I just want to clarify that compiling that repo without ALOps works and with ALOps fails

**Comment by waldo1001** [comment]
We'll foresee the parameter. #CustomersAreAlwaysRight ;-)

**Comment by tfenster** [comment]
Thanks a lot, very much appreciated!

**Comment by waldo1001** [comment]
The latest release has a new flag to disable output.  Could you test this?

Info about the release:
https://github.com/HodorNV/ALOps/issues/284#issuecomment-842096235

**Comment by NAVRockClimber** [comment]
It works smoothely. Thanks Waldo.
