### ISSUE TITLE
Deploy to a Azure Docker Container with ALOps App Publish

### ISSUE THREAD

**Issue by Kichnifou** [HodorNV/ALOps#36]
Hello,

I have an Azure Docker Container and I try to deploy a .app on it from DevOps with ALOps App Publish task

But there is just two parameters to fill
- Server Instance : (use web client url of my container ?)
- App filter : (use the path of my .app to deploy ?)

But I think it'snot enought informations. We don't have to give id and password connexion to the container ?

Maybe ALOps App Publish isn't the best way to do what I want to do ?

**Comment by waldo1001** [comment]
ALOps can do it - it's a matter of setting it up correctly.

I'm not exactly sure what you mean with "Azure Docker Container".  But I think there are two options to run:

If it's a VM on Azure with installed Docker (pretty much like Freddy's "aka.ms/getnav" templates), best thing to do is install a DevOps agent on that VM, and you can deploy with ALOps.  In that case, these are your settings:
![image](https://user-images.githubusercontent.com/12088142/65989414-eed37a00-e489-11e9-9aba-1b684a347840.png)
Indeed - you don't need much ;-)

If it's a service on Azure, and Docker is hosted on that (meaning - no possibility for you to add an agent) - the best thing to do is to install an agant on the docker container (can be scripted), and then let that agent use ALOps to deploy the app.  IN that case, you don't really use Docker (the agent is in the container):
![image](https://user-images.githubusercontent.com/12088142/65989448-06126780-e48a-11e9-94fa-7b9750be2f10.png)

Hope that helps.

**Comment by Kichnifou** [comment]
(I'm sorry by advance for my bad english)

Thank you for your time to write me this answer.
It will probably help me, but i'll try to be more specific.

I think it's the second proposition that you suggested me

I created an Azure Docker Image with this command in the Cloud Shell on Azure :
`az container create -g myNAVRG -n solliodev --image microsoft/dynamics-nav:2018 --os-type Windows --cpu 2 --memory 4 --ip-address public -e ACCEPT_EULA=Y ACCEPT_OUTDATED=Y USESSL=N ClickOnce=Y publicDnsName=solliodev.eastus.azurecontainer.io --dns-name-label solliodev --ports 80 1433 7046 7049 8080`

My ressource group name is "myNAVRG", the container name is "solliodev" and the image used is "microsoft/dynamics-nav:2018"

I already manage to deploy an app on this container manualy from VSCode. But now, I want to find a solution du publish this app thanks to a module on azure devops.
I already have a build that build me an artifact. I just have to take this artifact and publish it. Or I can take the .app from a path and publish from it.

So I create a Release and want to use a task to help me to deploy my .app
That's why I try to use ALOps App Publish

You said "the best thing to do is to install an agant on the docker container" but what is the best way to do that, and how ? I'm a novice so I don't know a lot of things about this, sorry

Otherwise, I thought to write a PowerShell script that permit me to deploy, and i just have to call it from a task on the Release. But it's the same problem, I don't know how to connect to my Azure Docker Container from powershell, maybe it's a specific script.

Sorry for this confuse post, I don't not feel confortable with this. But I try to find a way to reach my goal and I really hope you will help me

Thanks a lot for your attention

**Comment by waldo1001** [comment]
Few things: 
azure docker container is something we can't support.  Also, version 2018 might be the problem, because it had no way to publish through an API (afaik).. .

sorry ...
