### ISSUE TITLE
BC15 Test libaries are missing in Container

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [HodorNV/ALOps#37]
When using BC15 the Test Symbols are not imported in the Container

![image](https://user-images.githubusercontent.com/35697862/66031793-6cd46700-e504-11e9-9b29-a5722d454392.png)

There is also some Logical issue because the Option for importing Testtoolkit is on the "ALOps App Test", but you need the libaries to compile and publish first.

**Comment by waldo1001** [comment]
Microsoft is completely building the tests differently .. and they don't make it available yet 👍 https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/

> Please be aware…
Things are not cast in stone, things will change…

>Below is a list of things to be aware of when using the image:

>The Test Toolkit, the Test Libraries and the Tests are not included yet. We are currently refactoring tests into individual apps and will include those on the image as soon as we are ready.
The filename of the .vsix in the image is AL-<platformversionnumber>.vsix, uses the version number of the platform, which is NOT the version of the .vsix. In a future image, this will follow the version number of the .vsix.
 finsql.exe can still be found on the image. This doesn’t mean that C/AL still exists. finsql.exe is only used for database creation and will be removed when this functionality is moved to a different tool.
You will still find a folder called RoleTailored Client in the image. This doesn’t mean that the Windows Client still is available. The folder contains some tools, that needs to be moved before removing the folder.

**Comment by PatrickGrabensteiner** [comment]
When I use NAVContainerHelper to Import the testtoolkit i get the libaries is there a way to get the Name of the docker container from ALOps so i can use NAVContainerHelper to Import Testtoolkit?

**Comment by waldo1001** [comment]
I'm afraid it's not that simple.

What we will do is:
foresee a way for you to execute powershell in the container that was created by ALOps (an "Alops PowerShell step").

And - we will have the "Test"-step fixed pretty soon now (in test-phase...)

**Comment by waldo1001** [comment]
We have a fix in test .. should be released soon.

**Comment by waldo1001** [comment]
Hi @PatrickGrabensteiner ,

tests are approved and released.  I'm going to close the issue.  If you have still problems, please let us know!

**Comment by VejdelekJ-SOL** [comment]
Hi Waldo,
what should I use in "testpage" parameter in AlOpsAppTest for BC15?
When using 130409 I get:
Run-Test-Exception: Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefof

Thanks

**Comment by waldo1001** [comment]
This is how we test on version 15:

```yaml
- task: ALOpsAppTest@1
  displayName: 'ALOPS Run TestSuite'
  inputs:
    usedocker: true
    show_available_tests: false
    import_testtoolkit: false
    testpage: '130455'
    installaltesttool: false
    failed_test_action: "Warning"
  continueOnError: true   
```

**Comment by PatrickGrabensteiner** [comment]
Now i get an error when i want to run Tests
![image](https://user-images.githubusercontent.com/35697862/67081840-4109e000-f198-11e9-8fb9-002fe25cb820.png)
