### ISSUE TITLE
ALOps Sign (Test) App: Processing data for a remote command failed

### ISSUE THREAD

**Issue by mrabus** [HodorNV/ALOps#374]
**Describe the bug**
I create a BC14, CU18 pipeline, FOB file is imported, a dependecy AL app is imported as well. Then the app itself is compilied. The compliation of the test app fails with the following error: 
##[error]Processing data for a remote command failed with the following error message: Error with error code 14 occurred while calling method WSManPluginReceiveResult. For more information, see the about_Remote_Troubleshooting Help topic.

**the used yaml**
![image](https://user-images.githubusercontent.com/2485163/119849085-9d081f00-bf0c-11eb-84fe-b021f905a1be.png)

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
![image](https://user-images.githubusercontent.com/2485163/119848477-223f0400-bf0c-11eb-816a-e272a18ad98e.png)

**Expected behavior**
Compilation of the test app without error

**Comment by waldo1001** [comment]
When you look in the log, you see that the last successful message is "Download Symbols"   

It seems to fail on loading scripts.  Which is weird - because this is merely loading functions to be able to execute them later.

Could it be infrastructional (as it shows WSMan - which could refer to remote powershell)?

**Comment by waldo1001** [comment]
Hi @mrabus , can you answer the above?

**Comment by waldo1001** [comment]
@mrabus ,

could you look at the above?  Is this still an issue?

**Comment by waldo1001** [comment]
I'll close the issue - you can re-open it if you have feedback.
