### ISSUE TITLE
Will publishxlif work with ALOpsAppCompiler@1

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#378]
Will publishxlif: true work on ALOpsAppCompiler@1

**Comment by waldo1001** [comment]
I'm afraid not.  I'll try to put it on the list ... 
Is it prio?

**Comment by MortenRa** [comment]
It is not a prio, but trying to optimize our pipelines and it might just be my pipelines need to be changed to use ALOpsAppCompiler@2  

Do you have an example where you use ALOpsAppCompiler@2 where you check for previous and also uses dependency apps from other pipelines.

**Comment by waldo1001** [comment]
Dependency apps you simply download from pipelines.  Same as always.
check for previous is just a matter to add it in your repo (or also download it).  It's defined in the AppSourceCop.json on the repo, and the CompilerV2 will try to find it...

Let me know if you need help on that if this doesn't seem to work (should be very easy with CompilerV2).

**Comment by MortenRa** [comment]
I´ll sort it out thanks

**Comment by AdminHodor** [comment]
Dear @MortenRa ,

Please check our latest release v1.443.2509 which addresses this issue.

Kind regards
