### ISSUE TITLE
Different version of dll needed for compile and publish step

### ISSUE THREAD

**Issue by acjdekorte** [HodorNV/ALOps#380]
**Describe the bug**
During the last week, we have been working on getting a third-party assembly into the buildpipeline. The problem was that the assembly was not recognized by the compiler. The assembly was part of the .netpackages folder of repo and was copied to the docker container as well as to the Add-Ins folder (C:\Program Files\Microsoft Dyn....\170\Add-Ins\.netpackages). 
In the end, we found out that the compile step needs 32-bit version of the dlls, because then it is possible to build. But with the 32-bits dll's you are not able to publish the newly build app to the container. So in the end, we added two versions of the dlls to the repo (each in its own folder) and we are able to successfull run our buildpipeline.

**Question**
Could you confirm that our story around 32 and 64 bits dlls makes sense? 

**Expected Behaviour**
I am afraid that there will not much ALOps can change to this issue, but may be our story can help others to solve a simular problem.

**Comment by waldo1001** [comment]
Hi,

We don't have too much experience with dlls, to be honest.  And this is the first time I read this.. .

Thanks for the heads up .. may be someone else will give their thoughts...

**Comment by waldo1001** [comment]
Hi .. could it be that the dll is not built for "Any CPU", but separately per platform target?
![image](https://user-images.githubusercontent.com/12088142/121020220-7665a600-c7a0-11eb-819e-88443626baf0.png)

If they are built separately, you'll need to provide both of them ..

**Comment by acjdekorte** [comment]
Hi...

Since this dll are provided by a third party, I have no clue. But it sounds to me as logical explanation.
