### ISSUE TITLE
ALOpsAppCompiler v2 with updatebuildnumber param

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#384]
**Is your feature request related to a problem? Please describe.**
Expand the ALOpsAppCompiler v2 with the parameter 'updatebuildnumber' from the v1 compiler.

**Comment by AdminHodor** [comment]
Dear @Arthurvdv ,

Please check our latest release v1.144.2565, it contains a fix for the Update-Build-Number.

Kind regards,

**Comment by Arthurvdv** [comment]
Thanks for adding this param, works as expected!
