### ISSUE TITLE
[Ouestion / Feature Request] set artifact name on AlOpsCompile

### ISSUE THREAD

**Issue by NAVRockClimber** [HodorNV/ALOps#385]
Not sure if this exists at least it did not find anything in the documentation.
Is there a parameter for setting the name of the artifact thats uploaded to the pipeline after compiling?

Per default the AlOpsCompile publishes the artifact under the name "Dynamics 365". We would like to be able to set a name like "app","test".

**Comment by waldo1001** [comment]
We'll see if we can do this ..

**Comment by NAVRockClimber** [comment]
This would be really nice. :) 
Could you in the case it is possible also add it to the step ALOpsAppRuntimePackage. I just had this morning the same problem with this step.

**Comment by waldo1001** [comment]
If we do it, it will be a global variable you can set an the beginning of your pipeline, and it will be used on all steps.  You can even change it between your steps .. although I wouldn't recommend it..

**Comment by AdminHodor** [comment]
Dear @NAVRockClimber ,

Please check our latest release v1.144.2565, it contains a fix for this. The ArtifactFolder name can be set with the environment variable [Alops_ArtifactPublishFolder].

Kind regards,

**Comment by NAVRockClimber** [comment]
Sorry, for the late answer. But I have been dragged into other projects.

Is there a reason why you did not make it a parameter? I tried this; app and test app are compiled in the same job.
I wanted the app in folder called app and the test app in a folder called test. Both folders appear but both folders contains both apps.

Am I doing something wrong?

Excerpt from my template:
```
- task: ALOpsAppCompiler@1
    displayName: 'ALOps Compile App'
    inputs:
      usedocker: true
      targetproject:      $(Job.AppManifestFile)
      nav_app_version:    $(Job.AppVersion)
      vsix_download_path: '$(job.VSIX_PATH)'
      failed_on_warnings: $(job.Compile.FailOnWarning)
      al_analyzer: $(Job.CodeCops)
      ruleset: $(Job.RulesetFile)
      output_alc_logs: '$(job.Compile.EnableCompilerOutput)'
    env:
        Alops_ArtifactPublishFolder: "app"

...


- task: ALOpsAppCompiler@1
      displayName: 'ALOps Compile Test-App'
      inputs:
        usedocker: true
        targetproject:      $(Job.TestAppManifestFile)
        nav_app_version:    $(Job.TestAppVersion)
        vsix_download_path: '$(job.VSIX_PATH)'
        failed_on_warnings: false
        # publish_artifact: $(Job.PublishArtifactOnCompile)
      env:
        Alops_ArtifactPublishFolder: "test"
```

Result:

![image](https://user-images.githubusercontent.com/37535503/126180323-c8414385-ebc8-48c7-84fc-bdb0cb548827.png)

**Comment by NAVRockClimber** [comment]
Hi, is there any update on this?

**Comment by NAVRockClimber** [comment]
Hi, any updates on this one? I saw there's a new release.

**Comment by waldo1001** [comment]
We investigated it - but thing is, from PowerShell, there isn't much we can do (it's basically just a vsts-command we need to execute), and this indeed seems to be the way how that command is reacting on VSCode level.

What I would do is to NOT use the ALOps commands to upload artifacts, but use the DevOps steps to do that.  That seems to work.

Ps: we are not able to call DevOps steps, we are dependent from the vsts-commands in powershell.  So in other words - I don't think we can fix this :(.
