### ISSUE TITLE
Question: how can I find out what repos have been registered by ALOps?

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#389]
ALOps registers how many (and what) repos I am using for my pipelines. How can I find out which have been registered?

And as a next question: if one of those repos is deprecated, how can this be removed from the list ALOps has registered?

**Comment by lvanvugt** [comment]
@AdminHodor, can I expect a reply fairly soon?

**Comment by waldo1001** [comment]
Luc, you can expect an email today - even without the reminder ;-)

**Comment by lvanvugt** [comment]
Appreciated. Tip: if read just write on it that it is taken care of.

**Comment by waldo1001** [comment]
Handled..
