### ISSUE TITLE
Add info to ALOps License check in logs about number of repos registered 

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#397]
**Issue**
In #389 I asked how to find out how many repos have already been used/registered for our ALOps license. I did get a nice response on that for the situation at that time. However, using a _RepositoryPer5_ license I would like to now at every moment how many repos are registered. Of course your can probably help me again like you did before, but will probably not something you want to repeat over and over again.

**Solution**
Every ALOps steps checks the license and displays in the log of that step the result of the check, like:

```
*** ALOps License:
  * Licensed To: xxx BV (3x RepositoryPer5 License)
```
Add info on how many repos are registered by ALOps at moment the pipeline is running.

**Comment by waldo1001** [comment]
That would mean we'd have to pull back more info than we do now, which could be a possible performance impact.  We'll see what we can do..

**Comment by lvanvugt** [comment]
Would it be an option to have a separate step for that so that it is optional and potentially only happening one in a pipeline?

**Comment by waldo1001** [comment]
That might be a good idea - similar to the ALOpsInfo .. may be as part of it as well.  We'll take it into consideration!

**Comment by waldo1001** [comment]
Looking into this, it's not going to be easy, because there is no communication layer to get data back from the backend (from the API in the middle layer).  We'll keep in on the agenda, but it's not going to be a short term thing..

**Comment by lvanvugt** [comment]
So, you're going to be hooked on doing this on request manually. :-)

**Comment by waldo1001** [comment]
Well .. let's see how that goes first ;-).

**Comment by waldo1001** [comment]
We'll close this for now.
