### ISSUE TITLE
[Bug / blocking] Overrule the /parallel compiler option

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#410]
**Describe the bug**

We've various reports with a same dataset, all pointing to the same report layout. (will not question the design ...)

```
report 2060091 "RLG CMR Layout WMS Orders"
{

    DefaultLayout = RDLC;
    RDLCLayout = './Layouts/CMRLayoutNL.rdlc';

```

```
report 2060090 "RLG CMR Layout Trip"
{

    DefaultLayout = RDLC;
    RDLCLayout = './Layouts/CMRLayoutNL.rdlc';
```

To avoid issues while packaging the app in VS Code, we're forced to disable the parallel compilation (.vscode\settings.json)

```
"al.compilationOptions": {
        "parallel": false
    },

```

However, when compiling the app on DevOps, we get error below

`##[error]\app\src\report\CMRLayoutShipment.Report.al(4,18): error AL0445: The file './Layouts/CMRLayoutNL.rdlc' is opened in another application. Close the application to be able to compile.
`

Probably due to the /parallel option.

`& C:\bcartifacts.cache\sandbox\18.1.24822.28654\VSIX\extension\bin\alc.exe /packagecachepath:"C:\DockerInstallation\Agent\_work\255\s\app\.ALOPSCache" /project:"C:\DockerInstallation\Agent\_work\255\s\app" /out:"C:\DockerInstallation\Agent\_work\255\a\Rainbow Logistics IT_Rainbow Logistics General_18.0.0.15789_sandbox_18.1_nl.app" /fullpaths /analyzer:"C:\bcartifacts.cache\sandbox\18.1.24822.28654\VSIX\extension\bin\Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll","C:\bcartifacts.cache\sandbox\18.1.24822.28654\VSIX\extension\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll" /ruleset:"C:\DockerInstallation\Agent\_work\255\s\app\.vscode\nvt.ruleset.json" /parallel+ /maxDegreeOfParallelism:2 /assemblyprobingpaths:"C:\Windows\assembly","C:\Windows\Microsoft.NET\assembly","C:\bcartifacts.cache\sandbox\18.1.24822.28654\platform\Test Assemblies\Mock Assemblies","C:\bcartifacts.cache\sandbox\18.1.24822.28654\platform\LegacyDlls\program files\Microsoft Dynamics NAV\180\RoleTailored Client","C:\bcartifacts.cache\sandbox\18.1.24822.28654\platform\ServiceTier\program files\Microsoft Dynamics NAV\180\Service"`

**Expected behavior**
We'd like to be able to disable the /parallel option in the ALOpsAppCompiler@2 step via a new task parameter

**Comment by waldo1001** [comment]
We'll make a switch for it.

**Comment by waldo1001** [comment]
We found a solution - will make it into the next release.

**Comment by AdminHodor** [comment]
Dear @fvet ,

Please tryout our latest release v1.445.

Kind regards
