### ISSUE TITLE
[Feature Request] New ALOps step "Generate API documentation"

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#411]
**Is your feature request related to a problem? Please describe.**
Prior to this blog post (https://www.waldo.be/2021/06/09/documenting-your-business-central-custom-apis-with-openapi-swagger/) we already had similar tools in place to - **manually** - generate API / swagger documentation from within VS code when working on our custom APIs.

However, since we all face the same challenges, I was wondering if there are any plans to wrap the scripts from https://github.com/waldo1001/BusinessCentralOpenAPIToolkit via a new ALOps step to 'Create BC API Documentation'. This way, we could create up-to-date API documentation as part of our build process (not when deploying the apps, which seems to late in our opinion and does not work for SaaS)

Just wanted to double-check if you're open to this idea / have any short-term plans on the roadmap, before we internally start adding some PS scripts / build steps to our pipelines.

**Describe the solution you'd like**
- Add a new 'AlOpsCreateBCApiDocumentation' step with parameter
  - API endpoint: <publisher/group/version>
  - Output : yaml / json
  - PublishArtifacts : boolean
- _Provide sample script on how to integrate this in a build pipeline_

Idea would be to
- Create a PR with updated API al files
- Run the build pipeline
- Spin up a docker container
- Compile the app
- Publish the (dependend) extension(s) to the container
_(All pretty standard ALOps stuff)_
- (NEW) AlOpsCreateBCApiDocumentation
  - Download the edmx file from the container (path <publisher/group/version> as parameter)
  - Create the yaml / json file from the edmx file  (parameter)
_- (Custom PS script) Cleanup the yaml/json file from invalid attributes / update some attributes_
- Store the (modified) yaml / json files as build output / artifacts under a separare container (the files will not end up as source files within your repo)

These build artifacts could be used later on in the release process, to include as part of the 'installation media', deploy to Azure / website, ....

**Comment by waldo1001** [comment]
Nice idea - I didn't look at it this way, but it totally makes sense!

Let's see what we can do!

**Comment by waldo1001** [comment]
We're pretty far with this - hopefully it can be published soon .. (I know - "soon" is relative these days :( ).

**Comment by waldo1001** [comment]
This one is done (as a first release) and will be available in the next release in a new ALOps-task: ALOpsOpenAPI.
