### ISSUE TITLE
Question regarding app versioning

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#413]
Hey Guys, 
I have a question not directly related to the ALOPS. Perhaps you can help me. 

When we create an extension, we always leave default version (1.0.0.0) in app.json. 
App version is generated during the build pipeline (using ALOPS), and app is published to our test environment. 

Sometime developers want to refresh their local dev environments. They do it by taking backup/restore of our test environment. In this freshly restored  database your extension version is always higher than 1.0.0.0, and it's not longer possible to publish extension with version 1.0.0.0.

As a workaround they increase the version to 2.0.0.0 and proceed with publishing. But it poses the risk (someones commits 2.0.0.0 to the repo by mistake).
Another way, would be to completely uninstall extension, but then u loose the data. 

I was wondering if you have experienced the same case. Perhaps there's a more elegant way of dealing with it. 

Best Regards, 
Gintautas

**Comment by CarloAxians** [comment]
Hi Gintautas,

We had the same problem. We solved this be setting the version in the app.json to something like 1.0.99999999.0
In our DevOps pipelines we have set the appversiontemplate keyword to '?.?.[yyyyMMdd].*'

So after compiling our version is something like 1.0.20210820.1234 and this version is published to our test environment.

Hope this helps,

Kind Regards,
Carlo

**Comment by waldo1001** [comment]
We set in app.json the following major (like 2.0.0.0) so you'd always be able to publish a new version of the app from VSCode.
We always set the FULL version by ALOps, so version of the app is completely managed by ALOps.

If you'd accidentally commit the app.json, it's still not really a problem this way.. .

Hope that makes sense?

**Comment by gintuoklis** [comment]
hey @waldo1001, 
Sorry for reopening this topic, but i have another questions regarding versioning. 
How do you deal with versions in multiRoot scenarions?
Simple example. I have repo with two apps:
app
test

How would you recommend to version those apps, so it would be possible to work locally, and ALOPS would be able to compile extensions?

We tried likes this, but cannot get it working

|app name| version in app.json| version in AOPS yml|dependecies
|---|---|---|---|
|app|2.0.0.0|1.0.[yyyyWW].*'|none|
|test|2.0.0.0|1.0.[yyyyWW].*'|app v2.0.0.0|

With this setup compilation of test app fails to compile, since it cannot find need dependency. it's looking for v.2.0.0.0, while it has something like 1.0.202151.71309 installed.

**Comment by gintuoklis** [comment]
FYI, 
I also tried the following scenario. Just using version 1.0.0.0 eveythere. But even then, compillation of test extension fails, since it cannot find dependant app of version 1.0.0.0

app name | version in app.json | version in AOPS yml | dependecies
-- | -- | -- | --
app | 1.0.0.0 | 1.0.[yyyyWW].*' | none
test | 1.0.0.0 | 1.0.[yyyyWW].*' | app v1.0.0.0

**Comment by gintuoklis** [comment]
Ignore my questions :) All works fine. Managed to mix app name with published on app.json.
