### ISSUE TITLE
Control that Unit Test is not executed in 'My Company'

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#414]
**Question**
With reference to https://github.com/HodorNV/ALOps/issues/203 it is possible to specify which Company to run the unit test in, thank you for that. We are currently planning to release our app for 16 different localizations and this causes an issue if our Unit Test are executed in the 'My Company' company where a lot of basic parameter setup is missing.

Now to the question, which I cannot read in the documentation. Does the Company parameter in the step "ALOps App Test' support a filter as a parameter, like <> 'My Company'?

![image](https://user-images.githubusercontent.com/54669593/130229976-e518696f-c31a-4ec6-928e-4d7f7901a7c6.png)

**Comment by waldo1001** [comment]
No, it doesn't support it.  We use this company in the URL, so we couldn't even do this.

What you could do is to remove the company "My Company" in the "AlopsDockerExec" step?

**Comment by kasperdj** [comment]
ok, thx for the input.
