### ISSUE TITLE
Question: Does the Test build step support code coverage?

### ISSUE THREAD

**Issue by Athystrup** [HodorNV/ALOps#416]
Hi 

I saw this blog post by James Pearson  [link](https://jpearson.blog/2021/02/07/measuring-code-coverage-in-business-central-with-al-test-runner/) regarding his VS Code extension, which mentioned the possibility of getting code coverage in the TestResults.xml file. 

I have tried to look through your documentation, but I can't seem to find any way to activate this feature. 

Is this something that is already supported by ALOps in the Test step? Or is it something you think would be relevant to implement in the future? 

Best regards,
Andreas

**Comment by waldo1001** [comment]
We weren't really planning for that, as it's running a custom testrunner for that (afaik).. .  Let me talk with the dev team..

**Comment by waldo1001** [comment]
I heard MS is going to come with a Code Coverage solution in the next (or next+1) version.  I think it makes sense to wait for that.. .

Until then, I'll close this issue.. .  Thanks for the feedback!
