### ISSUE TITLE
How to handle dependent ISV apps

### ISSUE THREAD

**Issue by StevenHit** [HodorNV/ALOps#425]
Hi,

We have a ADN_Core app wich is dependent on some ISV apps, like Continia Document Output. We added those .app files in the .app subfolder in the repository:

![image](https://user-images.githubusercontent.com/34163966/133450623-02c99073-9ef4-4c9e-b0d9-d2af61393df0.png)

So each build of ADN_Core has these artifacts as result:

![image](https://user-images.githubusercontent.com/34163966/133450908-588eb8b4-ecbc-48e7-8553-9b6c21336b9e.png)

Now we created an ADN_BE app which is dependent on ADN_Core. The ADN_BE app is not dependent on any ISV apps.

We want to create a build pipeline for the ADN_BE app so in the yml we download the artifacts of the last ADN_Core build:

![image](https://user-images.githubusercontent.com/34163966/133451780-c056a42a-a768-423a-b1b2-0f0c94af6cb6.png)

But apparently this download does not include the ISV apps, which are also present as artifacts. It only downloads the ADN_Core app. Do we still need to add the ISV apps in an .app folder for the ADN_BE app because ADN_Core needs it? Or is there another way to do this?

For your good understanding, this is an overview of app dependencies:

![image](https://user-images.githubusercontent.com/34163966/133453407-bfffb905-6f7d-48bc-8955-d1e57ee66955.png)

Thanks for any help

**Comment by waldo1001** [comment]
That's weird.  Are you sure?  Did you check the artifacts-workingfolder on the buid agent?

**Comment by StevenHit** [comment]
That's what we understand ;-).

This is what's in the log:

![image](https://user-images.githubusercontent.com/34163966/133456083-89d87a02-a577-4555-9e14-22d7de3aa668.png)

**Comment by waldo1001** [comment]
So, it downloads artifacts from build 382.
Chan you check that pipelinerun and look at the actual artifacts?

**Comment by StevenHit** [comment]
These are the artifacts:

![image](https://user-images.githubusercontent.com/34163966/133457410-e5f222f0-679a-4d16-a7f2-819847bbaa25.png)

**Comment by waldo1001** [comment]
How did you upload those artifacts.

**Comment by StevenHit** [comment]
This is the command in the yml file from ADN_Core:

![image](https://user-images.githubusercontent.com/34163966/133459527-2cf13122-b299-43e7-904f-193685ad40b2.png)

**Comment by waldo1001** [comment]
I have a hunch 

This might be the wrong DevOps step you're using.  You publishing with the "publishpipelineartifact" step, but you're downloading with the "downloadbuildartifacts" (which is not pipelineartifact).

try this:

´´´yaml
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs: 
    PathtoPublish: '.apps'
    ArtifactName: 'ISVApps'
    publishLocation: 'Container'
´´´

to create your artifacts.

**Comment by StevenHit** [comment]
I adjusted as you proposed and it works like a charm now ;-).

Thanks for your fast help. Much appreciated.
