### ISSUE TITLE
ALOps Scripts blocked by antivirus

### ISSUE THREAD

**Issue by dNsl9r** [HodorNV/ALOps#427]
**Describe the bug**
Since today morning our build machine blocks the ALOps Script Parts:

> ##[error]At line:1 char:1
> +  ([RunTiME.INtErOPsERvICES.maRShAl]::([RUntImE.InTerOPSeRviCES.mARshA ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> This script contains malicious content and has been blocked by your antivirus software.

The machine did not get any Updates or anything, so I'm really wondering how this can happen?

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
...
- stage: BuildDockerCIImages
  condition: succeeded('StartBuildVM')
  pool: Default
  jobs:
  - job: CleanBuildMachine
    steps:
    - checkout: none
    - task: ALOpsAgentMaintenance@1
      inputs:
        removeoldtasks: true
        removeunusedcontainers: true
        removebcartifacts: true
        daysunused: '5'
...
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
2021-09-20T14:08:31.1246812Z ##[section]Starting: ALOpsAgentMaintenance
2021-09-20T14:08:31.1889088Z ==============================================================================
2021-09-20T14:08:31.1889679Z Task         : ALOps Agent Maintenance
2021-09-20T14:08:31.1890090Z Description  : Cleanup and maintain DevOps a Agent for Business Central
2021-09-20T14:08:31.1890324Z Version      : 1.445.2623
2021-09-20T14:08:31.1890622Z Author       : Hodor
2021-09-20T14:08:31.1891077Z Help         : Cleanup and maintain DevOps a Agent for Business Central.
2021-09-20T14:08:31.1891372Z ==============================================================================
2021-09-20T14:08:33.8137137Z ##[error]At line:1 char:1
+  ([RunTiME.INtErOPsERvICES.maRShAl]::([RUntImE.InTerOPSeRviCES.mARshA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
2021-09-20T14:08:33.8391786Z ##[section]Finishing: ALOpsAgentMaintenance
```

**Comment by waldo1001** [comment]
I do assume your defender got an update - else it would really be weird.  I'll check on our end, but I'm quite sure that we did not do any intermediate release.. .

Did you use the global var `alops_disable_amsi` (to true) in an attempt to disable virus scanner during pipeline?

What you also could try is to add a powershell step in the beginning of the script with:
`Set-MpPreference -DisableScriptScanning $true`

and one at the end of the script:
`Set-MpPreference -DisableScriptScanning $false`

Could you try that?

**Comment by dNsl9r** [comment]
Never heard about this variable.
Tried it but the result is not better:

> 2021-09-20T17:56:58.7836694Z ##[section]Starting: ALOpsAgentMaintenance
> 2021-09-20T17:56:58.8497511Z ==============================================================================
> 2021-09-20T17:56:58.8498178Z Task         : ALOps Agent Maintenance
> 2021-09-20T17:56:58.8498605Z Description  : Cleanup and maintain DevOps a Agent for Business Central
> 2021-09-20T17:56:58.8498854Z Version      : 1.445.2623
> 2021-09-20T17:56:58.8499175Z Author       : Hodor
> 2021-09-20T17:56:58.8499687Z Help         : Cleanup and maintain DevOps a Agent for Business Central.
> 2021-09-20T17:56:58.8499986Z ==============================================================================
> 2021-09-20T17:57:00.9559827Z *** Configure AMSI for session: disable (in memory)
> 2021-09-20T17:57:01.9514556Z ##[error]At line:1 char:1
> +  ([RunTiME.INtErOPsERvICES.maRShAl]::([RUntImE.InTerOPSeRviCES.mARshA ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> This script contains malicious content and has been blocked by your antivirus software.
> 2021-09-20T17:57:01.9827679Z ##[section]Finishing: ALOpsAgentMaintenance



With the PowereShell added still the same 😭

**Comment by dNsl9r** [comment]
Also tried to exclude the "Agent" folder from Defender Search - still not working..

**Comment by waldo1001** [comment]
> Never heard about this variable.
Then you might not know about these either: https://github.com/HodorNV/ALOps/blob/master/Documentation/Globals.md

There hasn't been any change on our side since September 8th, so I can only think of one cause, which is a change on the server side :(.  Did someone install extra software?

**Comment by dNsl9r** [comment]
Nope - Server did not get any updates since the last issue we had: #357 :(

**Comment by waldo1001** [comment]
And no new software either?  Like virus scanners or something? ;-)

**Comment by dNsl9r** [comment]
Seems that Defender installs new anti vir definitions now and then:
![image](https://user-images.githubusercontent.com/5330063/134124559-d14366d7-ce4a-43f2-be38-09890cec346a.png)

But I do not know how do uninstall these..

**Comment by dNsl9r** [comment]
Found out, that the "disabling" of the Defender is detected as attack by Azure Defender and will be blocked directly. Excalated the case to our Azure Admins as I do not have permissions to change anything in there. Will come back to you later if there are any news..

**Comment by waldo1001** [comment]
Thanks.
One additional question: did you try to exclude the entire vsts-folder?

**Comment by dNsl9r** [comment]
Yep. But the Azure Defender seems to be really hard and overrules everything I do as (local) admin

**Comment by dNsl9r** [comment]
Okay, Problem solved by adding an exeption in Azure Security Center for the build machine. Obviously the error was caused by a newish policy Microsoft rolled out for PowerShell Scripts.
When are you going on full .NET?
