### ISSUE TITLE
Dynamically adding PreprocessorSymbols to app.json in pipeline

### ISSUE THREAD

**Issue by acjdekorte** [HodorNV/ALOps#436]
**Background**
We have several pipelines using the same source code for different versions. Since the introduction of BC20, these pipelines for different localization are failing due to the removal of some pages and factbox by Microsoft. In order to cope with these differences between BC17/BC19 and BC20, I have made use of preprocessorSymbols. But since I use the same sourcecode, I only have one app.json available.

**Describe the solution you'd like**
I would like to be able to set the preprocessorSymbols in the buildpipeline in the same fashion as I am able to set the version number (or version number format) in the ALOpsAppCompiler step. 

**Describe alternatives you've considered**
I could of course write a powershell script that modifies the app.json in the buildpipeline, but I prefer ALOps to handle this.

**Comment by fvet** [comment]
@acjdekorte If ALOps would set the version and the preprocessorSymbols, then what about other app.json properties that could differ?

- How do you handle the different platform (e.g. `"platform":  "19.0.0.0"`) per version?
- Do you have dependencies that might have a different version per BC version?

**Comment by acjdekorte** [comment]
Yes, it makes sense. A different app.json is not that easy in our pipelines, since we build against the development branch for all versions at the moment. But I am sure that we can manage that either by introducing new parameters to select the correct app.json or as input to a powershell script.
