### ISSUE TITLE
ALOps Extension API with App certificate

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#438]
**Is your feature request related to a problem? Please describe.**
Our internal Cloud and Cyber Security department is strongly advising us to use Certificates in stead of Client secrets for authorization on App Registrations. For now they will allow Client secrets, but threats this as a potential security issue and will phase out this in the (near) future as a company policy.

**Describe the solution you'd like**
Storing the certificate in a Azure Key Vault and referencing to it from ALOps Extension API-step.
Maybe something like a extra input parameter 'azure_app_certificate_path' to point to the certificate and leave the 'azure_app_client_secret' empty? Not sure on al the details, this would be the first setup I need to configure using certificates.

**Describe alternatives you've considered**
Convincing our internal Cloud and Cyber Security department to keep supporting Client secrets :-)

**Additional context**
![image](https://user-images.githubusercontent.com/44637996/137314793-577f9490-d9b9-4f23-b6ca-d7464bdfa3df.png)

**Comment by waldo1001** [comment]
Thanks for this - we're going to have to look into this for sure indeed!

**Comment by AdminHodor** [comment]
Dear @Arthurvdv ,

Please check our latest release v1.451
We included "Certificate Authentication" in the tasks "ALOpsExtensionAPI" and "ALOpsOpenAPI".

An example on how to use it can be found here:
https://github.com/HodorNV/ALOps/blob/master/Examples/26_PublishSaaS%20-%20S2S%20-%20AppClientCertificate.yml

We recommend using the "Azure Key Vault" way:
  - Upload the certificate in an Azure Key Vault
  - Link the Key Vault to a "Variable Group" in the DevOps Library
  - Link the Variable-Group to your pipeline
  - Use the $(Certificate-Variable-Name) in the [azure_app_client_certificate] parameter on the step
  - Remove the [azure_app_client_secret] from the step where you use certificates

In one of the upcoming releases we'll provide Certificate-Authentication for the "ALOpsAppTest" task.

Kind regards,

**Comment by waldo1001** [comment]
@Arthurvdv , were you able to test this out?

**Comment by Arthurvdv** [comment]
To be honest it still on my backlog to implement. This should be probably in the next month or two.

I'm going to close this for now and report back in case I run into problems.
