### ISSUE TITLE
ALOpsDockerStart - Cannot find an overload for "GetObjectsForNativeVariants"

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#439]
**Describe the bug**
Encountered the issues similar to #138, but the funny thing is that there was no Windows Update installed, only some waiting. Installed them and build failed again. Removed the updates and build failed again.

Reading #138, but also #40, is the only option I have reinstalling the agent?

**Comment by lvanvugt** [comment]
Installed these Windows updates (again) and pipelines fails again. Also **ALOps Agent Maintenance**.

```
ALOps Agent Maintenance

View raw log
Starting: ALOps Agent Maintenance
==============================================================================
Task         : ALOps Agent Maintenance
Description  : Cleanup and maintain DevOps a Agent for Business Central
Version      : 1.445.2647
Author       : Hodor
Help         : Cleanup and maintain DevOps a Agent for Business Central.
==============================================================================
*** Validate configuration
##[error]Cannot find an overload for "GetObjectsForNativeVariants" and the argument count: "1".
Finishing: ALOps Agent Maintenance

```

**Comment by lvanvugt** [comment]
Strange behavior:

- Removed agent from and installed new on one of the 2 VMS
- Now all pipelines run well again on both VMs

**Comment by waldo1001** [comment]
That is strange behavior to say the least :-/.  Good info though!

**Comment by lvanvugt** [comment]
@waldo1001, close it **as is** or it this something you want to track still?

**Comment by waldo1001** [comment]
Just close it.

In many cases, a windows update needs quite some time to commit (or undo) the changes, which might cause issues in the pipeline.  That's why a general recommendation is: do not update, and if you do: be able to rollback, and apply the update while you don't need the agent for a while (during night).

**Comment by waldo1001** [comment]
We ARE thinking about providing a "BAaaS" (Build agent as a Service).  Because I see this as THE biggest bottleneck in anything DevOps.. .  While it's infrastructure, there simply isn't anything we can support about it 🤷‍♂️.
