### ISSUE TITLE
How is nav_app_version parameter of ALOpsAppCompiler evaluated when assigning it '?.?.[yyyyWW].*'?

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#441]
### Question
How is the **nav_app_version** parameter of `ALOpsAppCompiler` evaluated?

### Background
I am asking as we are getting a somewhat unexpected result.

We feed **nav_app_version** with the following string: `?.?.[yyyyWW].*`, which creates a version based on

- the two first numbers as provided in the `version` keyword in the _app.json_ replacing the two questions marks, i.e. `?`.
- a number based on `yyyyWW`
- an finally the number of the build run replacing the asterisk, i.e. `*`.

The `yyyyWW` is behaving unexpectedly with the respect the week number part , i.e. `WW`.
It appears that the week number changes when going from Wednesday to Thursday, where I would expect to change between Saturday and Sunday, or Sunday and Monday.

So, I was wondering how does ALOps evaluate the **nav_app_version** parameter of `ALOpsAppCompiler`.

- Is this week number an ALOps generated things or is it inherited form Azure DevOps (ADO)?
- What is the logic behind the week number changing between Wednesday and Thursday?

#### Note
Have been trying to find info on the web related to ADO but did not find anything so far.

**Comment by lvanvugt** [comment]
@AdminHodor isn't this question hanging for too long a time?

**Comment by waldo1001** [comment]
Hi Luc,

This can happen with "community support", I'm afraid.  As you know, the last weeks (months) have been busy for many reasons.  For priority support, you can look into our "Enterprise Agreement".

For a weeknumber, we're using basic DotNet.  In PowerShell:
```powershell
$WeekNumber = get-date -UFormat %V
```
Explanation:
```
‘%V’
ISO week number, that is, the week number of year, with Monday as the first day of the week (‘01’…‘53’). If the week containing January 1 has four or more days in the new year, then it is considered week 1; otherwise, it is week 53 of the previous year, and the next week is week 1. (See the ISO 8601 standard.)
```

**Comment by lvanvugt** [comment]
> This can happen with "community support", I'm afraid.

Indeed, I know, but I have no idea on whether an issue is in view or not. So, the only tool I have is to "rumble" by entering a comment. Sorry for that. ;-)

> As you know, the last weeks (months) have been busy for many reasons

To be honest: I did not know.

> For a weeknumber, we're using basic DotNet.

So, the week number on the build is indeed created by ALOps. I do get what is expected. But apparently it does not yield the expected in our build pipelines as the week number does not change from Sunday to Monday, but from Wednesday to Thursday.

**Comment by waldo1001** [comment]
I did some research and indeed - it switches the weeknumber on Thursday.  But that is expected behaviour for the %V (UFormat) .. .

I think I found a better way to do it:
```powershell
(Get-Culture).Calendar.GetWeekOfYear('2021-11-05', (Get-Culture).DateTimeFormat.CalendarWeekRule, (Get-Culture).DateTimeFormat.FirstDayOfWeek)
```

But in all honesty, if we apply this, I think we'll break builds/releases as it might happen that people will have a lower weeknumber (hence version). 🤔

**Comment by lvanvugt** [comment]
> But in all honesty, if we apply this, I think we'll break builds/releases as it might happen that people will have a lower weeknumber (hence version). 🤔

Well, doesn't that depend on when your going to deploy this? I you would deploy on after Wednesday and before Monday that shouldn't be an issue as that period both methods resolve to the same week number, right?

**Comment by waldo1001** [comment]
Well, not really.  I can't guarantee when the software gets updated at the people's system.  It might be immediate, it might be after a few days - I even had once that it took a week 🙄.  So it could be updated at the time it gets again a lower value than before, which would break many things .. .

Then again, we are using .Net/PowerShell defaults (recommended ways) .. .  A simple windows update might fix this "issue" - which might cause an issue .. .  Dear lord 😱.

I'll talk it through with my team - I can't put this on the "high prio" list, to be honest.

**Comment by waldo1001** [comment]
I'm beyond fumbled by this behavior, to be honest :(.

**Comment by lvanvugt** [comment]
I am sitting next to you. 8-)

**Comment by waldo1001** [comment]
We changed it, but just to be sure, we'll only change it from the 1/1/2022, assuming all weeknumbers will reset on that date 🤷‍♂️.  It's the most stable thing we could think about ...

**Comment by lvanvugt** [comment]
@waldo1001 I started counting the days until 1/1. 🙄

**Comment by waldo1001** [comment]
Sorry - it's the only way to make it as save as at all possible...

**Comment by lvanvugt** [comment]
No need to say sorry, Fully understood and agreed. I meant it positive, i.e. looking forward to it!

**Comment by lvanvugt** [comment]
Verifying the build year/week numbering of last week:

![image](https://user-images.githubusercontent.com/18466198/148679784-6767266d-bb28-4ba0-b69c-8f2e615a08c1.png)

It seems fixed as Thursday and Wednesday builds have same year/week number, so, not changing between these two week days.

Of course, still to be verified that the change from Sunday to Monday will higher the week number.

###Note
A minor issue:, the week passed - see also screenshot - was the first week of January. The build did not use `01`, but `02` for the week number.

**Comment by lvanvugt** [comment]
@waldo1001 see my findings since we're in 2022.

**Comment by waldo1001** [comment]
Well .. there isn't a whole lot we can do, honestly .. .  I hope you're happy (enough ;-)) with the current behavior.

**Comment by lvanvugt** [comment]
I more than happy. Just wanted to note that one issue to make this complete. Will close.

**Comment by waldo1001** [comment]
Glad to hear.  And appreciate it!
It's a sensitive thing to mess around with, as it could cause builds to have lower version numbers all of a sudden.. .  That's why we chose to only change it on a new year.  
On top of that, we're still just passing this to default .Net date formatting - so if the .Net libraries handle the weeknumbers like this, we're pretty much dependent from that 🤷‍♂️
