### ISSUE TITLE
Export app as runtime package

### ISSUE THREAD

**Issue by vody** [HodorNV/ALOps#45]
Hi, we have an AppSource extensions which we need to distribute among our on-prem customers before it is going to AppSource. My understanding is only way to do it is with Runtime packages: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages 

Will be nice to have a separate task to export app as runtime package or have it as additional option within complete task.

**Comment by waldo1001** [comment]
It's on the list!  Thanks!

**Comment by AdminHodor** [comment]
Is included in the next release v1.426 which will be made available this week.

**Comment by vody** [comment]
Thank you!
