### ISSUE TITLE
Missing documenation for createsqlbackup option for task ALOpsDockerRemove

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#450]
Hey Guys, 

Could you please document what is the syntax for option **createsqlbackup** in task **ALOpsDockerRemove**?

I tried to set it to **true**, but it does not work. 

p.s. could you please review your documentation. I bet there are more properties that are missing proper description. 

Best Regards, 
Gintautas

**Comment by waldo1001** [comment]
Hi,

IntelliSense gives you the options:
![image](https://user-images.githubusercontent.com/12088142/141465013-c6a0e23e-c6a1-480c-be91-836894cca247.png)

Here is an example:
https://github.com/HodorNV/ALOps/blob/master/Examples/18_backupsqldatabase.yml

**Comment by gintuoklis** [comment]
Thanks for the link, missed it somehow.
When it comes to IntelliSense,  it does not work, if you are working with template files. Plus IntelliSense <> Documeantion

**Comment by waldo1001** [comment]
Yeah, intellisense in templates is a challenge :-).  That's why we have these "test-pipelines" to compose the templates ;-)
