### ISSUE TITLE
ALOpsAppPublish: resolution of app to be published is not working right

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#451]
### Issue
Given the filter in `nav_artifact_app_filter` _ALOpsAppPublish_ tries to resolve this into getting the right .app file - i.e. the latest version -  in the pipeline's `Agent.BuildDirectory` for the current build agent. This however seems to have a bug, which we yesterday got confronted with painfully.

A number of nightly deployments failed due to some breaking change in one of our apps - we'll call it **BreakingApp** - which did not show in the preceding build pipelines. Apps, depending on the app holding the breaking change - we'll call them **DependingApps** - failed in the deployment but had been successfully built. It turned out that in the build pipelines _ALOpsAppPublish_ did not resolve to the latest version of the **BreakingApp**, but an older one. If this had been working right the build pipelines for the **DependingApps** should have been failed due to the breaking change in **BreakingApp**.

For completeness sake: in **BreakingApp** an enum value name had been changed. This enum was used in the **DependingApps**.

Our build pipelines have been build up in such a way that they always incorporate the pipelines building the apps they depend on. Not only by downloading and installing their artifacts, but also by publishing these apps artifacts on the current build. This is to always have the full - and right - collection of apps published as artifacts for one build pipeline.

When an app - at the end of a dependency chain - has been built the artifacts shows as follows:

![image](https://user-images.githubusercontent.com/18466198/141615409-88ee7b2b-3f4f-4d46-88aa-6f12226d4c0d.png)

Each underlying build has a similar - but of course somewhat smaller - set of artifacts. The consequence is that when running a build pipeline for **DependingApps** all artifacts of the underlying apps will be down loaded to the `Agent.BuildDirectory` potentially resulting in multiple app files for the same app which _ALOpsAppPublish_ has to resolve into the right one to be published and installed in the BC build environment. Overall this appears to work fine, but as mentioned above yesterday it became clear it does not always do this right.

The following part of the log for the _ALOpsAppPublish_ step shows where/how it goes wrong:

### part of _ALOpsAppPublish_ log
```
*** Multiple App files found with filter [*Agriware 365 L_*_APP.app].
  * C:\ADO Agents\Agent3\_work\70\AgriwareLB\AgriwareDevelopment\Mprise Agriware_Agriware 365 L_17.1.202146.22645_APP.app
  * C:\ADO Agents\Agent3\_work\70\a\Technical\.alpackages\Mprise Agriware_Agriware 365 L_17.1.202146.22645_APP.app
  * C:\ADO Agents\Agent3\_work\70\LApiB\Technical\.alpackages\Mprise Agriware_Agriware 365 L_17.1.202146.22645_APP.app
  * C:\ADO Agents\Agent3\_work\70\AgriwarePPLB\Technical\.alpackages\Mprise Agriware_Agriware 365 L_17.1.202146.22645_APP.app
  * C:\ADO Agents\Agent3\_work\70\AgriwarePPLApiB\Technical\.alpackages\Mprise Agriware_Agriware 365 L_17.1.202145.22372_APP.app
*** Resolved App File: [C:\ADO Agents\Agent3\_work\70\AgriwarePPLApiB\Technical\.alpackages\Mprise Agriware_Agriware 365 L_17.1.202145.22372_APP.app].
*** Copy Artifact: [C:\ADO Agents\Agent3\_work\70\AgriwarePPLApiB\Technical\.alpackages\Mprise Agriware_Agriware 365 L_17.1.202145.22372_APP.app]
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [BC].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\170\service]
*** Selected module: [C:\program files\microsoft dynamics nav\170\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\170\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\170\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\170\service\Microsoft.Dynamics.Nav.Management.dll]

**************************************
 * App File = [c:\Run\DevOps\Artifacts\Mprise Agriware_Agriware 365 L_17.1.202145.22372_APP.app]

 * App.ID        = bb50f88e-e4b0-4826-82d8-e26c823159a5
 * App.Name      = Agriware 365 L
 * App.Publisher = Mprise Agriware
 * App.Version   = 17.1.202145.22372
 => Publishing App 'Agriware 365 L v17.1.202145.22372'
```
As you can see it published  **v17.1.202145.22372** of the app _Agriware 365 L_, but there is a newer version available: **v17.1.202146.22645**.

### Expected behavior
So, an older version of the **BreakingApp** app is used in the build pipeline, while it should have used the latest one. The older version does not contain the breaking change and as the depending apps have not been updated yet, the pipelines succeeds where it should have failed because of the breaking change.

### Notes
1. We probably didn't run into this issue before - at least that we know of - because the whole _pipelines chain_ was mostly executed from bottom to top all the way. In the current stage of the project this is part of, however, the _chain_ might be triggered only halfway.
2. Not sure if sharing a pipeline .yml would make sense here. If so, please let me know.
3. The illustration of the artifacts and the log example are not from the same build pipeline.

**Comment by waldo1001** [comment]
It looks like there is some kind of misconception or bug in the way you set up the pipielines.  ALOps doesn't "pick versions" or "pick latest" or anything.  ALOps executes what you define.  So I don't see the ALOps issue here - but I do possibly see a pipeline-chain issue here.

For that to understand, I'll have to get more information on how this "chain" is set up, I'm afraid.  Or can you point to an ALOps step execution that didn't behave like it should have?

**Comment by lvanvugt** [comment]
Would it be possible to demo what it is doing?

**Comment by lvanvugt** [comment]
> Would it be possible to demo what it is doing?

I mean ... that I demo you what it is doing?

**Comment by lvanvugt** [comment]
@waldo1001 thanx for the discussion leading to a nice workable solution.

We came to two possible options given that we copy all underlying apps to `$(Build.ArtifactStagingDirectory)/Technical/.alpackages` from where they are published as artifacts for the build pipeline

1. Set the `artifact_path` on each `ALOpsAppPublish `task to this directory
1. Replace all individual `ALOpsAppPublish `task with one and set its `batch_publish_folder` to this directory

I have chosen to implement the second option as (1) this reduces the number of tasks in our .yml, (2) no additional task for any next underlying app is needed and (3) also appears to be a bit faster.
