### ISSUE TITLE
ALOpsCompile - Wrong warnings reported by pipeline on AL0667 applicationInsightsConnectionString failure

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#456]
**Describe the bug**
We've recently switched from bcartifact 18.1 to 19.1.

Pipeline started - as expected - failing on AL0667 warnings.
However, the warning that is returned by the pipeline (orange line in logs) is stating 

`##[warning]Compilation started for project 'Navitrans 365 Core' containing '222' files at '17:53:37.281'.`

instead of

`##[warning]warning AL0667: 'applicationInsightsKey' is being deprecated in the versions: '7.2' or greater. This property is being deprecated in favor of 'applicationInsightsConnectionString'. This warning will become an error in a future release.`

**the output**

```
...
Copyright (C) Microsoft Corporation. All rights reserved
C:\DockerInstallation\Agent3\_work\13\s\App\app.json(14,5): warning AL0667: 'applicationInsightsKey' is being deprecated in the versions: '7.2' or greater. This property is being deprecated in favor of 'applicationInsightsConnectionString'. This warning will become an error in a future release.
Compilation started for project 'Navitrans 365 Core' containing '222' files at '17:53:37.281'.
Compilation ended at '17:53:46.624'.
*** AL Compiler raw logs: End
*** Start processing compile results.
##[warning]Compilation started for project 'Navitrans 365 Core' containing '222' files at '17:53:37.281'.
*** Skip Uploading App as Build-Artifact
*** Publish XLIF as Artifact skipped
...
```

**Comment by waldo1001** [comment]
Hm, we have had the same errors - I didn't notice this. 
your "output" seems to include the right warnings though?

**Comment by fvet** [comment]
The output is correct

```
Copyright (C) Microsoft Corporation. All rights reserved
C:\DockerInstallation\Agent3\_work\13\s\App\app.json(14,5): warning AL0667: 'applicationInsightsKey' is being deprecated in the versions: '7.2' or greater. This property is being deprecated in favor of 'applicationInsightsConnectionString'. This warning will become an error in a future release.
Compilation started for project 'Navitrans 365 Core' containing '222' files at '17:53:37.281'.
Compilation ended at '17:53:46.624'.
```

The mentioned `##[warning]` after *`** Start processing compile results.` is the wrong one

**Comment by waldo1001** [comment]
We were able to repro this - it's a new way of "warnings" that MS does, I guess - we'll try to change our warning parsing accordingly
