### ISSUE TITLE
AL Ops script seen as malicious software

### ISSUE THREAD

**Issue by petertijsma** [HodorNV/ALOps#458]
Since this morning (v1.146) the ALOps Create and Remove Container scripts are seen as malicious software?

```
##[error]At F:\ADOAgents\Agent1\_work\_tasks\ALOpsDockerCreate_f4c04016-bb3f-4614-b978-ce92409ce78a\1.446.2712\ps_modules\alops\d1b572c5-5a48-44ec-9ea6-cdaf0b8c2684.ps1:1 char:1
+ Invoke-Expression -Command ([System.Text.Encoding]::UTF8.GetString([S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
Finishing: ALOPS - Create Docker Image
```

```
##[error]At line:1 char:1
+  ([RuNtiME.InTeRoPSeRVices.maRsHAL]::([RUNTime.inTeROpsErvices.MArsHa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
Finishing: ALOPS - Remove Docker Container
```

Any idea what's happening?

**Comment by lvanvugt** [comment]
Peter, did you have a look here #318?

**Comment by waldo1001** [comment]
Yeah, virusscanners and obfuscated scripting is not really a good match.  There is a plan in the long run to move everything over to .Net, but that takes time.

The link that Luc mentioned, does contain a few tips indeed (thanks, Luc ;-)).

A pipeline-variable: `"alops_disable_amsi" = true` - just make sure the variable is named that way, and is set before the pipeline runs 

Add a Powershell step with : `Set-MpPreference -DisableScriptScanning $true` .

Or, if that doesn't work: disable the agent-folder on the virusscanner.

And - if that doesn't work: isolate the agent, and remove the virus-scanner.

**Comment by petertijsma** [comment]
Yep, that did the trick indeed :-)

Just to e sure, I simply added both :-)

![image](https://user-images.githubusercontent.com/86952584/143684271-c512c1fc-451b-452e-9c05-bc8f3139013b.png)

and

![image](https://user-images.githubusercontent.com/86952584/143684277-4c025c62-26c8-40f5-990b-cad323fa16bd.png)

Now working again.
Thanks!

PS. Order for our company should be in your inbox ;-)
