### ISSUE TITLE
[Feature Request] ALOps task to GraphViz file

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#459]
**Is your feature request related to a problem? Please describe.**
Part of our release process is to include GraphViz files (to make the dependencies overview a bit more comprehensible for others). We do this using this cool VS Code commandlet ;)

![image](https://user-images.githubusercontent.com/25268332/144006829-7c381dbf-3691-443d-8056-dd422d1340bd.png)

Resulting in a .dot file

![image](https://user-images.githubusercontent.com/25268332/144006875-f17dcc6a-1ed5-4be8-aa75-85a463f0af26.png)

**Describe the solution you'd like**
Would be great if ALOps could add a new step to provide the same behaviour as the VS Code commandlet, so we can automate this step as part of our pipelines.

**Describe alternatives you've considered**
Run it manually ...

**Comment by waldo1001** [comment]
Seems a cool feature - never thought of it.  We'll put it on the list.

How we envision is: 
- we'll grab ALL the apps that we can find in the working folder, both downloaded, and part of the artifacts.  
- we'll add these settings:
```
    "CRS.DependencyGraph.IncludeTestApps": false,
    "CRS.DependencyGraph.RemovePrefix": "DISTRI-",
    "CRS.DependencyGraph.ExcludeAppNames": [],
    "CRS.DependencyGraph.ExcludePublishers": [
        "Microsoft"
    ],
```

**Comment by fvet** [comment]
Agree on the settings part!

_(PS, this has lower prio / nice to have)_
