### ISSUE TITLE
Set target in AppCompiler

### ISSUE THREAD

**Issue by Avanti05** [HodorNV/ALOps#46]
It would be nice to be able to set target for AppCompiler to be able to set up builds for both Cloud and OnPrem.

**Comment by waldo1001** [comment]
That's feasible - but, I don't see why this is useful.  Can you explain?

**Comment by Avanti05** [comment]
Our source code and versioning is the same for Onprem and Cloud, for now anyway, but i would think it would be best practice to set the target accordingly. 
The only difference at the moment would be target in the app.json. 
So to avoid having to have two branches or unnessessary merges only to set the target in the manifest.

**Comment by PatrickGrabensteiner** [comment]
You could use apps compiled for Cloud in onPrem environments

**Comment by waldo1001** [comment]
Exactly.  

I don't see a reason for doing so, @Avanti05 , so if you don't mind, I'll close this issue.  If there is a valid reason, please open it again :-).
