### ISSUE TITLE
Build warnings make changes re-appear in every subsequent build

### ISSUE THREAD

**Issue by StevenHit** [HodorNV/ALOps#467]
Sometimes we have AL compilation warnings in a build pipeline run. The result is an app that can be released without issues. Unfortunately, when we have a run with warnings like this one:

![image](https://user-images.githubusercontent.com/34163966/145250170-edd23eb0-47ea-4511-8ba8-54abc12bac23.png)

The same (commits) changes keep re-appearing again on subsequent runs, until a run gets the succeeded status:

![image](https://user-images.githubusercontent.com/34163966/145250339-dd268168-7e7a-4336-9eaf-08ea56caa2a4.png)

Is there a way to avoid this? I mean, when a build succeeds with warnings, the changes should still be assigned to that build. Not to the next build.

Thanks for your help

**Comment by StevenHit** [comment]
You are right. The fact that DevOps keeps repeating changes when the build status is "succeeded with warnings" is a DevOps thing.

But, as there is a "failed_on_warnings" parameter. There isn't something like "succeed on warnings" in ALOps?

Thanks

**Comment by waldo1001** [comment]
But you can't accomplish that with a ruleset and/or disabling codecops, no?

**Comment by waldo1001** [comment]
If you need help on setting up the rulesets, let me know - for now, I'll close this issue.
