### ISSUE TITLE
The form specified for the subject is not one supported or known by the specified trust provider

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#47]
I get above error, but have no Idea what is wrong when signing app with timestamp URI.  in below step. (works fine if I test in a cmd script with that uri)

- task: ALOpsAppSign@1
  displayName: 'ALOps App Sign'
  env:
    pfx_password: $(CodeSignPfxPassword)
  inputs:
    pfx_path: $(CodeSignPfxFile)
    nav_artifact_app_filter: '*.app'
    timestamp_uri: 'http://timestamp.verisign.com/scripts/timestamp.dll'
    usedocker: False
    publish_artifact: True

**Comment by waldo1001** [comment]
hey @MortenRa ,

Just a few basic questions:
- are you using Docker for your other steps?
- is the step able to access the actual certificate (the path to the file is accurate?)
- is it an actual "code signing" certificate?

**Comment by waldo1001** [comment]
Also, can you give us as much output as at all possible?

**Comment by MortenRa** [comment]
I´ll  send you the log file for the last run

I do however get the appsigned I guess the path is correct.
##[warning]App is Signed but not timestamped.

And it is an actual code signing certificat I use it several times for app sent to appsource.

**Comment by MortenRa** [comment]
> Also, can you give us as much output as at all possible?

I have send you an mail with the full log, if you didn´t notice

**Comment by AdminHodor** [comment]
Hello,

After some vigorous testing we noticed the default Url for timestamping is not 100% stable. 
As current default we use "http://timestamp.verisign.com/scripts/timestamp.dll" for timestamping.
After 250 iterations of the same build we noticed 26 similar failures.
We retried with another timestamp service: "http://timestamp.comodoca.com/authenticode" and got 100% success on the next 250 builds.

We changed (v1.426):
- The default timestamp service to "http://timestamp.comodoca.com/authenticode"
- Improved sign-checks on the ALOpsAppSign method, this will move the error to the correct place in the pipeline

Could you please check if the comodoca timestamp Url helps out your case?

Kind regards

**Comment by AdminHodor** [comment]
Hello @MortenRa ,

We did some improvement to the default Sign-Validation which is already included in the current release. Could you please check if this resolved your issues?

Kind regards,

Bart Bourgeois

**Comment by MortenRa** [comment]
Hi, 

Still getting this error: ##[error]Signature status: UnknownError. The form specified for the subject is not one supported or known by the specified trust provider.

Maybe me setup is wrong

- task: ALOpsAppSign@1
  displayName: 'ALOps App Sign'
  env:
    pfx_password: $(CodeSignPfxPassword)
  inputs:
    pfx_path: $(CodeSignPfxFile)
    nav_artifact_app_filter: '*.app'
    timestamp_uri: 'http://timestamp.comodoca.com/authenticode'
    usedocker: False
    publish_artifact: True

**Comment by waldo1001** [comment]
Hi Morten,
We are just not able to replicate the problem :-/.
Did you try to do it manually on the server, with the account, of/where the failing agent is running?

**Comment by MortenRa** [comment]
Hi,

Okey my last 3 test build did not report above error, and I did not change anything in regards to the sign task

**Comment by AdminHodor** [comment]
Hello @MortenRa ,

Thanks for the feedback, we'll close the issue.

Kind regards
