### ISSUE TITLE
Next Major: Downgrade license warnings to an information

### ISSUE THREAD

**Issue by NKarolak** [HodorNV/ALOps#470]
**Is your feature request related to a problem? Please describe.**
I try to keep all of my pipelines in status "green", even the next minor and next major. 
Whenever the status would turn into yellow (or red), I'd see that I need to take some action.

**Describe the solution you'd like**
For next major pipelines, I'd like to downgrade license warnings (that I cannot influence anyway) into an information.
`This license is not compatible with this version of Business Central.`

**Describe alternatives you've considered**
None really. The status is constantly yellow, so I have to check manually whether some warning is new.

**Additional context**
None.

**Comment by waldo1001** [comment]
Talked with development - it makes sense, so we'll see if we can make a solution for that!

**Comment by waldo1001** [comment]
We looked into this - MS isn't making it easy on us :(.  It's all just text we'll need to parse, redirect output, .. .

So, not sure we'll find a solution for this with the tools we get for now .. but we keep trying.
