### ISSUE TITLE
This script contains malicious content and has been blocked by your antivirus software.

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#482]
I'm using a release pipeline to release a generated app file to a customer server. On this server an agent was installed to execute the ALOps App Publish step. But it fails with: This script contains malicious content and has been blocked by your antivirus software.

I searched issues on this site and implemented the suggested solutions, but without success.
What I did:
added alops_disable_amsi variable:
![image](https://user-images.githubusercontent.com/25202313/154454236-698ee454-d613-44fc-8cec-0e8d7f57781c.png)

Added Powershell commands:
![image](https://user-images.githubusercontent.com/25202313/154454361-36d9f649-519d-4fbf-a16e-997ee482c577.png)

But the error still occurs:
![image](https://user-images.githubusercontent.com/25202313/154454516-19b6b1a1-c73f-4269-a30b-eb0c0cf2fb48.png)

Server is only running Windows Defender. Also excluded the C:\azagent folder from Windows Defender. Any idea what to do?

**Comment by peterz84** [comment]
Do you mean C:\azagent\A2\_work in this case? Isn't the whole folder excluded when I exclude C:\azagent ?

**Comment by waldo1001** [comment]
Sorry - yes - I missed your last sentence.. .

**Comment by a-augros** [comment]
Hello,

I have exactly the same problem for a customer, and tried the same solution without success...

Did you find a solution ?

Thanks

**Comment by peterz84** [comment]
Actually no, was hoping for a new idea by Waldo...

**Comment by waldo1001** [comment]
No new ideas.  There are quite some tips on how to handle this.  Let me sum them up, just to be sure:

- Disable the virus scanner / defender altogether
- Exclude the working folder and the entire agent-folder in the software

- Set variable "alops_disable_amsi" in the pipeline 
![image](https://user-images.githubusercontent.com/12088142/158358599-cc78905f-9e79-4f38-a6ef-fffbc8bb1c3d.png)

- Disable script scanning 
![image](https://user-images.githubusercontent.com/12088142/158358667-b6f6d3d8-65a7-417b-9e6d-c7fe4ec1bf7b.png)
(enabled it again at the end of the pipeline with:)
`Set-MpPreference -DisableScriptScanning $false`

- look into group policy / Azure Security Center (in fact, i'd always create a machine completely out of your domain, so you're not bothered with internal policies.  
If on Azure: Add an exeption in Azure Security Center for the build machine

**Comment by waldo1001** [comment]
Since we're talking about "publishing apps", I'm quite sure you can mitigate all these problems with the "API Deploy".  More info here:
https://www.waldo.be/2020/06/15/deploying-from-devops-the-right-way-enabling-external-deployment-in-onprem-business-central-environments/

**Comment by a-augros** [comment]
Thanks, I am going in this way to solve this problem, but for that, I need to open API to the outside, currently in the hands of Customer IT.

I will keep you informed

**Comment by waldo1001** [comment]
I'll close this issue.  If it's still a problem, please open it again, with detailed information.

**Comment by a-augros** [comment]
Sorry for late answer. We are actually facing to authentification issues with windows authentification but ALOps.ExternalDeployer seems to work.
I will reopen if needed
thanks for your support
