### ISSUE TITLE
Right for the agent's user account

### ISSUE THREAD

**Issue by OUAIRY** [HodorNV/ALOps#487]
Hello,

Do you have documentation or a link that clearly states what rights and permissions the account that is set up for the agent should have?

My customer doesn't want to give admin rights but I can't find any documentation to know what is needed to perform the pipeline and deployments.

Thanks in advance.

**Comment by waldo1001** [comment]
There is no document .. we can't specify what you want to do with the service.

can you provide me some context?
What do you want to do?  Why do you need a build server at the customer site?

**Comment by OUAIRY** [comment]
The client wanted to have its devops and pipeline generation on its servers.
For security reasons they do not want to give administrator rights on the service account. They want to limit it to what is necessary.
Unfortunately I find myself with errors during the generation of files where they can not create directories and files Cf. screen  
 
![Error 2](https://user-images.githubusercontent.com/41148282/160177879-9610cf6f-ece3-4cfe-9bbd-e1f3bdc37d59.JPG)
![Error 1](https://user-images.githubusercontent.com/41148282/160177896-4d193f72-7607-4249-bdca-54d79f74e901.JPG)

**Comment by waldo1001** [comment]
This is going to be very difficult, I'm afraid.  As I said, there is no documentation about this.. .  

May be an alternative: build a new server that is NOT part of the domain?

**Comment by OUAIRY** [comment]
Not at the moment. I have contacted Microsoft but have not had any information yet.

**Comment by waldo1001** [comment]
I'll close this issue - if you have any more questions, you can open it again, or create a new one.
