### ISSUE TITLE
Enable/disable ForceSync for all tasks in release

### ISSUE THREAD

**Issue by StevenHit** [HodorNV/ALOps#502]
Hi,
We have some big release pipelines to several test environment (see below).
From time to time, we need to run these releases with the ForceSync parameter enabled. In that case, we need to go into each task in the release and enable the "ALOps App Publish" parameter. We need to disable the parameter again after the run. Which is quite a big manual task. Is there an easy way to enable/disable it for all tasks in the release pipeline?
Many thanks

![image](https://user-images.githubusercontent.com/34163966/166434168-83f092ca-a07c-448d-a3ef-29df3e6af720.png)

![image](https://user-images.githubusercontent.com/34163966/166434244-5a51f11e-26a8-4271-a623-13c5a451473d.png)

**Comment by waldo1001** [comment]
Sorry - that's a DevOps limitation if this UI-designer.

The only way around that I see is to foresee multistage pipelines for this, not release pipelines.  Such a pipeline is pure yaml, and there, you can use variables for any kind of parameters.. .

**Comment by StevenHit** [comment]
Thanks for your answer. It's not possible to make "Force Sync" a normal field in which you enter True or False (not a checkbox)? Doing so, we could enter a variable in it.

**Comment by waldo1001** [comment]
That would solve one thing, and cause many possible other problems, not to mention breaking every existing pipeline.. .

**Comment by StevenHit** [comment]
OK, thanks. I solved it via the DevOps API.

**Comment by waldo1001** [comment]
Aha, that's interesting - one that I didn't think of.  Nice one!  Thanks for sharing!
