### ISSUE TITLE
ALOpsAppCompiler extra Parameter: suppressWarnings 

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#503]
**Is your feature request related to a problem? Please describe.**
We've set up our pipelines with all kinds of CodeCops enabled. In the pipeline the ruleset parameter is used to provide a company-wide ruleset. The goal here is that all PTE and/or AppSource projects confirm to the same minimum quality enforced by these rules (next other mechanisms like code reviews). The suppressWarnings parameter in the app.json "throws a spanner in the works".

**Describe the solution you'd like**
A overrule parameter in the ALOpsAppCompiler (and ALOpsAppCompilerV2): suppressWarnings with the options;
* Keep
* None / Disabled
* Comma separate string with values, for example "PTE0012, AA0072, AA0218"

**Describe alternatives you've considered**
Using custom PowerShell to archive this. For now my Use Case is to remove the property completely, because we use a custom ruleset in our pipeline. De feature description here is a more generic approach.

```YAML
- task: PowerShell@2
  displayName: 'Verify app.json'
  condition: always()
  env:
    app_folder: '$(Build.SourcesDirectory)\App\'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##[command]Search for 'suppressWarnings' in app.json"
      $obj = Get-Content (Join-Path $env:app_folder app.json) -Raw | ConvertFrom-Json
      
      if(-Not($obj.PSobject.Properties.name -match "suppressWarnings")) {
        Write-Host "##[command]No 'suppressWarnings' found in app.json"
        exit
      }

      Write-Host "##[command]Remove 'suppressWarnings' from app.json"
      $obj.PSObject.Properties.Remove('suppressWarnings')
      $obj | ConvertTo-Json | Set-Content (Join-Path $env:app_folder app.json)
```

**Comment by waldo1001** [comment]
We'll put it on the list.

**Comment by AdminHodor** [comment]
v1.449: ALOpsAppCompiler: Extra parameter 'suppressWarnings' allows for overwriting in the app.json. Options: "KEEP","NONE", "<Array of exclusions>"

@Arthurvdv Could you please validate if this works for you in our latest release?

**Comment by Arthurvdv** [comment]
Thanks, I will check next week and report back

**Comment by Arthurvdv** [comment]
Works perfect, thanks for adding this!
