### ISSUE TITLE
Verify that objects are included in licens before release to onprem installation

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#505]
**Is your feature request related to a problem? Please describe.**
Perhaps more of a question than a feature request. I don't know or how do you handle this?
The overall question is how we validate that objects in partner range are included in the license.

Scenario:
We have general apps in partner range that different customers use and most of our customers are onprem.
The thing I'm worried about is that we add a a new subscription codeunit that subscribes to a common event.
Once released/published it will stop the majority of users since the object is not included in the customer license.

**Describe the solution you'd like**
I would like to check in my release pipeline if the new release has objects that is outside of customers license so we can in an early stage before publish discover that we are missing some license object in this installation.

**Describe alternatives you've considered**
I have been thinking if this could be checked in an upgrade codeunit by using the "Effective permissions" functionality.
The downside is that this needs to be included as a test case in every single app. 

Then we also have the scenario with temporary tables that is not used in pages that doesn't need to be included in the license.
![image](https://user-images.githubusercontent.com/34970096/167561642-8edc4c8c-02f6-4abc-943b-4a6df2621237.png)

**Comment by waldo1001** [comment]
We have this on the roadmap: will only work on an app-file, so that kind of makes sense in your case.. .

**Comment by AdminHodor** [comment]
Dear @NAVFreak ,

Please check our latest release v1.451
We included a new task "ALOpsAppLicenseCheck" which allows for checking App(s) against a license file (.FLF)

A simple example of the task can be found here:
https://github.com/HodorNV/ALOps/blob/master/Examples/27_LicenseCheck.yml

Kind regards,
