### ISSUE TITLE
Azure DevOps changed default branch name to main

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#514]
This is more FYI.

I was experimenting with a new repo and pipelines and I it took me a while until I understood why the pipeline wasn't automatically triggered by push to branch.
Currently Azure DevOps has changed standard default branch from master to main.
You can always change it back. But if you want to follow the changing times (also known as the woke wave) you have to change your templates. 
An unexperienced user can get problem with setting upp ALOps for the first time if you don't specify to beware of the name of the default branch

https://devblogs.microsoft.com/devops/azure-repos-default-branch-name/

**Comment by waldo1001** [comment]
That is true ... 
May be include both 🤔
