### ISSUE TITLE
Please update the documentation

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#523]
**Is your feature request related to a problem? Please describe.**
Can you please update the [documentation ](https://github.com/HodorNV/ALOps/blob/master/Documentation/BuildSteps.md).

Currently I find myself scrolling through the issues posts whenever I need more details about parameters that should exist in the documentation for the task which is starting to get tiresome after a while

**Describe the solution you'd like**
Example :
I want my pipeline to fail if not all the tests succeed. What should I pass as parameter to achieve this? What are the other alternatives?
![image](https://user-images.githubusercontent.com/34970096/172764921-97fb52a1-b16a-49bb-b55f-e2d483681dcd.png)

**Comment by waldo1001** [comment]
The documentation is generated automatically - and since it's an integrated DevOps task, you can use intellisense while editing the pipeline in DevOps - which gives you all the options:

![image](https://user-images.githubusercontent.com/12088142/172785993-e3f77e4c-466f-4480-9ee3-34954c8f3513.png)

**Comment by waldo1001** [comment]
Here's a better screenshot:
![image](https://user-images.githubusercontent.com/12088142/172786280-d170f634-9de7-4dc2-a9fc-99abcc45f225.png)

We'll see if we can self-generate the option-documentation as well (not sure)

**Comment by NAVFreak** [comment]
Aaah, nice. Forgot about that 🤦‍♂️
