### ISSUE TITLE
ALOpsExtensionAPI: Change default value for Check Delay (Sec)

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#526]
**Is your feature request related to a problem? Please describe.**
The default value of 5 seconds for Check Delay on the ALOpsExtensionAPI seems very optimistic (especially for a SaaS Sandbox environment).

I'm aware we can now set the "Check Delay (Sec)" param to change this behavior and avoid the error: _"App publish failed. Check the 'Extension Deployment Status' page in the Business Central client."_

Before this new setting was introduced the default value had a bigger chance of succes for us. The delay time seemed to increase over the amount of calls (see printscreen previous) and got us more "status green" on the release pipelines.

Now
![image](https://user-images.githubusercontent.com/44637996/172876624-9ee348b7-ca01-4625-be57-ae5eac5b25d6.png)

Previous
![image](https://user-images.githubusercontent.com/44637996/172877015-04707837-5cbe-4191-9c83-655231ef48e0.png)

**Describe the solution you'd like**
I think it would be better to change the default value for Check Delay (Sec) from 5 seconds to 30 seconds.
In this way, combined with the default value of 10 on the "Max tries for status check", the total time for an extension to reach the status successful on publishing an extension increases from 50 seconds to an comfortable 5 minutes.
I believe it's better to have a longer wait period with the correct response, then try to retrieve faster an response whichs could results in a unknown response (..check the 'Extension Deployment Status' page..).

**Describe alternatives you've considered**
We have multiple release pipelines without use of a template set-upped. Manually changing all our release pipelines and add an extra step in our procedure to change the default value.

**Additional context**
I would love if other ALOps users would reply below with their thoughts about this. Maybe we can agree (or compromise) on a default value for Check Delay (Sec) where this benefits all of us. I'm not aware of a use case where a faster response (with possible increase false positives) of the release pipeline can add value to the CI/CD process. If there is it would be great if you're willing to share this here.

**Comment by waldo1001** [comment]
We'll do so!

**Comment by waldo1001** [comment]
About to be released.
New values:
delay: 30 seconds
retry: 20

**Comment by waldo1001** [comment]
At least the end of next week, but I hope sooner.  There are multiple fixes that need some testing before we can push...

**Comment by Arthurvdv** [comment]
Thank you for the update!

**Comment by AdminHodor** [comment]
Dear @Arthurvdv, 

The fix was released today in ALOps v1.450. Could you please validate?
We changed the defaults to:
- checksecondsdelay = 30
- maxtries = 20

Kind regards,

**Comment by Arthurvdv** [comment]
Thank you for changing the default values. The amount of successful releases has considerable increased.
