### ISSUE TITLE
what is and how to use ALOpsRepositoryPublish

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#527]
@waldo1001  

Not sure how  this task ALOpsRepositoryPublish could be used, do not quite understand the documentation can you maybe explain what this can be used for.

And do ALops have a wrapper task to publish build artifacts to Azure Blob Storage, like in the BC container helper : Publish-BuildOutputToStorage

**Comment by waldo1001** [comment]
Hi Morten - that's an internal step, I'm afraid.  It basically calls an BC API to upload an artifact .. nothing special, and not really reusable for you as you don't have the BC API.. . 

Sorry
