### ISSUE TITLE
Question: My docker compile is running well. Please where can I find the sample yaml for running builds without docker

### ISSUE THREAD

**Issue by olusola-adio-sweaty** [HodorNV/ALOps#528]
Question: My docker compile is running well. Please where can I find the sample yaml for running builds without docker

**Comment by waldo1001** [comment]
I think you mean these:
https://github.com/HodorNV/ALOps/tree/master/Examples/Compiler%20V2

**Comment by olusola-adio-sweaty** [comment]
Thanks a lot. Works like a dream. So much quicker.
