### ISSUE TITLE
Question: ALOpsAppCompiler@2 is the only ALOPS task on my pipeline, do I still neeed to retain docker on the build server

### ISSUE THREAD

**Issue by olusola-adio-sweaty** [HodorNV/ALOps#529]
Question: ALOpsAppCompiler@2 is the only ALOPS task on my pipeline, do I still neeed to retain docker on the build server

I was running docker builds up till a few minutes ago, when I cut over to ALOpsAppCompiler@2. Still using the same build server that has docker on it which is very 'beefy'. Can this run successfully on a build agent without any docker so I can switch to a 'lighter' build server that has no docker on it.

**Comment by waldo1001** [comment]
CompilerV2 (is how we call it) is not using docker at all, but it IS using the artifacts (including BcContainerHelper).

So yes, you should be able to switch.. (make sure you have the right .Net framework (4.8) installed)

**Comment by olusola-adio-sweaty** [comment]
Thanks a lot for this
