### ISSUE TITLE
Question: Are there any limitations on what can be done using the per pipeline run?

### ISSUE THREAD

**Issue by uncle-sola** [HodorNV/ALOps#534]
Please are there are any limitations on what can be done using the per pipeline run (i.e. restrictions on number of repos, projects, etc)

**Comment by waldo1001** [comment]
None.  Every step is available.  

You can use multiple ALOps steps in a pipeline, it will only cost 1 EUR for that run.
Every Run (build or release pipeline, failed or (partially) succeeded) that has one or more ALOps steps, will be charged once.
