### ISSUE TITLE
How do we start a paid subscription? No reply to our emails

### ISSUE THREAD

**Issue by olusola-adio-sweaty** [HodorNV/ALOps#537]
![image](https://user-images.githubusercontent.com/104525381/175890723-383bbda6-ba16-4a0b-ab84-e839efbf2d40.png)

![image](https://user-images.githubusercontent.com/104525381/175890884-773cf279-329c-4559-b732-dc8fa1f9c7e1.png)

Please reply to Brett (Brett.Vice@sweatybetty.com)

**Comment by waldo1001** [comment]
Hi Brett,
our apologies for this - we will get to it today!
