### ISSUE TITLE
ALOps Compile step fails as Analyzers can no longer be found!

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#539]
**Describe the bug**
We recieved an ALOps update to version 1.450.3068 an hour ago that makes all our pipelines on BC19 and BC20 fail due to the fact that ALOps no longer can find the analyzers!

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```Compile step with all the info needed
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile App'
  inputs:
    usedocker: true
    targetproject: $(AppJsonPath)
    nav_app_version: $(CompilerArgumentForVersionNo)
    al_analyzer: $(CodeAnalyzers)
    app_file_suffix: '_APP'
    failed_on_warnings: $(FailAppOnWarnings)    

See attached log for this step for more details
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
See attached file
[ALOps Compile step.txt](https://github.com/HodorNV/ALOps/files/9038174/ALOps.Compile.step.txt)

```

**Expected behavior**
Analyzers are identified and compilation works.

**Screenshots**
![image](https://user-images.githubusercontent.com/54669593/177125273-10cbfc03-6bba-4284-be30-77f357f235a6.png)
![image](https://user-images.githubusercontent.com/54669593/177125315-2cc03ff8-c281-4da4-8c40-f6c080717a94.png)

**Additional context**

**Comment by waldo1001** [comment]
Hotfix is online - can you verify?

**Comment by kasperdj** [comment]
The hotfix works, thx
