### ISSUE TITLE
Question: About new BC server setup

### ISSUE THREAD

**Issue by olusola-adio-sweaty** [HodorNV/ALOps#547]
I am currently building a new OnPrem BC sandbox. 

However, I am unable to change the credential type on the BC setup screen from “Windows” to “UserPassword”.
![Screenshot 2022-07-18 at 13 49 07](https://user-images.githubusercontent.com/104525381/179515966-f190266a-7c8c-4b8c-81d0-5fe49e98a512.png)

I wanted find out if you have encountered this problem before as I want to use my current build server (a separate VM) already using (UserPassword authentication successfully to other BC servers via ALOps extension) to deploy extensions to this new BC sandbox server. 

All the other options apart from "Windows" are not selectable

Thanks for your help.

**Comment by BartBourgeois** [comment]
Hello @olusola-adio-sweaty ,

Normally the Settings window is always read-only at first, should be an "Edit" button in bottom right of the window.

Kind regards
