### ISSUE TITLE
Deploy Extension to NAV Instance running on another machine

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#56]
Hey Guys, 

We are trying to setup release pipelines for our test environment(s) but realized, that that **"ALOps App Publish"** is limited to the localhost machine (or docker container) only. It cannot publish extenstion to remote machine. In our case we have multiple machines for different test env, and single machine that host buildagent on the same network. We don't want to install buildagent for each test envrionmnet since it leads to more maintenance, and cost.

"ALOps SaaS Publish Extension" looks like what we need, but it comes with all SaaS mandatory parameters (tenant id, client id, secret) that you don't have in on local installations.

Could you please either extend **"ALOps App Publish"** by adding host name, and authentification parameters, or just simplify "ALOps SaaS Publish Extension" by changing mandatory parameters to optional one.

If you have other suggestions how to solve these problems, please let us know.

Best Regards, 
Gintautas

**Comment by AdminHodor** [comment]
Hello @gintuoklis ,

Glad to inform you we already have this in the pipeline (by popular demand) and will be available in the next release (v1.427). We are going to introduce a new task for API-Publish, with multiple authentication methods (Basic,Windows,OAuth,..); We'll leave the SaaS-Publish in for while, leaving enough time for migrating to the new API-Publish task.
We'll send you an update as soon as it is available!

Kind regards,

Bart Bourgeois

**Comment by gintuoklis** [comment]
Great news Bart, 
Any ETA for next release?

**Comment by gintuoklis** [comment]
any update @AdminHodor ?

**Comment by gintuoklis** [comment]
Hey Guys, 
Sorry to bother you again. Perhaps you have any update regarding ETA for the next release?

**Comment by gintuoklis** [comment]
@AdminHodor, do you have any update on this case?

**Comment by DanielGoehler** [comment]
Hi @AdminHodor,

this feature would be very useful. Any new on that?

**Comment by DanielGoehler** [comment]
Hi @waldo1001, do you know anything about the state of this feature?

**Comment by waldo1001** [comment]
Hi @DanielGoehler ,

well, it's actually already released, but it needs some documentation.  The feature will enable API deploy in an OnPrem database. Basically the same as what you would do in the cloud, but OnPrem: using the Automation API to deploy apps.  

You will need to install an WebAPI with powershell (a module on the powershell gallery) to make it work.

This will most probably be a free install, but with a very big disclaimer: your own risk / "as is" / without support, as this is a reverse engineered hack that is very dependent on what Microsoft will do (open/close/remove/add/change .. ) in the future.  

On the other hand - we've been proofing it in our company, and are ourselves quite relying on it ;-).

More soon!

**Comment by gintuoklis** [comment]
hey @waldo1001,
Isn't automation API officially supported? At least MS has documentation describing it: 
https://docs.microsoft.com/nl-nl/dynamics365/business-central/dev-itpro/administration/dynamics-microsoft-automation-overview

Or you use something else for extension deployment?

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

The Automation API is indeed officially supported, but cannot be used to deploy extensions Non-SaaS.
Please check https://github.com/Microsoft/AL/issues/2310#issuecomment-411465438

Kind regards,
