### ISSUE TITLE
ALOps App License Check throws error: "License File is corrupt. Error code: Unknown Error."

### ISSUE THREAD

**Issue by InnoNavSupport** [HodorNV/ALOps#567]
**Describe the bug**
When we try to use the newly added License Check task to check our built apps against our license, the task always runs into an error claiming the license file is corrupt.
We tried with locally stored and online hosted license files, but that didn't change the result.
We are trying to get it running without a docker container, because we also run the batch compile task without a container before trying to check the compile output against the license.

We approached you guys last week at the BC Tech Days explaining the problem, and you guys recommended us to install the Visual C++ Redistributable on our agent machine, but that also didn't fix the problem.

Do you have any other idea how to fix the error? Do we have to install a specific VC++ version, or any other dependency to get it running on our machine?

**the used yaml**
```yaml
- task: ALOpsAppLicenseCheck@1
    displayName: 'ALOps App License Check'
    inputs:
        licensefile: "$(Build.SourcesDirectory)/Licenses/LicenseFile.flf"
        artifact_path: $(Build.ArtifactStagingDirectory)
        artifact_exclude: "*-TEST*"
```

**the output**
```
...
"Get-BCArtifactUrl" 
Name                           Value                                                                                   
----                           -----                                                                                   
select                         Latest                                                                                  
type                           OnPrem                                                                                  
country                        W1                                                                                      


 -select: Latest -type: OnPrem -country: W1
*** Platform: C:\bcartifacts.cache\onprem\20.5.45456.45889\platform
*** Localisation: C:\bcartifacts.cache\onprem\20.5.45456.45889\w1
*** BC Management DLL: C:\bcartifacts.cache\onprem\20.5.45456.45889\platform\ServiceTier\program files\Microsoft Dynamics NAV\200\Service\Microsoft.Dynamics.Nav.Management.dll
*** BC App Management DLL: C:\bcartifacts.cache\onprem\20.5.45456.45889\platform\ServiceTier\program files\Microsoft Dynamics NAV\200\Service\Microsoft.Dynamics.Nav.Apps.Management.dll
*** BC NCL Management DLL: C:\bcartifacts.cache\onprem\20.5.45456.45889\platform\ServiceTier\program files\Microsoft Dynamics NAV\200\Service\Microsoft.Dynamics.Nav.Ncl.dll
*** BC Types DLL: C:\bcartifacts.cache\onprem\20.5.45456.45889\platform\ServiceTier\program files\Microsoft Dynamics NAV\200\Service\Microsoft.Dynamics.Nav.Types.dll
*** Load CodeAnalysis from [C:\bcartifacts.cache\onprem\20.5.45456.45889\platform\ServiceTier\program files\Microsoft Dynamics NAV\200\Service]
*** Get License: [C:\DevOps_Agent_01\_work\124\s/Licenses/LicenseFile.flf]
*** App License Check: [C:\DevOps_Agent_01\_work\124\a]
*** Resolved Path  : C:\DevOps_Agent_01\_work\124\a
*** Apps to process:

Name                                                         
----                                                         
onprem_19.2_ch_App.app



*** Setup NAV-License Delegate
*** Using 'Microsoft.Dynamics.Nav.Types.ObjectType' signature
*** Load License
##[error]Ausnahme beim Aufrufen von "Invoke" mit 2 Argument(en):  "Die Lizenzdatei ist beschädigt. Fehlercode: Unknown error."
Finishing: ALOps App License Check
```

**Comment by InnoNavSupport** [comment]
The Apps are built on version 19.2 and the license used is a BC 20 license downloaded less than a month ago.
Will try to download a new license file tomorrow and see if that changes anything.

**Comment by InnoNavSupport** [comment]
Tried it with a newly downloaded BC20 Partner License but still get the same error message.

**Comment by waldo1001** [comment]
Well - as I said - not much we can do about BC licensing 🤷‍♂️

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport ,

Could you please try our latest release v1.454.3354 ?
You can now feed a .bclicense file in the "licensefile" parameter. 
The BCLicense work in an entirely other way and doesn't involve tricky DLLs to work with.

Kind regards,

**Comment by InnoNavSupport** [comment]
Dear @AdminHodor ,
We just tested the function with the bclicense File. Seems to work better.
One of the MS Apps is throwing an error.
![image](https://user-images.githubusercontent.com/62563638/207871002-11c62783-3f95-45fa-b0dd-e8f3f1e4e027.png)

I was only able to use the LicenseFile with a URL and not with a Path.
Does the license file need to be uploaded manually to the docker?

**Comment by waldo1001** [comment]
Duplicate: #612
