### ISSUE TITLE
Mising SchemaSyncMode options when using ALOps Extension API as dev mode

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#569]
When using ALOps Extension API in Dev mode we need the option to overrule the SchemaUpdateMode 

![image](https://user-images.githubusercontent.com/28138717/192258008-ef40f774-899d-420a-9f4e-fe295cfff465.png)

Default is Synchronize which is fine just as we have the ability to overrule as we can in other AL task.  @AdminHodor

**Comment by AdminHodor** [comment]
Please check our latest release v1.453 for this feature.
