### ISSUE TITLE
Invalid JSON primitive

### ISSUE THREAD

**Issue by TomTaffin** [HodorNV/ALOps#57]
Hi guys,
I am having some issues with the compiler step while setting up a new pipeline.

Error: Invalid JSON primitive: .

Also when testing a pipeline that ran correctly before, the same error is raised.
Last successful run was 22/11/2019 (didn't run any pipelines since then).

Tested today on both BC13 and 15.

Any idea?

See details below:

> Starting: Compile Extension
==============================================================================
Task         : ALOps App Compiler
Description  : Compiles NAV Apps
Version      : 1.426.946
Author       : Hodor
Help         : Compile a Business Central extension from AL code.
==============================================================================
*** Validate configuration
*** Importing required PS-Functions
*** Initiate Docker Session
*** Setting up AL Compiler [4.0.194000]
*** Downloading AL Compiler [4.0.194000]
*** Get Extension from Local-Disk...[C:\Run\al-4.0.194000.vsix]
*** Resolving Path [C:\Run\al-4.0.194000.vsix]
*** VSIX Path Resolved: [C:\Run\al-4.0.194000.vsix]
*** Unpacking Extension to folder...
*** Using AL Compiler [v4.0.194000] located [C:\Run\Microsoft.al\al-4.0.194000\extension\bin\alc.exe]
***
> *** Working folder: C:\agent\_work\1\s
***
> *** Copy Working folder to Docker Container: 185f74f8d560e1aac890ca600dac14a09975e7b962ed0be53ed8af990fe68225
*** Docker Working Folder: c:\Run\DevOps\
*** Copy from [C:\agent\_work\1\s] to [c:\Run\DevOps\]
*** Compression Enabled Transfer
*** Compress Source Files
*** Transfer compressed Archive to session
*** Expand source files in target session
*** Source File setup completed
*** Target Project: \src\Connector\app.json
*** Check for app.json files: c:\Run\DevOps\
*** Multiple projects found:
   C:\Run\DevOps\src\Connector
   C:\Run\DevOps\src\Demo
*** Retrieving App-Info [\src\Connector\app.json]
  App.ID          = f15bbe6d-c2a3-4828-aa98-5a77cff4cd41
  App.Name        = Dime.Scheduler
  App.Publisher   = Dime
  App.Version     = 1.0.0.0
  App.Platform    = 15.0.0.0
  App.Application = 
***
> *** Match: yyyyWW
*** Setting Managed App Version [c:\Run\DevOps\src\Connector\app.json] =>  1.0.201949.17508
***
> *** Working Direcotry: [c:\Run\DevOps\]
*** Target Project: [\src\Connector\app.json]
*** Project Directory: [c:\Run\DevOps\src\Connector]
*** VSCode Settings: [c:\Run\DevOps\src\Connector\.vscode\settings.json]
*** VSCode-Settings json found.
*** No AL-RuleSet json found.
***
> ##[error]Invalid JSON primitive: .
Async Command Start: Add Build Tag
Build '17508' has following tags now: mcr.microsoft.com/businesscentral/sandbox-latest-ltsc2019, AL.Compiler.4.0.194000, BC.Platform.15.0.37865.38374, BC.Version.15.1.37881.38431
Async Command End: Add Build Tag

**Yaml:**
name: $(Build.BuildId)

pool:
  name: 'Dime Hosted'

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/onprem:13.9.33838.0-w1'
    docker_pull: true
    accept_image_outdated: true

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    usedocker: true
    license_path: 'C:\Licenses\DIME-BC-130.flf'

- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    failed_on_warnings: true 
    targetproject: src/Connector/app.json

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

- task: ALOpsAppRuntimePackage@1
  displayName: 'ALOps App Runtime Package'
  inputs:
    usedocker: true
    targetproject: src/Connector/app.json
    showmycode: False
    publish_artifact: True

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()

**Comment by AdminHodor** [comment]
Hello @TomTaffin ,

We did find a simulation scenario for this error on another project. Most likely the settings.json file contains 'special' characters (which are not always visible in VSCode).

Could you please check the settings.json with Notepad++ or similar to check for these characters.

Furthermore we made an improvement to ALOps for detecting JSON file with invalid characters. If the JSON load fails, the json will be printed to the pipeline together with the error message. This improvement is included from version v1.426.959.

Please let us know if this resolves the issue.

Kind regards,

Bart Bourgeois

**Comment by TomTaffin** [comment]
Hi @AdminHodor ,

That was indeed the issue!  Thanks a lot!

Tom
