### ISSUE TITLE
[FEATURE REQUEST] Remove internalsVisibleTo property from app.json

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#574]
**Is your feature request related to a problem? Please describe.**
When working with one app.json for the App/Project, it's not uncommon to have an 'internalsVisibleTo'-property enabled for the Test-App. We now ship the .app file with this 'internalsVisibleTo'-property still present. This could have unwanted effects and/or potentially a security issue.

**Describe the solution you'd like**
When compiling an App-file for shipping it would be great to have a property like 'internalsvisibleto' with the options 'Keep' or 'Remove'. When set to Remove, the property 'internalsVisibleTo' is removed from the app.json.

**Describe alternatives you've considered (A)**
The compile step is getting more-and-more feature flags specific for the app.json. Maybe a separate ALOps buildingblock to modify the app.json. In this way the compile step gets less cluttered with parameters.

**Describe alternatives you've considered (B)**
An ALOps-post-compile-buildingblock. I think this specific request could maybe also be achieved by directly editing the NavxManifest.xml in the .app file in case it's not a runtime package. This would be the fasted way to achieve this (with an additional sign-app step again afterwards).

**Comment by waldo1001** [comment]
Will be in next release!

**Comment by AdminHodor** [comment]
Please check our latest release v1.453 for this feature.

**Comment by Arthurvdv** [comment]
Works perfectly, thank you!
