### ISSUE TITLE
Not all parameters are available in the visual editor (problem for release pipelines)

### ISSUE THREAD

**Issue by jcoe-nvt** [HodorNV/ALOps#586]
**Describe the bug**
I want to create a sql backup in my release pipeline. This fails due to the unability to disable the publish.
In release pipeline, I can only use the visual editor and parameter 'publishsqlbackup' is hidden & set by default to true.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/49404625/202667754-9d223a99-66e3-44f1-9df5-909e88d85c57.png">

**the output**
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/49404625/202667648-41750673-440b-42b0-a50c-ab56fbfb42ff.png">

**Expected behavior**
All parameters should be avaible in the visual editor if you want to have same posibilities in release pipelines as in yml-files.

**Comment by AdminHodor** [comment]
@jcoe-nvt ,

We just released a hotfix for this, v1.453.3319. 
Could you validate? Please note it might take a couple of pipeline runs before DevOps will pickup the new version.

Kind regards,

**Comment by jcoe-nvt** [comment]
@AdminHodor I can confirm that I'm now able to set these parameters in the visual editor. Thx for the quick fix!
