### ISSUE TITLE
ALOPS Compile App Issue

### ISSUE THREAD

**Issue by titofffffff** [HodorNV/ALOps#59]
hello,

I try to build a pipeline on NAV2018 (container 'microsoft/dynamics-nav:2018-cu9-fr')

I used this task :
  - task: ALOpsAppCompiler@1
    displayName: 'ALOPS Compile App'
    inputs:
      usedocker: true
      targetproject: 'BaseExtension/app.json'
      nav_app_version: '$(AppVersion)'

here below the result : 
![image](https://user-images.githubusercontent.com/5903546/70655574-c4a3f280-1c58-11ea-87b3-a07d45b76fce.png)

It seems that there is an issue on argument used to run the compilation process

thanks in advance for your help !

**Comment by AdminHodor** [comment]
Dear @titofffffff ,

We removed "AssemblyProbingPath" and "Ruleset"  parameters from the ALC wrapper for NAV2018.
Currently we support BC v13/v14/v15, but we will make the effort finetuning and adjusting to make v11/v12 work. We made pushed the change via hotfix, so it's already available in the new release v1.426.968.

Kind regards,

Bart Bourgeois
