### ISSUE TITLE
ALOpsAdminCenterAPI?

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#597]
What is the **ALOpsAdminCenterAPI** and what can you do with it?

I saw issue #596 and only found **environment_list** as interaction here: https://github.com/HodorNV/ALOps/blob/master/Documentation/BuildSteps.md

**Comment by waldo1001** [comment]
Just FYI - we're re-doing documentation ... 

but in the meantim: in DevOps you get auto-completion.  You'll see that the "interaction" will have different methods you can call.
![image](https://user-images.githubusercontent.com/12088142/210391128-45e3c1aa-b5e9-4dd5-97ea-e11ffb11457e.png)

**Comment by DanielGoehler** [comment]
Thanks
