### ISSUE TITLE
<!DOCTYPE HTML PUBLIC - 503 Server unavailable error - ALOPS Release Deployment failed

### ISSUE THREAD

**Issue by jithendra415** [HodorNV/ALOps#598]
One of our customer's PROD environment release pipeline failed its first release.

Error:
##[error]Exception in BCConnector.GetAPIData:
##[error]Cannot find an overload for "GetExtensions" and the argument count: "1".
![image](https://user-images.githubusercontent.com/61264260/210301036-1ac507c1-2f0d-4995-acff-4d37b427e34f.png)

Question: I'm first time facing this DOCTYPE HTML error. May I know what causes the "<!DOCTYPE HTML Public" error come?
Or is this just server down or something?

What I checked from my end:

The servicetier for deployment/pipeline is running
The DeployUser user does exist in the BC installation
The DeployUser user does have the right License Type (in BC) - External User type
The Microsoft API app Exclude_APIV1 is installed
The API endpoint port has been added in the firewall of the environment where the BC installation resides
The ALOps External Deployer has been installed
The user account (DeployUser) credentials on the pipeline are right
The NST SSL certificate is installed
On the NST the API services have been enabled
Recreated by cloning the TEST release pipeline and the result is same.
More Information:
We got our TEST environment release pipeline deploying successfully.
We use O365 logins for web client.

**Comment by waldo1001** [comment]
You see the blue line - can you check if you can access that url from the build server?

**Comment by jithendra415** [comment]
Pipeline instance not running, after starting, we were able to connect to the URL. 
![image](https://user-images.githubusercontent.com/61264260/210846879-d357b54e-8932-436f-9656-ee89d05662d4.png)
I did a redeployment and now, I got an error which I can handle: 'App publish failed. Check the 'Extension Deployment Status' page in the BC'.
