### ISSUE TITLE
Support for -enableexternalrulesets in ALOpsCompile 

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#609]
**Is your feature request related to a problem? Please describe.**
With BC22 nearing, we would like to switch asap to moving our rulesets to a central repository / location, using the new externalrulesets feature. Can ALOps please be prepared to support this parameter when calling the ALC.exe in the ALOpsCompile step?

`This feature can be used from alc as well by including the -enableexternalrulesets argument.`

![RuleSet path1](https://user-images.githubusercontent.com/25268332/218331962-3d3c3365-e70a-4c54-bfad-6efef533072a.png)

![RuleSet path2](https://user-images.githubusercontent.com/25268332/218331960-48c5b8ff-30af-4d2c-bceb-3cf58127aa71.png)

PS: Above info is from the changelog of the latest insider vsix.

**Comment by fvet** [comment]
@waldo1001 @AdminHodor Will above be supported by the next ALOps release?

**Comment by AdminHodor** [comment]
Dear @fvet ,

Please try our latest release v1.455.3559 which should solve this. 

Kind regards,
