### ISSUE TITLE
Run custom script inside container to install powershell module

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#61]
In our build pipeline I have all my source code in the folder app
I have as an early step in my build pipeline that copies a nupkg and a script til app/EVBCDEV/

I need to be able to invoke the script: app/EVBCDEV/Offline Installation of EVBusinessCentralDevelopmentHelper.ps1

Is there a system variable inside Docker I can use to navigate to this folder as I would like to use the following step:

    - task: ALOpsDockerExec@1
      displayName: 'ALOps Docker Execute'
      inputs:
        scriptsource: InLine
        script_location:  'The folder I don't know inside Docker'
        inline_script: EVBusinessCentralDevelopmentHelper.ps1

**Comment by AdminHodor** [comment]
Hello @kasperdj ,

We updated the documentation to reflect the different possible uses of the ALOps Docker Execute step. 
[RunPowershellInContainer.yml](https://github.com/HodorNV/ALOps/blob/master/Examples/07_UseDocker_RunPowershellInContainer.yml)

The scriptsources are intended as follows:
- InLine: specify the script to run via the [inline_script] parameter
- Download: specify the Url of the script to run
- Workfolder: specify a ps1 file included in your repository, the path is relative to the root of the repository
- Path: specify a ps1 file located on the Docker/Agent host

Kind regards,

Bart Bourgeois

**Comment by kasperdj** [comment]
Hi @AdminHodor  

Thx. for updating the documentation.

I need to run the script inside docker and the script is already in my repo as I handled that in a previous step. So based on your feedback, I believe the setup should be:

- task: ALOpsDockerExec@1
  displayName: 'ALOPS Docker Exec: Install EVBusinessCentralDevelopmentHelper'
  inputs:
    scriptsource: 'Workfolder'
    script_location: '*/app/EVBCDEV/Offline Installation of EVBusinessCentralDevelopmentHelper.ps1'

This I will test shortly.

The second thing regarding this issue is that I need to call the Invoke-EVGenerateXliff (part of the EVBusinessCentralDevelopmentHelper that is installed) which require that I am placed in the app folder of my repo (in Docker) before running the script.
Is there a built-in variable I can use in Docker to get the root of my repo?

Thx. in advance
