### ISSUE TITLE
Q: How to handle NextMinor/Public Preview when insider token is expired?

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#616]
We have pipelines setup for NextMinor and this works as long as the Insider Token from Microsoft is not expired.

At the moment our Insider Key is expired and based on dialog with Microsoft on Yammer, they will not release new Insider Tokens until after april 1st. This means that I have an issue in this timeframe :-(

Is there a magic option in ALOps that can e.g. automatically use the "Public Preview" artifacts if the Insider Token is expired and if so, can you provide an sample pipeline to illustrate this?

Thx. in advance

**Comment by MortenRa** [comment]
Current insider key should not expire until 1 of april.  and an replacement key should be available two weeks before the token expire according to documentation on collaborate

**Comment by kasperdj** [comment]
My bad, current issue was actually related to the restructure of management dll's in insider builds (there is already another issue on this). We will close this case.
