### ISSUE TITLE
Could not load file or assembly ...

### ISSUE THREAD

**Issue by waldo1001** [HodorNV/ALOps#621]
We have a problem...

Long story short - MIcrosoft's extension validation has changed, which means that we cannot use the tools we have been using for +2 years to build our DevOps extension.

This resulted into a failed way to load assembly dependencies ...  in short: https://learn.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.3

It's a big problem which has taken us by surprise and microsoft doesn't allow us to deploy the previous build, because of the marketplace validation that has changed.. 

A combination of the validation process of the devops marketplace, 
plus the fact Microsoft messes up the dependency loading of the dlls (we found 4 different system.runtime-versions on the artifact itself .. ), 
plus the fact we need to be backwards compatible .. 

it's complex, which will take time.  But we're working on it .. .

We do know your builds are failing, and it's absolutely our priority to resolve the issue!

We sincerely apologize for this inconvenience.

**Comment by lvanvugt** [comment]
Thanx for the headsup @waldo1001. I can almost feel things rumbling over there. Good luck and crossing fingers, saying my prayers, etc. in support.

**Comment by Arthurvdv** [comment]
Thank you for sharing the insights on this issue.

**Comment by acjdekorte** [comment]
Thank you for informing us on the issues and challenges. Good luck with fixing it

**Comment by kasperdj** [comment]
We have also received the ALOps hotfix and confirm that pipelines running on BC19, 20 and 21 with Unit Tests are working again. Thx for the quick fix.

**Comment by lvanvugt** [comment]
Can also confirm: running again. bog THANX!

**Comment by acjdekorte** [comment]
Yes all pipeline (except for the testing on BC22) are working. Thanx

**Comment by Arthurvdv** [comment]
Can confirm, where back in business. Thanks!
