### ISSUE TITLE
Urgent: ALOpsAppTest@1 Failing - Unable to find type [AuthenticationScheme]

### ISSUE THREAD

**Issue by rppwolfs** [HodorNV/ALOps#622]
**Describe the bug**
Since 21-03-2023 - Around 4:26 PM CET, ALL our automated test case runs are failing and throwing error messages like

@waldo1001 @AdminHodor 

At C:\a\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:18 char:41
         $this.Initialize($serviceUrl, ([AuthenticationScheme]::AzureA ...
                                         ~~~~~~~~~~~~~~~~~~~~
Unable to find type [AuthenticationScheme].
Unable to find type [ServiceAddressProvider].
Unable to find type [ClientStaticStringControl].

We have not changed anything on our end; but we noticed that ALOps was updated several times yesterday

**the used yaml**

    - task: ALOpsAppTest@1
      timeoutInMinutes: 30
      inputs:
        usedocker: true
        testfilter: "50000..99999"
        import_testtoolkit: false
        failed_test_action: Error
        testpage: 90409
        companyname: AutoTest
        show_available_tests: true
        bc_username: $(ALOPS_DOCKER_ADMINUSER)
        bc_password: $(ALOPS_DOCKER_ADMINPASSWORD)
        bc_authentication: NavUserPassword
        nav_serverinstance: $(ALOPS_DOCKER_NAVSERVERINSTANCE)

And this one:
        
- task: ALOpsAppTest@1
      timeoutInMinutes: 30
      displayName: "Run TestSuite"
      inputs:
        usedocker: true
        testfilter: "(50000..70099|70301..99999)&<>53051"
        import_testtoolkit: false
        show_available_tests: true
        failed_test_action: Error
        testpage: 90409   

Added two pipeline log's

1. [ALOpsAppTest-Error-01.txt](https://github.com/HodorNV/ALOps/files/11037725/ALOpsAppTest-Error-01.txt)
2. [ALOpsAppTest-Error-02.txt](https://github.com/HodorNV/ALOps/files/11037729/ALOpsAppTest-Error-02.txt)

**Comment by fvet** [comment]
Same here


```
+                                         ~~~~~~~~~~~~~~~~~~~~
Unable to find type [AuthenticationScheme].

At F:\Build Agents\BUILD-SERVER 1_1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:30 char:41
+         $this.Initialize($serviceUrl, ([AuthenticationScheme]::UserNa ...
+                                         ~~~~~~~~~~~~~~~~~~~~
Unable to find type [AuthenticationScheme].

At F:\Build Agents\BUILD-SERVER 1_1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:34 char:41
+         $this.Initialize($serviceUrl, ([AuthenticationScheme]::Window ...
+                                         ~~~~~~~~~~~~~~~~~~~~
Unable to find type [AuthenticationScheme].

At F:\Build Agents\BUILD-SERVER 1_1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:38 char:41
+         $this.Initialize($serviceUrl, ([AuthenticationScheme]::Window ...
+                                         ~~~~~~~~~~~~~~~~~~~~
Unable to find type [AuthenticationScheme].

At F:\Build Agents\BUILD-SERVER 1_1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:41 char:39
+     Initialize([string] $serviceUrl, [AuthenticationScheme] $authenti ...
+                                       ~~~~~~~~~~~~~~~~~~~~
Unable to find type [AuthenticationScheme].

At F:\Build Agents\BUILD-SERVER 1_1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:43 char:29
+         $this.addressUri = [ServiceAddressProvider]::ServiceAddress($ ...
+                             ~~~~~~~~~~~~~~~~~~~~~~
Unable to find type [ServiceAddressProvider].

At F:\Build Agents\BUILD-SERVER 1_1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:163 char:82
+ ... edControls | Where-Object { $_ -is [ClientStaticStringControl] } | Se ...
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
Unable to find type [ClientStaticStringControl].

At F:\Build Agents\BUILD-SERVER 1_1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:169 char:88
+ ... edControls | Where-Object { $_ -is [ClientStaticStringControl] } | Se ...
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
Unable to find type [ClientStaticStringControl].

Not all parse errors were reported.  Correct the reported errors and try again.
Finishing: Run Testsuite Dynavision Advanced Pricing & Discounts-Test

```

**Comment by PeterConijn** [comment]
@waldo1001 Same here

```
##[error]At C:\ADO_agents\agent1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:18 char:41
+         $this.Initialize($serviceUrl, ([AuthenticationScheme]::AzureA ...
+                                         ~~~~~~~~~~~~~~~~~~~~
Unable to find type [AuthenticationScheme].

At C:\ADO_agents\agent1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:22 char:41
+         $this.Initialize($serviceUrl, ([AuthenticationScheme]::AzureA ...
+                                         ~~~~~~~~~~~~~~~~~~~~
Unable to find type [AuthenticationScheme].

At C:\ADO_agents\agent1\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.455.3529\ps_modules\BCAppTest\53c7cbc7-dd57-4695-b567-600120945e9b.ps1:26 char:41
+         $this.Initialize($serviceUrl, ([AuthenticationScheme]::UserNa ...

etc. etc. etc.
```

**Comment by kaspermoerch** [comment]
Also experiencing this issue.

**Comment by rppwolfs** [comment]
@waldo1001 / @AdminHodor: Is this related to the issue #621 ?

**Comment by NAVFreak** [comment]
Same here

**Comment by ninjaniels** [comment]
We are also experiencing this issue on pipelines that have been running error free for a long time

**Comment by AdminHodor** [comment]
Dear @kaspermoerch , @fvet , @NAVFreak , @ninjaniels , @PeterConijn,

We just released a hotfix (v1.455.3559) which should solve the Assembly-Reference issue in all tasks.
Please let us know if this release works for you.

Kind regards,

**Comment by ninjaniels** [comment]
Hotfix is working for us. Thank you for speedy action

**Comment by acjdekorte** [comment]
Hotfix is working for us as well. Thank you for your work

**Comment by rppwolfs** [comment]
Hi, 

Initial error message is gone; but we are now receiving this error on multiple builds (all with the same error message)

Show form {00016129-0000-0000-0108-0000836BD2D2}
Title: MV Test Tool Page Edit - Test Tool - DEFAULT
Apply filter for Test-Codeunits: [(50000..70099|70301..99999)&<>53051]
**##[error]Run-Test-Exception: Exception calling ".ctor" with "2" argument(s): "Value cannot be null.**
Parameter name: logicalControl"
*** Get XUnit Test file from [] to [C:\a\6\s\]
**##[error]Cannot bind argument to parameter 'Path' because it is null.**


@AdminHodor

**Comment by PeterConijn** [comment]
![image](https://user-images.githubusercontent.com/47315514/226911192-e80dd5af-94f2-4c86-8398-ca1dc5c7d02d.png)

**Comment by AdminHodor** [comment]
Dear @rppwolfs,

Fix for v14 is on its way, we will release a couple of hotfixes concerning the Test-Module.
We'll ping you about this as soon as this specific fix is online

Kind regards,

**Comment by AdminHodor** [comment]
Dear @rppwolfs ,

Please try our latest release v1.455.3571.

Kind regards,

**Comment by rppwolfs** [comment]
> Dear @rppwolfs ,
> 
> Please try our latest release v1.455.3571.
> 
> Kind regards,

@AdminHodor: Just tested the latest version (v1.455.3571) and i it is working for our generic builds; **but not for the extensions** we create.  We are investigating if we can find out what is happening there. Seems like way more test cases are running for every extension as before.

**Comment by rppwolfs** [comment]
> > Dear @rppwolfs ,
> > Please try our latest release v1.455.3571.
> > Kind regards,
> 
> @AdminHodor: Just tested the latest version (v1.455.3571) and i it is working for our generic builds; **but not for the extensions** we create. We are investigating if we can find out what is happening there. Seems like way more test cases are running for every extension as before.

Checked the issue and it seems like the testfilter (50000..70099|70301..99999)&<>53051 is not validated.
It is running test cases like 53051 / 70202 / 70280 etc **which are not in the range set in the testfilter**; but it is as well not running the test cases 54763, 54775, 54810, 54812, 54853, 59343 which were running before.

i added the logs of both 


[Run-TestSuite - Current - ERR.txt](https://github.com/HodorNV/ALOps/files/11049960/Run-TestSuite.-.Current.-.ERR.txt)
[Run-TestSuite - Previous - OK.txt](https://github.com/HodorNV/ALOps/files/11049961/Run-TestSuite.-.Previous.-.OK.txt)



@AdminHodor / @waldo1001

**Comment by AdminHodor** [comment]
Dear @rppwolfs,

Thanks for detailed description, we managed to replicate the issue based on this.
Could you try again with v1.455.3577 ? The test should run exactly as before.

Kind regards,

**Comment by rppwolfs** [comment]
> Dear @rppwolfs,
> 
> Thanks for detailed description, we managed to replicate the issue based on this. Could you try again with v1.455.3577 ? The test should run exactly as before.
> 
> Kind regards,

Hi, we just tested it (ran a few builds) and everything seems to be back to normal
Thanks for the solution / fix.

**Comment by rppwolfs** [comment]
Issue can be closed - it's solved.
