### ISSUE TITLE
Qst: Connect to container and do manual troubleshooting/debugging

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#627]
Just a question top of my mind. I have the scenario where the tests fail in my pipeline but works like a charm on my local docker.

I have tried to make sure I have the same app files and BC artifact on both but still error.
Is it possible to skip the cleaning and then connect to the container manually on the server and do debugging?
![image](https://user-images.githubusercontent.com/34970096/229801684-bb6921f4-e574-4b24-8842-8f8adaa1bf4d.png)

I tried with a simple test but that didn't seem to work so either it doesn't work or I need to tweak it a bit.
![image](https://user-images.githubusercontent.com/34970096/229801969-a4487f4b-fa52-4db1-a273-165638457fc9.png)

**Comment by waldo1001** [comment]
Should work - I have done this countless of times.  Can you check the container logs?

What is also possible: in the remove-step, you can save the sql-db as an artifact.  You could download that, and set up a local container?
