### ISSUE TITLE
Add Parameter "Schedule" to ALOps Extension API

### ISSUE THREAD

**Issue by innonav-dev** [HodorNV/ALOps#635]
I would like to provide an Update on an App installed, e.g. after Microsoft has updated the major/minor version.
For this reason in the Microsoft API the Parameter "schedule" exist and it would be great to use it through ALOps too.
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/resources/dynamics_extensionupload

Thanks
Daniel

**Comment by elgitto** [comment]
I was just looking for this :)
So you have my support for this feature!

**Comment by waldo1001** [comment]
Looks like a great suggestion - I'll talk to the dev team!

**Comment by waldo1001** [comment]
On the roadmap!

**Comment by INNONAV** [comment]
Perfect thanks

**Comment by Softvaerket-DED** [comment]
Hi @waldo1001 

We currently have an issue with a extension (PTE) for BC v24 vs v23, where a `schedule: "Next major version"` option would fix the issue when we upload and deploy extensions to ~150 customers on mixed BC releases.

Our problem is:
- Release the extension now will break v23.x customers.
- Release when all customers has been upgraded to v24, will break customers until the extension is release.

I can see this feature is on the roadmap for an upcoming release, do you know if this is prioritized or planned for release in the near future?

**Comment by metda11** [comment]
Hi @waldo1001,
I hope you're doing well! I was wondering if there are any updates on when we can expect this to be released?
Thank you in advance!

**Comment by waldo1001** [comment]
Damn - that's a misunderstanding - please don't close issues.
Back on the roadmap...

**Comment by waldo1001** [comment]
Released in v1.467.6362

Schedule options is an auto-complete:
- "current"
- "nextminor"
- "nextmajor"

**Comment by thomari** [comment]
@waldo1001
Could you please check this one again? Seems like changing the parameter to nextmajor doesn't change anything. It is still publishing with schedule "Immediate".

Pipeline:
![image](https://github.com/user-attachments/assets/19466de0-7c34-4f18-ad0f-768f765d96ae)
![image](https://github.com/user-attachments/assets/9ae57cfa-9b52-460d-a25b-821a5088facb)

BC:
![image](https://github.com/user-attachments/assets/0de46d92-6435-4682-924a-35a14f7f29fd)

**Comment by waldo1001** [comment]
We should have mantioned, so we just added to documentation: you need to use apiversion: v2.0

**Comment by innonav-dev** [comment]
Works like expected after changing apiversion to v2.0. Thank you!
