### ISSUE TITLE
How to limit number build tags?

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#640]
We just started using ALOps, and I'm a little overwhelmed by the number of tags ALOps assigns to the build.

Is there a way to limit which tags to use and which to exclude?

**Comment by waldo1001** [comment]
There is no way to limit the tags, I'm afraid.  There are actually quite some people that use them in their pipelines in various ways.. (from APIs, for filtering deployments, .. ).

**Comment by waldo1001** [comment]
We'll create a global to `alops_disable_buildtags`.  Would that work for you?
