### ISSUE TITLE
How to get the Application and System symbol apps for v14

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#642]
When we use the ALOps v.2 compiler with version 22, then we automatically get the application and system apps from bcartifacts.cache.
But that does not work in v14, as the symbol apps are not in the bcartifacts.cache folders (except the system.app in the AL Development Folder).

So, do you have a smart way to get the symbol files, when we have no container to download it from?

**Comment by waldo1001** [comment]
Two options from the top of my head:
- You can make them available just before compile: just download them from a central place (blob storage?), or make them part of the repo, or ...
- Use CompilerV1 with Docker
