### ISSUE TITLE
ALOps App Publish task does not have option to deploy apps to SaaS instance of Business central.

### ISSUE THREAD

**Issue by vimannem** [HodorNV/ALOps#644]
when we tried to use 'ALOps App Publish' task to publish app to Business central SaaS, we are not sure what value to fill under ' nav_serverinstance:' as it looks like it's only for server instance.

Please help us with the options available for SaaS version of Business Central or if there is a different task we need to use.

**Comment by waldo1001** [comment]
Hi, for SaaS, you need to automation API, which is wrapped under the task "ALOps Automation API".

More info here: https://docs.alops.be/ALOpsSteps/Buildstepsv1/#alops_extension_api

Please let me know if you need more help!

**Comment by DhasaPrak** [comment]
![MicrosoftTeams-image](https://github.com/HodorNV/ALOps/assets/135129729/61f40a3c-bb5f-4e05-8e3b-69239a329d31)
We worked on the pipeline based on your inputs and used the “AlOps extension API” task. But unfortunately we ran into the errors  “RequestDataInvalid” and “Can’t find the overload for GetExtensions”. I have attached the screenshot of same. Can you please help us through?

**Comment by waldo1001** [comment]
I anwsered @DhasaPrak in this issue: https://github.com/HodorNV/ALOps/issues/646

**Comment by waldo1001** [comment]
@vimannem , do you need more help?

**Comment by DhasaPrak** [comment]
![image](https://github.com/HodorNV/ALOps/assets/135129729/1eaf835e-8673-4afa-9e7c-cd4f6c3df6a8)
Tried as you suggested I replaced "sandbox" with "dev" in the url. Now getting the error as bad request.
Can you please help?

**Comment by waldo1001** [comment]
I'll close this issue as I get no feedback from @vimannem .  If you have more info, feedback, issues, feel free to reopen the issue.
