### ISSUE TITLE
Getting errors while using "ALOps Extension API" task for business central saas applications

### ISSUE THREAD

**Issue by DhasaPrak** [HodorNV/ALOps#646]
We worked on the pipeline based on your inputs and used the “AlOps extension API” task. But unfortunately we ran into the errors “RequestDataInvalid” and “Can’t find the overload for GetExtensions”. I have attached the screenshot of same. Can you please help us through?
![MicrosoftTeams-image](https://github.com/HodorNV/ALOps/assets/135129729/3cbffb19-bea0-4f37-9402-8fe5e72541ea)

**Comment by waldo1001** [comment]
Hi, please provide yaml and full output, as requested when you create a new issue.. .

**Comment by DhasaPrak** [comment]
![MicrosoftTeams-image](https://github.com/HodorNV/ALOps/assets/135129729/8fd96c82-6b4a-4f9e-9fb5-fabb880867d1)
![MicrosoftTeams-image (2)](https://github.com/HodorNV/ALOps/assets/135129729/bbdc6ea2-3fb7-4610-81e8-b121e44cc399)

Hi, I have attached the full yaml code and the errors.

**Comment by waldo1001** [comment]
Seems your error is here:
![image](https://github.com/HodorNV/ALOps/assets/12088142/785432dd-27f4-4f86-a00b-4d889bcca8df)

it's clearly a wrong url with the "$(guid)" into it.
i see the same url in your yaml ..
![image](https://github.com/HodorNV/ALOps/assets/12088142/63dcb834-e22a-4832-b211-08bcdbdbe35f)

and .. please remove your screenshot with your secrets (always hide your secrets - it's best for you to now create a new secret ;-)).

**Comment by waldo1001** [comment]
also your dev-endpoint seems wrong:
![image](https://github.com/HodorNV/ALOps/assets/12088142/2f9a3369-7929-4c62-9dd0-002d8e6f099e)

since you supplied one - it will probably use the dev endpoint, and I'd expect "Sandbox" to be in it as well?

**Comment by DhasaPrak** [comment]
> also your dev-endpoint seems wrong: ![image](https://user-images.githubusercontent.com/12088142/243749227-2f9a3369-7929-4c62-9dd0-002d8e6f099e.png)
> 
> since you supplied one - it will probably use the dev endpoint, and I'd expect "Sandbox" to be in it as well?

But the URL displayed in business central admin center is: https://businesscentral.dynamics.com/e57ba7a8-7c87-455f-801f-bd284fe3c0eb/dev
How to add Sandbox in it?

**Comment by DhasaPrak** [comment]
> Seems your error is here: ![image](https://user-images.githubusercontent.com/12088142/243748664-785432dd-27f4-4f86-a00b-4d889bcca8df.png)
> 
> it's clearly a wrong url with the "$(guid)" into it. i see the same url in your yaml .. ![image](https://user-images.githubusercontent.com/12088142/243748891-63dcb834-e22a-4832-b211-08bcdbdbe35f.png)
> 
> and .. please remove your screenshot with your secrets (always hide your secrets - it's best for you to now create a new secret ;-)).

![image](https://github.com/HodorNV/ALOps/assets/135129729/d7049e8f-72d6-4cbe-8a85-559f8025f6bf)

As suggested I removed the $() from the url and now I'm getting the error that "environment doesn't exist". Please help me

**Comment by waldo1001** [comment]
Well - what environments do exist?

**Comment by DhasaPrak** [comment]
![image](https://github.com/HodorNV/ALOps/assets/135129729/94790a2d-4b1c-47ca-bd79-0a2c865b86f8)

These are the two available environments and I have used dev in the code.

**Comment by waldo1001** [comment]
In your URL, you have "Sandbox" as environment.  That doesn't exist.. .  Only "dev" and "Production" exists.

So .. replace "Sandbox" with "dev" or "Production" accordingly ..

**Comment by DhasaPrak** [comment]
![image](https://github.com/HodorNV/ALOps/assets/135129729/88f74220-7fad-47e1-ab7f-5a7e1087c5a3)

Tried as you suggested. Now getting the error as bad request. 
Can you please help?

**Comment by DhasaPrak** [comment]
![image](https://github.com/HodorNV/ALOps/assets/135129729/34705876-a11e-444e-9c6e-42f4d57e6402)

Please help me with this.

**Comment by waldo1001** [comment]
Dear @DhasaPrak ,

I have helped as much as I can.  If it doesn't work, you haven't done the setup correctly.

You can try all over by setting up the S2S authentication by following this blogpost:
https://www.kauffmann.nl/2020/09/14/service-to-service-authentication-for-automation-apis-in-business-central/

Then use those tenanid, clientid and clientsecret with the ALOpsExtensionAPI.

Furthermore, if that doesn't work - send me the full yaml and output in text, like I have requested before.. and also as requested when creating a new issue.

**Comment by waldo1001** [comment]
@DhasaPrak  ?

You can also mail the details to admin@hodor.be .
