### ISSUE TITLE
Can I specify "locale" when creating a new container?

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#655]
I'm trying to import text objects into an ALOps container, but it fails with: _'31-05-19;' is not a valid date._

Previously I have created the containers using my own script (using BCCH), where I were able to specify locale="da-DK".

Is there a way to specify this using ALOps?

**Comment by waldo1001** [comment]
Hey @epernst ,

you can use the ´docker_parameters´ to specify what you want!  probably very much the same as you did with BCCH (can you share that script?)

Here are some examples:
- https://github.com/HodorNV/ALOps/blob/9bb4c79c486c91d3f1f3ecba36cbc4a324a7f86a/Examples/23_UseDocker_AdditionalParams.yml#L23
- https://github.com/HodorNV/ALOps/blob/9bb4c79c486c91d3f1f3ecba36cbc4a324a7f86a/Examples/01_DefaultBuild_IncludingTestability.yml#L29
- https://github.com/HodorNV/ALOps/blob/9bb4c79c486c91d3f1f3ecba36cbc4a324a7f86a/Examples/Without%20Artifacts/12_UseDocker_RestoreSQLBackup.yml#L30
- https://github.com/HodorNV/ALOps/blob/9bb4c79c486c91d3f1f3ecba36cbc4a324a7f86a/Examples/12_UseDocker_RestoreSQLBackup.yml#L30

**Comment by epernst** [comment]
Today it's a regular parameter to new-bccontainer. But I've checked in "nav-docker", at it looks like I can specify $env:locale to do the same thing via the docker-parameters. Will try that! :)

**Comment by epernst** [comment]
Worked as expected! Thanks.
