### ISSUE TITLE
Issue AlOps APP Publish Test Tools

### ISSUE THREAD

**Issue by titofffffff** [HodorNV/ALOps#66]
hello,

I have an issue with AlOps App Publish with Container mcr.microsoft.com/businesscentral/onprem

My yaml 

    - task: ALOpsAppPublish@1
       displayName: 'ALOps Install AL TestTool'
       inputs:
         usedocker: true
         installaltesttool: true
         skip_verification: true
         install_al_app_names: |
           Tests-TestLibraries
           System Application Test
           System Application Test Library
           Any
           Library Assert
           Test Runner

here below the result : 
![image](https://user-images.githubusercontent.com/5903546/72443908-60240800-37af-11ea-85db-bebbd8d58bf7.png)

I tried to change the test library to install using the following yaml

    - task: ALOpsAppPublish@1
      displayName: 'ALOps Install AL TestTool'
      inputs:
        usedocker: true
        installaltesttool: true
        skip_verification: true
        install_al_app_names: Library Assert

the result is the same :
![image](https://user-images.githubusercontent.com/5903546/72444856-0d4b5000-37b1-11ea-9cba-b098ba82522c.png)

Thank in advance for your help !

**Comment by waldo1001** [comment]
@titofffffff , Ah, did you find a solution?

**Comment by titofffffff** [comment]
@waldo1001 : Yes, I stopped to try to build my process on Windows 10 :)
Now It works !
