### ISSUE TITLE
[Feature Request] Replace ShowMyCode flag in ALOps App Runtime Package with Resource Exposure Flags

### ISSUE THREAD

**Issue by PeterConijn** [HodorNV/ALOps#664]
**Is your feature request related to a problem? Please describe.**
I was working runtime packages into my release build pipelines when I noticed that the MS-documentation ([source](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages)) said that the allowDebugging flag is set to false by default. 

When trying to set this to true in the configuration, I only saw ShowMyCode, which is the old style feature. Now I do not know how this relates to the resource exposure policy and what this sets to true or false, but I am not certain what to do with this setting now.

**Describe the solution you'd like**
I would like the resource exposure policy flags to be added to the ALOps App Runtime Package

**Describe alternatives you've considered**
I don't really have an alternative, but I would like to know how ShowMyCode interacts with the resource exposure policy.

**Additional context**
See image for clarification on what I mean.

![image](https://github.com/HodorNV/ALOps/assets/47315514/f038c46f-5220-4e4e-beb7-74fdce1312d6)

Edit: uploaded correct image

**Comment by waldo1001** [comment]
Hi,

this is the docs we can find:
https://learn.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappruntimepackage?view=businesscentral-ps-22#-showmycode

If you want to change Resource Exposure Policy, you need to do that at compile time.

**Comment by PeterConijn** [comment]
Thanks! 
We already do that, but does that mean that the ShowMyCode field in the ALOps Runtime Package job has no influence if my app uses the resource exposure policy at compile time?

**Comment by waldo1001** [comment]
Well - all we are able to do is using the switch that Microsoft has created:

![image](https://github.com/HodorNV/ALOps/assets/12088142/275be70b-bc97-4689-a3e5-cfa2bdd7974d)

**Comment by PeterConijn** [comment]
That makes sense. Thanks Waldo! We'll just see what happens for now. Closing issue.
