### ISSUE TITLE
[FEATURE REQUEST] Verify Publisher name

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#667]
**Is your feature request related to a problem? Please describe.**
We're in the process of migration to a new Publisher name for all our Apps. It would be helpful to have an automated validation on the (new) Publisher name on the app.json with every pull-request on with Azure DevOps pipelines.

**Describe the solution you'd like**
Is it feasible to have a setting on one the ALOps building blocks to throw an warning/error when there's a mismatch on the Publisher name in the app.json file. A generic way could be to specify a list of allowed Publisher name values on the ALOpsAppCompiler step.

**Describe alternatives you've considered**
An other way to approach this is could be to hand over setting the Publisher name the same way as the versioning of the app.json with the ```appversiontemplate``` setting of the ALOpsAppCompiler step.

Last resort would be to write some PowerShell to throw an warning/error on a not compliant Publisher name.

**Comment by waldo1001** [comment]
Makes sense.

We're thinking about an "AllowedPublisherNames" parameter .. that will check during compile-time?

**Comment by Arthurvdv** [comment]
Sound perfect!

Tricky part could be the separator for the list? Could it be that the publisher name has a comma (,) in the name. Or in our case we have a pipe symbol (|) in our publisher name 🫠

**Comment by waldo1001** [comment]
Will be available in next version.

**Comment by AdminHodor** [comment]
Dear @Arthurvdv ,

Please try our latest release v1.459.
We added two parameters
  - allowed_publisher_names:  here you can place the list of Allowed Publishers (exact matches)
  -  allowed_publisher_names_separator: defaults to "," (comma) can be changed if required
Please not a do case-insensitive exact-matches.

Kind regards

**Comment by Arthurvdv** [comment]
Works perfectly, thank you!
