### ISSUE TITLE
Error during connect: Get docker engine

### ISSUE THREAD

**Issue by JeppeBylov** [HodorNV/ALOps#67]
Hi,

I'm testing ALOps with a Hello World application, using one of your example build templates.
The job fails when running ALOpsDockerStart, with following error: 
##[error]error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json?all=1&filters=%7B%22label%22%3A%7B%22TFSBuild%3DBuild+Pipeline_10%22%3Atrue%7D%7D: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Docker is installed and everything when fint when configuring the agent. So i figured it must be some sort of permissions error. I then tried to use my own account and not NETWORK SERVICE, and suddenly the job started running.

Can you identify the missing permission?
![Docker](https://user-images.githubusercontent.com/968411/72593854-53fe8e80-3906-11ea-8aa8-c8d461024e5f.png)

**Comment by waldo1001** [comment]
Hi Jeppe,

It seems you're not running on Windows 10, that's good!  You need indeed admin permissions to do anything with Docker.  We also learne d that the network service account doesn't work decently.$

In my introduction on ALOps, I also showed that we are usually setting up the devops agents (which honestly should be a dedicated server without anything but Docker - not even in a domain - which can be set up fairly easy and fast), where I always run the agent with a "localsystem" account:
https://youtu.be/iVLOerdCuwA?t=2332

**Comment by JeppeBylov** [comment]
Hi Waldo,

Alright. I watched the introduction, but was interrupted a few times, maybe this minute was one of those times.
I'll use a local admin user from now on. I just wanted to know if this was a common issue.

Loving the product already.
