### ISSUE TITLE
Creating container and test with v14: Symbol generation

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#676]
I am in the process of changing our build pipelines from using our own Powershell modules together with BcContainerHelper, to be using ALops. While this works great with our v22 repositories, then I'm not as impressed.
Whenever we build a new container for testing, we use our own database, containing our custom test data and all objects from Microsoft, including tests and 2 C/Side based ISV solutions and all our AL extensions. 

When we publish any apps depending on custom C/Side fields or functions, then it says the fields/functions does not exist.
We can make the error go ways if we perform a full regeneration of all symbols, but that takes 9-10 minutes extra build time to do it.
When we were using our own scripts with BcCH, we didn't need that step. Here it was enough if we published the Application symbols created, when we created the database. I have tried the same with ALOps, but here it does not work.

We have of course enabled symbol generation in the container.

Do you have any experience with ALOps, BC v14 and handling C/Side symbols? Are we doing something wrong or is this just the way it is? Or do you have any suggestions how to do this better?

**Comment by waldo1001** [comment]
As you know, I have no experience working with this: not with hybrid, nor with codecustomized baseapp.  This is a mix of both.

I'll talk this through with my dev team tomorrow, who have more experience in the matter.

**Comment by waldo1001** [comment]
Have you considered to create a database with the C/AL-part prebuilt (including symbols) and use that in the creation of the container.
