### ISSUE TITLE
License check: Output warning as a variable

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#683]
Thank you for that new Warning_Only option.

Could I also ask that you output the warning message i.e. Group_Test Libraries_0.1.0.141969_onprem_22.2_w1.app is fully unlicensed (3 objects) as a DevOps variable?

This way we can caption the warning and post it directly to the pull request for a more visible place, where the developer has to acknowledge the problem and resolve it. :)

**Comment by waldo1001** [comment]
We'll try.

**Comment by AdminHodor** [comment]
Dear @epernst ,

Please check our latest release v1.461. We added the environment variable "ALOPS_CHECKLICENSE_OUTPUT" which contains all warnings from the ALOpsCheckLicense step.

Kind regards,
