### ISSUE TITLE
Use the ALLanguage from marketplace

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#684]
**Is your feature request related to a problem? Please describe.**
We would like to use the BCLinter cop. But it won't work when running any different version than latest.
I have discussed this with [Arthur](https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/309). The reason for this seems to be that you use the vsix for ALLanguage from the artifact instead of the latest from marketplace.

**Describe the solution you'd like**
Isn't the ALLanguage backward compatible? In that case in theory it should be possible to always download it and use it for later compilation. BUT I know you don't want to break anything so perhaps a parameter instead that you can choose if you want vsix from marketplace or artifact.

**Comment by waldo1001** [comment]
In the compiler, you can set the vsix to latest - and use lintercop ;-).
Arthur was part of this - so he should know.  

So now I'm confused...

More info:
- https://docs.alops.be/ALOpsSteps/Buildstepsv2/#alops_app_compiler
- https://github.com/HodorNV/ALOps/blob/master/Examples/Compiler%20V2/07_CustomVisx.yml
- https://github.com/HodorNV/ALOps/blob/master/Examples/Compiler%20V2/09_CustomCodeCops.yml

Latest is example of Stefan Maron's CodeCop!

The version-limitation is Microsoft's "limitation"

**Comment by Arthurvdv** [comment]
You're absolutely right @waldo1001. I didn't realize that @NAVFreak is also a ALOps customer, otherwise I could have done a better job of support on the LinterCop issue. I'm quite sure that this issue can be closed, right @NAVFreak ?

**Comment by waldo1001** [comment]
uff :-).

Let's close it when his problem is solved ;-)

**Comment by NAVFreak** [comment]
My bad guys! Next time I will try to "rtfm" 😊
It works like charm now.

**Comment by waldo1001** [comment]
awesome :-)

If anything is unclear in the docs, let me know!
