### ISSUE TITLE
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified

### ISSUE THREAD

**Issue by jpreniers** [HodorNV/ALOps#688]
We have set-up 2 extra build servers and now on both new servers we get the following error message: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified
The complete raw log is attached. Do you have any idea why this error occurred? All specs on the other servers are the same as on the new server.

[CreateDockerFailed.txt](https://github.com/HodorNV/ALOps/files/13024702/CreateDockerFailed.txt)

**Comment by waldo1001** [comment]
Can you try to upgrade BCContainerHelper to v6 on those servers?

**Comment by jpreniers** [comment]
We started with v6 but then we've got the same error. See attached log
[CreateDockerFailedV6.txt](https://github.com/HodorNV/ALOps/files/12915789/CreateDockerFailedV6.txt)

**Comment by waldo1001** [comment]
Hm.  It's probably something on your system, as it's a very simply pipeline.
Also: it's all BCCH - creating the image.

Few things to try:
- Set forcecreateimage to "true" on the ask
- `Docker system prune  --all` (clean up docker) on the agents
- run ALOpsAppMaintance task

**Comment by jpreniers** [comment]
Hi, we just fix this issue by adding on the server:
[Environment]::SetEnvironmentVariable("Path", [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) + ";C:\Program Files\Docker", [EnvironmentVariableTarget]::Machine)

**Comment by waldo1001** [comment]
Path to docker - good one!  Thanks!
