### ISSUE TITLE
ALOpsLicenseCheck - Why are pages not checked?

### ISSUE THREAD

**Issue by Athystrup** [HodorNV/ALOps#691]
Hi 

I am looking at the ALOpsAppLicenseCheck and as far as I understand the license is only checked for TableData, Report, Codeunit, XMLPort and Query objects. I was wondering why Page objects seem to be left out of the license check?

**Comment by epernst** [comment]
Same issue here. Just found out that pages are not checked. :(

**Comment by waldo1001** [comment]
We also found the reason for that.  "page" are not called "pages" in the licensing component 🙈.

**Comment by AdminHodor** [comment]
Dear @Athystrup , @epernst,

Please check our latest release v1.461, Pages are now checked against the license.

Kind regards,

**Comment by Athystrup** [comment]
@AdminHodor @waldo1001 Thanks, that is great news! Quick question: How does "Exclude Range" work with new version? Say that I want to exclude Page 50000, if I set the exclude range to 50000..50000 all objects in that range will be excluded as I understand. Is this by design?

**Comment by AdminHodor** [comment]
Dear @Athystrup ,

The "Exclude Ranges" works exactly as before, no change has made on this part. The exclude range is for an entire Number-Range, over all object types. This is indeed by design, for example to exclude some 3rd party Apps, or temp/buffer tables.
What is the reason you would want to exclude a single page? 

Kind regards,

**Comment by Athystrup** [comment]
I am not sure that it will be an issue, but the scenario I had in mind is that we have some ISV apps, which contains extra objects available for additional purchase. Let's say these objects consists of a Page with ID 100000 and a Table with ID 200000. If other objects in that extensions uses the same ID, then we might have a problem as these would be filtered out. 

I'll close this issue as the problem has been resolved, and I don't think the above-mentioned issue is realistic.
