### ISSUE TITLE
##[error]Application manifest [c:\Run\DevOps\app.json] not found.

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#7]
Any Idea was this error arise? Is this because of the multiple app as the app.json is in the \app folder

Starting: ALOpsAppCompiler |  
-- | --
  | ============================================================================== |  
  | Task         : ALOps App Compiler |  
  | Description  : Compiles NAV Apps |  
  | Version      : 1.420.318 |  
  | Author       : Hodor |  
  | Help         : Compile a Business Central extension from AL code. |  
  | ============================================================================== |  
  | *** Validate configuration |  
  | *** Importing required PS-Functions |  
  | *** Setting up AL Compiler [3.0.124247] |  
  | *** Downloading AL Compiler [3.0.124247] |  
  | *** Get Extension from Local-Disk...[C:\Run\al-3.0.124247.vsix] |  
  | *** Unpacking Extension to folder... |  
  | *** Using AL Compiler [v3.0.124247] located [c:\Run\Microsoft.al\al-3.0.124247\extension\bin\alc.exe] |  
  | *** |  
  | *** Working folder: C:\Agent\_work\11\s |  
  | *** |  
  | *** Copy Working folder to Docker Container: 63e9e37a5cb5e5eb1f4ef6bbcd4edcf887bb22a612d9a7ea6b4767edfc463de1 |  
  | *** Docker Working Folder: c:\Run\DevOps\ |  
  | *** Copy from [C:\Agent\_work\11\s] to [c:\Run\DevOps\] |  
  | *** Compression Enabled Transfer |  
  | *** Compress Source Files |  
  | *** Transfer compressed Archive to session |  
  | *** Expand source files in target session |  
  | *** Source File setup completed |  
  | *** Target Project: \app.json |  
  | *** Check for app.json files: c:\Run\DevOps\ |  
  | *** Multiple projects found: |  
  | - C:\Run\DevOps\app |  
  | - C:\Run\DevOps\test |  
  | *** Retrieving App-Info [\app.json] |  
  | *** Match: yyyyWW |  
  | *** Setting Managed App Version =>  2.629.201925.133 |  
  | ##[error]Application manifest [c:\Run\DevOps\app.json] not found. |  
  | Async Command Start: Add Build Tag |  
  | Build '133' has following tags now: mcr.microsoft.com/businesscentral/sandbox-ltsc2019, BC.Platform.14.0.32600.0, BC.Version.14.1.32615.0, AL.Compiler.3.0.124247 |  
  | Async Command End: Add Build Tag |  
  | Finishing: ALOpsAppCompiler

**Comment by waldo1001** [comment]
It most probably is.  You have to point to the subfolder.  Here is an example:
https://dev.azure.com/msdyn365bc/WaldoDevOpsDemos/_git/HelloWorld%20(Freddy)?path=%2F.devops%2Fazure-pipelines.yml&version=GBmaster

and here is an example of such a compile-step:
![image](https://user-images.githubusercontent.com/12088142/59672123-35dd7e00-91bf-11e9-91f7-72897f929e88.png)

hope that helps :-)

**Comment by MortenRa** [comment]
Yep worked
