### ISSUE TITLE
Question: How to use Batch Publish with App Filter to avoid deploying Unit Test

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#702]
I have a build pipeline that generates 2 apps: 

- The Main App
- The Test App

If I setup a Release Pipeline to deploy to an online environment, then I encounter some limitations I would like to get your input on.

I only want to deploy the "Main App" to the online environment and this can acomplished using the "ALOps Extension API" by setting the following properties:

- API Interaction = Publish
- App filter = *_APP.app

This works when I only have only have **one set of artifacts**.

In other release pipeline I have a scenario where I need to include multiple articts from different build pipelines (one per app) and deploy all of these to the same online environment. In this case I have the "API Interaction" set to "Batch Publish" which works if I have no Unit Tests! If I have Unit Tests in my projects it will also try to deploy the Unit Test apps as well, which I would like to avoid as this will always fail.  When "Batch Publish" is being used, the parameter for "App filter" is not available :-(

Please suggest how to change my setup

**Comment by kasperdj** [comment]
Status?

**Comment by waldo1001** [comment]
What we do, is add one default DevOps step "Delete files" to delete whatever files we don't want to publish.

Example:

![image](https://github.com/HodorNV/ALOps/assets/12088142/323194e3-96cd-49c9-b265-8842a907a81b)

![image](https://github.com/HodorNV/ALOps/assets/12088142/b0314455-cb75-4242-bedd-6a8cd6ccd10f)

Or with PowerShell:
![image](https://github.com/HodorNV/ALOps/assets/12088142/0b0545a7-441c-4294-abbc-eb26488608b8)



The "AppFilter" has been on the list.  Thing is it's a rabbit hole to combine with all the other parameter-combo's .. hard to explain :(.

**Comment by kasperdj** [comment]
I will go for the powershell approach, thx

**Comment by waldo1001** [comment]
Tip: 
Powershell gives you the abilty to also display which apps you're deleting - which would be valuable output as well.
