### ISSUE TITLE
FastCompiler error: The property 'SourceTable' for Page 'xxx' has changed from value '167' to value 'Job' 

### ISSUE THREAD

**Issue by EV-ANK** [HodorNV/ALOps#711]
"The bug":
A simpel PullRequest errors with multiple warnings and errors regarding some things that are not changed.
The warnings concerns the proberty SourceTable - where the compiler seems to find a change from an integer value - to a text value. When opening the app-file for the Previous Version and looking at the specific page - there are no reference to 167 (se picture below). Also the current AL-file doesn't have a reference to 167, but to "Job" (se picture below).

![image](https://github.com/HodorNV/ALOps/assets/155533734/78e5cb9a-ecc6-4720-9f9d-0c87e3026910)

![image](https://github.com/HodorNV/ALOps/assets/155533734/4e7f8836-118a-4bac-b7f5-3cb00dd6ac2f)

![image](https://github.com/HodorNV/ALOps/assets/155533734/c4516fa8-6187-45aa-ba5f-7ccf54c13cf5)

The errors concerns the change from "__ MissingTypeSymbol __" to some Enum. But the same pattern are here as above - that files in the Previous Version and the Current are the same.

We are expecting no changes at all in this regard.

Environment informations:
EnvironmentType = OnPrem
Localization = dk
Version = 23.2
Major Version: 23

**Comment by waldo1001** [comment]
Hi, nothing we can do anything about, I'm afraid. We didn't write the compiler - we merely use it from Microsoft's artifacts.

Seems the "previous" app it refers to is corrupted.  I'd rebuild it again and try again.

**Comment by waldo1001** [comment]
Hi @EV-ANK , were you able to fix this?

**Comment by EV-ANK** [comment]
Yes @waldo1001 - we found the error - not related to ALOPS. 👍
