### ISSUE TITLE
Batch App-Publish failed | Unsatisfied dependencies: Performance Toolkit by Microsoft 23.0.0.0

### ISSUE THREAD

**Issue by jpreniers** [HodorNV/ALOps#720]
We have an issue build pipelines when we want to use the Performance Toolkit in our Test app as dependency.  We get the error:
Batch App-Publish failed: Cannot install the extension 'Medical 365 Tests by GAC Business Solutions 1.0.59436.0 published as Global application' because one or more dependencies could not be satisfied. Unsatisfied dependencies: Performance Toolkit by Microsoft 23.0.0.0

See attachment for the complete raw log. Do you have any idea how to solve this so that we can use the performance toolkit?

[LogBuildPipeline.txt](https://github.com/HodorNV/ALOps/files/14094791/LogBuildPipeline.txt)

**Comment by waldo1001** [comment]
Are you sure you installed it?

This does the trick on my end:
![image](https://github.com/HodorNV/ALOps/assets/12088142/eba9ff6a-3997-4a55-8c1c-a8e017001bba)

**Comment by waldo1001** [comment]
@jpreniers ?

**Comment by jpreniers** [comment]
Fixed! You can close this ticket. Thanks!
