### ISSUE TITLE
Update Documentation/Examples

### ISSUE THREAD

**Issue by m3koenig** [HodorNV/ALOps#727]
I try to understand the "NextMajor" and "NextMinor" Compile-task.
In the (old) example is a comment, that it does not use the docker container:
https://github.com/HodorNV/ALOps/blob/master/Examples/Compiler%20V2/02_NextMajor.yml
But why? is the "compile" always without docker containers? will it pull the artifacts for compilation like the "create" task?
I think there is a missing documentation or did I miss something?

**Comment by waldo1001** [comment]
Hi,

Compile v2 (the "2" in this task `ALOpsAppCompiler@2` points to the fact that it's v2) does not use containers.
´ALOpsAppCompiler@1´ (v1) does use containers.

v2 will pull the artifacts and get the compiler from the artifacts.

v1 docs: https://docs.alops.be/ALOpsSteps/Buildstepsv1/#alops_app_compiler
v2 docs: https://docs.alops.be/ALOpsSteps/Buildstepsv2/#alops_app_compiler

If anything more is missing, please let me know!

**Comment by waldo1001** [comment]
> But why? is the "compile" always without docker containers? will it pull the artifacts for compilation like the "create" task? I think there is a missing documentation or did I miss something?

The idea of v2 was to not have the delay for starting containers to "just "compile: this way, you're able to put the compile step much sooner in the pipeline, which means, it will fail fast (if necessary), without the delay of building a container.

**Comment by m3koenig** [comment]
First: Thanks for the fast reply! and sorry for my late response and special after you closed the issue.
I did not know that the v1 and the v2 handles the compilation that different.

And: I would assume, that this impacts projects with dependecies, or?
