### ISSUE TITLE
Update docs for non-SAS-token insider builds

### ISSUE THREAD

**Issue by PeterConijn** [HodorNV/ALOps#730]
**Is your feature request related to a problem? Please describe.**
As of April, the SAS token is expected to be deprecated in lieu of the Accept EULA property. This is not yet reflected in the examples.

**Describe the solution you'd like**
I am submitting a PR with updated examples. I would ask you to review this change to see if it is acceptable.

**Describe alternatives you've considered**
I can ask you to do it :)

**Comment by waldo1001** [comment]
Thanks so much - approved :-)

https://github.com/HodorNV/ALOps/pull/731
