### ISSUE TITLE
Release Pipiline ALOps Extension API fails

### ISSUE THREAD

**Issue by panas78** [HodorNV/ALOps#744]
Our daily release pipeline started to fail with error "The system cannot find the file specified"

Find attached the release log

[ReleaseLogs_4976.zip](https://github.com/HodorNV/ALOps/files/14883180/ReleaseLogs_4976.zip)

YAML : 
steps:
- task: Hodor.hodor-alops.ALOpsExtensionAPI.ALOpsExtensionAPI@1
  displayName: 'ALOps Extension API'
  inputs:
    interaction: batch
    api_endpoint: 'http://navapp.diastasys.gr:7058/Navins_200_W1_Dev/api'
    dev_schemeupdatemode: forcesync
    authentication: basic
    username: '$(release.user)'
    password: '$(release.pswd)'
    checksecondsdelay: 10
    maxtries: 10
  retryCountOnTaskFailure: 10

**Comment by panas78** [comment]
This is affecting our whole workflow as we cannot deploy anything, same problem for our dev servers but also for our customer systems

**Comment by panas78** [comment]
Similar problem report also here : 
https://github.com/HodorNV/ALOps/issues/743

**Comment by waldo1001** [comment]
Hi, we have a strong hunch you still have to install the by Microsoft required .Net and Powershell versions.

We made a quick issue here: https://github.com/HodorNV/ALOps/issues/745#issue-2227912063
