### ISSUE TITLE
Exception calling ".ctor" with "1" argument(s): "Invalid URI: The URI is empty."

### ISSUE THREAD

**Issue by andreassallstrom** [HodorNV/ALOps#75]
Hi,

I thought I'd give ALOps a try, but can't figure out how to use it correctly. When I run the ALOpsAppCompiler-task I get the following error message:.
"Exception calling ".ctor" with "1" argument(s): "Invalid URI: The URI is empty."

Complete task log:
Starting: ALOpsAppCompiler
Task         : ALOps App Compiler
Description  : Compiles NAV Apps
Version      : 1.427.1034
Author       : Hodor
Help         : Compile a Business Central extension from AL code.

*** Validate configuration
*** Importing required PS-Functions
*** Setting up AL Compiler [0.12.15355]
*** Downloading AL Compiler [0.12.15355]
##[error]Exception calling ".ctor" with "1" argument(s): "Invalid URI: The URI is empty."
Async Command Start: Add Build Tag
Build '86' has following tags now: AL.Compiler.0.12.15355
Async Command End: Add Build Tag
Finishing: ALOpsAppCompiler

Here's my task config:
- task: ALOpsAppCompiler@1
  inputs:
    nav_computername: 'localhost' //I've tried the computername also
    nav_serverinstance: '$(ServerInstanceName)'
    nav_ports_dev: 7064
    al_compiler_version: '0.12.15355'
    nav_app_version: '1.0.*.0'

Can you point me in the right direction?

**Comment by waldo1001** [comment]
Hi - thanks for giving ALOps a try.  Did you happen to watch our introductory video?
https://www.youtube.com/watch?v=iVLOerdCuwA

Next, I see you don't use Docker - is that intentional?
How did you set up the build agent?  An easy way to set up an agent is: aka.ms/getbuildagent

Can you share your entire yaml pipeline?

**Comment by AdminHodor** [comment]
Hello @andreassallstrom ,

When not using docker, you should supply a Url where the proper VSIX can be downloaded.
This is set with the parameter "vsix_download_path"

```
vsix_download_path:                   # Alternative VSIX download url. $(vsix_download_path)
```

Kind regards

**Comment by andreassallstrom** [comment]
Thanks guys! I watched the video and got a better understanding and am now using docker. 
I'm wondering though what the Publish-task from the video does without any nav_serverinstance.

Where is it published?

**Comment by waldo1001** [comment]
A Docker container always has "BC" as service instance - ALOps knows this ;-).
So, when you're using Docker in a pipeline, ALOps makes sure THAT Docker container is used for the entire pipeline, including the ServerInstance withing the docker container.

**Comment by andreassallstrom** [comment]
Ok, cool! So if every step of the pipeline process goes well and the container is disposed; could the build then be published to a "real" BC on prem server instance on the server that the agent pool is running on?

**Comment by waldo1001** [comment]
The build pipeline should create an artifact.
And a release pipeline should indeed publish it to server.  ALOps can do that as well.  Simply install an agent on that side, and use the publish-step in a release stage!

**Comment by andreassallstrom** [comment]
Great, thanks for the help!
