### ISSUE TITLE
[Question/Feature Request] Define drive and/or location for BC Artifacts Cache folder

### ISSUE THREAD

**Issue by PeterConijn** [HodorNV/ALOps#751]
**Is your feature request related to a problem? Please describe.**
To boost performance, we have moved the agents to a larger drive (let's call it E), but when pulling an image (ALOpsDockerCreate), the bcartifacts.cache folder is set to the C drive, which fills up quickly.

**Describe the solution you'd like**
Is it/can it become possible to define the location of the artifacts cache drive and/or folder as a variable in the pipeline and ensure the rest of the process(es) follow that logic? 

**Describe alternatives you've considered**
None as yet. We are currently running daily cleanup jobs to try and keep things clear.

**Comment by AdminHodor** [comment]
Dear @PeterConijn,

There are settings for managing this, although in our experience it doesn't work stable en requires setting the same setting in different places. 

We use "Symbolic Links" instead in our systems and build agents, this way we can easily move the folder anywhere we want without making any configuration change in other places. 
After the change, the default folder on the C-Drive is merely a link, data is stored on another drive. 
Reading/Writing to the default location, is automatically redirected by windows without any performance impact.

https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/#:~:text=Symbolic%20links%20are%20advanced%20shortcuts,were%20in%20a%20different%20location.

Kind regards,

**Comment by PeterConijn** [comment]
That's what I wanted to know. 

Thanks for the quick reply!
