### ISSUE TITLE
[Feature Request] Please add alternativeartifacturl to ALOpsDockerCreate

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#754]
**Is your feature request related to a problem? Please describe.**
In our CI pipeline, we build the app and then run tests in the Docker container.
We created our own container registry and have been using it for two days now to reduce the time it takes to build Docker images on each of the four build agents, and have noticed that there are multiple daily releases for sandbox current-1 (currently 23.5) as well as NextMinor and NextMajor.
![image](https://github.com/HodorNV/ALOps/assets/9556549/b0a24b9d-1578-42f4-9a9a-ac84a3b3d4d2)

**Describe the solution you'd like**
To streamline this, we would like to create and use only one image per day per version per country. Each new container adds 12-15 minutes to the pipeline runtime per version per country without adding any value to us.
One option would be to use [Tobias Fenster's artifact proxy](https://tobiasfenster.io/get-your-bc-artifact-urls-without-powershell) and tweak it so that it also caches sandbox images for one day or we find another solution. Also, new images are already being created nightly for sandbox current-1, NextMinor and NextMajor. But with the multiple releases, they get outdated pretty quickly.

What would be nice is if **alternativeartifacturl** from ALOpsAppCompiler@2 would be added to **ALOpsDockerCreate@1** so we can achieve this.

**Describe alternatives you've considered**
I've already tried to feed the **Get-BCArtifactUrl** to a NextMinor or NextMajor build no., but it doesn't seem to find anything, so I guess it's not possible to feed the **ALOpsDockerCreate@1** with current parameters either, since it uses Get-BCArtifactUrl in the background. So what might be possible for current-1 is currently not possible for NextMinor or NextMajor.

**Additional context**
We currently use 4 build agents for fast compilation (ALOpsAppCompiler@2), 4 build agents for testing in Docker container and 2x4 build agents for deployment to cloud (which are idle most of the time and waiting for BC cloud to deploy the app). We have a big mix of multiple OnPrem versions and a lot of same version sandbox jobs of a growing number for AL projects. We can add more agents, but it would be important to us to have the fastest CI pipeline possible, fulfilling the requirement of running tests for new developments.

**Comment by waldo1001** [comment]
We'll add a new parameter for you to provide an alernative URL.

**Comment by waldo1001** [comment]
Part of next release!

**Comment by DanielGoehler** [comment]
@waldo1001 Thanks, works fine.

**Comment by Arthurvdv** [comment]
@DanielGoehler Thank you for creating this request, where we now also can benefit in our pipelines of this 🤗

> One option would be to use [Tobias Fenster's artifact proxy](https://tobiasfenster.io/get-your-bc-artifact-urls-without-powershell) and tweak it so that it also caches sandbox images for one day or we find another solution.

I've also had the wish to cache sandbox images more then 1 hour, so I've created an PR for this (https://github.com/tfenster/bcartifacturl-proxy/pull/5). You can nu influence the duration of the cached results.
