### ISSUE TITLE
Deploying a single app to an instance that has apps published that are depending on the app I'm trying to deploy gives an error in a yaml pipeline, but works just fine in a release pipeline.

### ISSUE THREAD

**Issue by dvanes67** [HodorNV/ALOps#756]
**Describe the bug**
We have a yaml pipeline in DevOps that compiles, translate, compiles (again) and creates a runtime for an app. I thought I'd be nice if I could add a step to this pipeline to deploy the app to an instance, depending on the branch name.
Everything works fine, until it goes to the publish app stage in the pipeline. Then it goes:
##[error]The Extension cannot be unpublished because it is required by the following apps: xxxxxx

- task: ALOpsAppPublish@1
        displayName: 'ALOps App Publish'
        inputs:
          nav_serverinstance: '$(instance)'
          nav_artifact_app_filter: '*runtime.app'
          forcesync: true

If I create a release pipeline in Devops, I can actually deploy the same app, in the same instance without any issue. (and it uses the same code.

Am I missing something? or do I just want to much? We are still mostly onPrem, not sure if that makes a difference.

**Comment by waldo1001** [comment]
From the info above, I honestely don't know.  I'd have to debug ...

**Comment by waldo1001** [comment]
👍

Thanks for answering your own question ;-).
Mixing deployment scopes in one database is always to be avoided, in my honest opinion.. .
