### ISSUE TITLE
[Feature Request] AlOpsCompile alternativevsixurl 'latest-preview'

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#766]
**Is your feature request related to a problem? Please describe.**
Following up on issue #430, we are unable to run custom code analysis tools like BCLinterCop that require the next major version of the AL Language Extension. More details can be found here: [BusinessCentral.LinterCop Issue #629](https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/629). Currently, BCLinterCop only supports the latest marketplace releases of the AL Language Extension, which limits our ability to use these custom code cops effectively.

**Describe the solution you'd like**
I would like ALOps to support an alternative URL parameter for the AL Language Extension, specifically 'latest-preview'. This would allow us to use the latest preview version of the AL Language Extension in our Azure DevOps pipelines, enabling us to run custom code cops like BCLinterCop without any issues.

**Describe alternatives you've considered**
Not using BCLinterCop on Next Major Pipelines.

**Comment by waldo1001** [comment]
The compiler has a parameter `alternativevsixurl`.
Can you try using it like (in the compile step):
```yaml
alternativevsixurl: 'PRERELEASE'
```
