### ISSUE TITLE
ALOps Compile is generating a wrong app name

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#77]
When the compile step is creating the app (in which it removes the publisher) with a new name without the publisher and applying the version no., it will never create a correct name for us, see example.
![image](https://user-images.githubusercontent.com/54669593/73733292-fa86c400-473b-11ea-9c87-06763b67ed6b.png)

Note: I am quite happy with not have the publisher as a part of the app name - as long as it removes it correctly. Alternatively would be to preserve the original name and only have ALOps update the version no. part.

**Comment by waldo1001** [comment]
This is the AL compiler, I'm afraid.  The "/" in your name is making it into a new folder.
We're looking into it to see what we can do about it.  We already are working on another issue that might fix this one as well.

**Comment by AdminHodor** [comment]
Dear @kasperdj ,

Replacing of invalid characters is included in the latest release (today) build 1079. Every invalid character will be replaces by an underscore.

Kind regards,

**Comment by kasperdj** [comment]
Thx, I have as a workaround implemented the following powershell code as a part of my release pipeline:

Copy-Item (Join-Path $SourceDirectory "*.app") -Destination $appOutputShare -Force
Get-ChildItem -Path $appOutputShare -Include "*.app" -Recurse | Where-Object Name -like "s_*" | ForEach-Object { $_ | Rename-Item -NewName $_.Name.Substring(2) }
