### ISSUE TITLE
[Question]: How to set PublicDNSName

### ISSUE THREAD

**Issue by innonav-dev** [HodorNV/ALOps#772]
**Is your feature request related to a problem? Please describe.**
I need to set the PublicDNSName of a BCContainer.

**Describe the solution you'd like**
Add a global variable similar to 'Alops_UpdateHostsFile' or a Parameter for ALOpsDockerStart in order to enable us
to set the PublicDNSName.

**Comment by innonav-dev** [comment]
I think we solved the issue by adding in the task
ALOpsDockerStart
docker_parameters: '--hostname $(dockerName).int.abc.at'

**Comment by waldo1001** [comment]
Very grateful, because it would have cost us quite some time for figure out (since we don't use this ourselves)!
