### ISSUE TITLE
Publish dependant apps issue

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#78]
I do not have symbols as a part of my repo.
I have a folder in my repo: app\Dependencies\ where all of the projects dependent/ISV app's I stored.

How can I publish these apps in Docker **prior to the compilation of my source code**?

My issue is that it's the compile step that copies the source code to Docker and the compilation will fail if my dependent app(s) is not published prior to this step. However since I don't have the source code inside Docker before the compilation, I cannot run this pipeline step:

- task: ALOpsAppPublish@1
  displayName: 'ALOps Install ISV and dependencies apps'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    batch_publish_folder: 'C:\Run\DevOps\app\Dependencies'

Please advise on how to handle this situation.

**Comment by waldo1001** [comment]
This indeed seems to be an issue - we're working on it!  Thanks for taking the time to post!

**Comment by kasperdj** [comment]
Sounds good...In general it would be nice to separate the copying of source code to the docker container from the ALOpsCompile step.

**Comment by jcoe-nvt** [comment]
Any idea when a fix for this issue can be expected?

I should have the possibility to use the dependend artefacts generated by other pipelines (other repositories) before the compilation step.

This step from the template example in Issue 50, should be part of ALOps
![image](https://user-images.githubusercontent.com/49404625/74254420-b6be2c80-4cf0-11ea-818f-5580e2a932dd.png)

**Comment by AdminHodor** [comment]
Hello @kasperdj ,

>>In general it would be nice to separate the copying of source code to the docker container from the ALOpsCompile step
We included this in the new release (build 1079). The copy of source code is now done in the "Docker Wait" step by default when using docker. So all files are available from the start.

You can enable/disable this default behaviour by setting the "setup_working_folder" parameter on "ALOpsDockerWait" and "ALOpsAppCompile". By default the working folder will be setup in the WAIT step, and not triggered again in the compile step.

Kind regards

**Comment by AdminHodor** [comment]
Hello @kasperdj ,

Did you have any chance to validate the solution?

Kind regards,

**Comment by AdminHodor** [comment]
Hello @kasperdj ,

Did you have any chance to validate the solution? We want to be sure before we close the issue.

Kind regards,
