### ISSUE TITLE
Fixed Container Tag - Question

### ISSUE THREAD

**Issue by titofffffff** [HodorNV/ALOps#79]
hello,

I have the following use case : 

- An existing VM where I have installed a BC container
- I would like publish an app using ALOps App Publish

My issue is the following : 
the container exists so I can't modify its tag (if i'm not wrong !)

How can I setup Alps App Publish in order to allow the process to find my existing container ?

Thank in advance for your help !

**Comment by titofffffff** [comment]
I've found a workaround : install the agent directly on the container.

**Comment by waldo1001** [comment]
Well - that would work indeed :-);

But if you would "tag" your container, you could use that tag in the "Fixed Container Tag" as well.

**Comment by titofffffff** [comment]
@waldo1001  yes I know if I set a tag named TFSBuild but in my case the container already exists and you can't modify the tag of an existing container.
One remark : I'm not sure the documentation indicate the name of the tag (TFSBuild) which have to be setup. It took me some time to find this trick :)
![image](https://user-images.githubusercontent.com/5903546/74219934-763dbf00-4cae-11ea-9690-89dc576aad33.png)

**Comment by waldo1001** [comment]
You can set up another tag as well.  In that case, you need to use the "fixed_tag" parameter in the ALOps-steps.  The default value is TFSBuild, which we use to refer to the same container during a build process, that's all.

**Comment by titofffffff** [comment]
@waldo1001 : to be sure to understand, when I create a container I can setup a label like this : --label fixed_tag='devenv' and mention the value 'devenv' on parameter 'Fixed Container Tag' in AlOps ?

**Comment by borisimple** [comment]
Any updates on this?

I am trying to do the same thing at the moment, but it seems that ALOps does not pick up value from "fixed_tag" parameter.

![image](https://user-images.githubusercontent.com/16119596/102351035-14bd3f80-3fa6-11eb-9d12-5c407a181265.png)

@waldo1001 Can you help? 😊

**Comment by waldo1001** [comment]
Please create a new issue (this is completely under the radar), and share how you create the container (script).

**Comment by waldo1001** [comment]
Handled in #281
