### ISSUE TITLE
Powershell 7 Compatibility for AlOps Tasks

### ISSUE THREAD

**Issue by joandrsn** [HodorNV/ALOps#791]
As I understand it, to use PowerShell 7 with AlOps tasks, we need to set the pwsh flag (despite the documentation stating `# Run task in Powershell Core. $(pwsh)`, which is no longer accurate).

[Microsoft has announced that the PowerShell 5 module will be deprecated in BC26](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-features-platform#support-for-powershell-50-removal).

This means we need to update all AlOps tasks to use PowerShell 7 by adding the `pwsh: true` setting to each task.

Questions:
1. Are there any plans to automatically detect when PowerShell 7 should be used?
2. Could there be an option for a global variable to manage this?

I understand that there are challenges involved, particularly in ensuring that this change doesn't disrupt builds for customers using versions earlier than BC24.

**Comment by PeterConijn** [comment]
I have tried turning that on in our release pipeline, but it leads to error:

```Text
2024-09-04T10:53:35.1795744Z [33;1mWARNING: Proxy creation has been skipped for the following command: 'ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature, Get-CmsMessage, Get-Credential, Get-ExecutionPolicy, Get-PfxCertificate, New-FileCatalog, Protect-CmsMessage, Set-Acl, Set-AuthenticodeSignature, Set-ExecutionPolicy, Test-FileCatalog, Unprotect-CmsMessage', because it would shadow an existing local command.  Use the AllowClobber parameter if you want to shadow existing local commands.[0m
2024-09-04T10:53:35.3599517Z ##[error]Failed to generate proxies for remote module 'Microsoft.PowerShell.Security'. No command proxies have been created, because all of the requested remote commands would shadow existing local commands.  Use the AllowClobber parameter if you want to shadow existing local commands.
```

I am without a doubt missing a beat or two, but I don't know which one(s).

**Comment by PeterConijn** [comment]
Forgive my ignorance in this area, but is there something specific we need to change on our Azure VM agent server? I have been using the PowerShell Core boolean, but that led to the errors above, as did changing the startup load order.

Does anyone know the steps we need to take to migrate this to PS7?

**Comment by PeterConijn** [comment]
> Forgive my ignorance in this area, but is there something specific we need to change on our Azure VM agent server? I have been using the PowerShell Core boolean, but that led to the errors above, as did changing the startup load order.
> 
> Does anyone know the steps we need to take to migrate this to PS7?

Sorry to keep bugging, but is there any documentation I can use? I seem to keep getting the error in my post of last month.

**Comment by PeterConijn** [comment]
Issue [17708](https://github.com/microsoft/azure-pipelines-tasks/issues/17708) on Azure-Pipeline-Tasks seems to resolve this issue. Now we are running into incredible slowness on a simple delete task, but we will investigate that further.

**Comment by PeterConijn** [comment]
The advice to fix this is by setting AZP_AGENT_CLEANUP_PSMODULES_IN_POWERSHELL to true, but the ALOpsExtension does not allow me to set environment variables. 

Source: https://jessehouwing.net/vsbuild-task-fails-on-self-hosted-azure-pipelines-agent/

**Comment by waldo1001** [comment]
@joandrsn ,

we are ready for full PS7.  Good idea on the global - we're adding it to the list.
Automatically detect - that's another pair of sleeves.  The way devops runs tasks, ALOps doesn't really get the context of versions and such.. .  We'll think about it...

**Comment by waldo1001** [comment]
@PeterConijn ,

can you please rephrase your question if you don't mind?

**Comment by PeterConijn** [comment]
Hi @waldo1001, of course:

Given that we are running self-hosted on an Azure VM, what do we need to change exactly (either in the pipeline and/or server config) to get this to run on PS7?

**Comment by waldo1001** [comment]
Did you see this pinned issue?
https://github.com/HodorNV/ALOps/issues/745

**Comment by joandrsn** [comment]
Sounds like a great solution @waldo1001, then we would be able to detect the version we use and set the var accordingly.

**Comment by ptrk-tr** [comment]
> The global will be `alops_pwsh`, which is a boolean (so: set to true). We'll update the status of this issue when released.

@waldo1001 would probably be a good idea to also update the [Globals.md](https://github.com/HodorNV/ALOps/blob/master/Documentation/Globals.md) in the documentation so people don't have to randomly stumble on this issue to find out about the variable, what do you think? I assume that file is also the source for the documentation on [docs.alops.be](https://docs.alops.be/UsefulInfo/Globals/)?

**Comment by waldo1001** [comment]
> > The global will be `alops_pwsh`, which is a boolean (so: set to true). We'll update the status of this issue when released.
> 
> @waldo1001 would probably be a good idea to also update the [Globals.md](https://github.com/HodorNV/ALOps/blob/master/Documentation/Globals.md) in the documentation so people don't have to randomly stumble on this issue to find out about the variable, what do you think? I assume that file is also the source for the documentation on [docs.alops.be](https://docs.alops.be/UsefulInfo/Globals/)?

You won't believe it, but the PR with doc is ready, but the changelog needs to be pushed together, and that is not ready yet.

**Comment by PeterConijn** [comment]
> Did you see this pinned issue? #745

Sorry for the late reply, but I've been out for a bit. We did download PS7 onto our Azure VM agent machines, but when we use the "Powershell Core" tickbox in our deployments (which is a mask for the pwsh parameter), we get the error:

```text
Failed to generate proxies for remote module 'Microsoft.PowerShell.Security'. 
No command proxies have been created, because all of the requested remote commands would shadow existing local commands.  
Use the AllowClobber parameter if you want to shadow existing local commands.
```

We have tried setting PS7 above PS5 in load order, but that leads to the errors listed in my comment of October 1st. We are obviously missing a step or two, but I can't see which one(s).

**Comment by waldo1001** [comment]
We don't know exactly what to refer to.

I assume you're running as full admin for the server?  Local System?

May be reinstall the server altogether?

Maybe send a full log so we can see the PS version?  There seem to be some issues with some PS7 versions, like:
https://learn.microsoft.com/en-us/answers/questions/952054/failed-to-generate-proxies-for-remote-module-micro

**Comment by waldo1001** [comment]
If the issue persists, please open a new one with full output.
