### ISSUE TITLE
ALOPS Extension License Queries

### ISSUE THREAD

**Issue by ooham** [HodorNV/ALOps#793]
Hi Team,

I would like to know more about ALOPS license pricing, I would like to take ALOPS extension license for one of my private projects, which is D365 Business central Migration from NAV 2017, right now we are having 5-6 3rd applications and middle ware applications so i would like to go for ALOPS for BC Build\release pipelines and would like to know in more detail about 2 plans in ALOPS pricing guide, 
1) 50 EURO plan for 5 repositories with unlimited Builds.
2)250 Euro plan for whole project.
What is the list of items included and limitation for both the plans and what if i would go for 5 repositories plan now which is 50 Euro, can i upgrade the plan to next level if required in future.

Please Let me know ASAP.

**Comment by ooham** [comment]
Thank you for the response @waldo1001.
I have an another query regarding repository where if I choose 5 repository subscription , then can we create build and release pipelines for any number of branches in that specific repository.
2. For the above plan do we have unlimited number of runs for each build and release pipeline in that specific repository.?

My colleague has already dropped a mail regarding the pricing details (manvitha.r.vustala@gmail.com), anticipating a reply on the same.

**Comment by waldo1001** [comment]
1. Yes, you can.
2. Yes, you have.

I also replied to your colleague ;-).

**Comment by ooham** [comment]
Hi Team,

We are willing to purchase ALOPS extension for our client project, but we require few details to add ALOPS vendor in our systems for KYC.
We have dropped a mail with our Mail ID (manvitha.vustala), could you please provide us your response so, we can proceed and purchase ALOPS license, we are waiting for your response from long time.

Please let us know your response asap.

**Comment by ooham** [comment]
Hi @waldo1001,

Could you please provide your inputs for the KYC process sent by the client by responding to the mail as it is necessary for us to proceed further.
