### ISSUE TITLE
Import or Fork this repository to start development of your own app

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#8]
Not really linked to the ALOps extension, but just curious. 

Is it possible on Azure DevOps to really 'fork' (instead of Clone / download the repo) https://dev.azure.com/HodorNV/ALOps%20Templates/_git/Base%20AL%20App to another Organisation / Project? ('Fork' option on the repo is not available)

Using the 'Import Repository' option from within my project, results in an authorisation error.

`Oops! Your import of https://HodorNV@dev.azure.com/HodorNV/ALOps%20Templates/_git/Base%20AL%20App repository failed due to TF50309: The following account does not have sufficient permissions to complete the operation: fvet@mydomain. The following permissions are needed to perform this operation: **View project-level information**..`

**Comment by fvet** [comment]
Found out about https://github.com/HodorNV/ALOps/blob/master/Documentation/SettingUpYourFirstBuild.md in the meanwhile ;)

**Comment by waldo1001** [comment]
@fvet, so you're good to go for this one?
