### ISSUE TITLE
Question regarding ALOpsSaaSPublishExtension@1

### ISSUE THREAD

**Issue by CarlOhlsson** [HodorNV/ALOps#81]
Hi!

I am starting to look at how to setup CI/CD for Dynamics BC **(SaaS)**. So far it seems possible to automatically deploy the extension with a pipeline to the Sandbox environment. However i have found 1 comment on the internet stating that its not possible to do this into the production environment. Instead you or the customer themselves would have to install the extension from inside BC the normal way. 

I can also see in the task itself it says _bc_environment: sandbox_ indicating it is preset and not changeable?

If correct in my assumption that we cant publish to production automatically right now, is this something that will be possible in the future? 

I found this [link](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/itpro-introduction-to-automation-apis) talking about some API for updating extensions but cant find anything mentioning this being sandbox only.

**Comment by waldo1001** [comment]
That info is incorrect.  Please test it with ALOps :-).

You have to decently set up AzureAD (ref: https://vjeko.com/2019/02/16/how-do-i-really-set-up-azure-active-directory-based-authentication-for-business-central-apis/), but it should work!

**Comment by waldo1001** [comment]
the " bc_environment: sandbox " is merely a default value .. you can change it.

**Comment by AdminHodor** [comment]
Dear @CarlOhlsson ,

Did you get the pipeline to work ?

Kind regards,

**Comment by CarlOhlsson** [comment]
> Dear @CarlOhlsson ,
> 
> Did you get the pipeline to work ?
> 
> Kind regards,

Sadly we have not reached this state in the project. Our company have strict regulations about software being for our customer making it impossible for us to use some tools for BC development. This will probably done after the initial project since it is considered a nice to have feature when all the software regulations have been sorted.

**Comment by waldo1001** [comment]
Hi @CarlOhlsson ,

that's a "different" way to look at it  ;-) .  If there is anything we can do, let us know!
In the mean time - is it ok we close this issue?

**Comment by CarlOhlsson** [comment]
@waldo1001 Yes the issue can be closed, i got all i need from this. Thank you!
