### ISSUE TITLE
Question: how do you deal with custom dlls

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#83]
Hey Guys, 
I do have extension project that comes with custom dll. I store in my project folder ".netpackages", and have a record on settings.json pointing to that folder: 

```
   "al.assemblyProbingPaths": [
        "./.netpackages/",
    ]
```

When i try to compile this app using ALOps it does not work. I don't have that dll in my docker container NAV addins folder. One way would to solve it, would be to copy it to addin folder first. 
Is there another way? Can i adjust assemblyProbingPaths through ALOps settings?

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

Could you please post the output of this job? 
The ALOps Compile step should detect if there are DLL's located in your repository, if so, the path gets automatically added to the AssemblyProbingPaths.

You should see the following 3 lines in the log:
  - Checking for Assemblies in App
  - **Assemblies in App found. Adding Probing Path.**
  - Add Windows Assembly Path [C:\Windows\assembly]

Kind regards,

**Comment by gintuoklis** [comment]
Hey @AdminHodor, 
I did check as you advised. You are right. Assemblies are discovered and added for to the Probing Path.

Here's the compilation command with custom c:\Run\DevOps in probing path

`& C:\Run\Microsoft.al\al-3.0.154634\extension\bin\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps" /out:"c:\Run\DevOps\VerySpecialExtension_1.0.202007.33929.app" /fullpaths /ruleset:"c:\Run\DevOps\my.ruleset.json" /assemblyprobingpaths:c:\Run\DevOps\,C:\Windows\assembly`

But, the next step "ALOps App Publish" fails.  We have this step for testing the same app, we just compiled. 

Here is the error from "ALOps App Publish":

`src/dotnet.al(7,14): error AL0451: An assembly named 'EFTWrapper, PublicKeyToken=null' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics NAV\140\Service\Add-Ins, C:\Windows\TEMP\Microsoft Dynamics NAV\Add-Ins\14.0.35916.0, C:\Program Files\Microsoft Dynamics NAV\140\Service\, C:\Windows\Microsoft.NET\assembly\'`

As you can see, there's no "c:\Run\DevOps" in probing paths

**Comment by gintuoklis** [comment]
it discovers navservicetier assemblies correctly, but not finsql.exe. It takes executable from older version **100**. 
Strangest thing that it keeps importing the fob, even with older finsql.exe version. At least it did not crash yet, should take about 15minutes to know the result. It's big fob file i have there.

```
Starting: ALOps Import FOB
==============================================================================
Task         : ALOps Import FOB
Description  : ALOps Import FOB
Version      : 1.428.1193
Author       : Hodor
Help         : Import objects from .FOB file.
==============================================================================
*** Validate configuration
*** Importing required PS-Functions
*** Setup database connection
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [buildTest].
*** Loadin assemblies from: [C:\program files\microsoft dynamics nav\nav140.39277\nav140.39277]
*** Using Windows-Authentication for Database
*** Setup FinSql link
*** Searching for Client-FinSql in Registry
*** Client-FinSql from registry could not be located: [C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\finsql.exe C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client\finsql.exe]
*** Searching for Service-FinSql in Registry
*** Service-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\Service]
*** Searching for RoleTailoredClient-FinSql in FileSystem
*** Found FinSql path: [C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\finsql.exe]
C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\finsql.exe
*** FOB File filter: C:\agent\_work\1\Release\**\Release_CI_*.fob
*** Import Action: Overwrite
*** Start processing FOB: [Release_CI_38917.fob]
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [buildTest].
*** Loadin assemblies from: [C:\program files\microsoft dynamics nav\nav140.39277\nav140.39277]
*** Import FOB: [Release_CI_38917.fob] in [buildTest]
  * DatabaseServer   : mvx-sql
  * Database Instance: 
  * Database Name    : buildTest
  * Management Port  : 7045
*** Running command: & "C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\finsql.exe" --% Command=ImportObjects,ImportAction=Overwrite,SynchronizeSchemaChanges=no,File="C:\agent\_work\1\Release\mv_Release_CI_38917_master\Release_CI_38917.fob",LogFile="C:\Users\BUILDA~1\AppData\Local\Temp\NavIde\dcfd9c22-7464-453a-bd03-f055fae3883b\Release_CI_38917.log",ServerName="mvx-sql",generatesymbolreference=1,ServerName="mvx-sql",Database="buildTest",NavServerName="localhost",NavServerInstance="buildTest",NavServerManagementport=7045 | Out-Null
```

**Comment by InnoNavSupport** [comment]
Hey @AdminHodor,
we have exactly the same issue.
Any good workaround for this?

**Comment by waldo1001** [comment]
We just don't seem to be able to simulate this .. .

just to be clear .. 
@SimonOfHH, @InnoNavSupport , do you mean - publishing fails in the build pipeline?  or publishing fails in the release pipeline (which is different from build pipeline)?

**Comment by InnoNavSupport** [comment]
Hi @waldo1001,

In our case, we use the build pipeline. 
ALOPsCompileExtensionApp works well (it looks like) and then ALOpsAppPublish through an error.

During Compile Extension the following is in the Log:
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [BC].
*** Loadin assemblies from: [C:\program files\microsoft dynamics nav\160\service]

##[error]Extension compilation failed
Al/dotnet.al(26,14): error AL0451: An assembly named 'Lucene.Net, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics NAV\160\Service\Add-Ins, C:\Windows\TEMP\Microsoft Dynamics NAV\Add-Ins\16.0.12630.12758, C:\Program Files\Microsoft Dynamics NAV\160\Service\, C:\Windows\Microsoft.NET\assembly\'

There is a .netpackages Folder in the App-Folder with all necessary dll´s. On our local machine it works well.

![image](https://user-images.githubusercontent.com/62563638/86023603-2e84bd80-ba2c-11ea-95e0-5057429c5570.png)

**Comment by gintuoklis** [comment]
@InnoNavSupport, @SimonOfHH 
I don't have this issue you describe. I use custom made docker images where i installed all my assemblies to NAV add-ins folders (server/clients). Pethpaps, that's why it works for me.

**Comment by waldo1001** [comment]
We have introduced a fix in next release, where we copy the dlls - we noticed some issues with "in-use" dlls, which is probably causing the above.

We expect this release to be available this weekend.

**Comment by fvet** [comment]
@waldo1001, is there some ALOps changelog.md / release notes to see what has been updated in the next release? 

Currently, we've included a step to import the add-ins (of the current app and the dependend apps) between the DockerWait and before the Install AL Testtool, so when can restart the service afterwards. If we can get rid of this complexity since ALOps has added this by default, that would be fine.

```
- task: PowerShell@2
  displayName: 'Import Addins'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -ItemType Directory -Path "$(System.ArtifactsDirectory)\Add-Ins\NVT" -Force | Out-Null
      if (Test-Path -Path "$(System.ArtifactsDirectory)\App Addins\*") {
          Copy-Item -Path "$(System.ArtifactsDirectory)\App Addins\*" -Destination "$(System.ArtifactsDirectory)\Add-Ins\NVT" -Recurse -Force
      }
      if (Test-Path -Path "$(System.ArtifactsDirectory)\Addins\*") {
          Copy-Item -Path "$(System.ArtifactsDirectory)\Addins\*" -Destination "$(System.ArtifactsDirectory)\Add-Ins\NVT" -Recurse -Force
      }
      if (Test-Path -Path "$(System.DefaultWorkingDirectory)\app\.netpackages\*") {
          Copy-Item -Path "$(System.DefaultWorkingDirectory)\app\.netpackages\*" -Destination "$(System.ArtifactsDirectory)\Add-Ins\NVT" -Recurse -Force
      }
      if ("${{ parameters.publish_test }}" -eq 'true') {
          if (Test-Path -Path "$(System.ArtifactsDirectory)\Test Addins\*") {
              Copy-Item -Path "$(System.ArtifactsDirectory)\Test Addins\*" -Destination "$(System.ArtifactsDirectory)\Add-Ins\NVT" -Recurse -Force
          }
          if (Test-Path -Path "$(System.DefaultWorkingDirectory)\test\.netpackages\*") {
            Copy-Item -Path "$(System.DefaultWorkingDirectory)\test\.netpackages\*" -Destination "$(System.ArtifactsDirectory)\Add-Ins\NVT" -Recurse -Force
          }
      }
      if (Test-Path -Path "$(System.ArtifactsDirectory)\Add-Ins\NVT\*") {
          $containers_json = (docker container ls -a --no-trunc --format "{{json .Names}},{{json .ID}},{{json .Image}},{{json .Networks}},{{json .Mounts}},{{json .CreatedAt}}")
          $containers_object = ($containers_json | ConvertFrom-CSV -Header "Name","ID","Image","Network","Mounts","Created")
          $latest_container = ($containers_object | Sort-Object -Descending -Property Created | Select-Object -First 1)
          $container_addin_folder = $latest_container.Name + ":/Program Files/Microsoft Dynamics NAV/${{ parameters.nav_base_version }}/Service/Add-Ins"
          docker cp "$(System.ArtifactsDirectory)\Add-Ins\NVT" "$container_addin_folder"
      }

```

**Comment by waldo1001** [comment]
Hi Frédéric,

any major changes are reported here:
https://github.com/HodorNV/ALOps/blob/master/Documentation/changelog.md

The marketplace upload validation seems to be down .. we have been trying to push a new build for a couple of days now .. but it just keeps hanging at validation.. .

I contacted the marketplace-support - hopefully they "pick up the foon soon".

**Comment by gintuoklis** [comment]
hey @waldo1001, 
I think it's still not solved. Just tried to run pipeline for extension with dependecy to custom dll, and it failed again on AL ops Publish step (Version : 1.431.1520). 

As before, publish step does not take into account assemblies from this path: C:\Run\DevOps\.netpackages 
As temporary workaround, i build custom image with my copied to Addins folders. It works, but if my dll version changes, i need to rebuild my docker image.

**Comment by waldo1001** [comment]
Thanks for the feedback .. we have one more update for this by the end of the week .. hope that will fix it.

**Comment by mrabus** [comment]
I run into the same issue as described in this case

**Comment by mrabus** [comment]
@waldo1001 will the update release in the next days? Can you give us an outline regarding the plan?

**Comment by mrabus** [comment]
@waldo1001? :-)

**Comment by waldo1001** [comment]
Sorry - those custom dlls are still haunting us .. main problem is that we're not able to repro scenarios.. .

**Comment by waldo1001** [comment]
Progress .. we finally seem to have a decent repro scenario.  Good thing is that this will end up in the automated-testing as well .. .

**Comment by mrabus** [comment]
That's great :-) Looking forward for the fix

**Comment by mrabus** [comment]
Was the fix included in today's release? :)

**Comment by AdminHodor** [comment]
Dear @gintuoklis , @mrabus ,

In our latest release (v1.432.1558) there are some new features that will help you out with this. The DevOps workingfolder is scanned for DLL's, every folder containing DLL's is than copied to the container during "ALOpsDockerStart" before the container is actually started. This avoids the need for restarting the Service.

At the end of the ALOpsDockerWait step, we still copy all files from the workingfolder to the container. Here we made a change using dotnet ZIP instead of Powershell due to performance issues with the powershell ZIP.

Could you please check if this enhancement is working for you? The log for this DLL copy action can be found in the "ALOpsDockerStart" step between the two (blue) docker commands.

```
*** Checking for Assemblies in App
*** Create TempFile
*** Test Docker-Path: [/Program Files/Microsoft Dynamics NAV/160/Service/Add-ins/]
*** Cleanup TempFile
*** BC Service Folder: [/Program Files/Microsoft Dynamics NAV/160/Service/Add-ins/]
*** Assemblies in App found. Adding Probing Paths (1).
  * C:\vsts-agent-onpremise\_work\40\s\AddIns
##[command]"docker" start bb71e09ae4abbf0f29f4c18970df8bf5df3a6c520ce73384eaf4ab8dd29d0123
```

Please let us know if this works out for you.

Kind regards,

**Comment by gintuoklis** [comment]
Thanks, i will keep an eye on this one

**Comment by mrabus** [comment]
My issue still remains. 

I have a BaseApp X containing a few DLLs in a .netpackage folder in the repo. When I build the app itself, everything is just fine. 

But if I want to build App A with a dependency to X, it doesn't work. 
I download X fom artifacts and when publishing it tells me that 

"error AL0451: An assembly named 'PdfSharp, PublicKeyToken=null' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics NAV\160\Service\Add-Ins, C:\Windows\TEMP\Microsoft Dynamics NAV\Add-Ins\16.0.14073.14195, C:\Program Files\Microsoft Dynamics NAV\160\Service\, C:\Windows\Microsoft.NET\assembly\'" 

Any idea how to work around that?

**Comment by waldo1001** [comment]
Hi,
the dependency might be tricky, but we saw did an small fix in the build - can you try again?

**Comment by waldo1001** [comment]
@mrabus ,

I think the main thing you're forgetting is: there are no dlls in the app-file (which is a result of compilation) .. so you'll have to make the dlls available in the workingfolder of App A (like you did for App X).  

Makes sense?

**Comment by waldo1001** [comment]
@mrabus ,

If it would help: you can also download the dlls as artifacts (if made available as artifacts) .. but make sure to download them to the workingfolder (as we will only take the dlls in the workingfolder into account).

**Comment by mrabus** [comment]
> 
> 
> @mrabus ,
> 
> I think the main thing you're forgetting is: there are no dlls in the app-file (which is a result of compilation) .. so you'll have to make the dlls available in the workingfolder of App A (like you did for App X).
> 
> Makes sense?

I figured that out today. I believed MS had some magic inside the app packages to handle the DLLs. 

The working folder is not the $(System.ArtifactsDirectory), right?

**Comment by waldo1001** [comment]
Microsoft and magic - I don't think so ;-).

Should be `$(System.DefaultWorkingDirectory)`.

**Comment by mrabus** [comment]
That worked, thank you 

One last issue (for today ;) ) can you check why we didn't get a ALOps License yet?
