### ISSUE TITLE
ALOps Apps Test Issue ##[error]FinSql could not be located on host.

### ISSUE THREAD

**Issue by salaniko** [HodorNV/ALOps#84]
Hello,
I have an error in my pipeline when I try to launch the AlOpsAppsTest task. I don't understand why this happened. Did you see the origin of the error ?
I give you the YAML code of my pipeline 

	name: $(Build.BuildId)
	pool:
	    vmImage: 'windows-latest'
	steps:
	- checkout: self
	  clean: true 
	  
	- task: ALOpsDockerStart@1
	  inputs:
	    docker_image: 'mcr.microsoft.com/businesscentral/onprem'
	    docker_pull: true
	    
	- task: ALOpsDockerWait@1
	  inputs:
	    search_string: 'Ready for connections!'
	    
	- task: ALOpsAppCompiler@1
	  displayName: 'ALOps App Compiler'
	  inputs:
	    usedocker: true
	    nav_app_version: '1.0.*.0'
	    failed_on_warnings: true
	    
	- task: ALOpsAppPublish@1
	  displayName: 'ALOps App Publish'
	  inputs:
	    usedocker: true
	    nav_artifact_app_filter: '*.app'   
	    skip_verification: true 
	    
	- task: ALOpsAppTest@1
	  displayName: 'ALOps Run TestSuite'
	  inputs:
	    usedocker: true
	    import_action: "Skip"
	    show_available_tests: true
	    import_testtoolkit: true
	    failed_test_action: 'Ignore'
	  continueOnError: true   
	   
	- task: PublishTestResults@2
	  displayName: 'Publish Test Results **/TestResults.xml'
	  inputs:
	    testResultsFormat: XUnit
	    testResultsFiles: '**/TestResults.xml'
	    testRunTitle: 'BC Test Results: $(Build.BuildId)'
	    
	- task: ALOpsDockerRemove@1
	  displayName: 'Remove Docker Container'
	  enabled: true
	  condition: always()

and the error screen I have once I run the pipeline.

	Starting: ALOps Run TestSuite

	==============================================================================

	Task : ALOps App Test

	Description : ALOps App Test

	Version : 1.427.1034

	Author : Hodor

	Help : Run Business Central Test-Suite and collect results.

	==============================================================================

	*** Validate configuration

	*** Importing required PS-Functions

	*** Working folder: d:\a\1\s

	***

	*** Prepare Docker Session

	*** Connect Docker Session

	*** Initiate Docker Session

	*** Copy Modules to Docker

	*** Setup Docker Session

	*** Import Modules in Docker Session

	*** Import UI Client [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]

	VERBOSE: Loading module from path 'C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll'.

	*** Import NewtonSoft JSON [C:\Program Files\Microsoft Dynamics NAV\150\Service\Newtonsoft.Json.dll]

	*** Import Modules in Docker Session: class_ClientContext

	*** Setup BC Credentials in Docker

	*** Prepare FinSql

	*** Searching for Client-FinSql in Registry

	*** Client-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\RoleTailored Client]

	*** Searching for Service-FinSql in Registry

	*** Service-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\Service]

	*** Searching for RoleTailoredClient-FinSql in FileSystem

	*** RoleTailoredClient-FinSql not found in FileSystem: [C:\Program Files*\Microsoft Dynamics*\*\RoleTailored Client\finsql.exe]

	*** Searching for Service-FinSql in FileSystem

	*** Service-FinSql not found in FileSystem: [C:\Program Files*\Microsoft Dynamics*\*\*\finsql.exe]

	##[error]FinSql could not be located on host.

	Finishing: ALOps Run TestSuite

I hope you'll have an answer to this issue.
Best regards.

**Comment by AdminHodor** [comment]
Hello @salaniko ,

Please note the Test-Step has different parameters for Business Central v15 than for v14. 
You can find the correct parameters for v15 in our [example](https://github.com/HodorNV/ALOps/blob/master/Examples/06_UseDocker_TestTool_v15_Multiroot.yml).

Earlier versions of Business Central required the old DevEnv for uploading test objects, from v15 onward the DevEnv is fully removed and thus cannot be used anymore.

```yaml
- task: ALOpsAppTest@1
  displayName: 'ALOps Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    testsuite: 'DEFAULT'
    failed_test_action: 'Ignore'
  continueOnError: true   
```

Kind regards,

**Comment by AdminHodor** [comment]
Hello @salaniko ,

Did you have any chance to validate the solution?

Kind regards
