### ISSUE TITLE
How-to avoid generating an artifact when doing a build for a specific branch

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#87]
Is there an option that I can add in one of the build steps in the yaml file to specify that the artifact(s) should **not** be created if the following criteria is met:
- Branch = develop
- Build reason = Pull Request build

**Comment by waldo1001** [comment]
I don't think there is - you could create a dedicated build pipeline, obviously ;-).  If you work with yaml-templates, it's rather efficient, still (reusing yaml-configurations in multiple pipelines..).

**Comment by kasperdj** [comment]
ok
