### ISSUE TITLE
Forcing hyper-v Isolation not possible (?)

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [HodorNV/ALOps#89]
I am getting a compiler problem when i use insider builds, i guess it's related with the februar update problem ( https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/ )

How can i run Container in hyper-v isolation with AL Ops?

**Comment by waldo1001** [comment]
This should do the trick:
![image](https://user-images.githubusercontent.com/12088142/75347515-2dd2f380-58a1-11ea-9770-3be9133bfe59.png)

**Comment by PatrickGrabensteiner** [comment]
I already tried this, sorry for not mentioning it 
this is my yaml step
```
- task: ALOpsDockerStart@1
  inputs:
    accept_image_outdated: true
    dockerauthentication: 'UsernamePassword'
    docker_username: ${{ parameters.docker_username }}
    docker_password: ${{ parameters.docker_password }}
    docker_registry: ${{ parameters.docker_registry }}
    docker_image: ${{ parameters.DockerImage }}
    docker_parameters: '--isolation=hyperv'
```

And Here is the error
`##[error]C:\Program Files\Docker\docker.exe: Error response from daemon: container 62d1aa1b5e9d78be70e5d76f814bf5f9eb36e34ec276a3ae6c026685e7d5ac4e encountered an error during CreateContainer: failure in a Windows system call: The request is not supported. (0x32) extra info: {"SystemType":"Container","Name":"62d1aa1b5e9d78be70e5d76f814bf5f9eb36e34ec276a3ae6c026685e7d5ac4e","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\62d1aa1b5e9d78be70e5d76f814bf5f9eb36e34ec276a3ae6c026685e7d5ac4e","Layers":[{"ID":"9c90d764-e9fb-5b23-b24f-ba1e202d9f94","Path":"C:\\ProgramData\\docker\\windowsfilter\\1a1acf414fa24f47fd9e0959a0f8351547cadcbe69a94fcce4fecab2cd0080d0"},{"ID":"70f394bb-9358-570c-8f96-7224d786eaca","Path":"C:\\ProgramData\\docker\\windowsfilter\\cb28559d160413832f1c97a52492bd0fef7d8aeaa0dec70d3376b17b26ddfd83"},{"ID":"eb42fc13-16d7-50f7-9a67-247fc8cc8deb","Path":"C:\\ProgramData\\docker\\windowsfilter\\86de8a4dbc8555b7b959d99e8868d0562b50511e30f95328a419ede3888f9ceb"},{"ID":"5e74cee2-41e6-57c5-85f9-249ca00cc434","Path":"C:\\ProgramData\\docker\\windowsfilter\\f8d0719e133d72fa4c7cacc452c3954b36cbf222d57ec7d7d62a82515aad4684"},{"ID":"4a186b47-4b1c-58ec-b983-ac7057be7426","Path":"C:\\ProgramData\\docker\\windowsfilter\\a3b6fc50c2f11764ae5fc160d81d00b03542f8c8a42b557bba84b044fe93752d"},{"ID":"2cf5376c-22f5-5a76-a1ae-e9b3c23dbed2","Path":"C:\\ProgramData\\docker\\windowsfilter\\0b8cb8a5d73539c4195216b7638201e23583776f26b381b72f9975bdad0d57aa"},{"ID":"38fcfec4-01c2-5673-a904-fbd39325e389","Path":"C:\\ProgramData\\docker\\windowsfilter\\5510ec2acc6168f927dbf0f28ac7efb98671df386031a2a173e1acc5d54cdcc3"},{"ID":"da69d521-b30b-5382-bad8-4cb8241d7e79","Path":"C:\\ProgramData\\docker\\windowsfilter\\cf1a1189b7e797cfa434f05e934846f0f663c3f2f40cee0b39a6c4f390b684ce"},{"ID":"97bac05b-33d9-538d-97d6-38a907731132","Path":"C:\\ProgramData\\docker\\windowsfilter\\5db03489b387923b495e98edd1997adf2ddfb3ff6d89c45ef76998e159a803c5"},{"ID":"06d66cfb-3552-565a-a956-a4bc6aa9bbc9","Path":"C:\\ProgramData\\docker\\windowsfilter\\e6b5a526f4139902a4b8cd3f93d54a684b4cf1eb5d7d889d97d7a5bc8682290b"},{"ID":"bd2a18ec-2b1b-511d-8c7c-47655ae21019","Path":"C:\\ProgramData\\docker\\windowsfilter\\9649d058da46c8b9894aa37f12a3c9abd57954737a774858bd50ecb7a4a4e248"},{"ID":"8455033b-c369-54bf-91a5-04622da186c2","Path":"C:\\ProgramData\\docker\\windowsfilter\\a1210d53a2b4c46f5b26699060fa5bc783196cf14e292f65b7387e4455d03c59"},{"ID":"45ffa205-f4b4-5b06-8379-4e15b5ea6e3d","Path":"C:\\ProgramData\\docker\\windowsfilter\\4817dc2c32c1b027c0563b321218b3b0799ba84563963a9a2eb5134a6638dcb2"},{"ID":"c2078317-bf66-567a-96f0-0f7238d58826","Path":"C:\\ProgramData\\docker\\windowsfilter\\ce7e4dc6fd56e1614fcc4eaa9f375a6b8d760011ff27594e41370eff725d3491"},{"ID":"e13898f1-6ae2-575c-83e7-33e705383f7c","Path":"C:\\ProgramData\\docker\\windowsfilter\\11c317d94273420e7e504bc423ced95503d2326ff0cd6758707934b74908b901"},{"ID":"bb41521c-6fee-57b8-a32d-d0d30381bcdb","Path":"C:\\ProgramData\\docker\\windowsfilter\\5d45b2f7de1d6dcb7253c4984f008a80305771897f31ff968038d047a2ce7658"},{"ID":"e4f7950f-0ee3-5c9c-9bf3-70f07aba059a","Path":"C:\\ProgramData\\docker\\windowsfilter\\1de0f97e6a6532279d194fa4500f3062497f9c4ba8295afd60b301f9c09fb908"},{"ID":"59f4af72-0142-5618-ace7-af145a1b4cba","Path":"C:\\ProgramData\\docker\\windowsfilter\\db307e584e464e34180fb2821c3969d38988f60d8cbc3501126938b0a401e0b9"},{"ID":"ddafe938-7a6d-572b-a98f-c13277fdf4a2","Path":"C:\\ProgramData\\docker\\windowsfilter\\ba0bdbae1d70ea89852adf2e082a4312846651c4e7bd3e415b8cac946ca4c761"},{"ID":"7b191506-2673-5f57-a4b3-445c8caf38ac","Path":"C:\\ProgramData\\docker\\windowsfilter\\c51064d7295a6d8ccbb78770a72ca9198dc25825c19ff80ba93ad45924f09e93"},{"ID":"244f9632-2398-5e70-a645-6a83b121e6e4","Path":"C:\\ProgramData\\docker\\windowsfilter\\a3a105abebe52bde17f05f002abdd136dd5d10dad1713eeebd6b998f4169d3ac"},{"ID":"4de91ff1-f187-56bf-8aa2-16e7a8982f2e","Path":"C:\\ProgramData\\docker\\windowsfilter\\0ebd8da034290f1fbc1e0998c56df24035259488fb59c3164a75c3a137c2a599"},{"ID":"ef2a63d2-e315-5753-88cf-9edf63c76f62","Path":"C:\\ProgramData\\docker\\windowsfilter\\432e07cc4acde94bd3b29897fc13d2f053c15e358af59f34294d3a77a2cc3f8f"},{"ID":"c8e5d82b-e5ec-5aa0-8e40-c36033a4a99a","Path":"C:\\ProgramData\\docker\\windowsfilter\\c711236c95710a2ff3fe572d8004503732ac16aa8a6b549dbf63b8e29a7b6957"},{"ID":"9849bd1c-2068-5b59-86d7-cd4674f5b479","Path":"C:\\ProgramData\\docker\\windowsfilter\\7aeba0444ec6ca3be6a2a48fbd2439282c011c148213d8f165eec991fecf9bf0"},{"ID":"649f4cf5-04ab-5a9f-b013-240a16d5cbed","Path":"C:\\ProgramData\\docker\\windowsfilter\\583b5db3e72203fadde708c300f3d77e606ab444af3d1acba31f5e023f3bfa46"},{"ID":"66e047c8-db00-5953-81f3-0bafc58a4900","Path":"C:\\ProgramData\\docker\\windowsfilter\\d0d86503739a71ab218cf1aad1766ea57f122718678b1132b628b8fee72ec315"},{"ID":"47c5793c-d86e-5582-a45a-7bf65109ba6b","Path":"C:\\ProgramData\\docker\\windowsfilter\\aab97f9eb38078daf1b1af577d31a23a04ca198187e5029d343595c948317621"},{"ID":"53d8f5ff-b0ee-53a2-a405-2f324bb02f2a","Path":"C:\\ProgramData\\docker\\windowsfilter\\676ead906999f3db1e0955ab813bd2fc2cee069d39fc7a182b20806bf1c9fac2"},{"ID":"590b5eff-c82e-5c71-b541-0f43f23cf738","Path":"C:\\ProgramData\\docker\\windowsfilter\\dbe360ba29fbadcee8f49fa698758db564ca6d26a7b2d4912eeb92e19562b205"},{"ID":"8bd6f737-e34f-5ac1-9acd-b17e4aa3ee48","Path":"C:\\ProgramData\\docker\\windowsfilter\\b35f790f27b609b6588681fdb1e490cec7694c288d12f82bac49d00f0435edcc"},{"ID":"11673a2d-f567-5015-a019-a92fa2714fb3","Path":"C:\\ProgramData\\docker\\windowsfilter\\1254afcf2566d394251973f79421e36bbddda8dca6a4a0ac8c172d6780d9f646"},{"ID":"bdcb6c21-4126-5fc5-a122-8512f1336816","Path":"C:\\ProgramData\\docker\\windowsfilter\\65639ce48a24958636db0ae68b439bbd1b0b273c97923a6e4a824ad552d1ca9b"},{"ID":"11414d6b-b465-5495-a20c-5b4fd79aabcb","Path":"C:\\ProgramData\\docker\\windowsfilter\\1c12b60068151662b44288a7819a76b9a4f27c7cbc0a49d827f2bf79c49a4fba"},{"ID":"44ca0685-a53b-56fb-8df2-39f7114823fa","Path":"C:\\ProgramData\\docker\\windowsfilter\\868ee90e0adbc021e3a4a62355a8fc73e3b9b34cc739bbe882cf98ad4416953b"},{"ID":"bb4b7cb7-fb75-5d1e-8472-637215d23b8e","Path":"C:\\ProgramData\\docker\\windowsfilter\\d4b3134a46986ae3be80dd3c589905d3d3b14aa4d6b820aa2386663f3beb9574"}],"HostName":"62d1aa1b5e9d","HvPartition":true,"EndpointList":["EF7DE0CE-D4B1-4406-BA39-BD3DD6C8B8EF"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\docker\\windowsfilter\\868ee90e0adbc021e3a4a62355a8fc73e3b9b34cc739bbe882cf98ad4416953b\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.`

**Comment by waldo1001** [comment]
Did you try if docker works at all on the agent?  I mean - can you try to set up that same container with PowerShell/Cmd?  If that works, it could be ALOps related.  

However, we run insider builds daily - I just checked with the one that ran last night, and it basically just ran normally on this image: "bcinsider.azurecr.io/bcsandbox-master:be-ltsc2019"

**Comment by PatrickGrabensteiner** [comment]
It works now, there is a issue on our agent with hyperv isolation we fixed our agent and use the paramter mentioned above
