### ISSUE TITLE
License Import - preferred license storage location

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#9]
Struggled somewhat with defining the location of the License file. According to the documentation it

_Must be a fully qualified path or relative to $(System.DefaultWorkingDirectory) or a downloadable Url._

Can you share some best practices where to best store your DEV license?

- $(System.DefaultWorkingDirectory) : I've wrongly used the "C:\agent_alops\License.flf" from my build server / agent folder, with no luck.  (The 'C:\vsts-agent-azure\license.flf' parameter in the sample yml file is a bit misleading.)  Putting it in my project (root) instead - which made the license available on 'C:\agent_alops\_work\1\s\License.flf' - and referencing it by 'License.flf' failed as well. Where to place the file? Is it best practice keeping your license files part of the project as well?

- fully qualified path : Tried to point to the internal build server \\mybuildserver\agent_alops\License.flf with no luck.
- downloadable Url : Added the license to a _public_ Azure storage (or DropBox), which succeeded (although it is not prefered for DEV licenses ;)

- Option 4 : The solution of Freddy uses one common Azure KeyVault / Azure Storage account without public access to store credentials / licenses. Would that be an option?

PS: Would it be an option to add a step and test the availability of the files reference in the scripts (license files, add-ins, fob files, ...) before actually creating the container?

**Comment by AdminHodor** [comment]
Best practice for PFX/FLF files is using private download Urls, preferably with Azure Storage Account. 
It is possible to load FLF/PFX file from Disk, from the Repository, but these are not desirable. 

Securely Store the PFX/FLF File (Azure Storage Account):
  - Create a container **without** public access
  - Upload the PFX or FLF file to this container
  - Generate a "Shared Access Signature" for the specific file or entire container
  - Now you have a secured Url that can not be downloaded publicly

Link the Url into the DevOps pipeline there are different possible solutions:
  - **Pipeline variables**:
    These can be defined on Build-Level and are only valid within that build.
    ! Mark the variable as "Secret", this prevents accidental sharing of the Url in any log or display
  - **Variable Groups**
    These can be defined on Project-Level and be linked to Builds. Handy if you want to share some 
    ! Mark the variable as "Secret", this prevents accidental sharing of the Url in any log or displayparameters between builds in the same project.
  - **Azure Key Vault**
    Extends the Variable Groups and allows to pull in Secrets from Azure Key Vault into the group. 
    Once configured usage is identical to Pipeline variables or Variable Groups.
    Key Vault secrets are automatically protected, no extra settings required for protecting the string.
    Handy if you want admin the secrets in a central location and share them between multiple projects/builds

Use the Variable in a build:
  - You can use the defined variables/secrets as parameters in the yaml file. 
  - For example on the "ALOpsLicenseImport" Task, where in this case the name of the variable is "bc_license"
     license_path: $(bc_license)

The way this works is similar to what Freddy uses, the information in his blogpost about this is can also be used for ALOps.
https://blogs.msdn.microsoft.com/freddyk/2017/02/26/create-a-secure-url-to-a-file/
