### ISSUE TITLE
Question about "ALOps Import FOB" & FilePath

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#91]
Hey Guys, 
I am setting up my release pipeline to import fob to the certain environment. I'm having a challenge to specify the filepath for import. At the moment I specified it as full path from linked artifacts. But as you can see it's not very smart. I have versions as part of the file & folder name, and would need to change release definition with every release

- Does "ALOps Import FOB" has file discovery mechanism
- Can I use something like * in the filepath settings?

My current path is set like this:
$(System.DefaultWorkingDirectory)/_Release_CI/mv_Release_CI_35175_master/Release_CI_35175.fob

Screenshot:
![image](https://user-images.githubusercontent.com/16342128/75360257-d68b4e00-58b5-11ea-93a6-e7c765f848ff.png)

**Comment by gintuoklis** [comment]
Ignore my request. Managed to find a solution for it. If anyone is having similar question, here's how i solved:

`$(System.DefaultWorkingDirectory)/_Release_CI/**/Release_CI_*.fob`

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

**Comment by waldo1001** [comment]
Thank you, @gintuoklis
