### ISSUE TITLE
ALOpsRunTestSuite: "Path is null" when using a BC Insider image 

### ISSUE THREAD

**Issue by JesperNavtilus** [HodorNV/ALOps#98]
Hi,

When we run ALOpsRuntestSuite on a BC Insider image, it fails with a "Path is null" error. (it is a JsonReader error - not a TestSuite assert-error)

When running the same setup but on a BC Onprem image, it runs smoothly without any errors.

The YAML parameters and the resulting output are like this (in short):

For BC Insider:

	- task: ALOpsDockerStart@1
	  inputs:
	    docker_image: 'bcinsider.azurecr.io/bcsandbox-master:base'
	    docker_pull: true

	    # With or without a specific docker login - the result is the same
	    # dockerauthentication: 'UsernamePassword'
            # docker_username: '$(insider_docker_username)'
            # docker_password: '$(insider_docker_password)'

	Output from ALOpsDockerStart:
		*** Pull Docker Image: bcinsider.azurecr.io/bcsandbox-master:base [OK]
		*** Docker Start OK.
	...
	...
	...

	- task: ALOpsAppTest@1	
	  displayName: 'ALOps Run TestSuite'
	  inputs:
	    usedocker: true
       	    import_action: "Skip"	
	    import_testtoolkit: false
	    testpage: '130455'	
	    testsuite: 'DEFAULT'
	    failed_test_action: 'Ignore'    	
	  continueOnError: true   
	

	Output from ALOpsAppTest:
	
	##[section]Starting: ALOps Run TestSuite
	================================================================
	Task         : ALOps App Test
	Description  : ALOps App Test
	Version      : 1.427.1082
	Author       : Hodor
	Help         : Run Business Central Test-Suite and collect results.
	================================================================
	*** Validate configuration
	*** Importing required PS-Functions
	*** Working folder: C:\Navtilus\Azure Pipeline Agent\_work\5\s
	***
	*** Prepare Docker Session
	*** Connect Docker Session
	*** Initiate Docker Session
	*** Copy Modules to Docker
	*** Setup Docker Session
	*** Import Modules in Docker Session
	*** Import UI Client [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
	VERBOSE: Loading module from path 
	'C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll'.
	*** Import NewtonSoft JSON [C:\Program Files\Microsoft Dynamics NAV\160\Service\Newtonsoft.Json.dll]
	*** Import Modules in Docker Session: class_ClientContext
	*** Setup BC Credentials in Docker
	*** Set TCP Keep-Alive
	*** Start TestSuite
	*** Running TestSuite with authentication [NavUserPassword] with User [admin]
	*** Run warm-up with page [130455]
	*** Warm-up Client Context
	*** Create Client Context
	*** Get Available Tests for suite [DEFAULT] with page [130455]
	*** Set [CurrentSuiteName] => [DEFAULT]
	**CommunicationError : Error reading JObject from JsonReader. Path '', line 0, position 0.
	CommunicationError InnerException : Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.**
	   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
	   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass15_0.<EndInvokeInteractions>b__0() in s:\repo\src\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.cs:line 306
	   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action) in s:\repo\src\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.cs:line 181
	##[error]Run-Test-Exception: ClientSession in Error
	*** Get XUnit Test file from [] to [C:\Navtilus\Azure Pipeline Agent\_work\5\s\]
	##[error]Cannot bind argument to parameter 'Path' because it is null.
	##[section]Finishing: ALOps Run TestSuite

For BC Onprem:

	- task: ALOpsDockerStart@1
	  inputs:
	    docker_image: 'mcr.microsoft.com/businesscentral/onprem'
	    docker_pull: true

        Otherwise the setup is the same, but the result different (all ok).

Any idea, what is causing this issue and how to fix it?

Thanks, 
Jesper

**Comment by waldo1001** [comment]
I was able to replicate the error - it's not the first surprise with the insider builds :(.

investigating...

**Comment by ChristianMuetzePrintVis** [comment]
Hi @waldo1001 

I ran in the same issue last night.
Have you had any chance to investigate further?

**Comment by waldo1001** [comment]
Yes, we found the issue, working on a solution ...

Microsoft changed the way to run tests ... again ..

**Comment by AdminHodor** [comment]
Dear @ChristianMuetzePrintVis ,

Please try our latest release "1.428.1157", tests should work fine now for BC16. 

Kind regards

**Comment by JesperNavtilus** [comment]
Hi Hodor,
I can confirm that after the latest update of ALOps, the ALOpsRunTestSuite (and the rest of our pipeline) runs smoothly - just like with OnPrem.
I hereby close the ticket.
Thank you
